[package]
name = "remacs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
crossterm = "0.29.0"
flate2 = "1.1.5"
gpui = { version = "0.2.2", features = ["runtime_shaders"] }
html5ever = "0.40.1"
libc = "0.2.189"
markup5ever_rcdom = "0.39.0"
md-5 = "0.10.6"
roxmltree = "0.21.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
sha1 = "0.10.6"
sha2 = "0.10.8"
smol = "2.0.2"
unicode-width = "0.2.2"

[dev-dependencies]
gpui = { version = "0.2.2", features = ["runtime_shaders", "test-support"] }
