;; probe_editor3 — real executions of editor subrs (files, windows,
;; kill ring, regions, completion, syntax scanning)

;; ---- file operations on real files ----
(let ((f "/tmp/probe-e3-file.txt")
      (d "/tmp/probe-e3-dir"))
  (ignore-errors (delete-file f))
  (ignore-errors (make-directory d t))
  (write-region "hello\nworld\nline three\n" nil f nil 'quiet)
  (file-exists-p f)
  (file-readable-p f)
  (file-writable-p f)
  (file-regular-p f)
  (file-symlink-p f)
  (file-directory-p d)
  (file-executable-p "/bin/sh")
  (file-attributes f)
  (file-modes f)
  (file-newer-than-file-p f d)
  (file-name-absolute-p f)
  (file-name-directory f)
  (file-name-nondirectory f)
  (file-name-extension f)
  (file-name-sans-extension f)
  (file-name-base f)
  (file-name-as-directory d)
  (directory-file-name d)
  (file-name-concat d "inner.txt")
  (abbreviate-file-name f)
  (expand-file-name "x" d)
  (expand-file-name f)
  (substitute-in-file-name f)
  (file-name-all-completions "probe" "/tmp")
  (file-name-completion "probe-e3" "/tmp")
  (directory-files "/tmp" nil "^probe-e3")
  (directory-files-and-attributes "/tmp" nil "^probe-e3" t)
  (copy-file f "/tmp/probe-e3-copy.txt" t)
  (rename-file "/tmp/probe-e3-copy.txt" "/tmp/probe-e3-renamed.txt" t)
  (set-file-modes "/tmp/probe-e3-renamed.txt" 420)
  (set-file-times "/tmp/probe-e3-renamed.txt")
  (ignore-errors (make-temp-name "/tmp/probe-e3"))
  (delete-file "/tmp/probe-e3-renamed.txt")
  (with-temp-buffer
    (insert-file-contents f)
    (buffer-string))
  (with-temp-buffer
    (insert-file-contents-literally f)
    (buffer-string))
  (with-temp-buffer
    (set-visited-file-name f)
    (save-buffer)
    (write-file "/tmp/probe-e3-written.txt"))
  (write-region 1 3 f nil 'quiet)
  (append-to-file 1 4 f)
  (delete-file "/tmp/probe-e3-written.txt")
  (delete-file f)
  (delete-directory d))

;; ---- windows and frames ----
(let ((w (split-window))
       (w2 (split-window-right)))
  (window-list)
  (window-live-p w)
  (windowp w)
  (selected-window)
  (select-window w)
  (window-buffer w)
  (window-point w)
  (set-window-point w (point-min))
  (window-start w)
  (set-window-start w (point-min))
  (window-end w)
  (window-height w)
  (window-body-height w)
  (window-width w)
  (window-body-width w)
  (window-edges w)
  (window-margins w)
  (window-hscroll w)
  (set-window-hscroll w 0)
  (window-minibuffer-p w)
  (window-dedicated-p w)
  (set-window-dedicated-p w nil)
  (window-parameter w 'test)
  (set-window-parameter w 'test 1)
  (window-parameter w 'test)
  (window-parameters w)
  (window-frame w)
  (window-at 1 1)
  (walk-windows (lambda (x) x))
  (window-next-sibling w)
  (window-prev-sibling w)
  (frame-first-window)
  (delete-window w2)
  (delete-other-windows w)
  (set-window-buffer w (current-buffer)))
(other-buffer)
(ignore-errors (next-buffer))
(ignore-errors (previous-buffer))
(last-buffer)
(selected-frame)
(framep (selected-frame))
(window-frame (selected-window))
(frame-first-window)
(frame-selected-window)
(select-frame (selected-frame))
(set-frame-selected-window (selected-frame) (selected-window))
(frame-parameters)
(frame-parameter nil 'name)
(set-frame-parameter nil 'probe-param t)
(frame-parameter nil 'probe-param)
(modify-frame-parameters nil '((probe-p2 . t)))
(frame-height)
(frame-width)
(frame-pixel-height)
(frame-pixel-width)
(display-pixel-height)
(display-pixel-width)
(frame-visible-p (selected-frame))
(make-frame-visible (selected-frame))
(ignore-errors (iconify-frame (selected-frame)))
;; GNU errors on iconifying/invisibling the sole visible frame.
(ignore-errors (make-frame-invisible (selected-frame) t))
(make-frame-visible (selected-frame))
(lower-frame)
(raise-frame)
(frame-list)
(visible-frame-list)
(ignore-errors (frames-on-display-list))
(ignore-errors (frame-or-buffer-changed-p))
(selected-window)
(minibuffer-window)
(active-minibuffer-window)
(minibuffer-window-active-p (minibuffer-window))
(window-minibuffer-p (minibuffer-window))
(ignore-errors (delete-frame (selected-frame)))

;; ---- kill ring / yank ----
(with-temp-buffer
  (insert "kill this text and more words here\n")
  (goto-char (point-min))
  (kill-word 1)
  (backward-kill-word 1)
  (kill-line)
  (goto-char (point-min))
  (copy-region-as-kill (point-min) (point-max))
  (yank)
  (current-kill 0)
  (current-kill 1 t)
  (rotate-yank-pointer 1)
  (yank-pop)
  (kill-new "probe-kill")
  (kill-append " more" nil)
  kill-ring
  (boundp 'kill-ring-yank-pointer)
  (ignore-errors (zap-to-char 1 ?x)))

;; ---- regions / mark ----
(with-temp-buffer
  (insert "Region Text Here\nsecond line\n")
  (goto-char (point-min))
  (push-mark (point-max))
  (activate-mark)
  (region-active-p)
  (region-beginning)
  (region-end)
  (upcase-region (point-min) (point-max))
  (downcase-region (point-min) (+ 4 (point-min)))
  (capitalize-region (point-min) (point-max))
  (upcase-word 1)
  (downcase-word 1)
  (capitalize-word 1)
  (deactivate-mark)
  (mark)
  (mark-marker)
  (set-mark (point-min))
  (goto-char (point-max))
  (exchange-point-and-mark)
  (delete-trailing-whitespace)
  (delete-horizontal-space)
  (delete-indentation)
  (count-words-region (point-min) (point-max))
  (count-words (point-min) (point-max)))

;; ---- completion ----
(let ((col '("alpha" "alpine" "beta" "gamma")))
  (try-completion "al" col)
  (try-completion "zzz" col)
  (try-completion "" col)
  (all-completions "al" col)
  (all-completions "" col)
  (test-completion "alpha" col)
  (test-completion "zzz" col)
  (completion-boundaries "al" col nil "pha")
  (all-completions "a" obarray)
  (apropos-internal "buffer")
  (apropos-internal "buf" #'commandp))

;; ---- documentation / key description ----
(documentation 'car)
(documentation 'cons t)
(documentation-property 'car 'variable-documentation)
(describe-key (kbd "C-n"))
(ignore-errors (describe-bindings))
(help-function-arglist 'let)
(single-key-description 65)
(single-key-description ?\C-a)
(text-char-description 65)
(text-char-description ?\C-a)
(key-description [?\C-x ?\C-f])
(key-description "\C-x\C-f")
(substitute-command-keys "\\[next-line]")
(substitute-command-keys "\\{global-map}")
(where-is-internal 'next-line)
(where-is-internal 'self-insert-command)
(this-command-keys)
(this-command-keys-vector)
(commandp 'next-line)
(commandp 'car)
(command-remapping 'self-insert-command)

;; ---- syntax scanning ----
(with-temp-buffer
  (insert "(a (b c) \"str ; x\" d) ; comment\n(e f)\n")
  (goto-char (point-min))
  (syntax-ppss)
  (syntax-ppss 8)
  (parse-partial-sexp (point-min) (point-max))
  (parse-partial-sexp (point-min) 8)
  (syntax-table)
  (syntax-table-p (syntax-table))
  (standard-syntax-table)
  (copy-syntax-table)
  (set-syntax-table (syntax-table))
  (char-syntax ?a)
  (char-syntax ?\s)
  (char-syntax ?\()
  (modify-syntax-entry ?x "w")
  (ignore-errors (matching-paren ?\()))
(with-temp-buffer
  (ignore-errors (emacs-lisp-mode))
  (insert "(defun f (x) \"doc\" (list x))\n;; c\n(let ((y 1)) y)\n")
  (goto-char (point-min))
  (ignore-errors (beginning-of-defun))
  (ignore-errors (end-of-defun))
  (ignore-errors (forward-list))
  (ignore-errors (backward-list))
  (ignore-errors (down-list))
  (ignore-errors (backward-up-list))
  (ignore-errors (up-list))
  (syntax-ppss))

;; ---- scrolling / display ----
(recenter)
(recenter 0)
;; GNU signals end-of-buffer/beginning-of-buffer when the scroll
;; cannot complete (scroll-error-top-bottom nil), so wrap them.
(ignore-errors (scroll-up 1))
(ignore-errors (scroll-down 1))
(ignore-errors (scroll-up-command 1))
(ignore-errors (scroll-down-command 1))
(scroll-other-window 1)
(scroll-left 1)
(scroll-right 1)
(what-line)
(what-cursor-position)
(line-number-at-pos)
(current-column)
(move-to-column 0)
(ignore-errors (beginning-of-visual-line))
(ignore-errors (end-of-visual-line))
(posn-at-point)
(posn-at-x-y 0 0)
(tabify 1 10)
(untabify 1 10)
(goto-line 1)
(track-mouse)

;; ---- misc commands ----
(digit-argument 4)
(universal-argument)
(negative-argument 2)
(prefix-numeric-value '(4))
(prefix-numeric-value 7)
(forward-line -1)
(with-temp-buffer (insert "ab") (goto-char 2) (transpose-chars 1))
(execute-extended-command 4)
(ignore-errors (call-interactively 'next-line))
(called-interactively-p 'interactive)
(interactive-p)
(command-execute 'ignore)
(condition-case e (read-number "n: " 5) (error e))
(condition-case e (read-string "s: " "def") (error e))
(condition-case e (read-variable 'next-line) (error e))
(condition-case e (read-regexp "re: ") (error e))

;; ---- shell command ----
(shell-command-to-string "echo probe")
(call-process "echo" nil nil nil "probe")
(call-process-region "a b c" nil "tr" nil nil nil "a-z" "A-Z")

;; ---- overlays ----
(with-temp-buffer
  (insert "overlay text here")
  (let ((ov (make-overlay 1 5)))
    (overlay-put ov 'face 'bold)
    (overlay-get ov 'face)
    (overlay-start ov)
    (overlay-end ov)
    (overlay-buffer ov)
    (overlayp ov)
    (move-overlay ov 2 6)
    (overlays-at 3)
    (overlays-in 1 10)
    (next-overlay-change 1)
    (previous-overlay-change 10)
    (overlay-properties ov)
    (delete-overlay ov))
  (remove-overlays))
