;; Gap probe: exercise never-covered subrs with valid args.

;; --- special-form raw handlers ---
(ignore-errors (and t 1 2))
(ignore-errors (or nil nil 3))
(ignore-errors (prog1 'a 'b 'c))
(ignore-errors (function (lambda (x) x)))
(ignore-errors (function 'car))
(ignore-errors (condition-case e (error "x") (error e)))
(ignore-errors (run-hook-wrapped 'hooks (lambda (f) (funcall f) nil)))
(ignore-errors (run-hook-with-args 'hooks 1 2))
(ignore-errors (run-hook-with-args-until-failure 'hooks))
(ignore-errors (run-hook-with-args-until-success 'hooks))
(ignore-errors (command-execute 'self-insert-command))
(ignore-errors (compiled-function-p 'car))
(ignore-errors (subr-native-lambda-list 'car))
(ignore-errors (locate-library "subr"))
(ignore-errors (memory-info))
(ignore-errors (byte-code "" [] 0))

;; --- misc uncovered ---
(ignore-errors (user-login-name))
(ignore-errors (invocation-name))
(ignore-errors (get-file-buffer "nonexistent"))
(ignore-errors (buffer-hash))
(ignore-errors (buffer-hash (current-buffer)))
(ignore-errors (window-min-width))
(ignore-errors (window-min-height))
(ignore-errors (secure-hash 'md5 "abc"))
(ignore-errors (secure-hash 'sha256 "abc" 0 3 t))
(ignore-errors (time-convert 1000000 'list))
(ignore-errors (time-convert '(0 0) 'integer))
(ignore-errors (help-function-arglist 'car))
(ignore-errors (help-function-arglist 'car t))
(ignore-errors (file-attributes-lessp (file-attributes ".") (file-attributes "..")))
(ignore-errors (make-interpreted-closure '((x . 1)) '(x) nil))
(ignore-errors (bool-vector-count-consecutive (make-bool-vector 4 t) t 0))
(ignore-errors (bool-vector-count-population (make-bool-vector 4 t) 0))
(ignore-errors (bool-vector-not (make-bool-vector 3 t)))
(ignore-errors (bool-vector-set-difference (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-intersection (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-union (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-exclusive-or (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-subsetp (make-bool-vector 3 t) (make-bool-vector 3 nil)))

;; --- buffer primitives ---
(ignore-errors (insert-buffer-substring (current-buffer) 1 2))
(ignore-errors (insert-char ?a 3))
(ignore-errors (insert-char ?b 2 t))
(ignore-errors (open-line 1))
(ignore-errors (delete-backward-char 1))
(ignore-errors (exchange-point-and-mark))
(ignore-errors (set-marker (make-marker) 1))
(ignore-errors (set-marker (make-marker) 1 (current-buffer)))
(ignore-errors (move-to-column 2))
(ignore-errors (move-to-column 0 t))
(ignore-errors (symbol-at-point))
(ignore-errors (thing-at-point 'word))
(ignore-errors (thing-at-point 'symbol t))
(ignore-errors (bury-buffer))
(ignore-errors (bury-buffer (current-buffer)))
(ignore-errors (previous-property-change 1))
(ignore-errors (previous-property-change 1 (current-buffer)))
(ignore-errors (append-next-kill))

(with-temp-buffer
  (insert "aa\n\n\nbb\n\ncc\n")
  (ignore-errors (delete-blank-lines))
  (goto-char (point-min))
  (ignore-errors (delete-blank-lines)))

;; --- buffer extra ---
(with-temp-buffer
  (insert "foo bar\nbaz foo\nqux\n")
  (ignore-errors (how-many "foo"))
  (ignore-errors (count-matches "ba."))
  (goto-char (point-min))
  (ignore-errors (keep-lines "foo"))
  (goto-char (point-min))
  (insert "one\ntwo\nthree\n")
  (ignore-errors (flush-lines "o"))
  (ignore-errors (sort-lines nil (point-min) (point-max)))
  (ignore-errors (reverse-region (point-min) (point-max)))
  (goto-char (point-min))
  (insert "abc")
  (ignore-errors (subst-char-in-region 1 4 ?a ?z))
  (ignore-errors (translate-region 1 4 (make-char-table 'generic nil)))
  (ignore-errors (how-many "." 1 nil t)))

(with-temp-buffer
  (insert "aaa bbb")
  (ignore-errors (replace-regexp "a+" "X"))
  (goto-char (point-min))
  (ignore-errors (replace-string "b" "Y"))
  (goto-char (point-min))
  (insert "xy")
  (ignore-errors (transpose-regions 1 2 2 4)))

(with-temp-buffer
  (insert "aGVsbG8=")
  (ignore-errors (base64-decode-region 1 9))
  (goto-char (point-min))
  (insert "hello")
  (ignore-errors (base64-encode-region 1 6))
  (ignore-errors (base64url-encode-region 1 6 t))
  (ignore-errors (secure-hash-region 'sha256 1 6)))

(with-temp-buffer
  (insert "text")
  (let ((b2 (generate-new-buffer "swap")))
    (ignore-errors (buffer-swap-text b2))))

(with-temp-buffer
  (insert "abcdef")
  (put-text-property 1 3 'face 'bold)
  (ignore-errors (next-char-property-change 1))
  (ignore-errors (previous-char-property-change 6))
  (ignore-errors (text-property-not-all 1 6 'face 'bold))
  (ignore-errors (text-property-any 1 6 'face nil))
  (ignore-errors (remove-list-of-text-properties 1 6 '(face)))
  (ignore-errors (put-char-property 1 2 'face 'x (current-buffer)))
  (ignore-errors (add-face-text-property 1 3 'italic))
  (ignore-errors (get-pos-property 1 'face))
  (ignore-errors (get-char-property-and-overlay 1 'face))
  (ignore-errors (field-beginning))
  (ignore-errors (field-end 1))
  (ignore-errors (field-string 1))
  (ignore-errors (field-string-no-properties 1))
  (ignore-errors (delete-field 1))
  (ignore-errors (constrain-to-field 3 1))
  (ignore-errors (compute-motion 1 '(1 . 0) 4 '(4 . 0) 0 10 (selected-window)))
  (ignore-errors (vertical-motion 1))
  (ignore-errors (vertical-motion '(1 . 0) (selected-window)))
  (ignore-errors (line-pixel-height))
  (ignore-errors (window-line-height))
  (ignore-errors (backward-prefix-chars))
  (ignore-errors (move-point-visually 3))
  (ignore-errors (marker-last-position (make-marker))))

;; --- editor module ---
(ignore-errors (set-window-buffer (selected-window) (current-buffer)))
(ignore-errors (get-buffer-window))
(ignore-errors (get-buffer-window (current-buffer)))
(ignore-errors (minibuffer-window))
(ignore-errors (window-margins))
(ignore-errors (window-margins (selected-window)))
(ignore-errors (where-is-internal 'self-insert-command))
(ignore-errors (where-is-internal 'self-insert-command nil t))
(ignore-errors (apropos-internal "^car$"))
(ignore-errors (apropos-internal "point" 'commandp))
(ignore-errors (try-completion "al" '("alpha" "beta")))
(ignore-errors (all-completions "a" '("alpha" "beta")))
(ignore-errors (test-completion "alpha" '("alpha" "beta")))
(ignore-errors (find-file-noselect "Cargo.toml"))
(ignore-errors (directory-files "."))
(ignore-errors (directory-files "." nil "^Cargo"))
(ignore-errors (directory-files "." t nil t))
(ignore-errors (file-writable-p "Cargo.toml"))
(ignore-errors (file-symlink-p "."))
(ignore-errors (copy-to-buffer (current-buffer) 1 2))
(ignore-errors (call-process "echo" nil t nil "hi"))
(ignore-errors (call-process-region 1 5 "cat"))
(ignore-errors (substitute-command-keys "\\[self-insert-command]"))
(ignore-errors (set-keymap-parent (make-keymap) nil))
(ignore-errors (current-kill 0))
(ignore-errors (current-kill 0 t))
(let ((o (make-overlay 1 2)))
  (ignore-errors (remove-overlays))
  (ignore-errors (previous-overlay-change 5)))
(ignore-errors (describe-key [?a]))
(ignore-errors (display-buffer (current-buffer)))

;; --- hashfn / value gaps ---
(let ((h (make-hash-table)))
  (puthash 'a 1 h)
  (ignore-errors (maphash (lambda (k v) nil) h))
  (ignore-errors (hash-table-count h))
  (ignore-errors (hash-table-test h))
  (ignore-errors (hash-table-size h))
  (ignore-errors (clrhash h))
  (ignore-errors (remhash 'a h)))

;; --- printfn gaps ---
(ignore-errors (terpri 3))
(ignore-errors (with-output-to-string (princ "hi") (terpri)))
(ignore-errors (write-char 65))
(ignore-errors (prin1-to-string 'x t))
(ignore-errors (output-switches))
(ignore-errors (print "abc"))

;; --- strfn/seq/reader/regexp gaps ---
(ignore-errors (split-string "a,b;c" "," nil ";"))
(ignore-errors (string-width "abc"))
(ignore-errors (string-width (make-string 3 ?x)))
(ignore-errors (subst-char-in-string ?a ?z "banana"))
(ignore-errors (subst-char-in-string ?a ?z "banana" t))
(ignore-errors (string-search "b" "abc"))
(ignore-errors (string-search "b" "abc" 2))
(ignore-errors (unibyte-string 65 66 67))
(ignore-errors (string-trim "  x  "))
(ignore-errors (string-trim-left "  x" " +"))
(ignore-errors (string-trim-right "x  " " +"))
(ignore-errors (string-trim "x" "[ab]+"))
(ignore-errors (aset (make-bool-vector 3 nil) 0 t))
(ignore-errors (read-from-string "#16rff"))
(ignore-errors (read-from-string "#36rz"))
(ignore-errors (read-from-string "#b2"))
(with-temp-buffer
  (insert "aaa bbb")
  (goto-char (point-max))
  (ignore-errors (search-backward "aaa"))
  (goto-char (point-max))
  (ignore-errors (search-backward "x" nil t))
  (goto-char (point-max))
  (ignore-errors (re-search-backward "b+"))
  (goto-char (point-max))
  (ignore-errors (re-search-backward "z" nil t)))

;; --- winxtra gaps ---
(ignore-errors (posn-at-x-y 0 0))
(ignore-errors (posn-at-x-y 1 1 (selected-window)))
(ignore-errors (terminal-live-p nil))
(ignore-errors (terminal-live-p (selected-frame)))
(ignore-errors (make-frame-visible))
(ignore-errors (set-window-vscroll nil 0))
(ignore-errors (set-window-vscroll (selected-window) 2))
(ignore-errors (set-window-new-total nil 10))
(ignore-errors (set-window-new-normal nil 1))

;; --- eval internals ---
(ignore-errors (call-interactively 'forward-char))
(ignore-errors (call-interactively (lambda () (interactive) 5)))
(ignore-errors (funcall (lambda (x) x)))
(ignore-errors (func-arity (function (lambda (&rest x) x))))
(ignore-errors (func-arity 'if))
(ignore-errors (eval-buffer))
(ignore-errors (load-file "/tmp/nonexistent-remacs.el"))
(ignore-errors (prin1-to-string
                (let ((b (get-buffer-create " tmpk")))
                  (kill-buffer b)
                  b)))
(let ((l (list 1 2 3)))
  (setcdr (cddr l) l)
  (ignore-errors (length l))
  (ignore-errors (member 9 l))
  (ignore-errors (nthcdr 9 l)))

;; --- eval/value ---
(ignore-errors (eq 1.5 1.5))
(ignore-errors (equal-including-properties "a" "a"))
(ignore-errors (type-of (make-bool-vector 2 t)))
(ignore-errors (record 'foo 1 2))
(ignore-errors (records 'x))
