;; Probe: eval/regexp/arith/special-form branch coverage.
;; Raw special-form registrations are exercised via funcall/apply.
(progn
  ;; ---- read-from-string --------------------------------------------
  (prin1 (read-from-string "(a b)"))
  (prin1 (read-from-string "xx(a)" 2))
  (prin1 (read-from-string "(a b)tail" 0 5))
  (condition-case e (read-from-string "") (error (prin1 (car e))))
  (condition-case e (read-from-string "(unclosed") (error (prin1 (car e))))
  (condition-case e (read-from-string ")") (error (prin1 (car e))))
  (prin1 (read-from-string "  42"))
  (prin1 (read-from-string "\"str\""))
  (prin1 (read-from-string "?\\n"))
  ;; ---- backquote ---------------------------------------------------
  (let ((x 5) (l '(1 2)))
    (prin1 `(a ,x ,@l . tail))
    (prin1 `[v ,x ,@l])
    (prin1 `(outer `(inner ,,x)))
    (prin1 `(,(car l) . ,(cdr l))))
  (prin1 `x)
  (prin1 ``(,a ,b))
  (prin1 `(a . (b . (c . nil))))
  ;; ---- let* branches ------------------------------------------------
  (let* ((a 1) (b (+ a 1)) (a (+ b 1))) (prin1 (list a b)))
  (let* ((a)) (prin1 a))
  (let* () (prin1 'empty))
  (condition-case e (eval '(let* (((a b) '(1 2))) (list a b))) (error (prin1 (car e))))
  ;; ---- macroexpand parse body --------------------------------------
  (prin1 (macroexpand '(when a b)))
  (prin1 (macroexpand-1 '(when a b)))
  (prin1 (macroexpand-1 '(unless a b)))
  (condition-case e (macroexpand-1 5) (error (prin1 (car e))))
  ;; ---- regexp char classes / escapes --------------------------------
  (prin1 (string-match "[[:alpha:]]+" "123abc"))
  (prin1 (string-match "[[:digit:]x]+" "ab12x"))
  (prin1 (string-match "[[:space:]]" "a b"))
  (prin1 (string-match "[[:upper:]][[:lower:]]+" "HELLOworld"))
  (prin1 (string-match "[[:punct:]]" "a.b"))
  (prin1 (string-match "\\ca" "abc"))
  (prin1 (string-match "\\s-" "a b"))
  (prin1 (string-match "\\sw\\sw" "ab "))
  (prin1 (string-match "[^a-c]+" "abcxyz"))
  (prin1 (string-match "\\`abc\\'" "abc"))
  (prin1 (string-match "a\\{2,3\\}" "aaaa"))
  (prin1 (string-match "\\(x\\|y\\)+" "xyx"))
  (let ((case-fold-search t))
    (prin1 (string-match "ABC" "xxabc")))
  (let ((case-fold-search nil))
    (prin1 (string-match "ABC" "xxabc")))
  ;; ---- replace-regexp-in-string --------------------------------------
  (prin1 (replace-regexp-in-string "a\\(b\\)" "X\\1Y" "ab ab"))
  (prin1 (replace-regexp-in-string "o" "0" "foo" t))
  (prin1 (replace-regexp-in-string "o" "0" "foo" nil t))
  (prin1 (replace-regexp-in-string "o" "0" "foo" nil nil 1))
  (prin1 (replace-regexp-in-string "o" "0" "foo" nil nil nil 2))
  ;; ---- posix matching ------------------------------------------------
  (prin1 (posix-string-match "a\\|ab" "ab"))
  (prin1 (string-match "a\\|ab" "ab"))
  (with-temp-buffer
    (insert "ab")
    (goto-char (point-min))
    (prin1 (posix-search-forward "a\\|ab" nil t)))
  ;; ---- re-search-backward -------------------------------------------
  (with-temp-buffer
    (insert "a1 a2 a3")
    (goto-char (point-max))
    (prin1 (re-search-backward "a[0-9]" nil t))
    (prin1 (match-string 0))
    (prin1 (re-search-backward "a[0-9]" nil t 1))
    (condition-case e (re-search-backward "zzz") (error (prin1 (car e)))))
  ;; ---- fields --------------------------------------------------------
  (with-temp-buffer
    (insert "aaXbb")
    (put-text-property 3 4 'field 'stop)
    (prin1 (field-beginning))
    (prin1 (field-end))
    (goto-char 2)
    (prin1 (constrain-to-field nil 3))
    (prin1 (constrain-to-field nil 3 t))
    (prin1 (field-string 2)))
  ;; ---- buffer-swap-text ------------------------------------------------
  (let ((b1 (get-buffer-create " *sw1*"))
        (b2 (get-buffer-create " *sw2*")))
    (with-current-buffer b1 (insert "ONE"))
    (with-current-buffer b2 (insert "TWO"))
    (with-current-buffer b1 (buffer-swap-text b2))
    (prin1 (with-current-buffer b1 (buffer-string)))
    (prin1 (with-current-buffer b2 (buffer-string)))
    (condition-case e (with-current-buffer b1 (buffer-swap-text b1))
      (error (prin1 (car e)))))
  ;; ---- arith: / and - branches, rounding --------------------------------
  (prin1 (/ 7 2))
  (prin1 (/ 7.0 2))
  (prin1 (/ 6 3))
  (condition-case e (/ 1 0) (error (prin1 (car e))))
  (prin1 (/ 1.0 0))
  (prin1 (- 5))
  (prin1 (- 10 3 2))
  (prin1 (- 2.5 0.5))
  (prin1 (round 2.5))
  (prin1 (round -2.5))
  (prin1 (round 3))
  (prin1 (floor 2.9))
  (prin1 (floor -2.1))
  (prin1 (ceiling 2.1))
  (prin1 (truncate -2.9))
  (prin1 (ffloor 2.5))
  (prin1 (fceiling 2.5))
  (prin1 (fround 2.5))
  (prin1 (ftruncate 2.5))
  ;; ---- or/unwind-protect branches ---------------------------------------
  (prin1 (or nil nil 3 4))
  (prin1 (or))
  (prin1 (catch 'x (unwind-protect (throw 'x 9) (prin1 'unwound))))
  (prin1 (unwind-protect 1 (prin1 'cleanup1) (prin1 'cleanup2)))
  ;; ---- function special form ---------------------------------------------
  (prin1 (funcall (function (lambda (z) (* z 2))) 21))
  (prin1 (function 'car))
  (prin1 (functionp (function +)))
  ;; ---- special forms are not funcallable (matches GNU) --------------------
  (condition-case e (funcall 'or nil nil 7) (error (prin1 (car e))))
  (condition-case e (funcall 'function '(lambda (q) q)) (error (prin1 (car e))))
  (condition-case e (funcall 'and t t nil) (error (prin1 (car e))))
  ;; ---- require ------------------------------------------------------------
  (prin1 (require 'cl-lib nil t))
  (prin1 (require 'no-such-feature-xyz nil t))
  (condition-case e (require 'no-such-feature-xyz) (error (prin1 (car e))))
  (prin1 (featurep 'cl-lib))
  ;; ---- print destinations ----------------------------------------------------
  (let ((standard-output (get-buffer-create " *sout*")))
    (princ "into-buffer")
    (prin1 (with-current-buffer " *sout*" (buffer-string))))
  (let ((standard-output t))
    (princ "echo-area"))
  (let ((standard-output (marker-position (point-marker))))
    (princ "mrk"))
  ;; ---- syntax codes --------------------------------------------------------------
  (prin1 (char-syntax ?a))
  (prin1 (char-syntax ?\())
  (prin1 (char-syntax ? ))
  (prin1 (char-syntax ?'))
  (prin1 (string-to-syntax "w"))
  (prin1 (string-to-syntax "( "))
  ;; ---- wrong-argc errors -----------------------------------------------------
  (condition-case e (car) (error (prin1 e)))
  (condition-case e (car 1 2) (error (prin1 e)))
  (condition-case e (cons 1 2 3) (error (prin1 e)))
  ;; ---- optional defaults fill ----------------------------------------------------
  ;; (var init supplied-p) triples are valid in macro arglists.
  (funcall (defmacro m1 (&optional (p 10) (q 20 s-p)) `(list ',p ',q ',s-p)))
  (funcall (defmacro m2 (&optional (p 10) (q 20 s-p)) `(list ',p ',q ',s-p)) 1)
  (funcall (defmacro m3 (&optional (p 10) (q 20 s-p)) `(list ',p ',q ',s-p)) 1 2)
  (condition-case e
      (funcall (defmacro m4 (&optional (p 10) (q 20 s-p)) `(list ',p ',q ',s-p)) 1 2 3)
    (error (prin1 (car e))))
  ;; plain lambdas reject extended optional forms (matches GNU).
  (condition-case e
      (funcall (lambda (&optional (p 10)) p))
    (error (prin1 (car e))))
  (prin1 'done))
