;; Probe: reader radix/dot tokens, obarray, format specs, data fns.
(progn
  ;; ---- radix integers ------------------------------------------------
  (prin1 (list #x1f #o17 #b101 #16rff #08r17 #02r11 #36rz))
  (prin1 (list #x-1f #b+10 #o-7))
  (condition-case e (eval (read-from-string "#x")) (error (prin1 (car e))))
  (condition-case e (eval (read-from-string "#b2")) (error (prin1 (car e))))
  (condition-case e (eval (read-from-string "#xG")) (error (prin1 (car e))))
  ;; ---- dot tokens ----------------------------------------------------
  (prin1 (read-from-string "(a . b)"))
  (prin1 (read-from-string "(a .)"))
  (prin1 (read-from-string "(a b .)"))
  (prin1 (read-from-string "(.)"))
  (prin1 (read-from-string "(a . .)"))
  (prin1 (read-from-string "[a .]"))
  (condition-case e (read-from-string "(a . b c)") (error (prin1 (car e))))
  (condition-case e (read-from-string "(a b . )") (error (prin1 (car e))))
  (condition-case e (read-from-string "(. a)") (error (prin1 (car e))))
  (condition-case e (read-from-string "[a . b]") (error (prin1 (car e))))
  (condition-case e (read-from-string ".") (error (prin1 (car e))))
  (prin1 (car (read-from-string "..")))
  (prin1 (car (read-from-string "...")))
  ;; ---- uninterned symbols / function quote ----------------------------
  (prin1 (car (read-from-string "#:foo")))
  (prin1 (car (read-from-string "#'car")))
  (condition-case e (read-from-string "#:") (error (prin1 (car e))))
  ;; ---- char literals ---------------------------------------------------
  (prin1 (list ?a ?\n ?\t ?\\ ?\d ?\s ?\^A ?\M-a ?\C-\M-b ?\S-a))
  (prin1 (list ?\x41 ?\o101 ?\u0041))
  (condition-case e (car (read-from-string "?\\N{LATIN CAPITAL LETTER A}"))
    (error (prin1 (car e))))
  ;; ---- obarray ---------------------------------------------------------
  (let ((ob (obarray-make 10)))
    (intern "x" ob) (intern "y" ob)
    (prin1 (obarray-size ob))
    (prin1 (intern-soft "x" ob))
    (prin1 (intern-soft "zzz" ob))
    (unintern "x" ob)
    (prin1 (intern-soft "x" ob))
    (mapatoms (lambda (s) (prin1 (symbol-name s))) ob))
  (prin1 (obarray-size obarray))
  (prin1 (obarrayp obarray))
  ;; ---- format spec coverage ---------------------------------------------
  (prin1 (format "%S %s" '(1 . 2) "s"))
  (prin1 (format "%c %c" 65 66))
  (prin1 (format "%%"))
  (prin1 (format "%5d|%-5d|%05d" 42 42 42))
  (prin1 (format "%x %o" 255 8))
  (prin1 (format "%e %f %g" 1234.5 0.5 123456789.0))
  (prin1 (format "%.2f %.3s" 1.23456 "abcdef"))
  (condition-case e (format "%*d" 5 3) (error (prin1 (car e))))
  (condition-case e (format "%q") (error (prin1 (car e))))
  (condition-case e (format "%d" "x") (error (prin1 (car e))))
  ;; ---- princ / prin1 to string ------------------------------------------
  (prin1 (format "%s" 'a\b))
  (prin1 (format "%s" "a\nb"))
  (prin1 (prin1-to-string "a\nb"))
  (prin1 (prin1-to-string '(a . b)))
  ;; ---- plist --------------------------------------------------------------
  (let ((p (list 'a 1 'b 2)))
    (prin1 (plist-put p 'a 9))
    (prin1 (plist-put p 'c 3))
    (prin1 (plist-get p 'b))
    (prin1 (plist-member p 'b))
    (prin1 (plist-member p 'z))
    (condition-case e (plist-put p 'z) (error (prin1 (car e)))))
  (condition-case e (plist-get '(a) 'a) (error (prin1 (car e))))
  ;; ---- assoc / assoc-default ------------------------------------------------
  (prin1 (assoc 'b '((a . 1) (b . 2))))
  (prin1 (assoc 'z '((a . 1))))
  (prin1 (assoc-default 'b '((a . 1) (b . 2))))
  (prin1 (assoc-default 'z '((a . 1) (t . 9))))
  (prin1 (assoc-default 'z '((a . 1)) nil #'car-less-than-car))
  (prin1 (assoc-default "B" '(("a" . 1) ("B" . 2)) #'string=))
  ;; ---- let* / or branches ---------------------------------------------------
  (prin1 (let* ((a 1) (b (+ a 1)) (c (+ b 1))) (list a b c)))
  (prin1 (let* ((a 1) (a (+ a 10))) a))
  (prin1 (let* () 5))
  (prin1 (let* ((a)) a))
  (prin1 (or nil nil 7 8))
  (prin1 (or nil))
  (prin1 (or 1 2))
  ;; ---- elt / aset / nreverse across types ------------------------------------
  (let ((v (vector 'a 'b 'c))
        (s (copy-sequence "xyz"))
        (bv (bool-vector t nil t))
        (r (record 'rec 1 2 3)))
    (aset v 0 'z)
    (aset s 0 ?Z)
    (aset bv 1 t)
    (aset r 2 99)
    (prin1 (list v s bv r))
    (prin1 (list (elt v 1) (elt s 1) (elt bv 2)))
    (condition-case e (aset v 9 'q) (error (prin1 (car e))))
    (condition-case e (elt v 9) (error (prin1 (car e))))
    (condition-case e (aset 5 0 'q) (error (prin1 (car e))))
    (condition-case e (elt 5 0) (error (prin1 (car e)))))
  (prin1 (nreverse (list 1 2 3)))
  (prin1 (nreverse "abc"))
  (prin1 (nreverse [1 2 3]))
  ;; ---- division branches ------------------------------------------------------
  (prin1 (list (/ 10 3) (/ 10.0 3) (/ -7 2) (% 7 3) (% -7 3)))
  (condition-case e (/ 1 0) (error (prin1 (car e))))
  (condition-case e (% 1 0) (error (prin1 (car e))))
  (prin1 (/ 1.0 0))
  (prin1 (list (mod 7 3) (mod -7 3) (mod 7.5 2)))
  ;; ---- interactive spec remaining codes --------------------------------------
  (condition-case e (eval '(call-interactively (lambda (x) (interactive 5) x)))
    (error (prin1 (car e))))
  (condition-case e (funcall (lambda (x) (interactive "p") x))
    (error (prin1 (car e))))
  (condition-case e (command-execute (lambda (x) (interactive "p") x))
    (error (prin1 (car e))))
  ;; ---- print a closure --------------------------------------------------------
  (let ((f (let ((z 9)) (lambda (x) (+ x z)))))
    (prin1 (stringp (prin1-to-string f))))
  ;; ---- read-only strings -------------------------------------------------------
  (condition-case e (aset "ro" 0 ?x) (error (prin1 (car e))))
  ;; ---- string to number edge ----------------------------------------------------
  (prin1 (list (string-to-number " 42x") (string-to-number "-0.5e2")
               (string-to-number "" ) (string-to-number "1e" )))
  (prin1 (list (string-to-number "ff" 16) (string-to-number "17" 8)))
  ;; ---- buffer-swap-text error ----------------------------------------------------
  (condition-case e
      (with-temp-buffer (buffer-swap-text 5))
    (error (prin1 (car e)))))
(progn (prin1 'eval6-done))
