;; probe_eval10 — processes, charsets, command-loop misc.
(defun pe10 (label v) (princ label) (princ "=") (princ v) (princ " "))

;; --- processes ---
(pe10 'pl (process-lines "echo" "a" "b"))
(pe10 'pli (process-lines-ignore-status "sh" "-c" "echo x; exit 3"))
(pe10 'pl-err (condition-case e (process-lines "nonexistent-cmd-xyz") (file-missing 'file-missing) (error (car e))))
(let ((p (make-process :name "t" :command '("echo" "hi") :buffer (get-buffer-create " *pe10b*"))))
  (accept-process-output p 3)
  (pe10 'pc (list (processp p) (type-of p) (process-type p)
                  (integerp (process-id p)) (process-contact p)
                  (process-name p) (bufferp (process-buffer p))
                  (process-coding-system p)))
  (pe10 'pc-out (with-current-buffer (process-buffer p) (buffer-string)))
  (pe10 'pc-status (process-status p))
  (pe10 'pc-exit (process-exit-status p))
  (pe10 'pc-mark (and (markerp (process-mark p)) (marker-position (process-mark p))))
  (pe10 'pc-get (get-process "t")))
(let ((evs '()))
  (let ((p (make-process :name "pa" :command '("true") :sentinel (lambda (p e) (push (substring e 0 -1) evs)))))
    (accept-process-output p 3))
  (let ((p (make-process :name "pb" :command '("false") :sentinel (lambda (p e) (push (substring e 0 -1) evs)))))
    (accept-process-output p 3))
  (let ((p (make-process :name "pc2" :command '("sleep" "5") :sentinel (lambda (p e) (push (substring e 0 -1) evs)))))
    (kill-process p) (accept-process-output p 3))
  (pe10 'evs (nreverse evs)))
(let ((fgot nil))
  (let ((p (make-process :name "pq" :command '("cat") :filter (lambda (pr s) (setq fgot s)))))
    (process-send-string p "xy\n")
    (process-send-eof p)
    (accept-process-output p 3)
    (pe10 'fgot fgot)))
(let ((p (make-process :name "pl2" :command '("true"))))
  (pe10 'plist (progn (set-process-plist p '(a 1)) (process-get p 'a)))
  (pe10 'pquery (list (process-query-on-exit-flag p)
                      (progn (set-process-query-on-exit-flag p nil)
                             (process-query-on-exit-flag p))))
  (pe10 'pcoding (progn (set-process-coding-system p 'latin-1 'utf-8)
                        (process-coding-system p)))
  (pe10 'pdel (progn (delete-process p) (memq p (process-list)))))
(let ((p (make-process :name "s3" :command '("sleep" "5"))))
  (pe10 'stop (progn (stop-process p) (process-status p)))
  (pe10 'cont (progn (continue-process p) (process-status p)))
  (delete-process p))
(pe10 'sig (signal-process 999999 'SIGKILL))
(pe10 'start (let ((p (start-process "sp" " *pe10sp*" "echo" "zz")))
               (accept-process-output p 3)
               (with-current-buffer " *pe10sp*" (buffer-string))))
(pe10 'gbp (processp (get-buffer-process " *pe10sp*")))
(pe10 'plist-len (>= (length (process-list)) 1))
(pe10 'idpf (let ((p (make-process :name "idp" :command '("echo" "w") :buffer (get-buffer-create " *pe10i*"))))
              (accept-process-output p 3)
              (with-current-buffer " *pe10i*" (buffer-string))))
(pe10 'netinfo (consp (network-interface-info "lo0")))
(pe10 'fna (format-network-address [127 0 0 1 8080]))
(pe10 'fna2 (format-network-address [127 0 0 1 8080] t))
(pe10 'fna3 (format-network-address '(127 0 0 1)))
(pe10 'lsp (> (length (list-system-processes)) 1))
(pe10 'pat (let ((pa (process-attributes (emacs-pid)))) (and (consp pa) (assq 'comm pa) t)))
(pe10 'prcp (condition-case e (process-running-child-p nil) (error (car e))))
(pe10 'pipe (let ((p (make-pipe-process :name "pp" :buffer (get-buffer-create " *pe10p*"))))
              (process-send-string p "abc")
              (accept-process-output p 1)
              (list (process-type p) (with-current-buffer " *pe10p*" (buffer-string)))))

;; --- charsets / char-code properties ---
(pe10 'cp (list (charsetp 'ascii) (charsetp 'nope)))
(pe10 'gcp (list (get-char-code-property ?a 'general-category)
                 (get-char-code-property ?A 'general-category)
                 (get-char-code-property ?5 'general-category)))
(pe10 'ccpd (char-code-property-description 'general-category 'Lu))
(pe10 'pcp (progn (put-char-code-property ?x 'my-prop 'VAL)
                  (get-char-code-property ?x 'my-prop)))
(pe10 'ca (charset-after))
(pe10 'cst (list (coding-system-type 'utf-8) (coding-system-type 'no-conversion)))
(pe10 'cspl (coding-system-charset-list 'utf-8))
(pe10 'dcp-err (condition-case e (define-char-code-property 'my-prop '(a b)) (error 'err)))
(pe10 'csp-err (condition-case e (set-charset-plist 'nosuchcs '(a 1)) (error (car e))))
(pe10 'csp (progn (define-charset 'mine [0 255 -1 -1 -1 nil nil nil nil nil nil nil nil nil nil nil nil nil]
                                  :invalid-code 255 :code-offset 0)
                  (set-charset-plist 'mine '(a 1)) (charset-plist 'mine)))
(pe10 'csp-arity (condition-case e (define-charset 'mine2) (wrong-number-of-arguments 'wna) (error (car e))))
(pe10 'gsp (progn (put-charset-property 'mine 'foo 'bar)
                  (get-charset-property 'mine 'foo)))
(pe10 'dca (progn (define-charset-alias 'alias1 'ascii) (charsetp 'alias1)))
(pe10 'fcs (list (find-charset-string "abc") (find-charset-string "ab\x00e9")))
(pe10 'crm (list (char-resolve-modifiers ?\C-a) (char-resolve-modifiers ?\M-x)))
(pe10 'fcr (with-temp-buffer (insert "x") (find-charset-region 1 2)))
(pe10 'uc (condition-case e (progn (unify-charset 'ucs) (charsetp 'ucs)) (error (car e))))
(pe10 'skcsi (progn (set-keyboard-coding-system-internal 'latin-1) keyboard-coding-system))
(pe10 'mtt (char-table-p (make-translation-table '((?a . ?b)))))
(pe10 'fcsri (with-temp-buffer (insert "xy") (consp (find-coding-systems-region-internal 1 2))))

;; --- command-loop / terminal misc ---
(pe10 'bo (byteorder))
(pe10 'em (condition-case e (exit-minibuffer) (error (car e))))
(pe10 'siae (condition-case e (self-insert-and-exit) (error (car e))))
(pe10 'sul (condition-case e (scroll-up-line 2) (error (car e))))
(pe10 'sdl (condition-case e (scroll-down-line 2) (error (car e))))
(pe10 'mtw (move-to-window-line-top-bottom))
(pe10 'odf (open-dribble-file "/tmp/pe10drbl"))
(pe10 'sdei (standard-display-european-internal))
(pe10 'fbs (with-temp-buffer (insert "hello") (filter-buffer-substring 1 4)))
(pe10 'fbsd (with-temp-buffer (insert "hello") (filter-buffer-substring 1 4 t) (buffer-string)))
(pe10 'fbsf (let ((filter-buffer-substring-function
                   (lambda (b e d) (concat "[" (buffer-substring b e) "]"))))
              (with-temp-buffer (insert "hello") (filter-buffer-substring 1 4))))
(pe10 'row (condition-case e (recenter-other-window) (error (car e))))

;; --- new variables ---
(pe10 'vars (mapcar (lambda (s) (boundp s))
                    '(file-name-shadow-mode show-help-function glyph-table
                      system-type emacs-build-system delete-trailing-lines
                      keyboard-coding-system charset-list
                      default-process-coding-system
                      default-file-name-coding-system emacs-basic-display)))
(pe10 'v-fnsm file-name-shadow-mode)
(pe10 'v-shf show-help-function)
(pe10 'v-dtl delete-trailing-lines)
(pe10 'v-kcs keyboard-coding-system)
(pe10 'v-dpcs default-process-coding-system)
(pe10 'v-fncs file-name-coding-system)
(princ "\n")
