;; Gap probe: exercise never-covered subrs with valid args.

;; --- special-form raw handlers ---
(ignore-errors (and t 1 2))
(ignore-errors (or nil nil 3))
(ignore-errors (prog1 'a 'b 'c))
(ignore-errors (function (lambda (x) x)))
(ignore-errors (function 'car))
(ignore-errors (condition-case e (error "x") (error e)))
(ignore-errors (run-hook-wrapped 'hooks (lambda (f) (funcall f) nil)))
(ignore-errors (run-hook-with-args 'hooks 1 2))
(ignore-errors (run-hook-with-args-until-failure 'hooks))
(ignore-errors (run-hook-with-args-until-success 'hooks))
(ignore-errors (command-execute 'self-insert-command))
(ignore-errors (compiled-function-p 'car))
(ignore-errors (subr-native-lambda-list 'car))
(ignore-errors (locate-library "subr"))
(ignore-errors (memory-info))
(ignore-errors (byte-code "" [] 0))

;; --- misc uncovered ---
(ignore-errors (user-login-name))
(ignore-errors (invocation-name))
(ignore-errors (get-file-buffer "nonexistent"))
(ignore-errors (buffer-hash))
(ignore-errors (buffer-hash (current-buffer)))
(ignore-errors (window-min-width))
(ignore-errors (window-min-height))
(ignore-errors (secure-hash 'md5 "abc"))
(ignore-errors (secure-hash 'sha256 "abc" 0 3 t))
(ignore-errors (time-convert 1000000 'list))
(ignore-errors (time-convert '(0 0) 'integer))
(ignore-errors (help-function-arglist 'car))
(ignore-errors (help-function-arglist 'car t))
(ignore-errors (file-attributes-lessp (file-attributes ".") (file-attributes "..")))
(ignore-errors (make-interpreted-closure '((x . 1)) '(x) nil))
(ignore-errors (bool-vector-count-consecutive (make-bool-vector 4 t) t 0))
(ignore-errors (bool-vector-count-population (make-bool-vector 4 t) 0))
(ignore-errors (bool-vector-not (make-bool-vector 3 t)))
(ignore-errors (bool-vector-set-difference (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-intersection (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-union (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-exclusive-or (make-bool-vector 3 t) (make-bool-vector 3 nil)))
(ignore-errors (bool-vector-subsetp (make-bool-vector 3 t) (make-bool-vector 3 nil)))

;; --- buffer primitives ---
(ignore-errors (insert-buffer-substring (current-buffer) 1 2))
(ignore-errors (insert-char ?a 3))
(ignore-errors (insert-char ?b 2 t))
(ignore-errors (open-line 1))
(ignore-errors (delete-backward-char 1))
(ignore-errors (exchange-point-and-mark))
(ignore-errors (set-marker (make-marker) 1))
(ignore-errors (set-marker (make-marker) 1 (current-buffer)))
(ignore-errors (move-to-column 2))
(ignore-errors (move-to-column 0 t))
(ignore-errors (symbol-at-point))
(ignore-errors (thing-at-point 'word))
(ignore-errors (thing-at-point 'symbol t))
(ignore-errors (bury-buffer))
(ignore-errors (bury-buffer (current-buffer)))
(ignore-errors (previous-property-change 1))
(ignore-errors (previous-property-change 1 (current-buffer)))
(ignore-errors (append-next-kill))

(with-temp-buffer
  (insert "aa\n\n\nbb\n\ncc\n")
  (ignore-errors (delete-blank-lines))
  (goto-char (point-min))
  (ignore-errors (delete-blank-lines)))

;; --- buffer extra ---
(with-temp-buffer
  (insert "foo bar\nbaz foo\nqux\n")
  (ignore-errors (how-many "foo"))
  (ignore-errors (count-matches "ba."))
  (goto-char (point-min))
  (ignore-errors (keep-lines "foo"))
  (goto-char (point-min))
  (insert "one\ntwo\nthree\n")
  (ignore-errors (flush-lines "o"))
  (ignore-errors (sort-lines nil (point-min) (point-max)))
  (ignore-errors (reverse-region (point-min) (point-max)))
  (goto-char (point-min))
  (insert "abc")
  (ignore-errors (subst-char-in-region 1 4 ?a ?z))
  (ignore-errors (translate-region 1 4 (make-char-table 'generic nil)))
  (ignore-errors (how-many "." 1 nil t)))

(with-temp-buffer
  (insert "aaa bbb")
  (ignore-errors (replace-regexp "a+" "X"))
  (goto-char (point-min))
  (ignore-errors (replace-string "b" "Y"))
  (goto-char (point-min))
  (insert "xy")
  (ignore-errors (transpose-regions 1 2 2 4)))

(with-temp-buffer
  (insert "aGVsbG8=")
  (ignore-errors (base64-decode-region 1 9))
  (goto-char (point-min))
  (insert "hello")
  (ignore-errors (base64-encode-region 1 6))
  (ignore-errors (base64url-encode-region 1 6 t))
  (ignore-errors (secure-hash-region 'sha256 1 6)))

(with-temp-buffer
  (insert "text")
  (let ((b2 (generate-new-buffer "swap")))
    (ignore-errors (buffer-swap-text b2))))

(with-temp-buffer
  (insert "abcdef")
  (put-text-property 1 3 'face 'bold)
  (ignore-errors (next-char-property-change 1))
  (ignore-errors (previous-char-property-change 6))
  (ignore-errors (text-property-not-all 1 6 'face 'bold))
  (ignore-errors (text-property-any 1 6 'face nil))
  (ignore-errors (remove-list-of-text-properties 1 6 '(face)))
  (ignore-errors (put-char-property 1 2 'face 'x (current-buffer)))
  (ignore-errors (add-face-text-property 1 3 'italic))
  (ignore-errors (get-pos-property 1 'face))
  (ignore-errors (get-char-property-and-overlay 1 'face))
  (ignore-errors (field-beginning))
  (ignore-errors (field-end 1))
  (ignore-errors (field-string 1))
  (ignore-errors (field-string-no-properties 1))
  (ignore-errors (delete-field 1))
  (ignore-errors (constrain-to-field 3 1))
  (ignore-errors (compute-motion 1 '(1 . 0) 4 '(4 . 0) 0 10 (selected-window)))
  (ignore-errors (vertical-motion 1))
  (ignore-errors (vertical-motion '(1 . 0) (selected-window)))
  (ignore-errors (line-pixel-height))
  (ignore-errors (window-line-height))
  (ignore-errors (backward-prefix-chars))
  (ignore-errors (move-point-visually 3))
  (ignore-errors (marker-last-position (make-marker))))

;; --- editor module ---
(ignore-errors (set-window-buffer (selected-window) (current-buffer)))
(ignore-errors (get-buffer-window))
(ignore-errors (get-buffer-window (current-buffer)))
(ignore-errors (minibuffer-window))
(ignore-errors (window-margins))
(ignore-errors (window-margins (selected-window)))
(ignore-errors (where-is-internal 'self-insert-command))
(ignore-errors (where-is-internal 'self-insert-command nil t))
(ignore-errors (apropos-internal "^car$"))
(ignore-errors (apropos-internal "point" 'commandp))
(ignore-errors (try-completion "al" '("alpha" "beta")))
(ignore-errors (all-completions "a" '("alpha" "beta")))
(ignore-errors (test-completion "alpha" '("alpha" "beta")))
(ignore-errors (find-file-noselect "Cargo.toml"))
(ignore-errors (directory-files "."))
(ignore-errors (directory-files "." nil "^Cargo"))
(ignore-errors (directory-files "." t nil t))
(ignore-errors (file-writable-p "Cargo.toml"))
(ignore-errors (file-symlink-p "."))
(ignore-errors (copy-to-buffer (current-buffer) 1 2))
(ignore-errors (call-process "echo" nil t nil "hi"))
(ignore-errors (call-process-region 1 5 "cat"))
(ignore-errors (substitute-command-keys "\\[self-insert-command]"))
(ignore-errors (set-keymap-parent (make-keymap) nil))
(ignore-errors (current-kill 0))
(ignore-errors (current-kill 0 t))
(let ((o (make-overlay 1 2)))
  (ignore-errors (remove-overlays))
  (ignore-errors (previous-overlay-change 5)))
(ignore-errors (describe-key [?a]))
(ignore-errors (display-buffer (current-buffer)))

;; --- hashfn / value gaps ---
(let ((h (make-hash-table)))
  (puthash 'a 1 h)
  (ignore-errors (maphash (lambda (k v) nil) h))
  (ignore-errors (hash-table-count h))
  (ignore-errors (hash-table-test h))
  (ignore-errors (hash-table-size h))
  (ignore-errors (clrhash h))
  (ignore-errors (remhash 'a h)))
(dolist (test '(eq eql equal))
  (let ((h (make-hash-table :test test)))
    (puthash 'k 1 h)
    (puthash "s" 2 h)
    (puthash 3 3 h)
    (puthash 1.5 4 h)
    (puthash '(c . d) 5 h)
    (puthash [1 2] 6 h)
    (puthash (make-marker) 7 h)
    (puthash 'car 8 h)
    (puthash (current-buffer) 9 h)
    (puthash (make-hash-table) 10 h)
    (puthash (record 'r) 11 h)
    (puthash (selected-window) 12 h)
    (puthash (selected-frame) 13 h)
    (puthash (lambda (x) x) 14 h)
    (ignore-errors (gethash 'k h))
    (ignore-errors (gethash 'nope h 'default))
    (ignore-errors (hash-table-test h))
    (ignore-errors (hash-table-rehash-size h))
    (ignore-errors (hash-table-rehash-threshold h))
    (ignore-errors (hash-table-weakness h))))
(ignore-errors (hash-table-p 5))
(ignore-errors (hash-table-count 5))
(ignore-errors (hash-table-size 5))
(ignore-errors (hash-table-test 5))
(ignore-errors (gethash 'x 5))
(ignore-errors (puthash 'x 1 5))
(ignore-errors (remhash 'x 5))
(ignore-errors (clrhash 5))
(ignore-errors (maphash (lambda (k v) nil) 5))
(ignore-errors (sxhash 'x))
(ignore-errors (sxhash-equal '(a b)))
(ignore-errors (define-hash-table-test 'mytest 'eq 'sxhash))

;; --- printfn gaps ---
(ignore-errors (terpri 3))
(ignore-errors (with-output-to-string (princ "hi") (terpri)))
(ignore-errors (write-char 65))
(ignore-errors (prin1-to-string 'x t))
(ignore-errors (output-switches))
(ignore-errors (print "abc"))

;; --- strfn/seq/reader/regexp gaps ---
(ignore-errors (split-string "a,b;c" "," nil ";"))
(ignore-errors (string-width "abc"))
(ignore-errors (string-width (make-string 3 ?x)))
(ignore-errors (subst-char-in-string ?a ?z "banana"))
(ignore-errors (subst-char-in-string ?a ?z "banana" t))
(ignore-errors (string-search "b" "abc"))
(ignore-errors (string-search "b" "abc" 2))
(ignore-errors (unibyte-string 65 66 67))
(ignore-errors (string-trim "  x  "))
(ignore-errors (string-trim-left "  x" " +"))
(ignore-errors (string-trim-right "x  " " +"))
(ignore-errors (string-trim "x" "[ab]+"))
(ignore-errors (aset (make-bool-vector 3 nil) 0 t))
(ignore-errors (read-from-string "#16rff"))
(ignore-errors (read-from-string "#36rz"))
(ignore-errors (read-from-string "#b2"))
(with-temp-buffer
  (insert "aaa bbb")
  (goto-char (point-max))
  (ignore-errors (search-backward "aaa"))
  (goto-char (point-max))
  (ignore-errors (search-backward "x" nil t))
  (goto-char (point-max))
  (ignore-errors (re-search-backward "b+"))
  (goto-char (point-max))
  (ignore-errors (re-search-backward "z" nil t)))

;; --- winxtra gaps ---
(ignore-errors (posn-at-x-y 0 0))
(ignore-errors (posn-at-x-y 1 1 (selected-window)))
(ignore-errors (terminal-live-p nil))
(ignore-errors (terminal-live-p (selected-frame)))
(ignore-errors (make-frame-visible))
(ignore-errors (set-window-vscroll nil 0))
(ignore-errors (set-window-vscroll (selected-window) 2))
(ignore-errors (set-window-new-total nil 10))
(ignore-errors (set-window-new-normal nil 1))

;; --- eval internals ---
(ignore-errors (call-interactively 'forward-char))
(ignore-errors (call-interactively (lambda () (interactive) 5)))
(ignore-errors (funcall (lambda (x) x)))
(ignore-errors (func-arity (function (lambda (&rest x) x))))
(ignore-errors (func-arity 'if))
(ignore-errors (eval-buffer))
(ignore-errors (load-file "/tmp/nonexistent-remacs.el"))
(ignore-errors (prin1-to-string
                (let ((b (get-buffer-create " tmpk")))
                  (kill-buffer b)
                  b)))
(let ((l (list 1 2 3)))
  (setcdr (cddr l) l)
  (ignore-errors (length l))
  (ignore-errors (member 9 l))
  (ignore-errors (nthcdr 9 l)))

;; --- printer gaps ---
(ignore-errors (prin1-to-string (make-symbol "g")))
(ignore-errors (prin1-to-string "a\"b\\c"))
(ignore-errors (prin1-to-string "\xc3\xa9"))
(ignore-errors (prin1-to-string (eval '(lambda (x) x))))
(ignore-errors (prin1-to-string (function (lambda (x)))))
(ignore-errors (prin1-to-string (function (lambda (&rest r) r))))
(ignore-errors (prin1-to-string (function (lambda (a &optional b) a))))
(ignore-errors (prin1-to-string (eval '(lambda () x) '((x . 5)))))
(ignore-errors (prin1-to-string '(` (,. x))))
(ignore-errors (prin1-to-string '`,@x))
(ignore-errors (prin1-to-string '`,.x))
(let ((l (list 1 2 3)))
  (setcdr (cddr l) l)
  (ignore-errors (prin1-to-string l))
  (ignore-errors (format "%s" l))
  (ignore-errors (princ-to-string l)))
(ignore-errors (prin1-to-string (exp 1000)))
(ignore-errors (prin1-to-string (- (exp 1000) (exp 1000))))
(ignore-errors (prin1-to-string -0.0))
(ignore-errors (prin1-to-string 1.5e300))
(ignore-errors (format "%e" 1.5))
(ignore-errors (format "%g" 123456.789))
(ignore-errors (format "%g" 0.000012345))
(let ((print-level 2))
  (ignore-errors (prin1-to-string '(a (b (c (d))))))
  (ignore-errors (princ-to-string '(a (b (c (d)))))))
(let ((print-length 3))
  (ignore-errors (prin1-to-string '(1 2 3 4 5)))
  (ignore-errors (princ-to-string '(1 2 3 4 5))))
(ignore-errors (print 'x))

;; --- editor gaps: frames/windows ---
(ignore-errors (frame-parameter nil 'modeline))
(ignore-errors (frame-parameter nil 'visibility))
(ignore-errors (frame-parameter nil 'minibuffer))
(ignore-errors (frame-parameter nil 'unsplittable))
(ignore-errors (frame-parameter nil 'no-accept-focus))
(ignore-errors (frame-parameter nil 'buffer-list))
(ignore-errors (frame-parameter nil 'name))
(ignore-errors (frame-parameter nil 'width))
(ignore-errors (frame-parameters))
(ignore-errors (frame-parameters (selected-frame)))
(ignore-errors (set-frame-parameter (selected-frame) 'probe-x 1))
(ignore-errors (modify-frame-parameters nil '((probe-y . 2))))
(ignore-errors (frame-parameter (selected-frame) 'probe-y))
(ignore-errors (frame-first-window))
(ignore-errors (frame-first-window (selected-frame)))
(ignore-errors (frame-root-window))
(ignore-errors (frame-selected-window))
(ignore-errors (frame-list))
(ignore-errors (frames-on-display-list))
(ignore-errors (visible-frame-list))
(ignore-errors (window-frame))
(ignore-errors (window-frame (selected-window)))
(ignore-errors (frame-live-p (selected-frame)))
(ignore-errors (frame-live-p nil))
(ignore-errors (window-live-p (selected-window)))
(ignore-errors (window-minibuffer-p))
(ignore-errors (window-minibuffer-p (selected-window)))
(ignore-errors (minibuffer-window-active-p (minibuffer-window)))
(ignore-errors (window-at-side-p (selected-window) 'bottom))
(ignore-errors (window-total-height))
(ignore-errors (window-total-width))
(ignore-errors (window-body-height))
(ignore-errors (window-body-width))
(ignore-errors (window-pixel-height))
(ignore-errors (window-pixel-width))
(ignore-errors (window-mode-line-height))
(ignore-errors (window-header-line-height))
(ignore-errors (window-tab-line-height))
(ignore-errors (window-line-height 1 (selected-window)))
(ignore-errors (window-inside-edges))
(ignore-errors (window-edges))
(ignore-errors (window-absolute-pixel-edges))
(ignore-errors (window-text-pixel-size))
(ignore-errors (window-scroll-bars))
(ignore-errors (window-fringes))
(ignore-errors (window-left-fringe-width))
(ignore-errors (window-right-fringe-width))
(ignore-errors (window-vscroll))
(ignore-errors (window-new-normal))
(ignore-errors (window-new-total))
(ignore-errors (window-use-time))
(ignore-errors (window-old-point))
(ignore-errors (window-start))
(ignore-errors (window-end))
(ignore-errors (window-end nil t))
(ignore-errors (window-point))
(ignore-errors (window-buffer))
(ignore-errors (window-dedicated-p))
(ignore-errors (window-prev-buffers))
(ignore-errors (window-next-buffers))
(ignore-errors (set-window-point (selected-window) 1))
(ignore-errors (set-window-start (selected-window) 1))
(ignore-errors (set-window-dedicated-p (selected-window) t))
(ignore-errors (set-window-hscroll (selected-window) 0))
(ignore-errors (window-hscroll))
(ignore-errors (pos-visible-in-window-p))
(ignore-errors (pos-visible-in-window-p nil nil t))
(ignore-errors (window-parameter (selected-window) 'no-other-window))
(ignore-errors (set-window-parameter (selected-window) 'probe 1))
(ignore-errors (window-parameters))
(ignore-errors (walk-windows (lambda (w) w)))
(ignore-errors (window-list))
(ignore-errors (window-list-1))
(ignore-errors (get-lru-window))
(ignore-errors (get-largest-window))
(ignore-errors (next-window))
(ignore-errors (previous-window))
(ignore-errors (other-window 1))
(ignore-errors (other-window -1))
(ignore-errors (window-combination-limit))
(ignore-errors (window-splittable-p))
(ignore-errors (window-splittable-p nil t))
(ignore-errors (split-window))
(ignore-errors (delete-window (selected-window)))
(ignore-errors (window-valid-p (selected-window)))

;; --- editor gaps: keymaps/keys ---
(ignore-errors (kbd "H-a"))
(ignore-errors (kbd "s-a"))
(ignore-errors (kbd "A-a"))
(ignore-errors (kbd "S-M-a"))
(ignore-errors (kbd "C-S-a"))
(ignore-errors (kbd "<delchar>"))
(ignore-errors (kbd "<deletechar>"))
(ignore-errors (kbd "<pageup>"))
(ignore-errors (kbd "<pagedown>"))
(ignore-errors (kbd "<prior>"))
(ignore-errors (kbd "<next>"))
(ignore-errors (kbd "<S-down>"))
(ignore-errors (kbd "<M-right>"))
(ignore-errors (kbd "C-M-S-x"))
(ignore-errors (single-key-description (event-convert-list '(hyper a))))
(ignore-errors (single-key-description (event-convert-list '(super a))))
(ignore-errors (single-key-description (event-convert-list '(alt a))))
(ignore-errors (single-key-description (event-convert-list '(control shift a))))
(ignore-errors (key-description [?\C-a ?b]))
(ignore-errors (key-description [?\M-x]))
(ignore-errors (key-description (kbd "C-M-f")))
(ignore-errors (key-description [f5]))
(ignore-errors (key-description [?\s-x]))
(ignore-errors (key-description (list ?a ?b)))
(ignore-errors (key-valid-p "C-M-S-x"))
(ignore-errors (key-valid-p "<f5>"))
(ignore-errors (key-valid-p "a b c"))
(ignore-errors (set-keymap-parent (make-keymap) 5))
(ignore-errors (set-keymap-parent 5 (make-keymap)))
(ignore-errors (set-keymap-parent (make-keymap) (list (make-keymap))))
(let ((p (make-keymap)) (c (make-keymap)))
  (define-key p "a" 'foo)
  (set-keymap-parent c p)
  (ignore-errors (lookup-key c "a"))
  (ignore-errors (keymap-parent c)))
(let ((p (make-keymap)) (c (make-keymap)))
  (define-key p "a" 'foo)
  (define-key c "b" 'bar)
  (set-keymap-parent c p)
  (ignore-errors (lookup-key c "b")))
(ignore-errors (lookup-key (current-global-map) "a" t))
(ignore-errors (lookup-key (current-global-map) "C-x" t))
(ignore-errors (lookup-key 5 "a"))
(ignore-errors (map-keymap (lambda (k v) v) (current-global-map)))
(ignore-errors (map-keymap (lambda (k v) v) (make-keymap)))
(ignore-errors (map-keymap (lambda (k v) v) 5))
(ignore-errors (accessible-keymaps (current-global-map)))
(ignore-errors (accessible-keymaps (current-global-map) "C-x"))
(ignore-errors (accessible-keymaps (current-global-map) [24]))
(ignore-errors (accessible-keymaps 5))
(ignore-errors (where-is-internal 'undo (list (current-global-map)) t))
(ignore-errors (where-is-internal 'undo nil nil t))
(ignore-errors (where-is-internal 'undefined-cmd-xyz))
(ignore-errors (command-remapping 'self-insert-command))
(ignore-errors (command-remapping 'self-insert-command nil (list (make-keymap))))
(ignore-errors (key-binding "C-a"))
(ignore-errors (key-binding "\C-a"))
(ignore-errors (key-binding [?\C-a]))
(ignore-errors (key-binding "C-x" t))
(ignore-errors (key-binding "C-x" nil t))
(ignore-errors (key-binding "C-x" t t))
(ignore-errors (local-key-binding "a"))
(ignore-errors (global-key-binding "a"))
(ignore-errors (minor-mode-key-binding 'auto-fill-function))
(ignore-errors (local-set-key "a" 'ignore))
(ignore-errors (global-set-key "z" 'ignore))
(ignore-errors (local-unset-key "a"))
(ignore-errors (global-unset-key "z"))
(ignore-errors (undefine-key (current-global-map) "a"))
(ignore-errors (define-key (current-global-map) [tab] 'ignore))
(ignore-errors (define-key (current-global-map) (kbd "<f5>") 'ignore))
(ignore-errors (define-key (current-global-map) "zz" nil))
(ignore-errors (use-global-map (current-global-map)))
(ignore-errors (use-local-map nil))
(ignore-errors (use-local-map (make-keymap)))
(ignore-errors (current-local-map))
(ignore-errors (current-global-map))
(ignore-errors (current-active-maps))
(ignore-errors (current-active-maps t))
(ignore-errors (make-keymap "name"))
(ignore-errors (make-sparse-keymap))
(ignore-errors (make-sparse-keymap "name"))
(ignore-errors (copy-keymap (current-global-map)))
(ignore-errors (keymapp (current-global-map)))
(ignore-errors (keymapp 5))
(ignore-errors (keymap-prompt (current-global-map)))
(ignore-errors (suppress-keymap (make-keymap)))
(ignore-errors (suppress-keymap (make-keymap) t))
(ignore-errors (text-char-description 65))
(ignore-errors (text-char-description 7))
(ignore-errors (text-char-description 128))
(ignore-errors (describe-buffer-bindings (current-buffer) "a"))
(ignore-errors (read-key-sequence ""))
(ignore-errors (describe-key [?a] nil nil t))

;; --- editor gaps: buffers/files ---
(ignore-errors (file-exists-p "Cargo.toml"))
(ignore-errors (file-directory-p "."))
(ignore-errors (file-regular-p "Cargo.toml"))
(ignore-errors (file-readable-p "Cargo.toml"))
(ignore-errors (file-executable-p "Cargo.toml"))
(ignore-errors (file-newer-than-file-p "Cargo.toml" "Cargo.lock"))
(ignore-errors (file-attributes "Cargo.toml"))
(ignore-errors (file-attributes "Cargo.toml" 'integer))
(ignore-errors (file-name-nondirectory "/a/b/c"))
(ignore-errors (file-name-directory "/a/b/c"))
(ignore-errors (file-name-extension "foo.el"))
(ignore-errors (file-name-sans-extension "foo.el"))
(ignore-errors (file-name-as-directory "/tmp"))
(ignore-errors (expand-file-name "x" "/tmp"))
(ignore-errors (expand-file-name "~/x"))
(ignore-errors (abbreviate-file-name "/tmp/x"))
(ignore-errors (substitute-in-file-name "$HOME/x"))
(ignore-errors (directory-file-name "/tmp/"))
(ignore-errors (make-temp-name "/tmp/r"))
(ignore-errors (file-name-absolute-p "/x"))
(ignore-errors (file-name-absolute-p "x"))
(ignore-errors (file-name-concat "a" "b" "c"))
(ignore-errors (default-directory))
(ignore-errors (file-name-completion "Car" "."))
(ignore-errors (file-name-all-completions "Car" "."))
(ignore-errors (file-name-completion "zz-no" "."))
(ignore-errors (file-accessible-directory-p "."))
(ignore-errors (file-modes "Cargo.toml"))
(ignore-errors (file-remote-p "/tmp/x"))
(ignore-errors (unhandled-file-name-directory "/tmp/x"))
(ignore-errors (file-local-copy "/tmp/x"))
(ignore-errors (file-truename "."))
(ignore-errors (verify-visited-file-modtime))
(ignore-errors (clear-visited-file-modtime))
(ignore-errors (visited-file-modtime))
(ignore-errors (set-visited-file-modtime))
(ignore-errors (buffer-file-name))
(ignore-errors (buffer-file-truename))
(ignore-errors (get-buffer-create " probeh"))
(ignore-errors (generate-new-buffer "pz"))
(ignore-errors (generate-new-buffer-name "p"))
(ignore-errors (generate-new-buffer-name "*scratch*"))
(ignore-errors (rename-buffer "probename"))
(ignore-errors (rename-buffer "probename2" t))
(ignore-errors (buffer-name (get-buffer "probename2")))
(ignore-errors (set-buffer (get-buffer "*scratch*")))
(ignore-errors (buffer-list))
(ignore-errors (buffer-list (selected-frame)))
(ignore-errors (other-buffer))
(ignore-errors (other-buffer (current-buffer)))
(ignore-errors (other-buffer (current-buffer) t))
(ignore-errors (last-buffer))
(ignore-errors (last-buffer nil t))
(ignore-errors (buffer-name))
(ignore-errors (buffer-name (current-buffer)))
(ignore-errors (buffer-file-name))
(ignore-errors (get-buffer "*scratch*"))
(ignore-errors (get-buffer "nonexistent-xyz"))
(ignore-errors (get-buffer-create "zz"))
(ignore-errors (buffer-modified-p))
(ignore-errors (buffer-modified-p (current-buffer)))
(ignore-errors (set-buffer-modified-p t))
(ignore-errors (restore-buffer-modified-p nil))
(ignore-errors (buffer-modified-tick))
(ignore-errors (buffer-chars-modified-tick))
(ignore-errors (buffer-last-name))
(ignore-errors (buffer-enable-undo))
(ignore-errors (buffer-enable-undo (current-buffer)))
(ignore-errors (buffer-disable-undo))
(ignore-errors (buffer-disable-undo (current-buffer)))
(ignore-errors (buffer-base-buffer))
(ignore-errors (buffer-base-buffer (current-buffer)))
(ignore-errors (buffer-local-variables))
(ignore-errors (buffer-local-value 'fill-column (current-buffer)))
(ignore-errors (buffer-substring-no-properties 1 3))
(ignore-errors (erase-buffer))
(ignore-errors (kill-buffer "zz"))
(ignore-errors (kill-buffer nil))
(ignore-errors (unbury-buffer))
(ignore-errors (nlistp (current-buffer)))
(ignore-errors (list-buffers-directory))
(ignore-errors (buffer-size))
(ignore-errors (buffer-size (current-buffer)))
(ignore-errors (current-buffer))
(ignore-errors (buffer-live-p (current-buffer)))
(ignore-errors (buffer-live-p nil))
(ignore-errors (get-file-buffer "x"))
(ignore-errors (find-buffer-visiting "x"))
(ignore-errors (find-buffer-visiting "x" (lambda (b) b)))
(ignore-errors (make-indirect-buffer (current-buffer) "ind"))
(ignore-errors (clone-indirect-buffer "ind2" nil))
(ignore-errors (clone-buffer "ind3"))
(ignore-errors (insert-buffer-substring-as-yank (current-buffer)))

;; --- eval.rs gaps ---
(ignore-errors (setq t 1))
(ignore-errors (set 't 1))
(ignore-errors (setq nil 3))
(ignore-errors (set 'nil 3))
(ignore-errors (condition-case e (throw 'notacatch 1) (no-catch 'hit) (error 'err)))
(ignore-errors (call-interactively 'ignore))
(ignore-errors (call-interactively (lambda () (interactive "i") 7)))
(ignore-errors (call-interactively 'kill-buffer))
(ignore-errors (command-execute 'ignore))
(ignore-errors (signal 'error '("oops")))
(ignore-errors (condition-case e (signal 'arith-error nil) (arith-error 'ok)))
(ignore-errors (condition-case e (signal 'void-variable '(x)) (void-variable 'ok)))
(ignore-errors (condition-case e (signal 'error '("a" "b")) (error 'ok)))
(ignore-errors (condition-case e (signal 'undefined-error nil) (error 'other)))
(ignore-errors (define-error 'my-cond "msg" 'error))
(ignore-errors (condition-case e (signal 'my-cond '(data)) (my-cond 'handled)))
(ignore-errors (bound-and-true-p undefined-var-xyz))
(ignore-errors (makunbound 'fill-column))
(ignore-errors (fmakunbound 'nonexistent-fn-xyz))
(ignore-errors (special-variable-p 'fill-column))
(ignore-errors (defvar myprobevar 42 "doc"))
(ignore-errors (boundp 'myprobevar))
(ignore-errors (default-boundp 'fill-column))
(ignore-errors (set-default 'myprobevar 9))
(ignore-errors (default-value 'myprobevar))
(ignore-errors (kill-local-variable 'myprobevar))
(ignore-errors (make-variable-buffer-local 'myprobevar))
(ignore-errors (local-variable-p 'myprobevar))
(ignore-errors (local-variable-if-set-p 'myprobevar))
(ignore-errors (variable-binding-locus 'myprobevar))
(ignore-errors (indirect-variable 'myprobevar))
(ignore-errors (keywordp :x))
(ignore-errors (custom-variable-p 'myprobevar))
(ignore-errors (commandp 'self-insert-command))
(ignore-errors (commandp '(lambda (x) (interactive) x)))
(ignore-errors (commandp "x"))
(ignore-errors (interactive-p))
(ignore-errors (called-interactively-p))
(ignore-errors (called-interactively-p 'any))
(ignore-errors (functionp 'car))
(ignore-errors (functionp '(lambda (x) x)))
(ignore-errors (subrp 'car))
(ignore-errors (subr-arity 'car))
(ignore-errors (subr-name 'car))
(ignore-errors (apropos-internal "^zz-no-match$" nil))

;; --- eval/value ---
(ignore-errors (eq 1.5 1.5))
(ignore-errors (equal-including-properties "a" "a"))
(ignore-errors (type-of (make-bool-vector 2 t)))
(ignore-errors (record 'foo 1 2))
(ignore-errors (records 'x))
