;; probe_misc3 — misc builtins coverage: events, time, keymaps,
;; env, version, hash, char-tables, errors

;; ---- events ----
(event-convert-list '(control ?a))
(event-convert-list '(meta control ?b))
(event-convert-list '(shift ?a))
(event-convert-list '(control meta ?x))
(condition-case e (event-convert-list '(bogus-mod ?a)) (error e))
(event-modifiers ?\C-a)
(event-modifiers 'C-M-x)
(event-modifiers 'S-down)
(event-modifiers 'mouse-1)
(event-modifiers 'double-click)
(event-basic-type ?\C-a)
(event-basic-type 'C-M-x)
(event-basic-type 'S-down)
(event-basic-type 'mouse-1)
(event-basic-type 'double-down-mouse-3)
(condition-case e (event-convert-list nil) (error e))
(key-valid-p "<f1>")
(key-valid-p "C-f")
(key-valid-p "<badkey>")
(key-valid-p nil)

;; ---- keymap internals ----
(make-composed-keymap (list (make-sparse-keymap) global-map))
(make-composed-keymap (make-sparse-keymap))
(keymap-of '(keymap (t . ignore)))
(set-keymap-parent (make-sparse-keymap) (make-keymap))
(map-keymap (lambda (k v) (cons k v)) global-map)
(map-keymap 'ignore (make-sparse-keymap) t)
(copy-keymap (make-keymap))
(copy-keymap global-map)
(command-remapping 'self-insert-command)
(command-remapping 'no-such-cmd)

;; ---- env ----
(getenv "PATH")
(getenv "HOME")
(getenv-internal "PATH")
(getenv-internal "NO_SUCH_VAR_XYZ")
(setenv "PROBE_VAR_XYZ" "value1")
(getenv "PROBE_VAR_XYZ")
(setenv "PROBE_VAR_XYZ")
(getenv "PROBE_VAR_XYZ")
(setenv "PROBE_VAR_XYZ" "v2" t)
(setenv-internal "PROBE_VAR_XYZ" "v3")
process-environment

;; ---- time ----
(emacs-uptime)
(emacs-uptime "%S")
(current-time)
(current-time-string)
(current-time-zone)
(decode-time)
(decode-time (current-time))
(decode-time (current-time) t)
(encode-time 0 0 0 1 1 2020)
(encode-time '(0 0 0 1 1 2020))
(encode-time 30 15 12 15 6 2024 nil nil nil)
(date-to-time "Sat Jun 15 12:00:00 2024")
(condition-case e (date-to-time "garbage") (error e))
(days-between "2024-01-01" "2024-01-05")
(days-between "2020-02-28" "2020-03-01")
(time-to-days (current-time))
(time-to-day-in-year (current-time))
(date-leap-year-p 2024)
(date-leap-year-p 2023)
(time-since (current-time))
(time-subtract (current-time) (current-time))
(time-add (current-time) '(0 0))
(time-equal-p (current-time) (current-time))
(time-less-p '(0 0) (current-time))
(days-to-time 365)
(float-time)
(float-time (current-time))
(seconds-to-time 3661)
(condition-case e (time-convert (current-time) 'integer) (error e))
(condition-case e (time-convert (current-time) 'list) (error e))

;; ---- version ----
(version-to-list "1.2.3")
(version-to-list "31.1")
(version-list-< '(1 0) '(2 0))
(version-list-< '(1 2) '(1 2))
(version-list-<= '(1 0) '(1 0))
(version-list-= '(1 0) '(1 0))
(version= "1.0" "1.0")
(version-list-not-zero '(0 0 1))
(version-list-not-zero '(0 0))
(emacs-version)
(emacs-pid)

;; ---- errors ----
(error-message-string '(wrong-type-argument (stringp 5)))
(error-message-string '(arith-error))
(error-message-string nil)
(condition-case e (signal 'error '("custom msg")) (error e))
(condition-case e (signal 'void-variable '(x-y-z)) (error e))
(condition-case e (signal 'wrong-type-argument '(stringp 42)) (error e))
(condition-case e (signal 'args-out-of-range '(1 2 3)) (error e))
(condition-case e (signal 'file-error '("msg" "/path")) (error e))
(condition-case e (signal 'scan-error '("msg" 1 2)) (error e))
(condition-case e (signal 'arith-error nil) (error e))
(condition-case e (signal 'end-of-buffer nil) (error e))
(condition-case e (signal 'beginning-of-buffer nil) (error e))
(condition-case e (signal 'buffer-read-only '(*scratch*)) (error e))
(condition-case e (signal 'mark-inactive nil) (error e))
(condition-case e (signal 'text-read-only nil) (error e))
(condition-case e (signal 'circular-list '((a))) (error e))
(condition-case e (signal 'invalid-function '(x)) (error e))
(condition-case e (signal 'wrong-number-of-arguments '(f 5)) (error e))
(condition-case e (signal 'no-catch '(tag val)) (error e))
(condition-case e (signal 'invalid-read-syntax '("?" 1 2)) (error e))
(condition-case e (signal 'undefined-color '(c)) (error e))
(condition-case e (signal 'void-function '(nosuchfn)) (error e))
(condition-case e (signal 'setting-constant '(nil)) (error e))
(condition-case e (signal 'user-error '("user msg")) (error e))
(condition-case e (signal 'quit nil) (quit 'caught))
(condition-case e (error "msg %s" "arg") (error e))
(condition-case e (user-error "u %d" 4) (error e))
(condition-case e (warn "w %s" "x") (error e))
(condition-case e (display-warning 'test "msg") (error e))
(condition-case e (message "m %s" "y") (error e))
(message-box "box")
(message-or-box "mbox")
(condition-case e (ding) (error e))
(condition-case e (beep) (error e))

;; ---- arity/docs ----
(func-arity 'car)
(func-arity 'format)
(func-arity 'if)
(func-arity 'apply)
(func-arity (lambda (a &optional b) a))
(func-arity '(lambda (a) a))
(condition-case e (func-arity 5) (error e))
(subr-arity (symbol-function 'car))
(subr-arity (symbol-function 'format))
(indirect-function 'car)
(indirect-function 'forward-char t)
(symbol-function 'car)
(functionp 'car)
(functionp 'lambda)
(subrp (symbol-function 'car))
(subrp 'car)
(subr-native-elisp-p (symbol-function 'car))
(primitive-function-p 'car)
(condition-case e (function-get 'car 'x) (error e))
(condition-case e (function-put 'car 'k 'v) (error e))
(special-form-p 'if)
(special-form-p 'car)
(macrop 'when)
(macrop 'car)
(macrop 'and)

;; ---- get-file-buffer / misc buffer ----
(get-file-buffer "/etc/hosts")
(get-file-buffer "/nonexistent-xyz")
(find-buffer-visiting "/etc/hosts")
(buffer-base-buffer)
(set-buffer-multibyte t)
(condition-case e (bufferpos-to-filepos 1) (error e))
(condition-case e (filepos-to-bufferpos 1) (error e))

;; ---- char tables ----
(let ((ct (make-char-table 'test 'val)))
  (char-table-p ct)
  (char-table-subtype ct)
  (char-table-parent ct)
  (set-char-table-parent ct nil)
  (char-table-extra-slot ct 0)
  (set-char-table-extra-slot ct 0 'extra)
  (char-table-extra-slot ct 0)
  (char-table-range ct ?a)
  (set-char-table-range ct ?a 'va)
  (char-table-range ct ?a)
  (set-char-table-range ct '(?a . ?z) 'az)
  (char-table-range ct ?m)
  (set-char-table-range ct t 'all)
  (char-table-range ct ?x)
  (map-char-table (lambda (k v) (list k v)) ct)
  (condition-case e (optimize-char-table ct) (error e)))
(let ((d (make-display-table)))
  ;; `display-table-p' is not a GNU function; exercise the void path.
  (condition-case e (display-table-p d) (error e))
  ;; `standard-display-table' is a variable in GNU, not a function.
  (condition-case e (standard-display-table) (error e))
  (condition-case e (display-table-slot d 0) (error e))
  (condition-case e (set-display-table-slot d 0 ?x) (error e))
  (condition-case e (describe-display-table d) (error e))
  (condition-case e (describe-vector d) (error e)))

;; ---- secure hash / crypto ----
(secure-hash 'md5 "abc")
(secure-hash 'sha1 "abc")
(secure-hash 'sha224 "abc")
(secure-hash 'sha256 "abc")
(secure-hash 'sha384 "abc")
(secure-hash 'sha512 "abc")
(secure-hash 'sha256 "abc" t)
(secure-hash 'sha256 "abc" nil t)
(secure-hash-algorithms)
(condition-case e (secure-hash 'bogus "x") (error e))
(condition-case e (md5 "abc") (error e))

;; ---- misc ----
(get-buffer-window)
(get-buffer-window (current-buffer))
(get-buffer-window-list)
(window-with-parameter 'name)
(garbage-collect)
(memory-info)
(memory-limit)
(memory-use-counts)
(group-gid)
(group-real-gid)
(condition-case e (system-groups) (error e))
(system-users)
(system-name)
(condition-case e (user-login-name) (error e))
(condition-case e (user-real-login-name) (error e))
(condition-case e (user-full-name) (error e))
(condition-case e (user-real-uid) (error e))
(condition-case e (user-uid) (error e))
(condition-case e (length< "abc" 5) (error e))
(condition-case e (length> "abc" 5) (error e))
(condition-case e (length= "abc" 3) (error e))
(condition-case e (value< 1 2) (error e))
(condition-case e (max-char) (error e))
(condition-case e (locale-info 'codeset) (error e))
(condition-case e (locale-info 'days) (error e))
(condition-case e (locale-info 'paper) (error e))
(condition-case e (recursion-depth) (error e))
(condition-case e (internal--syntax-propertize 1) (error e))
(condition-case e (internal-describe-syntax-value) (error e))
(condition-case e (eval-buffer) (error e))
(condition-case e (eval-region 1 2) (error e))
(condition-case e (read--expression "(1 2)") (error e))
(condition-case e (read-positioning-symbols) (error e))
(condition-case e (internal-show-cursor nil nil) (error e))
(condition-case e (internal-complete-buffer "x" nil nil) (error e))
(condition-case e (internal-timer-start-idle) (error e))
(condition-case e (mapbacktrace 'ignore) (error e))
(condition-case e (mapbacktrace (lambda (evald fn args flags) (list evald fn))) (error e))
(condition-case e (function-equal 1 2) (error e))
(condition-case e (clear-face-cache) (error e))
(condition-case e (font-get-glyphs nil 0 1) (error e))
(condition-case e (locale-translate "x") (error e))
(condition-case e (internal-char-font nil) (error e))
(condition-case e (internal-char-font nil ?a) (error e))
(condition-case e (font-at 1) (error e))
(condition-case e (font-face-attributes "default") (error e))
(condition-case e (x-begin-drag nil nil) (error e))
(condition-case e (x-focus-frame nil) (error e))
(condition-case e (x-set-selection nil nil) (error e))
(condition-case e (x-get-selection nil nil) (error e))
(condition-case e (x-selection-exists-p nil) (error e))
(condition-case e (x-own-selection-internal nil nil) (error e))
(condition-case e (x-disown-selection-internal nil) (error e))
(condition-case e (x-get-clipboard) (error e))
(condition-case e (x-set-clipboard "x") (error e))
(condition-case e (x-register-dnd-atom nil) (error e))
(condition-case e (x-send-client-message nil nil nil nil nil) (error e))
(condition-case e (x-window-property nil) (error e))
(condition-case e (x-change-window-property nil nil nil nil nil) (error e))
(condition-case e (x-delete-window-property nil nil) (error e))
(condition-case e (xw-color-values "red") (error e))
(condition-case e (xw-color-defined-p "red") (error e))
(condition-case e (xw-display-color-p) (error e))
(condition-case e (x-display-grayscale-p) (error e))
(condition-case e (x-display-pixel-width) (error e))
(condition-case e (x-display-pixel-height) (error e))
(condition-case e (x-display-planes) (error e))
(condition-case e (x-display-color-cells) (error e))
(condition-case e (x-server-max-request-size) (error e))
(condition-case e (x-server-vendor) (error e))
(condition-case e (x-server-version) (error e))
(condition-case e (x-display-screens) (error e))
(condition-case e (x-display-mm-height) (error e))
(condition-case e (x-display-mm-width) (error e))
(condition-case e (x-display-backing-store) (error e))
(condition-case e (x-display-visual-class) (error e))
(condition-case e (x-display-save-under) (error e))
(condition-case e (x-get-resource nil nil) (error e))
(condition-case e (x-parse-geometry nil) (error e))
(condition-case e (x-mouse-absolute-pixel-position) (error e))
(condition-case e (set-mouse-absolute-pixel-position 0 0) (error e))
(condition-case e (frame-edge-alist) (error e))
(condition-case e (track-mouse) (error e))
(condition-case e (display-monitor-attributes-list) (error e))
(condition-case e (display-usable-bounds) (error e))
(condition-case e (frame-monitor-attributes) (error e))
(condition-case e (frame-edges) (error e))
(condition-case e (frame-geometry) (error e))
(condition-case e (frame-text-width) (error e))
(condition-case e (frame-text-height) (error e))
(condition-case e (frame-native-width) (error e))
(condition-case e (frame-native-height) (error e))
(condition-case e (frame-inner-width) (error e))
(condition-case e (frame-inner-height) (error e))
(condition-case e (frame-outer-width) (error e))
(condition-case e (frame-outer-height) (error e))
(condition-case e (frame-scroll-bar-width) (error e))
(condition-case e (frame-scroll-bar-height) (error e))
(condition-case e (frame-fringe-width) (error e))
(condition-case e (frame-right-divider-width) (error e))
(condition-case e (frame-bottom-divider-width) (error e))
(condition-case e (frame-total-cols) (error e))
(condition-case e (frame-total-lines) (error e))
(condition-case e (frame-scale-factor) (error e))
(condition-case e (gui-set-selection nil nil) (error e))
(condition-case e (gui-get-selection nil nil) (error e))
(condition-case e (gui-selection-exists-p nil) (error e))
(condition-case e (terminal-coding-system) (error e))
(condition-case e (set-terminal-coding-system nil) (error e))
(condition-case e (keyboard-coding-system) (error e))
(condition-case e (set-keyboard-coding-system nil) (error e))
(condition-case e (terminal-live-p nil) (error e))
(condition-case e (tty-display-color-p) (error e))
(condition-case e (tty-display-color-cells) (error e))
(condition-case e (tty-type) (error e))
(condition-case e (tty-no-underline) (error e))
(condition-case e (tty-suppress-bold-inverse-default-colors) (error e))
(condition-case e (controlling-tty-p) (error e))
(condition-case e (tty-top-frame) (error e))
(condition-case e (suspend-tty) (error e))
(condition-case e (resume-tty) (error e))
(condition-case e (gpm-mouse-start) (error e))
(condition-case e (gpm-mouse-stop) (error e))
(condition-case e (window-system) (error e))
(condition-case e (window-system nil) (error e))
(condition-case e (display-graphic-p) (error e))
(condition-case e (display-images-p) (error e))
(condition-case e (display-supports-face-attributes-p nil) (error e))
(condition-case e (display-selections-p) (error e))
(condition-case e (display-popup-menus-p) (error e))
(condition-case e (display-color-p) (error e))
(condition-case e (display-grayscale-p) (error e))
(condition-case e (display-pixel-width) (error e))
(condition-case e (display-pixel-height) (error e))
(condition-case e (display-planes) (error e))
(condition-case e (display-color-cells) (error e))
(condition-case e (display-save-under) (error e))
(condition-case e (display-screens) (error e))
(condition-case e (display-mm-height) (error e))
(condition-case e (display-mm-width) (error e))
(condition-case e (display-backing-store) (error e))
(condition-case e (display-visual-class) (error e))
(condition-case e (display-monitor-attributes-list) (error e))
(condition-case e (image-size nil) (error e))
(condition-case e (image-mask-p nil) (error e))
(condition-case e (image-metadata nil) (error e))
(condition-case e (image-flush nil) (error e))
(condition-case e (lookup-image nil) (error e))
(condition-case e (put-image nil nil) (error e))
(condition-case e (remove-images 1 2) (error e))
(condition-case e (image-types) (error e))
(condition-case e (image-type-available-p 'png) (error e))
(condition-case e (image-type nil) (error e))
(condition-case e (init-image-library 'png) (error e))
(condition-case e (can-use-svg-p) (error e))
(condition-case e (image-transforms-p) (error e))
(condition-case e (compute-motion 1 2 3 4 5 6) (error e))
(condition-case e (line-pixel-height) (error e))
(condition-case e (frame-or-buffer-changed-p 'x) (error e))
(condition-case e (recompute-lucid-menubar) (error e))
(condition-case e (scroll-bar-scale nil 1) (error e))
(condition-case e (tab-bar-tab-name-function) (error e))
(condition-case e (x-tab-bar-height) (error e))
(condition-case e (tool-bar-height) (error e))
(condition-case e (tool-bar-position) (error e))
(condition-case e (menu-bar-open nil) (error e))
(condition-case e (popup-menu nil) (error e))
(condition-case e (x-popup-menu nil nil) (error e))
(condition-case e (x-menu-bar-open nil) (error e))
(condition-case e (menu-or-popup-active-p) (error e))
(condition-case e (x-show-tip nil) (error e))
(condition-case e (x-hide-tip) (error e))
(condition-case e (tooltip-mode) (error e))
(condition-case e (internal-make-lisp-face nil) (error e))
(condition-case e (internal-lisp-face-p 'default) (error e))
(condition-case e (internal-lisp-face-attribute-values 'default nil) (error e))
(condition-case e (internal-lisp-face-equal-p 'default 'default) (error e))
(condition-case e (internal-lisp-face-empty-p 'default) (error e))
(condition-case e (internal-copy-lisp-face 'a 'b) (error e))
(condition-case e (internal-merge-in-global-face 'default) (error e))
(condition-case e (internal-set-lisp-face-attribute 'default :weight 'bold) (error e))
(condition-case e (internal-get-lisp-face-attribute 'default :weight) (error e))
(condition-case e (face-all-attributes 'default) (error e))
(condition-case e (face-attribute 'default :weight) (error e))
(condition-case e (face-attributes-as-vector nil) (error e))
(condition-case e (face-font 'default) (error e))
(condition-case e (face-list) (error e))
(condition-case e (face-id 'default) (error e))
(condition-case e (face-documentation 'default) (error e))
(condition-case e (face-near-same-color-p nil nil) (error e))
(condition-case e (color-supported-p "red") (error e))
(condition-case e (color-gray-p "red") (error e))
(condition-case e (color-distance "red" "blue") (error e))
(condition-case e (clear-font-cache) (error e))
(condition-case e (font-family-list) (error e))
(condition-case e (font-xlfd-name nil) (error e))
(condition-case e (font-info nil) (error e))
(condition-case e (query-font nil) (error e))
(condition-case e (font-get nil :name) (error e))
(condition-case e (font-face-attributes nil) (error e))
(condition-case e (font-put nil :name "x") (error e))
(condition-case e (list-fonts nil) (error e))
(condition-case e (font-names nil) (error e))
(condition-case e (font-spec) (error e))
(condition-case e (font-spec :name "x") (error e))
(condition-case e (fontp nil) (error e))
(condition-case e (font-entity-info nil) (error e))
(condition-case e (font-match-p nil nil) (error e))
(condition-case e (find-font nil) (error e))
(condition-case e (font-get-system-font) (error e))
(condition-case e (font-get-system-normal-font) (error e))
(condition-case e (x-list-fonts nil) (error e))
(condition-case e (x-font-family-list) (error e))
(condition-case e (frame-font) (error e))
(condition-case e (set-frame-font nil) (error e))
(condition-case e (default-font-width) (error e))
(condition-case e (default-font-height) (error e))
(condition-case e (window-font-width) (error e))
(condition-case e (window-font-height) (error e))
(condition-case e (char-width ?a) (error e))
(condition-case e (string-width "x") (error e))
(condition-case e (line-height) (error e))
(condition-case e (window-text-pixel-size) (error e))
(condition-case e (window-text-height) (error e))
(condition-case e (glyph-char nil) (error e))
(condition-case e (glyph-face nil) (error e))
(condition-case e (glyph-glyph nil) (error e))
(condition-case e (dump-glyph-matrix) (error e))
(condition-case e (dump-glyph-row nil 0) (error e))
(condition-case e (dump-tools) (error e))
(condition-case e (print--precomputed-regexp-something-otherwise-inconsistent) (error e))

;; ---- branch coverage round 2 ----
(x-parse-geometry "80x24+10+20")
(x-parse-geometry "+5-3")
(x-parse-geometry "-10-5")
(x-parse-geometry "80x24")
(x-parse-geometry "80")
(x-parse-geometry "")
(condition-case e (x-parse-geometry nil) (error e))
(make-interpreted-closure '(a b) '((+ a b)) nil)
(make-interpreted-closure '(a &optional b) '((+ a b)) nil)
(make-interpreted-closure '(&rest r) '(car r) nil)
(make-interpreted-closure '(a &rest r) '(list a r) nil)
(funcall (make-interpreted-closure '(a) '((+ a 1)) nil) 5)
(let ((f (make-interpreted-closure '(a) '((+ a z)) '((z . 10)))))
  (funcall f 5))
(func-arity '(lambda (a) a))
(func-arity '(lambda (a &optional b) a))
(func-arity '(lambda (&rest r) r))
(func-arity '(closure (t) (a) a))
(func-arity 'car)
(func-arity 'if)
(color-distance "#ff0000" "#0000ff")
(color-distance "red" "blue")
(color-distance "#ffffff" "#000000")
(color-distance (list 65535 0 0) (list 0 0 0))
(color-distance (list 255 0 0) (list 0 0 0))
(color-distance "#f00" "#00f")
(condition-case e (color-distance "notacolor" "red") (error e))
(let ((f (make-temp-file "mtf")))
  (file-exists-p f) (delete-file f))
(make-temp-file "mtf" t)
(make-temp-file "mtf" nil "TX")
(condition-case e (make-symbolic-link "/tmp/fbv-test.el" "/tmp/remacs-slink" t) (error e))
(condition-case e (set-file-times "/tmp/fbv-test.el" '(0 0)) (error e))
(condition-case e (set-file-times "/tmp/fbv-test.el") (error e))
(value< 1 2)
(value< 2.0 3)
(value< 'a 'b)
(value< "a" "b")
(value< '(1) '(2))
(value< [1] [2])
(emacs-uptime "%S")
(emacs-uptime "%M")
(emacs-uptime "%H")
(emacs-uptime "%D")
(emacs-uptime "%T")
(emacs-uptime "x%y")
(locale-info 'codeset)
(locale-info 'days)
(locale-info 'months)
(locale-info 'bogus-item)
(time-convert '(1 2 3 4) 'integer)
(time-convert 1000000 'list)
(time-add '(1 2) '(3 4))
(time-subtract '(5 6) '(1 2))
(current-time)
(float-time '(100 200 300 0))
(float-time '(ticks . hz))
(condition-case e (float-time "x") (error e))
(secure-hash 'md5 "abc")
(secure-hash 'sha1 "abc")
(secure-hash 'sha256 "abc" nil nil t)
(secure-hash 'sha512 '(1 2))
(condition-case e (secure-hash 'bogus "x") (error e))
(help-function-arglist 'car)
(help-function-arglist 'when)
(help-function-arglist '(lambda (a &optional b) a))
(bool-vector-not (bool-vector t nil t))
(bool-vector-count-population (bool-vector t nil t))
(bool-vector-subsetp (bool-vector t nil) (bool-vector t t))
(bool-vector-count-consecutive (bool-vector t nil) 0 nil)
(bool-vector-count-consecutive (bool-vector t nil) 0 t)
(read--expression "P: " "(1 2 3)")
(condition-case e (read--expression "P: ") (error e))
(map-keymap (lambda (k v) (list k v)) global-map)
(map-keymap 'ignore (make-keymap))
(coding-system-eol-type 'utf-8)
(coding-system-eol-type 'utf-8-unix)
(coding-system-plist 'utf-8)
(coding-system-get 'utf-8 :name)
(coding-system-get 'utf-8 :coding-type)
(pos-visible-in-window-p)
(pos-visible-in-window-p 1)
(pos-visible-in-window-p 1 nil t)
(window-normalize-buffer (current-buffer))
(window-normalize-frame (selected-frame))
(condition-case e (window-normalize-buffer "x") (error e))
(event-basic-type 'C-M-S-f)
(event-modifiers 'C-M-S-f)
(listify-key-sequence "ab")
(listify-key-sequence (kbd "C-f M-x"))
(not-modified)
;; `suspend-tty' signals in batch (GNU: "Attempt to suspend a non-text
;; terminal device"); exercise it under condition-case.
(condition-case e (suspend-tty) (error e))
;; `resume-tty' likewise signals in batch ("Attempt to resume a
;; non-text terminal device").
(condition-case e (resume-tty) (error e))
(internal-timer-start-idle)
