;; Runtime coverage: special forms, control flow, symbols, hashes,
;; print streams, reader paths, regexp engine, eval machinery.
(progn
  ;; ---- special forms ----
  (ignore-errors (if t 1 2)) (ignore-errors (if nil 1 2))
  (ignore-errors (if nil 1)) (ignore-errors (if t))
  (ignore-errors (cond)) (ignore-errors (cond (nil 1) (t 2)))
  (ignore-errors (cond (t 1 2 3))) (ignore-errors (cond ((> 1 2) 'a) ((< 1 2) 'b)))
  (ignore-errors (progn)) (ignore-errors (progn 1 2 3))
  (ignore-errors (prog1 1 2 3)) (ignore-errors (prog1 nil 2))
  (ignore-errors (prog2 1 2 3)) (ignore-errors (prog2))
  (ignore-errors (and)) (ignore-errors (and 1)) (ignore-errors (and 1 2))
  (ignore-errors (and nil 2)) (ignore-errors (and 1 nil 3))
  (ignore-errors (or)) (ignore-errors (or nil)) (ignore-errors (or nil 2 3))
  (ignore-errors (or 1 2)) (ignore-errors (or nil nil nil))
  (ignore-errors (let (a b) a)) (ignore-errors (let ((a 1) (b 2)) (+ a b)))
  (ignore-errors (let ((a 1) a) a)) (ignore-errors (let nil 5))
  (ignore-errors (let* ((a 1) (b a)) (+ a b))) (ignore-errors (let* (a) a))
  (ignore-errors (let ((a 1)) (let ((a 2)) a) a))
  (ignore-errors (let (a b c) (setq a 1 b 2 c 3) (list a b c)))
  (ignore-errors (setq x1 1 x2 2)) (ignore-errors (setq))
  (ignore-errors (setq x3)) (ignore-errors (setq-default dd 1))
  (ignore-errors (defvar dv1 1)) (ignore-errors (defvar dv2 2 "doc"))
  (ignore-errors (defvar dv3)) (ignore-errors (defconst dc1 1))
  (ignore-errors (defconst dc2 2 "doc"))
  (ignore-errors (defun pfn1 () 1)) (ignore-errors (defun pfn2 (a b) (+ a b)))
  (ignore-errors (defun pfn3 (&rest r) r)) (ignore-errors (defun pfn4 (a &optional b) (list a b)))
  (ignore-errors (defun pfn5 (a &optional (b 5) (c 6)) (list a b c)))
  (ignore-errors (defun pfn6 (&optional (a 1 ap)) (list a ap)))
  (ignore-errors (defun pfn7 (a) "doc" (+ a 1)))
  (ignore-errors (defun pfn8 () (interactive) 5))
  (ignore-errors (defun pfn9 () (declare (indent 1)) 9))
  (ignore-errors (defun pfn10 () (interactive "p") 10))
  (ignore-errors (defmacro pm1 (x) `(+ ,x 1))) (ignore-errors (pm1 5))
  (ignore-errors (defmacro pm2 (a &rest r) `(list ,a ,@r))) (ignore-errors (pm2 1 2 3))
  (ignore-errors (defmacro pm3 (x) "doc" `(1+ ,x)))
  (ignore-errors (lambda (x) x)) (ignore-errors (funcall (lambda (x) (* x 2)) 5))
  (ignore-errors (funcall (lambda (&rest r) r) 1 2))
  (ignore-errors (funcall (lambda (a &optional b) (list a b)) 1))
  (ignore-errors (funcall (lambda (a &optional b) (list a b)) 1 2))
  (ignore-errors ((lambda (x) x) 5))
  (ignore-errors (while nil 1)) (ignore-errors (let ((n 0)) (while (< n 5) (setq n (1+ n))) n))
  (ignore-errors (let ((n 0)) (while t (setq n (1+ n)) (when (> n 3) (throw 'done n)))))
  (ignore-errors (dolist (x '(1 2 3)) x)) (ignore-errors (dolist (x '(1 2) 'res) x))
  (ignore-errors (dolist (x nil 'res) x)) (ignore-errors (dolist (x '(1)) (print x)))
  (ignore-errors (dotimes (n 3) n)) (ignore-errors (dotimes (n 3 'res) n))
  (ignore-errors (dotimes (n 0 'res) n)) (ignore-errors (dotimes (n -1 'res) n))
  (ignore-errors (when t 1 2)) (ignore-errors (when nil 1)) (ignore-errors (when t))
  (ignore-errors (unless nil 1 2)) (ignore-errors (unless t 1)) (ignore-errors (unless nil))
  ;; catch/throw
  (ignore-errors (catch 'tag 1 2)) (ignore-errors (catch 'tag (throw 'tag 'val) 99))
  (ignore-errors (catch nil 1)) (ignore-errors (throw 'tag 'val))
  (ignore-errors (catch 'a (catch 'b (throw 'a 'x))))
  (ignore-errors (catch 'tag (unwind-protect (throw 'tag 1) (setq unwound t))))
  ;; unwind-protect / condition-case
  (ignore-errors (unwind-protect 1)) (ignore-errors (unwind-protect 1 2 3))
  (ignore-errors (unwind-protect (error "x") (setq cleaned t)))
  (ignore-errors (condition-case nil (error "boom") (error 'caught)))
  (ignore-errors (condition-case v (error "boom") (error v)))
  (ignore-errors (condition-case v (error "boom") (error (cdr v))))
  (ignore-errors (condition-case v (car 1) (wrong-type-argument 'wta)))
  (ignore-errors (condition-case v (car 1) (error 'e)))
  (ignore-errors (condition-case v 42 (error 'e)))
  (ignore-errors (condition-case v (error "x") (wrong-type-argument 'w) (error 'e)))
  (ignore-errors (condition-case v (throw 'tt 'vv) (error 'e)))
  (ignore-errors (condition-case v (signal 'my-sym '(d1 d2)) (my-sym v)))
  (ignore-errors (condition-case v (signal 'my-sym '(1)) ((my-sym other) v)))
  (ignore-errors (condition-case-unless-debug v (error "x") (error v)))
  (ignore-errors (condition-case v (/ 1 0) (arith-error 'ae) (error 'e)))
  (ignore-errors (condition-case v (car 1) ((wrong-type-argument arith-error) v)))
  (ignore-errors (condition-case nil (signal 'quit nil) (quit 'q)))
  (ignore-errors (signal 'error '("msg")))
  (ignore-errors (signal 'wrong-type-argument '(stringp 5)))
  (ignore-errors (signal 'void-function '(nosuch)))
  (ignore-errors (signal 'args-out-of-range '(1 2 3)))
  (condition-case v (signal 'my-custom-error '(a b)) (my-custom-error v))
  ;; error/warn/message
  (ignore-errors (error "fmt %s" 'x)) (ignore-errors (error "%d %d" 1 2))
  (ignore-errors (error nil)) (ignore-errors (user-error "uerr"))
  (ignore-errors (warn "w %s" 'x)) (ignore-errors (display-warning 'type "msg"))
  (ignore-errors (message "m")) (ignore-errors (message "m %s" 'x))
  (ignore-errors (message nil)) (ignore-errors (minibuffer-message "mm"))
  (ignore-errors (error-message-string '(err data)))
  (ignore-errors (error-message-string nil))
  (ignore-errors (lwarn 't :warning "msg %s" 'x))
  (ignore-errors (ding)) (ignore-errors (ding t))
  ;; save-* forms
  (with-temp-buffer
    (insert "abcdef") (goto-char 3)
    (ignore-errors (save-excursion (goto-char 1) (insert "X")))
    (ignore-errors (save-current-buffer (set-buffer (get-buffer-create "tb2")) (insert "Y")))
    (ignore-errors (with-current-buffer (get-buffer-create "tb3") (insert "Z")))
    (ignore-errors (save-restriction (narrow-to-region 1 3) (point-min)))
    (ignore-errors (save-window-excursion (split-window)))
    (ignore-errors (save-match-data (string-match "a" "a") (match-data))))
  ;; backquote
  (ignore-errors `(1 2)) (ignore-errors `(1 ,(+ 1 1)))
  (ignore-errors `(a ,@'(b c))) (ignore-errors `(a ,(list 1) ,@(list 2 3)))
  (ignore-errors `(a . ,1)) (ignore-errors `,@'(1))
  (ignore-errors (let ((x 5)) `(,x . x))) (ignore-errors ``(a ,b))
  ;; eval machinery
  (ignore-errors (eval '(+ 1 2))) (ignore-errors (eval '(+ 1 2) t))
  (ignore-errors (eval 42)) (ignore-errors (eval 'sym-unbound-xyz))
  (ignore-errors (eval '(let ((a 5)) a) '((a . 9))))
  (ignore-errors (eval-and-compile 1)) (ignore-errors (eval-when-compile 1))
  (ignore-errors (macroexpand '(pm1 5))) (ignore-errors (macroexpand '(when t 1)))
  (ignore-errors (macroexpand-all '(when t (pm1 5))))
  (ignore-errors (macroexpand '(car x))) (ignore-errors (macroexpand-1 '(pm1 5)))
  (ignore-errors (macroexpand-1 '(when t 1)))
  (ignore-errors (functionp #'car)) (ignore-errors (functionp 'car))
  (ignore-errors (functionp (lambda (x) x))) (ignore-errors (functionp 'pm1))
  (ignore-errors (functionp 5)) (ignore-errors (functionp nil))
  (ignore-errors (macrop 'pm1)) (ignore-errors (macrop 'car))
  (ignore-errors (subrp (symbol-function 'car))) (ignore-errors (subrp 'car))
  (ignore-errors (subrp #'car)) (ignore-errors (subrp nil))
  (ignore-errors (special-form-p 'if)) (ignore-errors (special-form-p 'car))
  (ignore-errors (special-form-p 'progn)) (ignore-errors (interpreted-function-p (lambda (x) x)))
  (ignore-errors (interpreted-function-p #'car))
  (ignore-errors (closurep (lambda (x) x))) (ignore-errors (closurep #'car))
  (ignore-errors (make-interpreted-closure '(lambda (x) x) nil nil nil))
  (ignore-errors (indirect-function 'car)) (ignore-errors (indirect-function 'car t))
  (ignore-errors (defalias 'pa 'car)) (ignore-errors (indirect-function 'pa))
  (ignore-errors (defalias 'pb 'pa)) (ignore-errors (indirect-function 'pb))
  (ignore-errors (indirect-function 'nosuch-sym-xyz))
  (ignore-errors (subr-arity (symbol-function 'car))) (ignore-errors (subr-arity #'format))
  (ignore-errors (subr-arity #'forward-char)) (ignore-errors (subr-name #'car))
  (ignore-errors (func-arity 'car)) (ignore-errors (func-arity 'pfn2))
  (ignore-errors (func-arity #'car)) (ignore-errors (func-arity 'nosuch))
  (ignore-errors (function-equal #'car #'car)) (ignore-errors (function-equal #'car #'cdr))
  (ignore-errors (function-get 'car 'x)) (ignore-errors (function-put 'car 'pk 'pv))
  (ignore-errors (function-get 'car 'pk))
  ;; fset/fboundp/fmakunbound
  (ignore-errors (fset 'fs1 #'car)) (ignore-errors (fboundp 'fs1))
  (ignore-errors (fset 'fs2 (lambda (x) x))) (ignore-errors (fs2 5))
  (ignore-errors (fset 'fs3 '(lambda (x) x))) (ignore-errors (fs3 6))
  (ignore-errors (fmakunbound 'fs1)) (ignore-errors (fboundp 'fs1))
  (ignore-errors (fmakunbound 'car)) (ignore-errors (fboundp 'car))
  (ignore-errors (symbol-function 'car)) (ignore-errors (symbol-function 'fs3))
  (ignore-errors (symbol-function 'nosuch-xyz)) (ignore-errors (symbol-function 5))
  (ignore-errors (command-modes 'forward-char)) (ignore-errors (command-modes 'car))
  (ignore-errors (interactive-form 'forward-char)) (ignore-errors (interactive-form 'car))
  (ignore-errors (interactive-form 'pfn8))
  ;; symbol value/plist
  (ignore-errors (symbol-value 'dv1)) (ignore-errors (symbol-value 'nosuch-v))
  (ignore-errors (symbol-plist 'car)) (ignore-errors (setplist 'sp1 '(a 1)))
  (ignore-errors (symbol-plist 'sp1)) (ignore-errors (get 'sp1 'a))
  (ignore-errors (put 'sp1 'b 2)) (ignore-errors (symbol-plist 'sp1))
  (ignore-errors (put 'sp1 'a 'new)) (ignore-errors (get 'sp1 'a))
  (ignore-errors (get 'nosuch 'x)) (ignore-errors (put 5 'a 1))
  (ignore-errors (default-boundp 'dv1)) (ignore-errors (default-value 'dv1))
  (ignore-errors (set-default 'dv1 9)) (ignore-errors (default-value 'dv1))
  (ignore-errors (makunbound 'dv1)) (ignore-errors (boundp 'dv1))
  (ignore-errors (makunbound 'nosuch)) (ignore-errors (bare-symbol 'car))
  (ignore-errors (bare-symbol-p 'car)) (ignore-errors (bare-symbol-p 5))
  (ignore-errors (position-symbol 'car 5)) (ignore-errors (symbol-with-pos-p 'car))
  (ignore-errors (symbol-with-pos-pos 'car)) (ignore-errors (remove-pos-from-symbol 'car))
  ;; hash tables
  (let ((h (make-hash-table)))
    (ignore-errors (puthash 'a 1 h)) (ignore-errors (puthash 'b 2 h))
    (ignore-errors (gethash 'a h)) (ignore-errors (gethash 'z h))
    (ignore-errors (gethash 'z h 'def)) (ignore-errors (remhash 'a h))
    (ignore-errors (remhash 'z h)) (ignore-errors (hash-table-count h))
    (ignore-errors (clrhash h)) (ignore-errors (hash-table-count h))
    (ignore-errors (puthash "k" "v" h)))
  (let ((h (make-hash-table :test 'equal)))
    (ignore-errors (puthash "k" 1 h)) (ignore-errors (gethash "k" h)))
  (let ((h (make-hash-table :test 'eql)))
    (ignore-errors (puthash 1.0 'x h)) (ignore-errors (gethash 1.0 h)))
  (ignore-errors (make-hash-table :test 'equal :size 100))
  (ignore-errors (make-hash-table :test 'equal :weakness 'key))
  (ignore-errors (make-hash-table :weakness 'value))
  (ignore-errors (make-hash-table :rehash-size 2.0))
  (ignore-errors (make-hash-table :rehash-threshold 0.5))
  (ignore-errors (make-hash-table :test 'badtest))
  (let ((h (make-hash-table)))
    (puthash 'a 1 h) (puthash 'b 2 h)
    (ignore-errors (hash-table-keys h)) (ignore-errors (hash-table-values h))
    (ignore-errors (hash-table-test h)) (ignore-errors (hash-table-size h))
    (ignore-errors (hash-table-weakness h)) (ignore-errors (hash-table-rehash-size h))
    (ignore-errors (hash-table-rehash-threshold h))
    (ignore-errors (hash-table-p h)) (ignore-errors (hash-table-p nil))
    (let ((h2 (copy-hash-table h))) (ignore-errors (gethash 'a h2)))
    (let ((acc nil)) (maphash (lambda (k v) (push k acc)) h) acc)
    (ignore-errors (maphash #'list h))
    (ignore-errors (sxhash 'a)) (ignore-errors (sxhash "s"))
    (ignore-errors (sxhash '(1 . 2))) (ignore-errors (sxhash [1 2])))
  (ignore-errors (define-hash-table-test 'mytest #'eq #'sxhash))
  (ignore-errors (maphash #'identity nil)) (ignore-errors (maphash #'identity 5))
  (ignore-errors (puthash 'a 1 nil)) (ignore-errors (gethash 'a nil))
  (ignore-errors (gethash 'a 5)) (ignore-errors (remhash 'a 5))
  (ignore-errors (clrhash 5)) (ignore-errors (hash-table-count 5))
  ;; obarray
  (ignore-errors (obarray-make)) (ignore-errors (obarray-make 100))
  (ignore-errors (obarray-make 0)) (ignore-errors (obarrayp (obarray-make)))
  (ignore-errors (obarrayp nil)) (ignore-errors (obarray-clear (obarray-make)))
  (ignore-errors (mapatoms #'identity)) (ignore-errors (mapatoms #'identity (obarray-make)))
  (ignore-errors (mapatoms 5)) (ignore-errors (intern "sym-probe" (obarray-make)))
  (ignore-errors (intern-soft "car")) (ignore-errors (intern-soft "car" (obarray-make)))
  (ignore-errors (intern-soft "car" 5)) (ignore-errors (unintern "sym-probe-2"))
  (ignore-errors (unintern 'sym-probe-3)) (ignore-errors (unintern 5))
  (ignore-errors (make-symbol "ms")) (ignore-errors (symbol-name (make-symbol "ms")))
  (ignore-errors (make-symbol "")) (ignore-errors (gensym))
  (ignore-errors (gensym "pre")) (ignore-errors (gensym 5))
  ;; print functions / streams
  (ignore-errors (prin1 'x)) (ignore-errors (prin1 "s")) (ignore-errors (prin1 5 t))
  (ignore-errors (princ 'x)) (ignore-errors (princ "s")) (ignore-errors (princ 5))
  (ignore-errors (print 'x)) (ignore-errors (terpri)) (ignore-errors (terpri t))
  (ignore-errors (write-char ?a)) (ignore-errors (write-char ?a t))
  (ignore-errors (prin1 'x (current-buffer))) (ignore-errors (princ "inbuf" (current-buffer)))
  (ignore-errors (prin1 'x (get-buffer-create "prbuf")))
  (ignore-errors (princ "marker-stream" (point-marker)))
  (ignore-errors (princ "fn-stream" (lambda (c) c)))
  (ignore-errors (prin1-to-string 'x)) (ignore-errors (prin1-to-string 'x t))
  (ignore-errors (external-debugging-output ?x))
  (ignore-errors (send-string-to-terminal "tty-out"))
  (ignore-errors (flush-standard-output))
  (ignore-errors (redirect-debugging-output "/tmp/remacs-dbg"))
  (ignore-errors (redirect-debugging-output nil))
  ;; read functions
  (ignore-errors (read "(a)")) (ignore-errors (read "(a)" t))
  (ignore-errors (read (current-buffer))) (ignore-errors (read-from-string "5"))
  (ignore-errors (read-from-string "5" 1)) (ignore-errors (read-from-string "(a b) (c)" 2))
  (ignore-errors (read-string "P: ")) (ignore-errors (read-string "P: " "init"))
  (ignore-errors (read-no-blanks-input "P: ")) (ignore-errors (read-regexp "R: "))
  (ignore-errors (read-regexp "R: " '("sug")))
  ;; misc/time/hash-string
  (ignore-errors (current-time)) (ignore-errors (current-time-string))
  (ignore-errors (current-time-string (current-time)))
  (ignore-errors (current-time-string nil "UTC"))
  (ignore-errors (current-time-zone)) (ignore-errors (current-time-zone nil))
  (ignore-errors (current-time-zone nil "UTC"))
  (ignore-errors (decode-time)) (ignore-errors (decode-time (current-time)))
  (ignore-errors (decode-time 0)) (ignore-errors (decode-time '(0 . 1)))
  (ignore-errors (decode-time (current-time) "UTC"))
  (ignore-errors (encode-time '(0 0 0 1 1 2020)))
  (ignore-errors (encode-time 0 0 0 1 1 2020))
  (ignore-errors (encode-time 0 0 0 1 1 2020 nil nil "UTC"))
  (ignore-errors (time-add (current-time) 5)) (ignore-errors (time-add '(1 . 2) '(3 . 4)))
  (ignore-errors (time-subtract (current-time) 5))
  (ignore-errors (time-less-p (current-time) nil))
  (ignore-errors (time-less-p '(1 . 2) '(3 . 4)))
  (ignore-errors (time-equal-p (current-time) (current-time)))
  (ignore-errors (time-convert (current-time) 'integer))
  (ignore-errors (time-convert (current-time) 'list))
  (ignore-errors (time-convert (current-time) 1000))
  (ignore-errors (time-convert 5 'list))
  (ignore-errors (float-time)) (ignore-errors (float-time (current-time)))
  (ignore-errors (float-time '(1 . 2)))
  (ignore-errors (emacs-uptime)) (ignore-errors (emacs-uptime "%S"))
  (ignore-errors (emacs-uptime "%D, %H"))
  (ignore-errors (current-cpu-time))
  (ignore-errors (md5 "abc")) (ignore-errors (md5 "abc" nil nil 'binary))
  (ignore-errors (md5 "abc" nil nil nil t))
  (ignore-errors (secure-hash 'md5 "abc")) (ignore-errors (secure-hash 'sha1 "abc"))
  (ignore-errors (secure-hash 'sha256 "abc")) (ignore-errors (secure-hash 'sha512 "abc"))
  (ignore-errors (secure-hash 'sha224 "abc")) (ignore-errors (secure-hash 'sha384 "abc"))
  (ignore-errors (secure-hash 'badalgo "x")) (ignore-errors (secure-hash 'md5 "abc" nil nil t))
  (ignore-errors (base64-encode-string "abc")) (ignore-errors (base64-encode-string "abc" t))
  (ignore-errors (base64-decode-string "YWJj")) (ignore-errors (base64-decode-string "!!!"))
  (ignore-errors (base64url-encode-string "abc")) (ignore-errors (base64url-encode-string "abc" t))
  (ignore-errors (buffer-hash)) (ignore-errors (buffer-hash (current-buffer)))
  (ignore-errors (buffer-hash "scratch"))
  (ignore-errors (getenv-internal "HOME")) (ignore-errors (getenv-internal "HOME" nil))
  (ignore-errors (getenv-internal "NOSUCHVARXYZ"))
  (ignore-errors (setenv "REMACS_PROBE" "1")) (ignore-errors (getenv "REMACS_PROBE"))
  (ignore-errors (setenv "REMACS_PROBE")) (ignore-errors (getenv "REMACS_PROBE"))
  (ignore-errors (getenv "HOME")) (ignore-errors (getenv "HOME" t))
  (ignore-errors (set-time-zone-rule "UTC")) (ignore-errors (set-time-zone-rule nil))
  (ignore-errors (set-file-times "/tmp/remacs-p2.txt" (current-time)))
  (ignore-errors (file-acl "/tmp")) (ignore-errors (file-attributes-lessp '((1)) '((2))))
  (ignore-errors (file-name-case-insensitive-p "/tmp/x"))
  (ignore-errors (directory-name-p "/tmp/")) (ignore-errors (directory-name-p "/tmp/x"))
  (ignore-errors (lock-file "/tmp/remacs-p2.txt")) (ignore-errors (unlock-file "/tmp/remacs-p2.txt"))
  (ignore-errors (file-locked-p "/tmp/remacs-p2.txt"))
  (ignore-errors (make-temp-file-internal "rp" nil "" nil))
  (ignore-errors (make-temp-file-internal "rp" nil ".el" "text"))
  (ignore-errors (describe-buffer-bindings (current-buffer)))
  (ignore-errors (describe-buffer-bindings (current-buffer) [1]))
  (ignore-errors (accessible-keymaps (current-global-map)))
  (ignore-errors (accessible-keymaps (current-global-map) [?a]))
  (ignore-errors (map-keymap #'ignore (current-global-map)))
  (ignore-errors (map-keymap-internal #'ignore (current-global-map)))
  (ignore-errors (keymap--get-keyelt 'car nil))
  (ignore-errors (abort-minibuffers))
  (ignore-errors (get-file-buffer "/tmp/remacs-p1.txt"))
  (ignore-errors (documentation-stringp "doc")) (ignore-errors (documentation-stringp 5))
  (ignore-errors (internal-make-var-non-special 'dv1))
  (ignore-errors (special-variable-p 'dv1)) (ignore-errors (special-variable-p 'x1))
  (ignore-errors (open-termscript "/tmp/remacs-ts")) (ignore-errors (open-termscript nil))
  (ignore-errors (open-dribble-file "/tmp/remacs-dr"))
  (ignore-errors (set--this-command-keys "ab"))
  ;; regexp engine
  (ignore-errors (string-match "abc" "xabcx"))
  (ignore-errors (string-match "abc" "xabcx" 1))
  (ignore-errors (string-match "^abc" "abcdef"))
  (ignore-errors (string-match "^abc" "xabc"))
  (ignore-errors (string-match "abc$" "xabc"))
  (ignore-errors (string-match "a.c" "axc"))
  (ignore-errors (string-match "a*c" "c"))
  (ignore-errors (string-match "a+c" "aaac"))
  (ignore-errors (string-match "a?c" "c"))
  (ignore-errors (string-match "a\\{2\\}c" "aac"))
  (ignore-errors (string-match "a\\{2,3\\}c" "aaac"))
  (ignore-errors (string-match "a\\{2,\\}c" "aaaac"))
  (ignore-errors (string-match "[abc]x" "bx"))
  (ignore-errors (string-match "[^abc]x" "dx"))
  (ignore-errors (string-match "[a-c]x" "bx"))
  (ignore-errors (string-match "[]a]x" "]x"))
  (ignore-errors (string-match "[[:alpha:]]+" "abc123"))
  (ignore-errors (string-match "[[:digit:]]+" "abc123"))
  (ignore-errors (string-match "[[:space:]]" "a b"))
  (ignore-errors (string-match "[[:upper:]]+" "abCD"))
  (ignore-errors (string-match "[[:lower:]]+" "abCD"))
  (ignore-errors (string-match "[[:alnum:]]+" "!!a1"))
  (ignore-errors (string-match "[[:punct:]]" "a.b"))
  (ignore-errors (string-match "\\(a\\)\\(b\\)" "ab"))
  (ignore-errors (string-match "\\(a\\|b\\)c" "bc"))
  (ignore-errors (string-match "\\(ab\\)+c" "ababc"))
  (ignore-errors (string-match "\\(a\\)*x" "x"))
  (ignore-errors (string-match "\\(?:a\\|b\\)c" "ac"))
  (ignore-errors (string-match "\\(a\\)?b" "b"))
  (ignore-errors (string-match "a\\|b" "xb"))
  (ignore-errors (string-match "\\<word\\>" "a word here"))
  (ignore-errors (string-match "\\<word" "wordy"))
  (ignore-errors (string-match "word\\>" "sword"))
  (ignore-errors (string-match "\\bword\\b" "a word"))
  (ignore-errors (string-match "\\Bord" "word"))
  (ignore-errors (string-match "\\w+" "abc_def"))
  (ignore-errors (string-match "\\W+" "ab cd"))
  (ignore-errors (string-match "\\s-+" "a  b"))
  (ignore-errors (string-match "\\sw+" "abc "))
  (ignore-errors (string-match "\\s_+" "a_b "))
  (ignore-errors (string-match "\\`abc" "abcdef"))
  (ignore-errors (string-match "def\\'" "abcdef"))
  (ignore-errors (string-match "\\'end" "the end"))
  (ignore-errors (string-match "a\\\\b" "a\\b"))
  (ignore-errors (string-match "a\\.b" "a.b"))
  (ignore-errors (string-match "\\(a\\)b\\1" "aba"))
  (ignore-errors (string-match "case" "CASE"))
  (ignore-errors (let ((case-fold-search t)) (string-match "case" "CASE")))
  (ignore-errors (string-match "invalid\\(" "x"))
  (ignore-errors (string-match "a{2}" "aa"))
  ;; match-data ops
  (progn (string-match "\\(a\\)\\(b\\)" "xab")
         (ignore-errors (match-beginning 0)) (ignore-errors (match-end 0))
         (ignore-errors (match-beginning 1)) (ignore-errors (match-end 1))
         (ignore-errors (match-beginning 2)) (ignore-errors (match-beginning 3))
         (ignore-errors (match-string 0 "xab")) (ignore-errors (match-string 1 "xab"))
         (ignore-errors (match-string 2 "xab")) (ignore-errors (match-string-no-properties 0 "xab"))
         (ignore-errors (match-data)) (ignore-errors (match-data t))
         (ignore-errors (set-match-data '(1 3)))
         (ignore-errors (set-match-data (match-data)))
         (ignore-errors (replace-match "X" nil nil "xab"))
         (ignore-errors (replace-match "X" nil nil "xab" 1))
         (ignore-errors (match-substitute-replacement "r" nil nil "xab")))
  (ignore-errors (looking-at "abc"))
  (with-temp-buffer (insert "abcdef") (goto-char 1)
                    (ignore-errors (looking-at "abc"))
                    (ignore-errors (looking-at "bc"))
                    (ignore-errors (looking-at "a\\(b\\)c"))
                    (ignore-errors (looking-at-p "abc"))
                    (ignore-errors (re-search-forward "c"))
                    (ignore-errors (re-search-forward "z" nil t))
                    (ignore-errors (re-search-forward "z" nil nil))
                    (goto-char 6)
                    (ignore-errors (re-search-backward "b"))
                    (ignore-errors (re-search-backward "z" nil t))
                    (ignore-errors (search-forward "d" nil t))
                    (ignore-errors (search-backward "a" nil t))
                    (ignore-errors (skip-chars-forward "a-c"))
                    (ignore-errors (skip-chars-backward "a-c"))
                    (ignore-errors (skip-syntax-forward "w"))
                    (ignore-errors (skip-syntax-backward "w")))
  (ignore-errors (regexp-quote "a.b*c"))
  (ignore-errors (regexp-quote ""))
  (ignore-errors (regexp-opt '("a" "ab" "abc")))
  (ignore-errors (regexp-opt '("a" "b") t))
  (ignore-errors (regexp-opt nil))
  (ignore-errors (regexp-opt-depth "\\(a\\)\\(?:b\\(c\\)\\)"))
  (ignore-errors (regexp-opt-depth "abc"))
  ;; eval/apply edges
  (ignore-errors (apply #'+ '(1 2))) (ignore-errors (apply 'list 1 2 '(3)))
  (ignore-errors (apply #'list)) (ignore-errors (apply "str" nil))
  (ignore-errors (funcall #'list 1 2)) (ignore-errors (funcall 'nosuch-fn))
  (ignore-errors (funcall nil)) (ignore-errors (funcall t 1))
  (ignore-errors (funcall '(lambda (x) x) 9))
  (ignore-errors (funcall (lambda (&key a) a) :a 5))
  (ignore-errors (funcall (lambda (a &optional (b 2 bp)) (list a b bp)) 1))
  (ignore-errors (let ((f #'car)) (funcall f '(1))))
  (ignore-errors (funcall 'car '(1 2)))
  (ignore-errors (funcall '+ 1 2 3))
  (ignore-errors (run-hook-with-args 'nosuch-hook))
  (ignore-errors (run-hooks 'nosuch-hook))
  (ignore-errors (run-hooks 'probe-h1 'probe-h2))
  (ignore-errors (run-hook-with-args 'h 'x 'y))
  (ignore-errors (run-hook-wrapped 'h #'list))
  (ignore-errors (run-hook-with-args-until-failure 'h))
  (ignore-errors (run-hook-with-args-until-success 'h))
  (ignore-errors (add-hook 'ph #'car)) (ignore-errors (add-hook 'ph #'cdr t))
  (ignore-errors (add-hook 'ph #'cdr nil t)) (ignore-errors (remove-hook 'ph #'car))
  (ignore-errors (remove-hook 'ph #'nosuch)) (ignore-errors (remove-hook 'nosuch-hook #'car))
  (ignore-errors (add-hook 'ph 5)) (ignore-errors (remove-hook 5 #'car))
  (ignore-errors (add-to-list 'atl 'x)) (ignore-errors (add-to-list 'atl 'x t))
  (ignore-errors (add-to-list 'atl 'x nil #'equal))
  ;; with-* wrappers & with-silent-modifications
  (ignore-errors (with-silent-modifications (insert "q")))
  (ignore-errors (with-local-quit 1))
  (ignore-errors (with-demoted-errors "E: %s" (error "x")))
  (ignore-errors (with-demoted-errors (error "x")))
  (ignore-errors (with-case-table (standard-case-table) 1))
  (ignore-errors (with-output-to-string (princ "out")))
  (ignore-errors (with-output-to-temp-buffer "tb" (princ "x")))
  (ignore-errors (with-temp-message "tmp" 5))
  (ignore-errors (with-timeout (5 'timed-out) 'done))
  (ignore-errors (with-selected-window (selected-window) 7))
  (ignore-errors (with-current-buffer (current-buffer) (point)))
  (ignore-errors (with-no-warnings (car 1)))
  (ignore-errors (with-file-modes 493 1))
  (ignore-errors (with-syntax-table (standard-syntax-table) 2))
  (ignore-errors (combine-after-change-calls 1))
  (ignore-errors (track-mouse 1))
  (ignore-errors (setq lexical-binding nil))
  (ignore-errors (let ((lexical-binding t)) (eval '(lambda (x) x))))
  nil)
