(progn
  (ignore-errors (1+ 'x))
  (ignore-errors (1- 'x))
  (ignore-errors (abs nil))
  (ignore-errors (acos '(1 2)))
  (ignore-errors (activate-change-group ))
  (ignore-errors (add-face-text-property 'face [1 2] 1))
  (ignore-errors (add-hook 'x nil))
  (ignore-errors (add-name-to-file "/tmp/x" [1 2]))
  (ignore-errors (add-text-properties 'face 'x nil))
  (ignore-errors (append-to-list 2 nil))
  (ignore-errors (arrayp 1))
  (ignore-errors (ash nil '(1 2)))
  (ignore-errors (asin 42))
  (ignore-errors (atan 42))
  (ignore-errors (atom '(1 2)))
  (ignore-errors (bare-symbol 'car))
  (ignore-errors (bare-symbol-p 'car))
  (ignore-errors (barf-if-buffer-read-only ))
  (ignore-errors (base64url-encode-region 42 1))
  (ignore-errors (beginning-of-buffer-other-window ))
  (ignore-errors (bignump 42))
  (ignore-errors (blink-cursor-mode ))
  (ignore-errors (booleanp 42))
  (ignore-errors (boundp 42))
  (ignore-errors (buffer-hash ))
  (ignore-errors (buffer-last-name ))
  (ignore-errors (buffer-word-at-point ))
  (ignore-errors (bufferp "*scratch*"))
  (ignore-errors (butlast "x"))
  (ignore-errors (byte-to-position 1))
  (ignore-errors (cancel-change-group ))
  (ignore-errors (cancel-kbd-macro-events ))
  (ignore-errors (capitalize '(1 2)))
  (ignore-errors (car-less-than-car 42 1))
  (ignore-errors (car-or-marker-p (point-marker)))
  (ignore-errors (cdaadr 1))
  (ignore-errors (cdaddr 1))
  (ignore-errors (ceiling 42))
  (ignore-errors (char-after ))
  (ignore-errors (char-before ))
  (ignore-errors (char-charset ?a))
  (ignore-errors (char-equal ?a [1 2]))
  (ignore-errors (char-or-string-p "abc def"))
  (ignore-errors (char-to-string "abc def"))
  (ignore-errors (char-width ?a))
  (ignore-errors (characterp ?a))
  (ignore-errors (clear-vector [1 2 3] "x"))
  (ignore-errors (closurep 'x))
  (ignore-errors (color-values 1))
  (ignore-errors (combine-windows (selected-window)))
  (ignore-errors (comment-beginning ))
  (ignore-errors (compute-motion-hints 42))
  (ignore-errors (consp 42))
  (ignore-errors (coordinates-in-window-p (selected-window) 1))
  (ignore-errors (copy-hash-table (make-hash-table)))
  (ignore-errors (copy-marker ))
  (ignore-errors (copy-seq '(1 2 3)))
  (ignore-errors (copy-to-buffer "*scratch*" nil '(1 2)))
  (ignore-errors (copysign 42 nil))
  (ignore-errors (cos nil))
  (ignore-errors (count-lines 42 1))
  (ignore-errors (count-lines-page ))
  (ignore-errors (count-matches 42 'x))
  (ignore-errors (count-words 42 1))
  (ignore-errors (count-words-region 42 "x"))
  (ignore-errors (current-cpu-time ))
  (ignore-errors (current-word ))
  (ignore-errors (cursor-type ))
  (ignore-errors (declare-functionp 'car))
  (ignore-errors (decode-char ?a 1))
  (ignore-errors (default-boundp 42))
  (ignore-errors (default-value "x"))
  (ignore-errors (defined-colors ))
  (ignore-errors (defining-kbd-macro ))
  (ignore-errors (delete-backward-char ))
  (ignore-errors (delete-char ))
  (ignore-errors (delete-overlay 'x))
  (ignore-errors (delete-window-internal (selected-window)))
  (ignore-errors (dir-locals-set-class-variables "/tmp"))
  (ignore-errors (directory-name-p "/tmp"))
  (ignore-errors (display-mouse-p ))
  (ignore-errors (display-supports-face-attributes-p 'default))
  (ignore-errors (display-table-p (make-hash-table)))
  (ignore-errors (display-table-slot (make-hash-table) "x"))
  (ignore-errors (documentation-stringp "abc def"))
  (ignore-errors (downcase 42))
  (ignore-errors (dump-glyph-matrix ))
  (ignore-errors (encode-char ?a 1))
  (ignore-errors (eq 'x nil))
  (ignore-errors (eql nil '(1 2)))
  (ignore-errors (equal [1 2] 1))
  (ignore-errors (equal-including-properties 42 nil))
  (ignore-errors (eval '(1 2)))
  (ignore-errors (evenp 42))
  (ignore-errors (exchange-point-and-mark-inactive ))
  (ignore-errors (exp nil))
  (ignore-errors (expt '(1 2) [1 2]))
  (ignore-errors (external-debugging-output 42))
  (ignore-errors (face-attrs-more-relative-p 'default nil))
  (ignore-errors (fceiling 42))
  (ignore-errors (ffloor 1))
  (ignore-errors (file-attributes-lessp "/tmp/x" '(1 2)))
  (ignore-errors (file-equal-p "/tmp/x" "x"))
  (ignore-errors (file-name-case-insensitive-p "/tmp/x"))
  (ignore-errors (file-name-history ))
  (ignore-errors (find-file-literally "/tmp/x"))
  (ignore-errors (find-font 42))
  (ignore-errors (fixnump 42))
  (ignore-errors (flatten-tree 42))
  (ignore-errors (float 1.5))
  (ignore-errors (floatp 1.5))
  (ignore-errors (floor [1 2]))
  (ignore-errors (flush-lines 42))
  (ignore-errors (flush-standard-output ))
  (ignore-errors (following-char ))
  (ignore-errors (fontp 42))
  (ignore-errors (fontset-list-all ))
  (ignore-errors (force-window-update ))
  (ignore-errors (forward-line-command ))
  (ignore-errors (frame--face-hash-table ))
  (ignore-errors (frame--list-z-order ))
  (ignore-errors (frame--set-was-invisible (selected-frame)))
  (ignore-errors (frame--z-order-lessp (selected-frame) nil))
  (ignore-errors (frame-after-make-frame (selected-frame) [1 2]))
  (ignore-errors (frame-ancestor-p (selected-frame) [1 2]))
  (ignore-errors (frame-bottom-divider-width ))
  (ignore-errors (frame-child-frame-border-width ))
  (ignore-errors (frame-focus-state ))
  (ignore-errors (frame-font-cache ))
  (ignore-errors (frame-fringe-width ))
  (ignore-errors (frame-id ))
  (ignore-errors (frame-initial-p ))
  (ignore-errors (frame-internal-border-width ))
  (ignore-errors (frame-old-selected-window ))
  (ignore-errors (frame-parent ))
  (ignore-errors (frame-pointer-visible-p ))
  (ignore-errors (frame-right-divider-width ))
  (ignore-errors (frame-root-frame ))
  (ignore-errors (frame-scale-factor ))
  (ignore-errors (frame-scroll-bar-height ))
  (ignore-errors (frame-scroll-bar-width ))
  (ignore-errors (frame-selected-window ))
  (ignore-errors (frame-selected-window ))
  (ignore-errors (frame-text-cols ))
  (ignore-errors (frame-text-lines ))
  (ignore-errors (frame-total-cols ))
  (ignore-errors (frame-total-lines ))
  (ignore-errors (frame-window-state-change ))
  (ignore-errors (frexp [1 2]))
  (ignore-errors (fround 42))
  (ignore-errors (ftruncate 42))
  (ignore-errors (funcall-with-delayed-message 42 [1 2]))
  (ignore-errors (function-equal 'car nil))
  (ignore-errors (fundamental-mode ))
  (ignore-errors (gap-position ))
  (ignore-errors (gap-size ))
  (ignore-errors (gensym ))
  (ignore-errors (get-char-property ?a 1))
  (ignore-errors (get-char-property-and-overlay ?a 1 "x"))
  (ignore-errors (get-file-buffer "*scratch*"))
  (ignore-errors (get-pos-property 1 [1 2]))
  (ignore-errors (get-process nil))
  (ignore-errors (get-text-property 'face 1))
  (ignore-errors (getenv-internal 42))
  (ignore-errors (gethash (make-hash-table) 'x))
  (ignore-errors (global-key-binding "\C-f"))
  (ignore-errors (hack-dir-local-variables ))
  (ignore-errors (hack-local-variables ))
  (ignore-errors (handle-change-group ))
  (ignore-errors (handle-select-window (selected-window)))
  (ignore-errors (hash-table-count 42))
  (ignore-errors (hash-table-keys "\C-f"))
  (ignore-errors (hash-table-p (make-hash-table)))
  (ignore-errors (hash-table-rehash-size (make-hash-table)))
  (ignore-errors (hash-table-rehash-threshold (make-hash-table)))
  (ignore-errors (hash-table-size (make-hash-table)))
  (ignore-errors (hash-table-test (make-hash-table)))
  (ignore-errors (hash-table-values (make-hash-table)))
  (ignore-errors (hash-table-weakness 42))
  (ignore-errors (help--docstring-quote ))
  (ignore-errors (how-many 42 nil))
  (ignore-errors (identity 42))
  (ignore-errors (innermost-minibuffer-p ))
  (ignore-errors (inside-comment-p ))
  (ignore-errors (integer-or-marker-p (point-marker)))
  (ignore-errors (integerp 42))
  (ignore-errors (interactive-p ))
  (ignore-errors (intern 42))
  (ignore-errors (internal--set-subr-doc ))
  (ignore-errors (internal--syntax-propertize ))
  (ignore-errors (internal-doc-string-p ))
  (ignore-errors (internal-event-symbol-parse-modifiers 'car))
  (ignore-errors (internal-make-interpreted-closure-function 'car "x" 'x))
  (ignore-errors (internal-make-var-non-special 42))
  (ignore-errors (internal-set-alist ))
  (ignore-errors (interpreted-function-p 'car))
  (ignore-errors (isnan 42))
  (ignore-errors (isqrt [1 2]))
  (ignore-errors (kbd-macro-query ))
  (ignore-errors (keep-lines 42))
  (ignore-errors (keymap--get-keyelt (current-global-map) "x"))
  (ignore-errors (keymap-get-key ))
  (ignore-errors (keywordp "\C-f"))
  (ignore-errors (kmacro-exec-ring-item 42 '(1 2)))
  (ignore-errors (last '(1 2)))
  (ignore-errors (ldexp [1 2]))
  (ignore-errors (line-number-at-pos ))
  (ignore-errors (list-fonts 42 [1 2] 1))
  (ignore-errors (list-length 42))
  (ignore-errors (list-tail '(1 2 3) '(1 2)))
  (ignore-errors (listp '(1 2 3)))
  (ignore-errors (local-variable-if-set-p 'point))
  (ignore-errors (local-variable-p 'point))
  (ignore-errors (lock-file "/tmp/x"))
  (ignore-errors (log nil))
  (ignore-errors (logb '(1 2)))
  (ignore-errors (logcount 42))
  (ignore-errors (lognot 42))
  (ignore-errors (lsh nil '(1 2)))
  (ignore-errors (macroexp-if [1 2] 1 "x"))
  (ignore-errors (macroexp-let* "x" 'x))
  (ignore-errors (macroexp-let2 "x" 'x nil))
  (ignore-errors (macroexp-parse-body "x"))
  (ignore-errors (macroexp-progn 42))
  (ignore-errors (macroexpand-1 42))
  (ignore-errors (major-mode-suspend ))
  (ignore-errors (make-char ?a))
  (ignore-errors (make-display-table ))
  (ignore-errors (make-marker ))
  (ignore-errors (make-overlay 1 "x"))
  (ignore-errors (make-string "abc def" 1))
  (ignore-errors (make-symbol 'car))
  (ignore-errors (make-symbolic-link 'car "x"))
  (ignore-errors (make-syntax-table ))
  (ignore-errors (make-temp-file-internal "/tmp/x" 1 "x"))
  (ignore-errors (make-vector [1 2 3] 1))
  (ignore-errors (map-keymap-internal (current-global-map) 'x))
  (ignore-errors (mapatoms (current-global-map)))
  (ignore-errors (mapc (current-global-map) [1 2]))
  (ignore-errors (mapcan (current-global-map) "x"))
  (ignore-errors (mapcar (current-global-map) "x"))
  (ignore-errors (mapconcat (current-global-map) '(1 2) [1 2]))
  (ignore-errors (mark-defun ))
  (ignore-errors (mark-page ))
  (ignore-errors (mark-whole-buffer ))
  (ignore-errors (marker-buffer "*scratch*"))
  (ignore-errors (marker-insertion-type (point-marker)))
  (ignore-errors (marker-last-position (point-marker)))
  (ignore-errors (marker-position (point-marker)))
  (ignore-errors (markerp (point-marker)))
  (ignore-errors (max-char ))
  (ignore-errors (menu-bar-menu-at-x-y 42 nil))
  (ignore-errors (menu-or-popup-active-p ))
  (ignore-errors (minibuffer-innermost-command-loop-p ))
  (ignore-errors (minibuffer-window-active-p "*scratch*"))
  (ignore-errors (minusp 42))
  (ignore-errors (mod nil '(1 2)))
  (ignore-errors (move-marker (point-marker)))
  (ignore-errors (move-overlay 1 "x" 'x))
  (ignore-errors (move-point-visually 1))
  (ignore-errors (multibyte-char-to-unibyte ?a))
  (ignore-errors (native-comp-available-p ))
  (ignore-errors (natnump 42))
  (ignore-errors (nbutlast 42))
  (ignore-errors (next-char-property-change ?a))
  (ignore-errors (next-line ))
  (ignore-errors (next-overlay-change 42))
  (ignore-errors (next-property-change 42))
  (ignore-errors (next-single-property-change 42 '(1 2)))
  (ignore-errors (nlistp 42))
  (ignore-errors (normal-mode ))
  (ignore-errors (not 42))
  (ignore-errors (ntake 42 1))
  (ignore-errors (null 42))
  (ignore-errors (number-or-marker-p (point-marker)))
  (ignore-errors (number-to-string "abc def"))
  (ignore-errors (numberp 42))
  (ignore-errors (obarray-make ))
  (ignore-errors (obarrayp 'x))
  (ignore-errors (object-intervals ))
  (ignore-errors (oddp '(1 2)))
  (ignore-errors (old-selected-frame ))
  (ignore-errors (old-selected-window ))
  (ignore-errors (one-window-p ))
  (ignore-errors (open-font 42))
  (ignore-errors (other-window-for-scrolling ))
  (ignore-errors (overlay-buffer "*scratch*"))
  (ignore-errors (overlay-end 2))
  (ignore-errors (overlay-get [1 2] 1))
  (ignore-errors (overlay-properties 'face))
  (ignore-errors (overlay-put [1 2] 1 "x"))
  (ignore-errors (overlay-start 1))
  (ignore-errors (overlayp 'x))
  (ignore-errors (overlays-at [1 2]))
  (ignore-errors (overlays-at-point ))
  (ignore-errors (overlays-in 42 1))
  (ignore-errors (plusp [1 2]))
  (ignore-errors (point-marker ))
  (ignore-errors (point-max-marker ))
  (ignore-errors (point-min-marker ))
  (ignore-errors (pos-bol ))
  (ignore-errors (pos-eol ))
  (ignore-errors (position-bytes 1))
  (ignore-errors (position-symbol 'car '(1 2)))
  (ignore-errors (preceding-char ))
  (ignore-errors (previous-char-property-change ?a))
  (ignore-errors (previous-line ))
  (ignore-errors (previous-overlay-change 42))
  (ignore-errors (previous-property-change 42))
  (ignore-errors (previous-single-property-change 42 'x))
  (ignore-errors (previous-window ))
  (ignore-errors (process-buffer "*scratch*"))
  (ignore-errors (process-exit-status nil))
  (ignore-errors (process-get nil 1))
  (ignore-errors (process-id nil))
  (ignore-errors (process-list ))
  (ignore-errors (process-mark nil))
  (ignore-errors (process-name nil))
  (ignore-errors (process-put nil 1 "x"))
  (ignore-errors (process-send-eof ))
  (ignore-errors (process-send-string "abc def" 'x))
  (ignore-errors (process-status nil))
  (ignore-errors (processp nil))
  (ignore-errors (proper-list-p '(1 2 3)))
  (ignore-errors (purecopy 'x))
  (ignore-errors (put-char-property ?a 1 "x"))
  (ignore-errors (put-text-property 'face 1 "x"))
  (ignore-errors (reconsider-frame-fonts ))
  (ignore-errors (redraw-display ))
  (ignore-errors (redraw-frame ))
  (ignore-errors (region-active-p ))
  (ignore-errors (remove-hook [1 2] 1))
  (ignore-errors (remove-list-of-text-properties '(1 2 3) "x" 'x))
  (ignore-errors (remove-overlays ))
  (ignore-errors (remove-pos-from-symbol 'car))
  (ignore-errors (remove-text-properties 'face [1 2] 1))
  (ignore-errors (replace-regexp "a+" nil))
  (ignore-errors (replace-string "abc def" nil))
  (ignore-errors (resize-mini-window-internal (selected-window)))
  (ignore-errors (reverse-region 42 nil))
  (ignore-errors (round 42))
  (ignore-errors (run-hook-wrapped 42 [1 2] 1))
  (ignore-errors (run-window-configuration-change-hook ))
  (ignore-errors (run-window-scroll-functions ))
  (ignore-errors (search-backward-regexp "a+"))
  (ignore-errors (search-forward-regexp "a+"))
  (ignore-errors (secure-hash-region 42 "x" 'x))
  (ignore-errors (seq-concatenate 42 '(1 2) [1 2]))
  (ignore-errors (seq-contains-p 42 nil))
  (ignore-errors (seq-copy '(1 2 3)))
  (ignore-errors (seq-count 42 '(1 2)))
  (ignore-errors (seq-do '(1 2 3) "x"))
  (ignore-errors (seq-drop '(1 2 3) nil))
  (ignore-errors (seq-drop-while '(1 2 3) nil))
  (ignore-errors (seq-elt '(1 2 3) 'x))
  (ignore-errors (seq-empty-p '(1 2 3)))
  (ignore-errors (seq-every-p '(1 2 3) 1))
  (ignore-errors (seq-filter '(1 2 3) [1 2]))
  (ignore-errors (seq-find 42 nil))
  (ignore-errors (seq-first '(1 2 3)))
  (ignore-errors (seq-into 42 nil))
  (ignore-errors (seq-last '(1 2 3)))
  (ignore-errors (seq-length 42))
  (ignore-errors (seq-map (current-global-map) 'x))
  (ignore-errors (seq-max '(1 2 3)))
  (ignore-errors (seq-min 42))
  (ignore-errors (seq-position 1 "x"))
  (ignore-errors (seq-reduce '(1 2 3) [1 2] 1))
  (ignore-errors (seq-remove '(1 2 3) [1 2]))
  (ignore-errors (seq-rest '(1 2 3)))
  (ignore-errors (seq-reverse '(1 2 3)))
  (ignore-errors (seq-some '(1 2 3) nil))
  (ignore-errors (seq-subseq '(1 2 3) [1 2]))
  (ignore-errors (seq-take '(1 2 3) nil))
  (ignore-errors (seq-take-while '(1 2 3) nil))
  (ignore-errors (seq-uniq 42))
  (ignore-errors (seqp '(1 2 3)))
  (ignore-errors (sequencep 42))
  (ignore-errors (set--this-command-keys 'forward-char))
  (ignore-errors (set-auto-mode ))
  (ignore-errors (set-auto-mode-0 ))
  (ignore-errors (set-default-toplevel-value 'x nil))
  (ignore-errors (set-display-table-slot (make-hash-table) [1 2] 1))
  (ignore-errors (set-frame-selected-window (selected-window) 'x))
  (ignore-errors (set-frame-size-and-position-pixelwise ))
  (ignore-errors (set-frame-window-state-change ))
  (ignore-errors (set-goal-column 42))
  (ignore-errors (set-marker (point-marker)))
  (ignore-errors (set-marker-insertion-type (point-marker) 'x))
  (ignore-errors (set-message-functions ))
  (ignore-errors (set-process-filter nil "x"))
  (ignore-errors (set-text-properties 'face 'x nil))
  (ignore-errors (set-visited-file-name ))
  (ignore-errors (set-window-cursor-type (selected-window) [1 2]))
  (ignore-errors (sin 42))
  (ignore-errors (sort-lines 42 [1 2]))
  (ignore-errors (special-variable-p 'point))
  (ignore-errors (split-char ?a))
  (ignore-errors (split-string "abc def"))
  (ignore-errors (sqrt '(1 2)))
  (ignore-errors (standard-display-table ))
  (ignore-errors (store-kbd-macro-event 42))
  (ignore-errors (store-substring "abc def" '(1 2) [1 2]))
  (ignore-errors (string-aref "abc def" 1))
  (ignore-errors (string-blank-p "abc def"))
  (ignore-errors (string-chop-newline "abc def"))
  (ignore-errors (string-compare "abc def" nil '(1 2)))
  (ignore-errors (string-distance "abc def" '(1 2)))
  (ignore-errors (string-empty-p "abc def"))
  (ignore-errors (string-fill "abc def" 1))
  (ignore-errors (string-glyph-split "abc def"))
  (ignore-errors (string-greaterp "abc def" '(1 2)))
  (ignore-errors (string-join "abc def"))
  (ignore-errors (string-pad "abc def" [1 2]))
  (ignore-errors (string-pixel-width "abc def"))
  (ignore-errors (string-replace "abc def" nil '(1 2)))
  (ignore-errors (string-search "abc def" 'x))
  (ignore-errors (string-to-char "abc def"))
  (ignore-errors (string-to-list "abc def"))
  (ignore-errors (string-to-number "abc def"))
  (ignore-errors (string-to-sequence "abc def"))
  (ignore-errors (string-to-vector "abc def"))
  (ignore-errors (string-trim "abc def"))
  (ignore-errors (string-trim-left "abc def"))
  (ignore-errors (string-trim-right "abc def"))
  (ignore-errors (string-version-lessp "abc def" nil))
  (ignore-errors (stringp "abc def"))
  (ignore-errors (substring "abc def"))
  (ignore-errors (substring-no-properties "abc def"))
  (ignore-errors (sxhash (make-hash-table)))
  (ignore-errors (sxhash-eq (make-hash-table)))
  (ignore-errors (sxhash-eql (make-hash-table)))
  (ignore-errors (sxhash-equal (make-hash-table)))
  (ignore-errors (sxhash-equal-including-properties 42))
  (ignore-errors (symbol-at-point ))
  (ignore-errors (symbol-name 'car))
  (ignore-errors (symbol-value 'car))
  (ignore-errors (symbol-with-pos-p 'car))
  (ignore-errors (symbol-with-pos-pos 'car))
  (ignore-errors (symbolp 'car))
  (ignore-errors (tab-to-tab-stop ))
  (ignore-errors (tabify ))
  (ignore-errors (take '(1 2) [1 2]))
  (ignore-errors (tan 42))
  (ignore-errors (terminal-id 42))
  (ignore-errors (text-properties-at 'face))
  (ignore-errors (text-property-any 42 1 "x"))
  (ignore-errors (text-property-not-all 42 '(1 2) [1 2]))
  (ignore-errors (text-props-copy 'face))
  (ignore-errors (thing-at-point 1))
  (ignore-errors (timer-activate (current-time)))
  (ignore-errors (timerp (current-time)))
  (ignore-errors (truncate 42))
  (ignore-errors (truncate-string-to-width "abc def" "x"))
  (ignore-errors (truncated-partial-width-window-p ))
  (ignore-errors (tty--output-buffer-size ))
  (ignore-errors (tty--set-output-buffer-size "*scratch*"))
  (ignore-errors (tty-color-values '(1 2)))
  (ignore-errors (tty-display-pixel-height ))
  (ignore-errors (tty-display-pixel-width ))
  (ignore-errors (tty-find-type 42 'x nil))
  (ignore-errors (tty-frame-at (selected-frame) "x"))
  (ignore-errors (tty-frame-list-z-order ))
  (ignore-errors (tty-frame-restack (selected-frame) 1 "x"))
  (ignore-errors (type-of "x"))
  (ignore-errors (uncombine-window (selected-window)))
  (ignore-errors (undo-auto-amalgamate ))
  (ignore-errors (undo-more 42))
  (ignore-errors (undo-outer-limit-truncate ))
  (ignore-errors (unibyte-char-to-multibyte ?a))
  (ignore-errors (unlock-file "/tmp/x"))
  (ignore-errors (untabify ))
  (ignore-errors (upcase 1))
  (ignore-errors (upcase-initials 42))
  (ignore-errors (use-region-p ))
  (ignore-errors (user-variable-p 'point))
  (ignore-errors (variable-binding-locus 'point))
  (ignore-errors (vectorp [1 2 3]))
  (ignore-errors (verify-visited-file-modtime-princ ))
  (ignore-errors (visible-p ))
  (ignore-errors (walk-windows (selected-window)))
  (ignore-errors (what-cursor-position ))
  (ignore-errors (what-line ))
  (ignore-errors (wholenump 42))
  (ignore-errors (window-absolute-body-pixel-edges ))
  (ignore-errors (window-absolute-pixel-position (selected-window) "x"))
  (ignore-errors (window-at (selected-window) '(1 2)))
  (ignore-errors (window-body-pixel-edges ))
  (ignore-errors (window-bottom-divider-width ))
  (ignore-errors (window-bump-use-time (selected-window)))
  (ignore-errors (window-combination-p (selected-window)))
  (ignore-errors (window-current-scroll-bars ))
  (ignore-errors (window-cursor-type ))
  (ignore-errors (window-deletable-p ))
  (ignore-errors (window-discard-buffer-from-window "*scratch*" '(1 2)))
  (ignore-errors (window-divider-width-valid-p (selected-window)))
  (ignore-errors (window-frame ))
  (ignore-errors (window-has-parameters ))
  (ignore-errors (window-inside-absolute-body-pixel-edges ))
  (ignore-errors (window-inside-absolute-pixel-edges ))
  (ignore-errors (window-left-char ))
  (ignore-errors (window-lines-pixel-dimensions ))
  (ignore-errors (window-max-delta ))
  (ignore-errors (window-min-delta ))
  (ignore-errors (window-min-size ))
  (ignore-errors (window-normal-size ))
  (ignore-errors (window-old-body-pixel-height ))
  (ignore-errors (window-old-body-pixel-width ))
  (ignore-errors (window-old-buffer ))
  (ignore-errors (window-old-pixel-height ))
  (ignore-errors (window-old-pixel-width ))
  (ignore-errors (window-old-point ))
  (ignore-errors (window-pixel-edges ))
  (ignore-errors (window-pixel-left ))
  (ignore-errors (window-pixel-top ))
  (ignore-errors (window-resize-apply (selected-window) 'x))
  (ignore-errors (window-resize-apply-total (selected-window) 'x))
  (ignore-errors (window-right-divider-width ))
  (ignore-errors (window-safe-min-height ))
  (ignore-errors (window-safe-min-width ))
  (ignore-errors (window-safe-p ))
  (ignore-errors (window-screen-lines ))
  (ignore-errors (window-sizable-p (selected-window)))
  (ignore-errors (window-size-fixed-p ))
  (ignore-errors (window-splittable-p ))
  (ignore-errors (windowp (selected-window)))
  (ignore-errors (word-at-point ))
  (ignore-errors (write-char ?a))
  (ignore-errors (write-region-annotate-functions ))
  (ignore-errors (write-region-charset-for-write ))
  (ignore-errors (write-region-post-annotation-function ))
  (ignore-errors (x-color-values 'x))
  (ignore-errors (x-focus-frame (selected-frame)))
  (ignore-errors (x-menu-bar-open-internal ))
  (ignore-errors (zerop [1 2]))
  nil)