;; Edge-args coverage probe: typed values exercising branch bodies.
(progn
  ;; ---- arithmetic ----
  (ignore-errors (+)) (ignore-errors (+ 5)) (ignore-errors (+ 1 2 3.5))
  (ignore-errors (- 10 3)) (ignore-errors (- 10)) (ignore-errors (- 1.5))
  (ignore-errors (*)) (ignore-errors (* 2 3 4)) (ignore-errors (* 2.5 4))
  (ignore-errors (/ 10 3)) (ignore-errors (/ 10.0 3)) (ignore-errors (/ 1 0))
  (ignore-errors (/ 1.0 0)) (ignore-errors (% 10 3)) (ignore-errors (% -10 3))
  (ignore-errors (% 10 -3)) (ignore-errors (% 10.5 3)) (ignore-errors (mod 10 3))
  (ignore-errors (mod -10 3)) (ignore-errors (mod 10 -3)) (ignore-errors (mod 10.5 3))
  (ignore-errors (1+ 5)) (ignore-errors (1- 5)) (ignore-errors (abs -5))
  (ignore-errors (abs 5.5)) (ignore-errors (abs -5.5))
  (ignore-errors (min 1 2 3)) (ignore-errors (min 1.5 2)) (ignore-errors (min 1))
  (ignore-errors (max 1 2 3)) (ignore-errors (max 1.5 2)) (ignore-errors (max 1))
  (ignore-errors (expt 2 10)) (ignore-errors (expt 2 0)) (ignore-errors (expt 2 -1))
  (ignore-errors (expt 2.0 10)) (ignore-errors (expt -2 3)) (ignore-errors (expt 0 0))
  (ignore-errors (sqrt 16)) (ignore-errors (sqrt 2.0)) (ignore-errors (sqrt -1))
  (ignore-errors (isqrt 16)) (ignore-errors (isqrt 17)) (ignore-errors (isqrt -1))
  (ignore-errors (floor 7.5)) (ignore-errors (floor -7.5)) (ignore-errors (floor 7.5 2))
  (ignore-errors (floor 7)) (ignore-errors (ceiling 7.5)) (ignore-errors (ceiling -7.5))
  (ignore-errors (ceiling 7)) (ignore-errors (round 7.5)) (ignore-errors (round -7.5))
  (ignore-errors (round 7.4)) (ignore-errors (round 7.6)) (ignore-errors (round 7))
  (ignore-errors (truncate 7.5)) (ignore-errors (truncate -7.5)) (ignore-errors (truncate 7))
  (ignore-errors (ffloor 7.5)) (ignore-errors (fceiling 7.5))
  (ignore-errors (fround 7.5)) (ignore-errors (ftruncate 7.5))
  (ignore-errors (ash 1 10)) (ignore-errors (ash -1 10)) (ignore-errors (ash 256 -4))
  (ignore-errors (ash 1 -10)) (ignore-errors (ash -256 -4)) (ignore-errors (ash 1 100))
  (ignore-errors (lsh 1 10)) (ignore-errors (lsh -1 10)) (ignore-errors (lsh -1 -1))
  (ignore-errors (lsh 256 -4)) (ignore-errors (lsh -1 62)) (ignore-errors (lsh -1 -62))
  (ignore-errors (logand 15 9)) (ignore-errors (logand 15)) (ignore-errors (logand))
  (ignore-errors (logior 8 4)) (ignore-errors (logior)) (ignore-errors (logxor 15 9))
  (ignore-errors (logxor)) (ignore-errors (lognot 0)) (ignore-errors (lognot -1))
  (ignore-errors (logcount 15)) (ignore-errors (logcount -1)) (ignore-errors (logcount 0))
  (ignore-errors (= 1 1)) (ignore-errors (= 1 1.0)) (ignore-errors (= 1 2))
  (ignore-errors (= 1 1 1)) (ignore-errors (< 1 2)) (ignore-errors (< 1 1))
  (ignore-errors (< 1 2 3)) (ignore-errors (< 1 3 2)) (ignore-errors (> 2 1))
  (ignore-errors (<= 1 1)) (ignore-errors (>= 1 1)) (ignore-errors (/= 1 2))
  (ignore-errors (/= 1 1)) (ignore-errors (eq 1 1)) (ignore-errors (eql 1 1))
  (ignore-errors (eql 1 1.0)) (ignore-errors (eql 'a 'a))
  (ignore-errors (sin 0)) (ignore-errors (cos 0)) (ignore-errors (tan 0))
  (ignore-errors (asin 0)) (ignore-errors (acos 1)) (ignore-errors (atan 1))
  (ignore-errors (atan 1 2)) (ignore-errors (exp 0)) (ignore-errors (exp 1))
  (ignore-errors (log 1)) (ignore-errors (log 10 10)) (ignore-errors (log -1))
  (ignore-errors (log 0)) (ignore-errors (expt 10 2)) (ignore-errors (logb 8))
  (ignore-errors (logb -8)) (ignore-errors (logb 0.5))
  (ignore-errors (float 5)) (ignore-errors (float -5)) (ignore-errors (float 5.5))
  (ignore-errors (truncate 5.9)) (ignore-errors (copysign 1.5 -2.0))
  (ignore-errors (copysign -1.5 2.0)) (ignore-errors (copysign 1.5 2.0))
  (ignore-errors (frexp 8.0)) (ignore-errors (frexp -8.0)) (ignore-errors (frexp 0.0))
  (ignore-errors (ldexp 0.5 4)) (ignore-errors (ldexp 1.0 -4))
  (ignore-errors (fexpt 2.0 3.0)) (ignore-errors (fmin 1.5 2.5))
  (ignore-errors (fmax 1.5 2.5)) (ignore-errors (fabs -1.5))
  (ignore-errors (fceiling 1.2)) (ignore-errors (ffloor 1.8))
  (ignore-errors (float-e 0)) (ignore-errors (float-pi 0))
  (ignore-errors (degrees-to-radians 180)) (ignore-errors (radians-to-degrees 3.14159))
  (ignore-errors (most-positive-fixnum)) (ignore-errors (most-negative-fixnum))
  (ignore-errors (+ most-positive-fixnum 1))
  (ignore-errors (* most-positive-fixnum 2))
  (ignore-errors (- most-negative-fixnum 1))
  (ignore-errors (ash 1 61)) (ignore-errors (ash 1 62))
  (ignore-errors (random)) (ignore-errors (random 10)) (ignore-errors (random -5))
  (ignore-errors (random 1.5)) (ignore-errors (random t))
  ;; ---- numbers<->strings ----
  (ignore-errors (number-to-string 42)) (ignore-errors (number-to-string -42))
  (ignore-errors (number-to-string 4.5)) (ignore-errors (string-to-number "42"))
  (ignore-errors (string-to-number "-42")) (ignore-errors (string-to-number "4.5"))
  (ignore-errors (string-to-number "0x10")) (ignore-errors (string-to-number "#x10"))
  (ignore-errors (string-to-number "10abc")) (ignore-errors (string-to-number "abc"))
  (ignore-errors (string-to-number "")) (ignore-errors (string-to-number "42" 16))
  (ignore-errors (string-to-number "ff" 16)) (ignore-errors (string-to-number "b101" 2))
  (ignore-errors (string-to-number "o17" 8)) (ignore-errors (string-to-number "10" 0))
  (ignore-errors (string-to-number "10" 37))
  ;; ---- sequences ----
  (ignore-errors (length '(1 2 3))) (ignore-errors (length [1 2 3]))
  (ignore-errors (length "abc")) (ignore-errors (length nil))
  (ignore-errors (safe-length '(1 2 3))) (ignore-errors (safe-length nil))
  (ignore-errors (elt '(1 2 3) 0)) (ignore-errors (elt '(1 2 3) 2))
  (ignore-errors (elt '(1 2 3) 5)) (ignore-errors (elt '(1 2 3) -1))
  (ignore-errors (elt [1 2 3] 1)) (ignore-errors (elt "abc" 1))
  (ignore-errors (aref [1 2 3] 0)) (ignore-errors (aset [1 2 3] 0 9))
  (ignore-errors (aref "abc" 0)) (ignore-errors (fillarray [1 2] 9))
  (ignore-errors (fillarray "abc" ?x)) (ignore-errors (fillarray (make-bool-vector 3 nil) t))
  (ignore-errors (vconcat [1] [2])) (ignore-errors (vconcat "ab" "cd"))
  (ignore-errors (vconcat '(1) '(2))) (ignore-errors (vconcat [1] '(2) "ab" 1 2.5))
  (ignore-errors (append '(1) '(2))) (ignore-errors (append '(1) [2]))
  (ignore-errors (append "ab" "cd")) (ignore-errors (append nil '(1)))
  (ignore-errors (append '(1) 5)) (ignore-errors (append '(1) '(2) '(3)))
  (ignore-errors (reverse '(1 2 3))) (ignore-errors (reverse [1 2 3]))
  (ignore-errors (reverse "abc")) (ignore-errors (reverse nil))
  (ignore-errors (nreverse '(1 2 3))) (ignore-errors (nreverse [1 2 3]))
  (ignore-errors (nreverse "abc"))
  (ignore-errors (copy-sequence '(1 2))) (ignore-errors (copy-sequence [1 2]))
  (ignore-errors (copy-sequence "ab")) (ignore-errors (copy-tree '(1 (2))))
  (ignore-errors (seqp '(1))) (ignore-errors (seqp "x")) (ignore-errors (seqp [1]))
  (ignore-errors (seqp 1)) (ignore-errors (sequencep '(1)))
  (ignore-errors (seq-length '(1 2))) (ignore-errors (seq-length "ab"))
  (ignore-errors (seq-elt '(1 2) 1)) (ignore-errors (seq-elt "ab" 1))
  (ignore-errors (seq-take '(1 2 3) 2)) (ignore-errors (seq-take "abc" 2))
  (ignore-errors (seq-drop '(1 2 3) 1)) (ignore-errors (seq-drop "abc" 1))
  (ignore-errors (seq-subseq '(1 2 3) 1 2)) (ignore-errors (seq-subseq "abc" 1 2))
  (ignore-errors (seq-position '(1 2 3) 2)) (ignore-errors (seq-position "abc" ?b))
  (ignore-errors (seq-contains '(1 2) 2)) (ignore-errors (seq-contains "ab" ?z))
  (ignore-errors (seq-find #'integerp '(a 1 b))) (ignore-errors (seq-find #'symbolp '(1)))
  (ignore-errors (seq-count #'integerp '(a 1 b 2))) (ignore-errors (seq-remove 1 '(1 2 1)))
  (ignore-errors (seq-remove-if #'integerp '(a 1 b))) (ignore-errors (seq-remove-if-not #'integerp '(a 1)))
  (ignore-errors (seq-filter #'integerp '(a 1 b 2))) (ignore-errors (seq-map #'1+ '(1 2)))
  (ignore-errors (seq-map #'1+ [1 2])) (ignore-errors (seq-map #'upcase "ab"))
  (ignore-errors (seq-mapn #'+ '(1 2) '(3 4))) (ignore-errors (seq-concatenate 'list "ab" '(1)))
  (ignore-errors (seq-concatenate 'string '(97) "x")) (ignore-errors (seq-concatenate 'vector '(1) [2]))
  (ignore-errors (seq-into '(1 2) 'vector)) (ignore-errors (seq-into "ab" 'list))
  (ignore-errors (seq-into [1] 'string)) (ignore-errors (seq-into '(1) 'string))
  (ignore-errors (seq-copy '(1 2))) (ignore-errors (seq-sort #'< '(3 1 2)))
  (ignore-errors (seq-sort #'> '(3 1 2))) (ignore-errors (seq-reverse '(1 2 3)))
  (ignore-errors (seq-uniq '(1 1 2 2))) (ignore-errors (seq-uniq '(1 1 2) #'eql))
  (ignore-errors (seq-group-by #'integerp '(a 1 b 2))) (ignore-errors (seq-union '(1 2) '(2 3)))
  (ignore-errors (seq-intersection '(1 2) '(2 3))) (ignore-errors (seq-difference '(1 2) '(2)))
  (ignore-errors (seq-every-p #'integerp '(1 2))) (ignore-errors (seq-some #'integerp '(a 1)))
  (ignore-errors (seq-first '(1 2))) (ignore-errors (seq-rest '(1 2)))
  (ignore-errors (seq-last '(1 2))) (ignore-errors (seq-head '(1 2 3) 2))
  (ignore-errors (seq-tail '(1 2 3) 1)) (ignore-errors (seq-take-while #'integerp '(1 2 a)))
  (ignore-errors (seq-drop-while #'integerp '(1 2 a))) (ignore-errors (seq-map-indexed (lambda (x i) i) '(a b)))
  (ignore-errors (seq-min '(3 1 2))) (ignore-errors (seq-max '(3 1 2)))
  (ignore-errors (seq-random-elt '(1 2 3))) (ignore-errors (seq-empty-p nil))
  (ignore-errors (seq-empty-p '(1))) (ignore-errors (seq-empty-p ""))
  (ignore-errors (seq-do (lambda (x) x) '(1 2))) (ignore-errors (seq-do-indexed (lambda (x i) x) '(a)))
  (ignore-errors (seq-reduce #'+ '(1 2 3) 0)) (ignore-errors (seq-reduce #'cons '(1 2) nil))
  (ignore-errors (seq-partition '(1 2 3 4) 2)) (ignore-errors (seq-split '(1 2 3) 2))
  (ignore-errors (seq-position '(1 2) 2 #'eql)) (ignore-errors (seq-mapcat #'list '(1 2)))
  (ignore-errors (seq-let (a b) '(1 2) (+ a b)))
  ;; ---- lists ----
  (ignore-errors (car '(1 2))) (ignore-errors (cdr '(1 2))) (ignore-errors (car nil))
  (ignore-errors (cdr nil)) (ignore-errors (car-safe '(1))) (ignore-errors (cdr-safe '(1)))
  (ignore-errors (car-safe 1)) (ignore-errors (cdr-safe 1))
  (ignore-errors (caar '((1) 2))) (ignore-errors (cadr '(1 2)))
  (ignore-errors (cdar '((1) 2))) (ignore-errors (cddr '(1 2 3)))
  (ignore-errors (caaar '(((1))))) (ignore-errors (caadr '(1 (2))))
  (ignore-errors (cadar '((1 2)))) (ignore-errors (caddr '(1 2 3)))
  (ignore-errors (cdaar '(((1))))) (ignore-errors (cdadr '(1 (2 3))))
  (ignore-errors (cddar '((1 2 3)))) (ignore-errors (cdddr '(1 2 3 4)))
  (ignore-errors (caaaar '((((1)))))) (ignore-errors (caaadr '(1 ((2)))))
  (ignore-errors (caadar '((1 (2))))) (ignore-errors (caaddr '(1 2 (3))))
  (ignore-errors (cadaar '(((1) 2)))) (ignore-errors (cadadr '(1 (2 3))))
  (ignore-errors (caddar '((1 2 3)))) (ignore-errors (cadddr '(1 2 3 4)))
  (ignore-errors (cdaaar '((((1) 2))))) (ignore-errors (cdadar '((1 (2 3)))))
  (ignore-errors (cddaar '(((1 2 3))))) (ignore-errors (cddadr '(1 (2 3 4))))
  (ignore-errors (cdddar '((1 2 3 4)))) (ignore-errors (cddddr '(1 2 3 4 5)))
  (ignore-errors (first '(1 2))) (ignore-errors (second '(1 2)))
  (ignore-errors (third '(1 2 3))) (ignore-errors (fourth '(1 2 3 4)))
  (ignore-errors (fifth '(1 2 3 4 5))) (ignore-errors (sixth '(1 2 3 4 5 6)))
  (ignore-errors (seventh '(1 2 3 4 5 6 7))) (ignore-errors (eighth '(1 2 3 4 5 6 7 8)))
  (ignore-errors (ninth '(1 2 3 4 5 6 7 8 9))) (ignore-errors (tenth '(1 2 3 4 5 6 7 8 9 10)))
  (ignore-errors (rest '(1 2))) (ignore-errors (nth 0 '(a b c)))
  (ignore-errors (nth 1 '(a b c))) (ignore-errors (nth 2 '(a b c)))
  (ignore-errors (nth 5 '(a b))) (ignore-errors (nth -1 '(a b)))
  (ignore-errors (nth -5 '(a b))) (ignore-errors (nthcdr 0 '(a b c)))
  (ignore-errors (nthcdr 2 '(a b c))) (ignore-errors (nthcdr 5 '(a b)))
  (ignore-errors (nthcdr -1 '(a b))) (ignore-errors (last '(1 2 3)))
  (ignore-errors (last '(1 . 2))) (ignore-errors (last nil))
  (ignore-errors (last '(1 2 3) 2)) (ignore-errors (last '(1 2 3) 0))
  (ignore-errors (butlast '(1 2 3))) (ignore-errors (butlast '(1 2 3) 2))
  (ignore-errors (butlast nil)) (ignore-errors (nbutlast '(1 2 3)))
  (ignore-errors (nbutlast '(1 2 3) 1)) (ignore-errors (take 2 '(1 2 3)))
  (ignore-errors (take 5 '(1 2))) (ignore-errors (take 0 '(1 2)))
  (ignore-errors (ntake 2 '(1 2 3))) (ignore-errors (ntake 0 '(1 2)))
  (ignore-errors (cons 1 2)) (ignore-errors (cons 1 '(2))) (ignore-errors (cons nil nil))
  (ignore-errors (list)) (ignore-errors (list 1)) (ignore-errors (list 1 2 3))
  (ignore-errors (list* 1 2)) (ignore-errors (list* 1 '(2))) (ignore-errors (list* 1))
  (ignore-errors (make-list 3 'x)) (ignore-errors (make-list 0 'x))
  (ignore-errors (member 2 '(1 2 3))) (ignore-errors (member 5 '(1 2)))
  (ignore-errors (member "b" '("a" "b"))) (ignore-errors (memq 'b '(a b c)))
  (ignore-errors (memq 5 '(1 2))) (ignore-errors (memql 1.5 '(1 1.5)))
  (ignore-errors (delq 'b '(a b c))) (ignore-errors (remq 'b '(a b c)))
  (ignore-errors (delete 2 '(1 2 3))) (ignore-errors (delete "b" '("a" "b")))
  (ignore-errors (remove 2 '(1 2 3))) (ignore-errors (remq 'x nil))
  (ignore-errors (assoc 'b '((a . 1) (b . 2)))) (ignore-errors (assoc 2 '((1 . a) (2 . b))))
  (ignore-errors (assoc "b" '(("a" . 1)))) (ignore-errors (assq 'b '((a . 1) (b . 2))))
  (ignore-errors (rassoc 2 '((a . 1) (b . 2)))) (ignore-errors (rassq 'b '((a . 1) (b . 2))))
  (ignore-errors (assoc-default 'a '((a . 1)))) (ignore-errors (assoc-string "b" '(("b" . 1))))
  (ignore-errors (assoc-string "B" '(("b" . 1)) t)) (ignore-errors (assq-delete-all 'a '((a . 1) (b . 2))))
  (ignore-errors (rassq-delete-all 1 '((a . 1) (b . 2)))) (ignore-errors (copy-alist '((a . 1))))
  (ignore-errors (assoc-if #'consp '((1) . 2))) (ignore-errors (assoc-if-not #'consp '((1 . 2))))
  (ignore-errors (plist-get '(a 1 b 2) 'a)) (ignore-errors (plist-get '(a 1) 'z))
  (ignore-errors (plist-get '(a 1) 'a 'x)) (ignore-errors (plist-put '(a 1) 'b 2))
  (ignore-errors (plist-put nil 'a 1)) (ignore-errors (plist-member '(a 1) 'a))
  (ignore-errors (plist-member '(a 1) 'b)) (ignore-errors (lax-plist-get '(a 1) 'a))
  (ignore-errors (lax-plist-put '(a 1) 'b 2)) (ignore-errors (lax-plist-member '(a 1) 'a))
  (ignore-errors (proper-list-p '(1 2))) (ignore-errors (proper-list-p '(1 . 2)))
  (ignore-errors (proper-list-p nil)) (ignore-errors (proper-list-p 1))
  (ignore-errors (consp '(1 . 2))) (ignore-errors (atom '(1))) (ignore-errors (atom 1))
  (ignore-errors (listp '(1 . 2))) (ignore-errors (nlistp '(1))) (ignore-errors (nlistp 1))
  (ignore-errors (push 'x 'l)) (ignore-errors (pop 'l))
  (ignore-errors (add-to-list 'l 'x)) (ignore-errors (add-to-ordered-list 'l 1))
  (ignore-errors (delq-from-list 'l 'x)) (ignore-errors (delete-from-list 'l 'x))
  (ignore-errors (list-insert 'l 0 'x))
  ;; ---- strings ----
  (ignore-errors (string "")) (ignore-errors (string ?a ?b ?c)) (ignore-errors (string 65))
  (ignore-errors (make-string 5 ?x)) (ignore-errors (make-string 0 ?x))
  (ignore-errors (substring "abcdef" 1)) (ignore-errors (substring "abcdef" 1 3))
  (ignore-errors (substring "abcdef" -2)) (ignore-errors (substring "abcdef" 0 0))
  (ignore-errors (substring "abcdef" -3 -1)) (ignore-errors (substring "abcdef" 1 99))
  (ignore-errors (substring "abcdef" 5 1)) (ignore-errors (substring [1 2 3] 1))
  (ignore-errors (substring [1 2 3] 1 2)) (ignore-errors (substring "abcdef" nil nil))
  (ignore-errors (concat)) (ignore-errors (concat "a")) (ignore-errors (concat "a" "b"))
  (ignore-errors (concat "a" '(98) "c")) (ignore-errors (concat '(97) "bc"))
  (ignore-errors (concat [97] "bc")) (ignore-errors (concat ?a)) (ignore-errors (concat 1))
  (ignore-errors (concat "a" nil "b"))
  (ignore-errors (string= "a" "a")) (ignore-errors (string= "a" "b"))
  (ignore-errors (string= "a" 'a)) (ignore-errors (string= 'a "a"))
  (ignore-errors (string= "a" 1)) (ignore-errors (string-equal "a" "a"))
  (ignore-errors (string< "a" "b")) (ignore-errors (string< "b" "a"))
  (ignore-errors (string< "a" "a")) (ignore-errors (string< 'a 'b))
  (ignore-errors (string< 'a "b")) (ignore-errors (string< "a" 'b))
  (ignore-errors (string< "a" 1)) (ignore-errors (string-lessp "a" "b"))
  (ignore-errors (string> "b" "a")) (ignore-errors (string<= "a" "a"))
  (ignore-errors (string<= "a" "b")) (ignore-errors (string>= "b" "a"))
  (ignore-errors (string-equal-ignore-case "ABC" "abc"))
  (ignore-errors (string-collate-equalp "a" "a")) (ignore-errors (string-collate-lessp "a" "b"))
  (ignore-errors (compare-strings "abc" 0 2 "abc" 0 2))
  (ignore-errors (compare-strings "abc" 0 nil "abd" 0 nil))
  (ignore-errors (compare-strings "abc" 0 nil "abd" 0 nil t))
  (ignore-errors (string-prefix-p "ab" "abc")) (ignore-errors (string-prefix-p "ab" "abc" t))
  (ignore-errors (string-prefix-p "AB" "abc" t)) (ignore-errors (string-suffix-p "bc" "abc"))
  (ignore-errors (string-suffix-p "BC" "abc" t)) (ignore-errors (string-contains-p "b" "abc"))
  (ignore-errors (string-contains-p "z" "abc"))
  (ignore-errors (string-blank-p "")) (ignore-errors (string-blank-p "  "))
  (ignore-errors (string-blank-p " x ")) (ignore-errors (string-blank-p "a"))
  (ignore-errors (string-empty-p "")) (ignore-errors (string-empty-p "x"))
  (ignore-errors (string-pad "x" 5)) (ignore-errors (string-pad "x" 5 ?-))
  (ignore-errors (string-pad "x" 5 ?- t)) (ignore-errors (string-pad "longstring" 2))
  (ignore-errors (string-chop-newline "x\n")) (ignore-errors (string-chop-newline "x"))
  (ignore-errors (string-trim "  x  ")) (ignore-errors (string-trim "xxax" "x"))
  (ignore-errors (string-trim "xxax" "x" "x")) (ignore-errors (string-trim-left "  x  "))
  (ignore-errors (string-trim-left "xxy" "x")) (ignore-errors (string-trim-right "  x  "))
  (ignore-errors (string-trim-right "yxx" "x"))
  (ignore-errors (string-split "a b c")) (ignore-errors (string-split "a b c" " "))
  (ignore-errors (string-split "a, b, c" ", ")) (ignore-errors (string-split "a  b" " +" t))
  (ignore-errors (string-split "a, b, c" ", " t)) (ignore-errors (string-split "" ""))
  (ignore-errors (split-string "a b c")) (ignore-errors (split-string "a b c" " "))
  (ignore-errors (split-string "a, b" ", " t)) (ignore-errors (split-string "a,b" "," nil "trim"))
  (ignore-errors (split-string-and-unquote "a 'b' c"))
  (ignore-errors (split-string-shell-command "a 'b c' d"))
  (ignore-errors (string-join '("a" "b"))) (ignore-errors (string-join '("a" "b") "-"))
  (ignore-errors (string-join '("a") "-")) (ignore-errors (string-join nil "-"))
  (ignore-errors (string-lines "a\nb\nc")) (ignore-errors (string-lines "a"))
  (ignore-errors (string-lines "")) (ignore-errors (string-lines "a\n"))
  (ignore-errors (string-replace "a" "X" "banana")) (ignore-errors (string-replace "z" "X" "abc"))
  (ignore-errors (replace-regexp-in-string "a" "X" "banana"))
  (ignore-errors (replace-regexp-in-string "a" "X" "banana" t))
  (ignore-errors (replace-regexp-in-string "\\(a\\)" "[\\1]" "banana"))
  (ignore-errors (match-substitute-replacement "X&Y"))
  (ignore-errors (match-substitute-replacement "X\\&Y"))
  (ignore-errors (string-fill "abc" 10)) (ignore-errors (string-limit "abcdef" 3))
  (ignore-errors (string-limit "abcdef" 3 t)) (ignore-errors (string-limit "abc" 3))
  (ignore-errors (string-clean-whitespace " a  b   c "))
  (ignore-errors (string-clean-whitespace "a\nb\tc"))
  (ignore-errors (string-replace-from-to-string "a" "b" "aaa"))
  (ignore-errors (string-replace "x" "y" "abc"))
  (ignore-errors (upcase "abc")) (ignore-errors (downcase "ABC"))
  (ignore-errors (upcase-initials "abc def")) (ignore-errors (capitalize "abc def"))
  (ignore-errors (upcase ?a)) (ignore-errors (downcase ?A)) (ignore-errors (capitalize ?a))
  (ignore-errors (upcase 97)) (ignore-errors (upcase -1))
  (ignore-errors (char-to-string ?a)) (ignore-errors (char-to-string 65))
  (ignore-errors (string-to-char "abc")) (ignore-errors (string-to-char ""))
  (ignore-errors (string-to-vector "abc")) (ignore-errors (string-to-vector "abc" 1))
  (ignore-errors (string-to-vector "abc" 1 2)) (ignore-errors (vector-to-string [97 98]))
  (ignore-errors (vconcat "ab" "cd"))
  (ignore-errors (format "x")) (ignore-errors (format "%s" 'a)) (ignore-errors (format "%s" "a"))
  (ignore-errors (format "%S" "a")) (ignore-errors (format "%d" 5)) (ignore-errors (format "%c" 65))
  (ignore-errors (format "%c" ?a)) (ignore-errors (format "%e" 1.5)) (ignore-errors (format "%f" 1.5))
  (ignore-errors (format "%g" 1.5)) (ignore-errors (format "%o" 8)) (ignore-errors (format "%x" 255))
  (ignore-errors (format "%X" 255)) (ignore-errors (format "%%")) (ignore-errors (format "%5d" 3))
  (ignore-errors (format "%-5d" 3)) (ignore-errors (format "%05d" 3)) (ignore-errors (format "%+d" 3))
  (ignore-errors (format "% d" 3)) (ignore-errors (format "%.2f" 1.234)) (ignore-errors (format "%10.3f" 1.2345))
  (ignore-errors (format "%2$s %1$s" 'a 'b)) (ignore-errors (format "%1$s %1$s" 'a))
  (ignore-errors (format "%s %s %s" 'a 'b 'c)) (ignore-errors (format "%s" 1 2 3))
  (ignore-errors (format "%s %s" 1)) (ignore-errors (format "%z" 1))
  (ignore-errors (format nil)) (ignore-errors (format ""))
  (ignore-errors (format-message "%s" 'a)) (ignore-errors (format-network-address nil))
  (ignore-errors (format-time-string "%Y" (current-time)))
  (ignore-errors (format-time-string "%Y-%m-%d" (current-time) "UTC"))
  (ignore-errors (format-seconds "%y %d %h %m %s %z" 1000000))
  (ignore-errors (format-spec "%a %b" '((?a . "A") (?b . "B"))))
  ;; ---- print/read ----
  (ignore-errors (prin1-to-string 42)) (ignore-errors (prin1-to-string "s"))
  (ignore-errors (prin1-to-string 'sym)) (ignore-errors (prin1-to-string '(1 . 2)))
  (ignore-errors (prin1-to-string '(1 2 3))) (ignore-errors (prin1-to-string [1 2]))
  (ignore-errors (prin1-to-string 1.5)) (ignore-errors (prin1-to-string nil))
  (ignore-errors (prin1-to-string t)) (ignore-errors (prin1-to-string (make-hash-table)))
  (ignore-errors (prin1-to-string (point-marker))) (ignore-errors (prin1-to-string #'car))
  (ignore-errors (princ-to-string 42)) (ignore-errors (princ-to-string "s"))
  (ignore-errors (princ-to-string 'sym)) (ignore-errors (prin1-to-string "a\nb"))
  (ignore-errors (prin1-to-string "a\"b")) (ignore-errors (prin1-to-string 'a\ b))
  (ignore-errors (prin1-to-string (make-symbol "x")))
  (ignore-errors (let ((print-gensym t)) (prin1-to-string (make-symbol "x"))))
  (ignore-errors (let ((print-gensym nil)) (prin1-to-string (make-symbol "x"))))
  (ignore-errors (let ((print-quoted t)) (prin1-to-string '(quote a))))
  (ignore-errors (let ((print-quoted nil)) (prin1-to-string '(quote a))))
  (ignore-errors (let ((print-escape-newlines t)) (prin1-to-string "a\nb")))
  (ignore-errors (let ((print-escape-newlines nil)) (prin1-to-string "a\nb")))
  (ignore-errors (let ((print-escape-multibyte t)) (prin1-to-string "あ")))
  (ignore-errors (let ((print-escape-nonascii t)) (prin1-to-string "あ")))
  (ignore-errors (let ((print-length 2)) (prin1-to-string '(1 2 3))))
  (ignore-errors (let ((print-level 1)) (prin1-to-string '((1) (2)))))
  (ignore-errors (let ((print-circle t)) (prin1-to-string '(1 2))))
  (ignore-errors (let ((print-integer-radix t)) (prin1-to-string 255)))
  (ignore-errors (let ((print-integer-radix t) (print-radix 16)) (prin1-to-string 255)))
  (ignore-errors (read "(a b)")) (ignore-errors (read "42")) (ignore-errors (read "\"s\""))
  (ignore-errors (read "'a")) (ignore-errors (read "(quote a)"))
  (ignore-errors (read "`(a ,b ,@c)")) (ignore-errors (read "(a . b)"))
  (ignore-errors (read "[1 2 3]")) (ignore-errors (read "#s(a 1)"))
  (ignore-errors (read "?a")) (ignore-errors (read "?\\C-a")) (ignore-errors (read "?\\M-x"))
  (ignore-errors (read "#:sym")) (ignore-errors (read "#1=(a . #1#)"))
  (ignore-errors (read "(a #1=(b) #1#)")) (ignore-errors (read "#s(rec 1 2)"))
  (ignore-errors (read "(a .)")) (ignore-errors (read "()"))
  (ignore-errors (read "(a b . c)")) (ignore-errors (read "(a . b c)"))
  (ignore-errors (read "#<x>")) (ignore-errors (read "#("))
  (ignore-errors (read "1.5")) (ignore-errors (read "1e3")) (ignore-errors (read "1."))
  (ignore-errors (read ".5")) (ignore-errors (read "+1")) (ignore-errors (read "-1"))
  (ignore-errors (read "0x10")) (ignore-errors (read "#x10")) (ignore-errors (read "#o17"))
  (ignore-errors (read "#b101")) (ignore-errors (read "#16rff"))
  (ignore-errors (read "\\")) (ignore-errors (read "a\\ b"))
  (ignore-errors (read-from-string "(a) (b)")) (ignore-errors (car (read-from-string "5" 0)))
  (ignore-errors (read-from-string "")) (ignore-errors (read-from-string ")"))
  (ignore-errors (read-from-string "#$"))
  ;; ---- data/types ----
  (ignore-errors (car (read-from-string "#s(r 1 2)")))
  (ignore-errors (setcar '(1 2) 9)) (ignore-errors (setcdr '(1 2) 9))
  (ignore-errors (setcdr '(1 2) '(3))) (ignore-errors (setq a 1))
  (ignore-errors (set 'a 5)) (ignore-errors (set-default 'a 1))
  (ignore-errors (default-value 'a)) (ignore-errors (set-marker (point-marker) 1))
  (ignore-errors (set-marker (point-marker) 1 nil)) (ignore-errors (set-marker (point-marker) nil))
  (ignore-errors (marker-position (point-marker))) (ignore-errors (marker-buffer (point-marker)))
  (ignore-errors (copy-marker (point-marker))) (ignore-errors (copy-marker 5))
  (ignore-errors (copy-marker nil)) (ignore-errors (copy-marker (point-marker) t))
  (ignore-errors (marker-insertion-type (point-marker)))
  (ignore-errors (set-marker-insertion-type (point-marker) t))
  (ignore-errors (make-marker)) (ignore-errors (markerp (make-marker)))
  (ignore-errors (markerp 1)) (ignore-errors (markerp nil))
  (ignore-errors (keywordp :a)) (ignore-errors (keywordp 'a)) (ignore-errors (keywordp nil))
  (ignore-errors (indirect-variable 'a)) (ignore-errors (defvaralias 'va 'a))
  (ignore-errors (variable-alias 'a)) (ignore-errors (bound-and-true-p a))
  (ignore-errors (buffer-local-value 'point (current-buffer)))
  (ignore-errors (make-local-variable 'lv)) (ignore-errors (make-variable-buffer-local 'bv))
  (ignore-errors (local-variable-p 'lv)) (ignore-errors (local-variable-if-set-p 'lv))
  (ignore-errors (variable-binding-locus 'lv)) (ignore-errors (kill-local-variable 'lv))
  (ignore-errors (kill-all-local-variables)) (ignore-errors (buffer-local-variables))
  (ignore-errors (default-boundp 'a)) (ignore-errors (makunbound 'a))
  (ignore-errors (special-variable-p 'a)) (ignore-errors (risky-local-variable-p 'a))
  (ignore-errors (safe-local-variable-p 'a)) (ignore-errors (hack-local-variables))
  (ignore-errors (hack-dir-local-variables)) (ignore-errors (dir-locals-set-class-variables 'c nil))
  (ignore-errors (defvar 'dv 1)) (ignore-errors (defconst 'dc 1))
  (ignore-errors (defvaralias 'dva 'a)) (ignore-errors (internal-make-var-non-special 'dv))
  (ignore-errors (user-variable-p 'dv)) (ignore-errors (custom-variable-p 'dv))
  (ignore-errors (internal-default-value 'dv)) (ignore-errors (set-default-toplevel-value 'dv 2))
  (ignore-errors (set-temporary-overlay-map (make-sparse-keymap)))
  ;; vectors/records
  (ignore-errors (vector 1 2 3)) (ignore-errors (make-vector 3 'x)) (ignore-errors (make-vector 0 'x))
  (ignore-errors (vectorp [1])) (ignore-errors (vectorp '(1)))
  (ignore-errors (aref [1 2] 1)) (ignore-errors (aset [1 2] 1 9))
  (ignore-errors (vconcat [1 2] [3])) (ignore-errors (vconcat '(1) [2]))
  (ignore-errors (record 'a 1 2)) (ignore-errors (recordp (record 'a)))
  (ignore-errors (recordp '(a))) (ignore-errors (car (read-from-string "#s(r 1 2)")))
  ;; gensym/uninterned
  (ignore-errors (make-symbol "gs")) (ignore-errors (symbol-name (make-symbol "gs")))
  (ignore-errors (intern "gs2")) (ignore-errors (intern-soft "gs2"))
  (ignore-errors (intern-soft "nosuch-xyz")) (ignore-errors (intern "sym" nil))
  (ignore-errors (unintern "gs2" nil)) (ignore-errors (unintern 'gs3 nil))
  (ignore-errors (mapatoms #'identity)) (ignore-errors (mapatoms #'identity nil))
  (ignore-errors (obarray-make)) (ignore-errors (obarray-make 100))
  (ignore-errors (obarrayp nil)) (ignore-errors (obarray-clear nil))
  ;; conversions
  (ignore-errors (symbol-name 'sym)) (ignore-errors (symbol-name (make-symbol "x")))
  (ignore-errors (symbol-name 1)) (ignore-errors (number-to-string 255))
  (ignore-errors (string-to-symbol "abc")) (ignore-errors (string-to-symbol ""))
  (ignore-errors (int-to-string 42)) (ignore-errors (string-to-int "42"))
  (ignore-errors (char-to-string 97)) (ignore-errors (string-to-char "a"))
  (ignore-errors (number-to-marker 5)) (ignore-errors (marker-position (point-marker)))
  (ignore-errors (nconc '(1) '(2))) (ignore-errors (nconc '(1) '(2) '(3)))
  (ignore-errors (nconc nil '(1))) (ignore-errors (mapcar #'1+ '(1 2)))
  (ignore-errors (mapc #'identity '(1 2))) (ignore-errors (mapcan #'list '(1 2)))
  (ignore-errors (mapconcat #'prin1-to-string '(1 2) "-")) (ignore-errors (mapconcat #'identity nil "-"))
  (ignore-errors (mapcar #'1+ [1 2])) (ignore-errors (mapcar #'upcase "ab"))
  (ignore-errors (mapcar #'identity "ab")) (ignore-errors (mapcan #'list '(1) '(2)))
  (ignore-errors (mapcar #'list '(1 2) '(a b))) (ignore-errors (mapcar #'list '(1) '(a b)))
  (ignore-errors (mapc #'print '(1))) (ignore-errors (mapc-internal #'1+ '(1)))
  (ignore-errors (mapatoms #'identity)) (ignore-errors (maphash #'identity nil))
  (ignore-errors (apply #'+ 1 2 '(3))) (ignore-errors (apply #'+ nil))
  (ignore-errors (apply 1 nil)) (ignore-errors (funcall #'+ 1))
  (ignore-errors (funcall 'car '(1))) (ignore-errors (funcall 1 2))
  (ignore-errors (funcall-interactively 'forward-char))
  (ignore-errors (funcall-interactively 'car '(1)))
  (ignore-errors (partial-apply #'+ 1)) (ignore-errors (apply-partially #'cons 1))
  (ignore-errors (let ((f (apply-partially #'list 1))) (funcall f 2 3)))
  (ignore-errors (compose #'1+ #'1+)) (ignore-errors (funcall (compose #'1+ #'1+) 5))
  (ignore-errors (funcall (constantly 7)))
  ;; sequences of errors
  (ignore-errors (car 5)) (ignore-errors (cdr 5)) (ignore-errors (nth "x" '(1)))
  (ignore-errors (member 'x 5)) (ignore-errors (assoc 'x 5)) (ignore-errors (length 5))
  (ignore-errors (elt 5 0)) (ignore-errors (elt '(1) "x")) (ignore-errors (substring "ab" "x"))
  (ignore-errors (concat 1 2)) (ignore-errors (concat '(1) 2)) (ignore-errors (string= 1 2))
  (ignore-errors (string< 1 "a")) (ignore-errors (upcase "ab")) (ignore-errors (number-to-string "x"))
  (ignore-errors (string-to-number 5)) (ignore-errors (intern 5)) (ignore-errors (symbol-name "x"))
  (ignore-errors (ash "x" 1)) (ignore-errors (lsh 1.5 1)) (ignore-errors (% "x" 1))
  (ignore-errors (mod 1 0)) (ignore-errors (/ 1 "x")) (ignore-errors (min "a" 1))
  (ignore-errors (aref '(1) 0)) (ignore-errors (aref [1] "x")) (ignore-errors (aref [1] 5))
  (ignore-errors (aset '(1) 0 1)) (ignore-errors (aset [1] 5 1)) (ignore-errors (aset [1] -1 1))
  (ignore-errors (fillarray '(1) 1)) (ignore-errors (vconcat 1)) (ignore-errors (vconcat [1] 2))
  (ignore-errors (append 1)) (ignore-errors (reverse 1)) (ignore-errors (copy-sequence 1))
  (ignore-errors (seqp 5)) (ignore-errors (elt nil 0)) (ignore-errors (nthcdr "x" '(1)))
  (ignore-errors (put-text-property "x" 0 1 'a 1)) (ignore-errors (get-text-property 0 'a "x"))
  (ignore-errors (get-text-property "x" 'a "y")) (ignore-errors (text-properties-at 0 "x"))
  (ignore-errors (next-property-change 0 "x")) (ignore-errors (previous-property-change 0 "x"))
  (ignore-errors (add-text-properties 0 1 '(a 1) "x")) (ignore-errors (remove-text-properties 0 1 '(a) "x"))
  (ignore-errors (set-text-properties 0 1 nil "x")) (ignore-errors (propertize 5 'a 1))
  (ignore-errors (propertize "x" 'a)) (ignore-errors (propertize "x" 'a 1 'b 2))
  (ignore-errors (add-face-text-property 0 1 'bold nil "x"))
  nil)
