;; probe_editor5.el — target uncovered branches in editor/mod.rs

;; ---- temp/directory file ops ----
(let ((f (make-temp-file "pfx")))
  (file-exists-p f)
  (delete-file f))
(make-temp-file "pfx" t)
(let ((d (make-temp-file "dtmp" t)))
  (file-directory-p d)
  (delete-directory d))
(make-temp-file "pfx" nil "TEXT")
(condition-case e (make-temp-file "/nonexistent-dir-xyz/f") (error e))
(make-temp-name "pfx")
(make-directory-internal "/tmp/remacs-mkdir-a")
(file-directory-p "/tmp/remacs-mkdir-a")
(make-directory "/tmp/remacs-mkdir-b/c" t)
(file-directory-p "/tmp/remacs-mkdir-b/c")
(delete-directory "/tmp/remacs-mkdir-a")
(delete-directory "/tmp/remacs-mkdir-b" t)
(rename-file "/tmp/fbv-test.el" "/tmp/fbv-test2.el")
(file-exists-p "/tmp/fbv-test2.el")
(rename-file "/tmp/fbv-test2.el" "/tmp/fbv-test.el" t)
(condition-case e (rename-file "/nonexistent-xyz" "/tmp/z") (error e))

;; ---- substitute-command-keys / describe-key / keymaps ----
(substitute-command-keys "press \\[forward-char] now")
(substitute-command-keys "\\{global-map}")
(substitute-command-keys "\\<global-map>\\[forward-char]")
(substitute-command-keys "plain text")
(substitute-command-keys "\\[not-a-command-xyz]")
(substitute-command-keys "\\=x")
(let ((m (make-keymap)))
  (define-key m "a" 'ignore)
  (substitute-command-keys (concat "\\<" (symbol-name 'ignore))))
(set-keymap-parent (make-keymap) global-map)
(let ((m (make-sparse-keymap)))
  (set-keymap-parent m global-map)
  (keymap-parent m)
  (lookup-key m "a"))
(describe-key "C-f")
(describe-key 'forward-char)
(describe-key (kbd "C-x C-f"))
(describe-bindings)
(key-binding "C-f")
(key-binding [6])
(key-binding (kbd "M-x"))
(global-key-binding "C-f")
(global-key-binding (kbd "C-x C-s"))
(global-set-key (kbd "C-c z") 'ignore)
(global-key-binding (kbd "C-c z"))
(define-prefix-command 'my-prefix-map)
(key-binding (kbd "C-c z"))

;; ---- completion / reading ----
(completing-read "P: " '("aa" "ab" "b"))
(completing-read "P: " '("aa" "ab") nil t "a")
(completing-read "P: " '(("x" . 1) ("y" . 2)))
(try-completion "a" '("aa" "ab" "b"))
(all-completions "a" '("aa" "ab" "b"))
(test-completion "aa" '("aa" "ab"))
(completion-boundaries "a" '("aa") nil "")

;; ---- processes ----
(call-process "echo" nil nil nil "hi")
(let ((b (generate-new-buffer "pout")))
  (call-process "echo" nil b nil "hello")
  (with-current-buffer b (buffer-string)))
(call-process "echo" nil t nil "ins")
(call-process "true" nil nil nil)
(call-process "false" nil nil nil)
(condition-case e (call-process "/nonexistent-cmd-xyz" nil nil nil) (error e))
(call-process-region 1 2 "cat" nil nil nil)
(with-temp-buffer
  (insert "abc")
  (call-process-region 1 4 "cat" nil t nil))
(with-temp-buffer
  (insert "line1\nline2\n")
  (call-process-region 1 12 "grep" nil t nil "line1"))

;; ---- files ----
(let ((f (make-temp-file "ic")))
  (with-temp-file f (insert "file-content-xyz"))
  (with-temp-buffer
    (insert-file-contents f)
    (buffer-string))
  (with-temp-buffer
    (insert-file-contents f nil 1 4)
    (buffer-string))
  (with-temp-buffer
    (insert-file-contents f nil nil nil t)
    (buffer-string))
  (delete-file f))
(let ((b (find-file-noselect "/tmp/fbv-test.el")))
  (buffer-name b)
  (buffer-file-name b))
(find-file-noselect "/tmp/fbv-test.el" t)
(condition-case e (find-file-noselect "/nonexistent-dir-xyz/f.el" nil nil t) (error e))
(condition-case e (save-buffer 0) (error e))
(with-current-buffer (find-file-noselect "/tmp/fbv-test.el")
  (set-buffer-modified-p nil))
(with-temp-buffer
  (insert "data")
  (write-file "/tmp/probe-write.el")
  (buffer-file-name))
(delete-file "/tmp/probe-write.el")
(expand-file-name "x" "/tmp")
(expand-file-name "~/x")
(expand-file-name "x" "~/")
(expand-file-name "")
(expand-file-name "." "/tmp")
(expand-file-name "..")
(expand-file-name "a/../b" "/tmp")
(expand-file-name "./x")
(condition-case e (expand-file-name nil) (error e))
default-directory
(file-name-as-directory "/tmp")
(file-name-as-directory "/tmp/")
(directory-file-name "/tmp/")
(directory-file-name "/tmp")

;; ---- overlays / region ----
(with-temp-buffer
  (insert "hello world")
  (let ((o (make-overlay 1 6)))
    (overlay-put o 'face 'bold)
    (overlay-get o 'face)
    (overlay-start o)
    (overlay-end o)
    (move-overlay o 2 4)
    (overlay-start o)
    (delete-overlay o)
    (overlays-at 2))
  (let ((o (make-overlay 1 3 (current-buffer) t t)))
    (overlay-buffer o))
  (overlays-in 1 5)
  (overlay-start (make-overlay 1 1)))

;; ---- window/frame misc ----
(minibuffer-window)
(minibuffer-window (selected-frame))
(window-margins)
(window-margins (selected-window))
(window-frame)
(window-frame (selected-window))
(set-window-vscroll (selected-window) 2)
(window-vscroll)
(set-window-vscroll (selected-window) 0)
(delete-frame (make-frame '((name . "f2"))))
(frame-list)
(condition-case e (delete-frame) (error e))

;; ---- misc interactive-ish ----
(color-defined-p "red")
(color-defined-p "notacolor-xyz")
(color-defined-p "#ff0000")
(y-or-n-p "q?")
(yes-or-no-p "q?")
(digit-argument nil)
(digit-argument '(4))
(condition-case e (yank-pop) (error e))
(condition-case e (current-kill 0) (error e))
(kill-new "killed-text")
(current-kill 0)
(current-kill -1)
(current-kill 1 t)
(condition-case e (yank) (error e))
(condition-case e (yank-pop) (error e))
(with-temp-buffer
  (insert "azbz")
  (goto-char (point-min))
  (zap-to-char 1 ?z)
  (buffer-string))
(condition-case e (zap-to-char 1 ?z) (error e))
(beginning-of-defun)
(beginning-of-defun 2)
(end-of-defun)
(documentation 'car)
(documentation 'if)
(documentation 'forward-char)
(documentation-property 'car 'function-documentation)
(with-timeout (1 nil) 42)
(with-timeout (0.001 (message "timed-out")) (sleep-for 0) 'done)

;; ---- copy-to-buffer ----
(copy-to-buffer (generate-new-buffer "dst") 1 2)
(with-temp-buffer
  (insert "abc")
  (copy-to-buffer (generate-new-buffer "d2") 1 4))

;; ---- round 3: remaining editor branches ----
(let ((p (make-sparse-keymap)) (c (make-keymap)))
  (set-keymap-parent c p)
  (keymap-parent c)
  (keymapp c))
(window-margins)
(set-window-margins nil 2 3)
(window-margins)
(set-window-margins nil nil nil)
(call-process "echo" nil t nil "hello")
(let ((b (generate-new-buffer "cp")))
  (call-process "echo" nil b nil "out")
  (with-current-buffer b (buffer-string)))
(call-process-region 1 1 "cat" t t)
(condition-case e (call-process "/nonexistent-cmd-xyz" nil t nil) (error e))
(with-temp-file "/tmp/remacs-ic.el" (insert "ic-body"))
(insert-file-contents "/tmp/remacs-ic.el")
(condition-case e (insert-file-contents "/nonexistent-xyz") (error e))
(with-temp-buffer
  (insert "x")
  (write-file "/tmp/remacs-wf-test.el")
  (buffer-file-name)
  (set-buffer-modified-p t)
  (save-buffer)
  (buffer-modified-p))
(let ((b (find-file-noselect "/tmp/remacs-wf-test.el")))
  (with-current-buffer b
    (buffer-string)
    (kill-buffer b)))
(condition-case e (with-timeout (0.01 (insert "a")) (sleep-for 0.1)) (error e))
(with-timeout (5 'timeout-tag) 'done)
(documentation 'forward-char)
(documentation 'car t)
(condition-case e (documentation 'nonexistent-fn-xyz) (error e))
(color-defined-p "red")
(color-defined-p "#ff0000")
(color-defined-p "not-a-color-xyz")
(global-set-key [f18] 'ignore)
(define-prefix-command 'my-prefix-map)
(key-binding [f18])
(local-key-binding "a")
(global-key-binding "a")
(minor-mode-key-binding "a")
(minibuffer-window)
(minibuffer-window-active-p (minibuffer-window))
(window-frame (selected-window))
(frame-first-window)
(key-binding "a" t)
(key-binding "a" t 1)
(substitute-command-keys "\\<global-map>\\[forward-char]")
(substitute-command-keys "plain text")
(substitute-command-keys "\\{global-map}")
(substitute-command-keys "\\=`quoted'")
(this-command-keys)
(this-command-keys-vector)
(this-single-command-keys)
(this-single-command-raw-keys)
;; `command-line' signals in batch (GNU recurses into top-level).
(condition-case e (command-line) (error e))
(make-directory "/tmp/remacs-mkd/sub" t)
(make-directory "/tmp/remacs-mkd/sub2")
(directory-files "/tmp/remacs-mkd")
(delete-directory "/tmp/remacs-mkd" t)
(rename-file "/tmp/remacs-wf-test.el" "/tmp/remacs-wf-test2.el" t)
(copy-file "/tmp/remacs-wf-test2.el" "/tmp/remacs-wf-test3.el" t)
(delete-file "/tmp/remacs-wf-test2.el")
(delete-file "/tmp/remacs-wf-test3.el")
(condition-case e (make-directory "/tmp/remacs-mkd") (error e))
(condition-case e (rename-file "/nonexistent-xyz" "/tmp/x") (error e))
(expand-file-name "rel")
(expand-file-name "rel" "/tmp/")
(expand-file-name "/abs/x")
(expand-file-name "~/x")
(expand-file-name "~user/x")
(expand-file-name "")
(file-name-absolute-p "/x")
(file-name-absolute-p "x")
(substitute-in-file-name "$HOME/x")
(substitute-in-file-name "plain")
(abbreviate-file-name (expand-file-name "~/abc"))
(featurep 'windowsystem)
(emacs-pid)
(recursion-depth)
(minibuffer-depth)
(condition-case e (signal 'file-error '("msg")) (error e))
(commandp 'ignore)
(special-form-p 'if)
(macrop 'when)
