(defun P (x) (princ (format "%S\n" x)))
(P (set-register ?a "hello"))
(P (get-register ?a))
(P register-alist)
(P (number-to-register 42 ?b))
(P (increment-register 8 ?b))
(P (get-register ?b))
(P (increment-register 0.5 ?b))
(P (get-register ?z))
(P (condition-case e (increment-register 7 ?z) (error e)))
(P (condition-case e (increment-register 7) (error e)))
(set-register ?a nil)
(P register-alist)
(P (get-register ?a))
(set-register ?a "txt")
(with-temp-buffer (insert "REGION") (set-mark (point-min)) (push-mark nil t)
  (P (condition-case e (increment-register 7 ?a) (error e)))
  (P (get-register ?a)))
(with-temp-buffer (insert "abcdef")
  (P (copy-to-register ?c 1 4))
  (P (get-register ?c))
  (copy-to-register ?c 4 7 t)
  (P (get-register ?c))
  (P (buffer-string)))
(P (point-to-register ?d))
(P (get-register ?d))
(P (jump-to-register ?d))
(number-to-register 9 ?n)
(P (condition-case e (jump-to-register ?n) (error e)))
(P (condition-case e (jump-to-register ?v) (error e)))
(set-register ?e "ins")
(with-temp-buffer (insert "X") (goto-char 2)
  (P (insert-register ?e))
  (P (buffer-string)))
(with-temp-buffer (insert "X") (goto-char 2)
  (insert-register ?e t)
  (P (buffer-string)))
(with-temp-buffer
  (number-to-register 33 ?m)
  (P (insert-register ?m))
  (P (buffer-string)))
(with-temp-buffer
  (P (condition-case e (insert-register ?d) (error e))))
(P (window-configuration-to-register ?w))
(P (frame-configuration-to-register ?f))
(P (jump-to-register ?w))
(P (condition-case e (insert-register ?q) (error e)))

;; register-alist edge cases.
(set-register ?x "a")
(P (get-register 'x))
(P (assq ?x register-alist))
(P (assq 'x register-alist))
(copy-to-register ?y 1 1)
(P (get-register ?y))
