;; Deep coverage probe: realistic editing-session exercise of editor,
;; buffer, window, keymap, search/replace, and motion subrs.
(progn
  ;; insertion + point/mark/motion
  (ignore-errors (insert "The quick brown fox jumps over the lazy dog.\n"))
  (ignore-errors (insert "second line here\nthird line\n"))
  (ignore-errors (goto-char 1))
  (ignore-errors (forward-char 5))
  (ignore-errors (backward-char 2))
  (ignore-errors (forward-word 2))
  (ignore-errors (backward-word 1))
  (ignore-errors (move-beginning-of-line 1))
  (ignore-errors (move-end-of-line 1))
  (ignore-errors (forward-line 1))
  (ignore-errors (forward-line -1))
  (ignore-errors (beginning-of-buffer))
  (ignore-errors (end-of-buffer))
  (ignore-errors (goto-line 2))
  (ignore-errors (back-to-indentation))
  (ignore-errors (forward-sexp 1))
  (ignore-errors (backward-sexp 1))
  (ignore-errors (forward-sentence 1))
  (ignore-errors (backward-sentence 1))
  (ignore-errors (forward-paragraph 1))
  (ignore-errors (backward-paragraph 1))
  (ignore-errors (forward-page 1))
  (ignore-errors (backward-page 1))
  (ignore-errors (beginning-of-defun 1))
  (ignore-errors (end-of-defun 1))
  (ignore-errors (forward-comment 1))
  (ignore-errors (skip-chars-forward "a-z"))
  (ignore-errors (skip-chars-backward "a-z"))
  (ignore-errors (skip-syntax-forward "w"))
  (ignore-errors (skip-syntax-backward "w"))
  (ignore-errors (point))
  (ignore-errors (point-min))
  (ignore-errors (point-max))
  (ignore-errors (mark))
  (ignore-errors (mark-marker))
  (ignore-errors (buffer-size))
  (ignore-errors (current-column))
  (ignore-errors (move-to-column 10))
  (ignore-errors (current-indentation))
  (ignore-errors (indent-to 8))
  (ignore-errors (line-beginning-position))
  (ignore-errors (line-end-position))
  (ignore-errors (bolp))
  (ignore-errors (eolp))
  (ignore-errors (bobp))
  (ignore-errors (eobp))
  (ignore-errors (char-after))
  (ignore-errors (char-after 1))
  (ignore-errors (char-before))
  (ignore-errors (following-char))
  (ignore-errors (preceding-char))
  (ignore-errors (line-number-at-pos))
  (ignore-errors (line-number-at-pos 10))
  (ignore-errors (count-lines 1 10))
  (ignore-errors (line-end-position 2))
  (ignore-errors (vertical-motion 1))
  (ignore-errors (move-to-window-line 0))
  ;; narrowing/widening + restriction
  (ignore-errors (narrow-to-region 1 20))
  (ignore-errors (widen))
  (ignore-errors (narrow-to-page 1))
  (ignore-errors (widen))
  (ignore-errors (save-restriction (narrow-to-region 1 5) (buffer-string)))
  ;; mark/region
  (ignore-errors (goto-char 1))
  (ignore-errors (set-mark 10))
  (ignore-errors (push-mark 20))
  (ignore-errors (pop-mark))
  (ignore-errors (activate-mark))
  (ignore-errors (deactivate-mark))
  (ignore-errors (exchange-point-and-mark))
  (ignore-errors (region-beginning))
  (ignore-errors (region-end))
  (ignore-errors (set-mark-command nil))
  (ignore-errors (transient-mark-mode 1))
  (ignore-errors (transient-mark-mode -1))
  ;; kill ring / regions
  (ignore-errors (goto-char 1))
  (ignore-errors (kill-line))
  (ignore-errors (yank))
  (ignore-errors (kill-word))
  (ignore-errors (backward-kill-word 1))
  (ignore-errors (kill-region 1 5))
  (ignore-errors (copy-region-as-kill 1 10))
  (ignore-errors (kill-ring-save 1 10))
  (ignore-errors (kill-new "xyz"))
  (ignore-errors (kill-append "abc" nil))
  (ignore-errors (current-kill 0))
  (ignore-errors (current-kill 1 t))
  (ignore-errors (rotate-yank-pointer 1))
  (ignore-errors (yank-pop))
  (ignore-errors (zap-to-char 1 ?x))
  (ignore-errors (delete-region 1 2))
  (ignore-errors (delete-and-extract-region 1 2))
  ;; undo
  (ignore-errors (undo-boundary))
  (ignore-errors (undo 1))
  (ignore-errors (primitive-undo 1 buffer-undo-list))
  ;; buffer queries
  (ignore-errors (buffer-string))
  (ignore-errors (buffer-substring 1 10))
  (ignore-errors (buffer-substring-no-properties 1 10))
  (ignore-errors (buffer-modified-p))
  (ignore-errors (set-buffer-modified-p nil))
  (ignore-errors (buffer-modified-tick))
  (ignore-errors (buffer-chars-modified-tick))
  (ignore-errors (restore-buffer-modified-p nil))
  (ignore-errors (buffer-name))
  (ignore-errors (buffer-file-name))
  (ignore-errors (buffer-live-p (current-buffer)))
  (ignore-errors (buffer-list))
  (ignore-errors (other-buffer))
  (ignore-errors (last-buffer))
  (ignore-errors (get-buffer "*scratch*"))
  (ignore-errors (get-buffer-create "probe-tmp"))
  (ignore-errors (generate-new-buffer "gen"))
  (ignore-errors (generate-new-buffer-name "g"))
  (ignore-errors (rename-buffer "renamed"))
  (ignore-errors (with-current-buffer "probe-tmp" (insert "x") (buffer-string)))
  (ignore-errors (set-buffer (get-buffer "*scratch*")))
  (ignore-errors (bury-buffer "probe-tmp"))
  (ignore-errors (unbury-buffer))
  (ignore-errors (erase-buffer))
  (ignore-errors (insert "abcdef\nghijkl\n"))
  ;; search & match
  (ignore-errors (goto-char 1))
  (ignore-errors (search-forward "abc" nil t))
  (ignore-errors (search-backward "abc" nil t))
  (ignore-errors (re-search-forward "a.c" nil t))
  (ignore-errors (re-search-backward "a.c" nil t))
  (ignore-errors (word-search-forward "abc" nil t))
  (ignore-errors (word-search-backward "abc" nil t))
  (ignore-errors (looking-at "abc"))
  (ignore-errors (string-match "a.c" "abc"))
  (ignore-errors (string-match "a.c" "abc" 1))
  (ignore-errors (match-beginning 0))
  (ignore-errors (match-end 0))
  (ignore-errors (match-string 0 "abc"))
  (ignore-errors (match-data))
  (ignore-errors (set-match-data '(1 3)))
  (ignore-errors (store-match-data '(1 3)))
  (ignore-errors (regexp-quote "a.b*c"))
  (ignore-errors (regexp-opt '("a" "bb" "ccc")))
  (ignore-errors (regexp-opt-depth "a"))
  (ignore-errors (goto-char 1))
  (ignore-errors (replace-match "X" nil nil "abc"))
  (ignore-errors (perform-replace "a" "X" nil nil nil))
  (ignore-errors (replace-regexp-in-string "a" "X" "banana"))
  (ignore-errors (subst-char-in-region 1 10 ?a ?z))
  (ignore-errors (translate-region 1 10 (make-char-table 'translation-table)))
  ;; case
  (ignore-errors (upcase "abc"))
  (ignore-errors (downcase "ABC"))
  (ignore-errors (capitalize "abc def"))
  (ignore-errors (upcase-initials "abc def"))
  (ignore-errors (upcase-word 1))
  (ignore-errors (downcase-word 1))
  (ignore-errors (capitalize-word 1))
  (ignore-errors (upcase-region 1 5))
  (ignore-errors (downcase-region 1 5))
  (ignore-errors (capitalize-region 1 5))
  (ignore-errors (upcase-initials-region 1 5))
  ;; transpose
  (ignore-errors (transpose-chars 1))
  (ignore-errors (transpose-words 1))
  (ignore-errors (transpose-sexps 1))
  (ignore-errors (transpose-lines 1))
  (ignore-errors (transpose-regions 1 2 3 4))
  ;; text properties
  (ignore-errors (put-text-property 1 3 'face 'bold))
  (ignore-errors (get-text-property 1 'face))
  (ignore-errors (text-properties-at 1))
  (ignore-errors (add-text-properties 1 3 '(face bold)))
  (ignore-errors (remove-text-properties 1 3 '(face)))
  (ignore-errors (set-text-properties 1 3 nil))
  (ignore-errors (next-property-change 1))
  (ignore-errors (previous-property-change 3))
  (ignore-errors (next-single-property-change 1 'face))
  (ignore-errors (previous-single-property-change 3 'face))
  (ignore-errors (text-property-any 1 10 'face 'bold))
  (ignore-errors (text-property-not-all 1 10 'face 'bold))
  (ignore-errors (propertize "x" 'face 'bold))
  (ignore-errors (add-face-text-property 1 3 'bold))
  (ignore-errors (remove-list-of-text-properties 1 3 '(face)))
  ;; windows/frames
  (ignore-errors (selected-window))
  (ignore-errors (window-list))
  (ignore-errors (window-buffer))
  (ignore-errors (window-point))
  (ignore-errors (set-window-point (selected-window) 1))
  (ignore-errors (window-start))
  (ignore-errors (set-window-start (selected-window) 1))
  (ignore-errors (window-end))
  (ignore-errors (window-live-p (selected-window)))
  (ignore-errors (window-minibuffer-p (selected-window)))
  (ignore-errors (window-body-width))
  (ignore-errors (window-body-height))
  (ignore-errors (window-total-height))
  (ignore-errors (window-total-width))
  (ignore-errors (window-height))
  (ignore-errors (window-width))
  (ignore-errors (window-edges))
  (ignore-errors (window-inside-edges))
  (ignore-errors (window-pixel-edges))
  (ignore-errors (window-inside-pixel-edges))
  (ignore-errors (window-absolute-pixel-edges))
  (ignore-errors (window-hscroll))
  (ignore-errors (set-window-hscroll (selected-window) 0))
  (ignore-errors (window-vscroll))
  (ignore-errors (set-window-vscroll (selected-window) 0))
  (ignore-errors (window-line-height 1))
  (ignore-errors (window-mode-line-height))
  (ignore-errors (window-header-line-height))
  (ignore-errors (pos-visible-in-window-p))
  (ignore-errors (pos-visible-in-window-p 1))
  (ignore-errors (posn-at-point))
  (ignore-errors (posn-at-x-y 0 0))
  (ignore-errors (line-pixel-height))
  (ignore-errors (window-text-pixel-size))
  (ignore-errors (recenter))
  (ignore-errors (recenter-top-bottom))
  (ignore-errors (scroll-up 1))
  (ignore-errors (scroll-down 1))
  (ignore-errors (scroll-up-command))
  (ignore-errors (scroll-down-command))
  (ignore-errors (scroll-other-window 1))
  (ignore-errors (scroll-left 1))
  (ignore-errors (scroll-right 1))
  (ignore-errors (move-to-window-line 1))
  (ignore-errors (other-window 1))
  (ignore-errors (next-window))
  (ignore-errors (prev-window))
  (ignore-errors (get-lru-window))
  (ignore-errors (get-largest-window))
  (ignore-errors (split-window-below))
  (ignore-errors (split-window-right))
  (ignore-errors (delete-window))
  (ignore-errors (delete-other-windows))
  (ignore-errors (delete-windows-on "*scratch*"))
  (ignore-errors (one-window-p))
  (ignore-errors (window-use-time))
  (ignore-errors (window-dedicated-p))
  (ignore-errors (set-window-dedicated-p (selected-window) nil))
  (ignore-errors (window-parameter (selected-window) 'x))
  (ignore-errors (set-window-parameter (selected-window) 'x 1))
  (ignore-errors (window-parameters))
  (ignore-errors (window-parent))
  (ignore-errors (window-child))
  (ignore-errors (window-next-sibling))
  (ignore-errors (window-prev-sibling))
  (ignore-errors (window-combination-limit))
  (ignore-errors (set-window-combination-limit (selected-window) nil))
  (ignore-errors (window-prev-buffers))
  (ignore-errors (window-next-buffers))
  (ignore-errors (balance-windows))
  (ignore-errors (window-fixed-size-p))
  (ignore-errors (fit-window-to-buffer))
  (ignore-errors (window-resizable (selected-window) 1))
  (ignore-errors (window-resize (selected-window) 1))
  (ignore-errors (window-tree))
  (ignore-errors (frame-root-window))
  (ignore-errors (frame-first-window))
  (ignore-errors (minibuffer-window))
  (ignore-errors (window-minibuffer-p))
  ;; frames
  (ignore-errors (selected-frame))
  (ignore-errors (frame-list))
  (ignore-errors (visible-frame-list))
  (ignore-errors (framep (selected-frame)))
  (ignore-errors (frame-live-p (selected-frame)))
  (ignore-errors (frame-visible-p (selected-frame)))
  (ignore-errors (frame-iconified-p (selected-frame)))
  (ignore-errors (frame-parameters))
  (ignore-errors (frame-parameter (selected-frame) 'name))
  (ignore-errors (modify-frame-parameters (selected-frame) '((name . "f"))))
  (ignore-errors (set-frame-parameter (selected-frame) 'name "g"))
  (ignore-errors (frame-height))
  (ignore-errors (frame-width))
  (ignore-errors (set-frame-height (selected-frame) 30))
  (ignore-errors (set-frame-width (selected-frame) 90))
  (ignore-errors (frame-char-height))
  (ignore-errors (frame-char-width))
  (ignore-errors (frame-pixel-height))
  (ignore-errors (frame-pixel-width))
  (ignore-errors (frame-position))
  (ignore-errors (frame-geometry))
  (ignore-errors (frame-edges))
  (ignore-errors (frame-terminal))
  (ignore-errors (terminal-list))
  (ignore-errors (terminal-name))
  (ignore-errors (terminal-of))
  (ignore-errors (display-graphic-p))
  (ignore-errors (window-system))
  (ignore-errors (tty-type))
  (ignore-errors (tty-top-frame))
  (ignore-errors (tty-display-color-p))
  (ignore-errors (tty-display-color-cells))
  (ignore-errors (tty-defined-colors))
  (ignore-errors (controlling-tty-p))
  (ignore-errors (suspend-tty))
  (ignore-errors (resume-tty))
  ;; keymaps
  (ignore-errors (keymapp (current-global-map)))
  (ignore-errors (make-sparse-keymap))
  (ignore-errors (make-keymap))
  (ignore-errors (copy-keymap (current-global-map)))
  (ignore-errors (keymap-parent (current-global-map)))
  (ignore-errors (set-keymap-parent (make-sparse-keymap) (current-global-map)))
  (ignore-errors (keymap-prompt (current-global-map)))
  (ignore-errors (define-key (current-global-map) [f6] 'ignore))
  (ignore-errors (lookup-key (current-global-map) [f6]))
  (ignore-errors (local-key-binding "a"))
  (ignore-errors (minor-mode-key-binding "a"))
  (ignore-errors (current-active-maps))
  (ignore-errors (accessible-keymaps (current-global-map)))
  (ignore-errors (map-keymap (lambda (k v) v) (current-global-map)))
  (ignore-errors (suppress-keymap (make-sparse-keymap)))
  (ignore-errors (use-local-map (make-sparse-keymap)))
  (ignore-errors (current-local-map))
  (ignore-errors (local-set-key [f7] 'ignore))
  (ignore-errors (global-set-key [f8] 'ignore))
  (ignore-errors (local-unset-key [f7]))
  (ignore-errors (global-unset-key [f8]))
  (ignore-errors (define-prefix-command 'myprefix))
  (ignore-errors (command-remapping 'self-insert-command))
  (ignore-errors (substitute-key-definition 'a 'b (make-sparse-keymap)))
  (ignore-errors (where-is-internal 'forward-char))
  (ignore-errors (where-is 'forward-char))
  (ignore-errors (substitute-command-keys "\\[forward-char]"))
  (ignore-errors (key-description [97]))
  (ignore-errors (single-key-description 97))
  (ignore-errors (text-char-description 97))
  (ignore-errors (kbd "C-f"))
  (ignore-errors (key-binding "\C-x\C-c"))
  (ignore-errors (this-command-keys))
  (ignore-errors (this-command-keys-vector))
  (ignore-errors (this-single-command-keys))
  (ignore-errors (this-single-command-raw-keys))
  (ignore-errors (recent-keys))
  (ignore-errors (clear-this-command-keys))
  (ignore-errors (command-history))
  (ignore-errors (recursion-depth))
  (ignore-errors (minibuffer-depth))
  (ignore-errors (prefix-numeric-value '(4)))
  (ignore-errors (prefix-numeric-value '-))
  (ignore-errors (prefix-numeric-value nil))
  ;; eval/apply/funcs
  (ignore-errors (funcall '+ 1 2))
  (ignore-errors (apply '+ '(1 2 3)))
  (ignore-errors (apply '+ 1 '(2 3)))
  (ignore-errors (apply-partially '+ 1))
  (ignore-errors (funcall-interactively 'forward-char))
  (ignore-errors (eval '(+ 1 2)))
  (ignore-errors (eval '(+ 1 2) t))
  (ignore-errors (macroexpand '(when t 1)))
  (ignore-errors (macroexpand-all '(when t 1)))
  (ignore-errors (eval-buffer))
  (ignore-errors (eval-region 1 5))
  (ignore-errors (eval-last-sexp nil))
  (ignore-errors (documentation 'car))
  (ignore-errors (documentation-property 'car 'variable-documentation))
  (ignore-errors (apropos-internal "^car"))
  (ignore-errors (indirect-function 'car))
  (ignore-errors (symbol-function 'car))
  (ignore-errors (fboundp 'car))
  (ignore-errors (boundp 'point))
  (ignore-errors (boundp 'no-such-var))
  (ignore-errors (fmakunbound 'nosuchfn))
  (ignore-errors (makunbound 'nosuchvar))
  (ignore-errors (fset 'x-alias 'car))
  (ignore-errors (defalias 'y-alias 'car))
  (ignore-errors (subrp 'car))
  (ignore-errors (subrp (symbol-function 'car)))
  (ignore-errors (subr-arity (symbol-function 'car)))
  (ignore-errors (subr-name (symbol-function 'car)))
  (ignore-errors (special-form-p 'if))
  (ignore-errors (macrop 'when))
  (ignore-errors (functionp 'car))
  (ignore-errors (commandp 'forward-char))
  (ignore-errors (interactive-form 'forward-char))
  (ignore-errors (command-modes 'forward-char))
  (ignore-errors (called-interactively-p))
  (ignore-errors (func-arity 'car))
  (ignore-errors (help-function-arglist 'car))
  (ignore-errors (byte-code-function-p (symbol-function 'car)))
  (ignore-errors (native-comp-function-p (symbol-function 'car)))
  (ignore-errors (subr-native-elisp-p (symbol-function 'car)))
  ;; symbols/obarray
  (ignore-errors (intern "new-sym"))
  (ignore-errors (intern-soft "car"))
  (ignore-errors (unintern "tmp-sym" nil))
  (ignore-errors (make-symbol "ms"))
  (ignore-errors (symbol-name 'car))
  (ignore-errors (symbol-value 'point))
  (ignore-errors (symbol-plist 'car))
  (ignore-errors (setplist 'car nil))
  (ignore-errors (get 'car 'error-message))
  (ignore-errors (put 'car 'myprop 42))
  (ignore-errors (function-get 'car 'x))
  (ignore-errors (function-put 'car 'y 1))
  (ignore-errors (symbol-file 'car))
  (ignore-errors (featurep 'cl-lib))
  (ignore-errors (features))
  (ignore-errors (keywordp :a))
  (ignore-errors (gensym))
  (ignore-errors (gensym "p"))
  (ignore-errors (mapatoms (lambda (s) s)))
  (ignore-errors (obarray-make))
  (ignore-errors (obarray-make 10))
  (ignore-errors (obarrayp (obarray-make)))
  ;; read
  (ignore-errors (read "(a b c)"))
  (ignore-errors (read-from-string "(a b)"))
  (ignore-errors (read-from-string "x" 0))
  (ignore-errors (car (read-from-string "1")))
  (ignore-errors (read-regexp "P: "))
  (ignore-errors (read-coding-system "P: "))
  ;; syntax
  (ignore-errors (syntax-table))
  (ignore-errors (syntax-table-p (syntax-table)))
  (ignore-errors (standard-syntax-table))
  (ignore-errors (copy-syntax-table))
  (ignore-errors (set-syntax-table (copy-syntax-table)))
  (ignore-errors (modify-syntax-entry ?a "w"))
  (ignore-errors (char-syntax ?a))
  (ignore-errors (syntax-class 0))
  (ignore-errors (syntax-after 1))
  (ignore-errors (matching-paren 40))
  (ignore-errors (string-to-syntax "w"))
  (ignore-errors (internal-describe-syntax-value))
  (ignore-errors (scan-lists 1 1 0))
  (ignore-errors (scan-sexps 1 1))
  (ignore-errors (parse-partial-sexp 1 10))
  (ignore-errors (backward-prefix-chars))
  (ignore-errors (syntax-ppss))
  (ignore-errors (syntax-propertize 10))
  (ignore-errors (modify-category-entry ?a ?x))
  (ignore-errors (char-category-set ?a))
  (ignore-errors (category-docstring ?x))
  (ignore-errors (get-unused-category nil))
  (ignore-errors (category-table))
  (ignore-errors (category-table-p (category-table)))
  (ignore-errors (standard-category-table))
  (ignore-errors (copy-category-table (category-table)))
  (ignore-errors (set-category-table (category-table)))
  ;; case tables
  (ignore-errors (case-table-p (case-table)))
  (ignore-errors (standard-case-table))
  (ignore-errors (current-case-table))
  (ignore-errors (set-case-table (current-case-table)))
  (ignore-errors (set-standard-case-table (current-case-table)))
  (ignore-errors (set-case-syntax-pair ?a ?b (current-case-table)))
  (ignore-errors (set-case-syntax-delims ?a ?b (current-case-table)))
  (ignore-errors (set-case-syntax ?a "w" (current-case-table)))
  ;; char tables & bool vectors
  (ignore-errors (char-table-p (make-char-table 'x)))
  (ignore-errors (make-char-table 'x 1))
  (ignore-errors (char-table-extra-slot (make-char-table 'x) 0))
  (ignore-errors (set-char-table-extra-slot (make-char-table 'x) 0 1))
  (ignore-errors (char-table-range (make-char-table 'x) 65))
  (ignore-errors (set-char-table-range (make-char-table 'x) 65 1))
  (ignore-errors (char-table-parent (make-char-table 'x)))
  (ignore-errors (set-char-table-parent (make-char-table 'x) nil))
  (ignore-errors (char-table-subtype (make-char-table 'x)))
  (ignore-errors (map-char-table (lambda (k v) v) (make-char-table 'x)))
  (ignore-errors (optimize-char-table (make-char-table 'x)))
  (ignore-errors (bool-vector-p (make-bool-vector 3 t)))
  (ignore-errors (make-bool-vector 3 t))
  (ignore-errors (bool-vector))
  (ignore-errors (bool-vector t nil t))
  (ignore-errors (bool-vector-length (make-bool-vector 3 t)))
  (ignore-errors (bool-vector-subsetp (make-bool-vector 3 t) (make-bool-vector 3 t)))
  (ignore-errors (bool-vector-not (make-bool-vector 3 t)))
  (ignore-errors (bool-vector-exclusive-or (make-bool-vector 3 t) (make-bool-vector 3 nil)))
  (ignore-errors (bool-vector-union (make-bool-vector 3 t) (make-bool-vector 3 nil)))
  (ignore-errors (bool-vector-intersection (make-bool-vector 3 t) (make-bool-vector 3 nil)))
  (ignore-errors (bool-vector-set-difference (make-bool-vector 3 t) (make-bool-vector 3 nil)))
  (ignore-errors (bool-vector-count-population (make-bool-vector 3 t) 0))
  (ignore-errors (bool-vector-count-consecutive (make-bool-vector 3 t) t 0))
  ;; hash tables
  (ignore-errors (make-hash-table))
  (ignore-errors (make-hash-table :test 'equal))
  (ignore-errors (hash-table-p (make-hash-table)))
  (ignore-errors (hash-table-count (make-hash-table)))
  (ignore-errors (hash-table-test (make-hash-table)))
  (ignore-errors (hash-table-weakness (make-hash-table)))
  (ignore-errors (hash-table-size (make-hash-table)))
  (ignore-errors (hash-table-rehash-size (make-hash-table)))
  (ignore-errors (hash-table-rehash-threshold (make-hash-table)))
  (ignore-errors (copy-hash-table (make-hash-table)))
  (ignore-errors (gethash 'a (make-hash-table)))
  (ignore-errors (puthash 'a 1 (make-hash-table)))
  (ignore-errors (remhash 'a (make-hash-table)))
  (ignore-errors (clrhash (make-hash-table)))
  (ignore-errors (maphash (lambda (k v) v) (make-hash-table)))
  (ignore-errors (sxhash 'a))
  (ignore-errors (sxhash-eq 'a))
  (ignore-errors (sxhash-eql 'a))
  (ignore-errors (sxhash-equal 'a))
  (ignore-errors (sxhash-equal-including-properties "x"))
  (ignore-errors (define-hash-table-test 'mytest 'eq 'sxhash-eq))
  ;; misc interpreter
  (ignore-errors (run-hooks 'x-hook))
  (ignore-errors (add-hook 'x-hook 'car))
  (ignore-errors (remove-hook 'x-hook 'car))
  (ignore-errors (run-hook-with-args 'x-hook 1))
  (ignore-errors (run-hook-wrapped 'x-hook (lambda (h) h)))
  (ignore-errors (run-hook-with-args-until-failure 'x-hook))
  (ignore-errors (run-hook-with-args-until-success 'x-hook))
  (ignore-errors (provide 'myfeature))
  (ignore-errors (featurep 'myfeature))
  (ignore-errors (unload-feature 'myfeature))
  (ignore-errors (load-history))
  (ignore-errors (symbol-file 'myfeature))
  (ignore-errors (eval-after-load "nofile" '(+ 1 2)))
  (ignore-errors (autoload 'myauto "nofile"))
  (ignore-errors (autoloadp (symbol-function 'myauto)))
  (ignore-errors (autoload-do-load (symbol-function 'myauto) 'myauto))
  (ignore-errors (declare-function 'x "y" "z"))
  (ignore-errors (record 'a 1 2))
  (ignore-errors (recordp (record 'a 1 2)))
  (ignore-errors (type-of (record 'a 1 2)))
  (ignore-errors (type-of 1))
  (ignore-errors (type-of "x"))
  (ignore-errors (type-of 'a))
  (ignore-errors (type-of nil))
  (ignore-errors (type-of t))
  (ignore-errors (type-of '(1)))
  (ignore-errors (type-of [1]))
  (ignore-errors (type-of (make-hash-table)))
  (ignore-errors (type-of (point-marker)))
  (ignore-errors (type-of (selected-window)))
  (ignore-errors (type-of (selected-frame)))
  (ignore-errors (type-of (current-buffer)))
  (ignore-errors (type-of (current-global-map)))
  (ignore-errors (type-of (syntax-table)))
  (ignore-errors (type-of #'car))
  (ignore-errors (eq 'a 'a))
  (ignore-errors (eql 1 1))
  (ignore-errors (equal '(1 2) '(1 2)))
  (ignore-errors (equal-including-properties "a" "a"))
  (ignore-errors (null nil))
  (ignore-errors (consp '(1)))
  (ignore-errors (atom 1))
  (ignore-errors (listp '(1)))
  (ignore-errors (listp nil))
  (ignore-errors (nlistp 1))
  (ignore-errors (symbolp 'a))
  (ignore-errors (integerp 1))
  (ignore-errors (numberp 1))
  (ignore-errors (natnump 1))
  (ignore-errors (floatp 1.5))
  (ignore-errors (integer-or-marker-p 1))
  (ignore-errors (number-or-marker-p 1))
  (ignore-errors (wholenump 1))
  (ignore-errors (fixnump 1))
  (ignore-errors (bignump 1))
  (ignore-errors (zerop 0))
  (ignore-errors (plusp 1))
  (ignore-errors (minusp -1))
  (ignore-errors (oddp 3))
  (ignore-errors (evenp 4))
  (ignore-errors (stringp "x"))
  (ignore-errors (string-or-null-p "x"))
  (ignore-errors (vectorp [1]))
  (ignore-errors (vector-or-char-table-p [1]))
  (ignore-errors (sequencep '(1)))
  (ignore-errors (sequencep [1]))
  (ignore-errors (sequencep "x"))
  (ignore-errors (arrayp [1]))
  (ignore-errors (arrayp "x"))
  (ignore-errors (bufferp (current-buffer)))
  (ignore-errors (markerp (point-marker)))
  (ignore-errors (windowp (selected-window)))
  (ignore-errors (framep (selected-frame)))
  (ignore-errors (processp nil))
  (ignore-errors (user-ptrp nil))
  (ignore-errors (threadp nil))
  (ignore-errors (mutexp nil))
  (ignore-errors (condition-variable-p nil))
  (ignore-errors (char-table-p nil))
  (ignore-errors (bool-vector-p nil))
  (ignore-errors (hash-table-p nil))
  (ignore-errors (keywordp 'a))
  (ignore-errors (functionp nil))
  (ignore-errors (subrp nil))
  (ignore-errors (byte-code-function-p nil))
  (ignore-errors (case 1 (1 'one) (2 'two)))
  (ignore-errors (bool-vector '(1)))
  nil)
