;; probe_eval2 — evalfn/data/readfn/buffer-extra branch coverage
;; hooks
(progn
  (ignore-errors (run-hooks 'no-such-hook))
  (ignore-errors (add-hook 'probe-hook (lambda (x) (+ x 1))))
  (ignore-errors (run-hook-with-args 'probe-hook 41))
  (ignore-errors (run-hook-with-args-until-success 'probe-hook 1))
  (ignore-errors (run-hook-with-args-until-failure 'probe-hook 1))
  (ignore-errors (remove-hook 'probe-hook (lambda (x) x))))
;; fields / fill
(ignore-errors (set-fill-prefix))
(ignore-errors (delete-field))
(ignore-errors (field-end))
(ignore-errors (field-string))
(with-temp-buffer
  (insert "abc def")
  (ignore-errors (field-beginning))
  (ignore-errors (field-end))
  (ignore-errors (field-string))
  (ignore-errors (field-string-no-properties))
  (ignore-errors (constrain-to-field nil 3))
  (ignore-errors (delete-field))
  (ignore-errors (set-fill-prefix)))
;; docs / internals
(ignore-errors (internal-doc-string-p "doc"))
(ignore-errors (help--docstring-quote "test"))
(ignore-errors (internal--set-subr-doc #'car "doc" 0))
(ignore-errors (subr-name #'car))
(ignore-errors (function-equal #'car #'car))
(ignore-errors (function-equal #'car #'cdr))
(ignore-errors (function-equal (lambda (x) x) (lambda (x) x)))
(ignore-errors (make-byte-code '(x) '(x) "" 1))
(ignore-errors (macroexp-if 'a 'b 'c))
(ignore-errors (macroexp-let2 'v 'init 'body))
(ignore-errors (autoload 'fn "file"))
(ignore-errors (autoload 'fn "file" "doc" t))
(ignore-errors (declare-function 'fn "file"))
(ignore-errors (lwarn 'probe :warning "msg %s" 'x))
(ignore-errors (minibuffer-message "msg"))
(ignore-errors (set-message-functions nil))
;; eval paths
(ignore-errors (eval '(+ 1 2)))
(ignore-errors (eval '(+ 1 2) t))
(ignore-errors (eval '(list a b) '((a . 1) (b . 2))))
(ignore-errors (apply #'+ '(1 2)))
(ignore-errors (apply #'+ 1 '(2)))
(ignore-errors (funcall #'+ 1 2 3))
(ignore-errors (funcall-interactively 'ignore))
(ignore-errors (run-hook-wrapped 'probe-hook (lambda (f) (funcall f 1))))
(ignore-errors (values 1 2 3))
(ignore-errors (values))
(ignore-errors (ignore 1 2 3))
(ignore-errors (identity 42))
(ignore-errors (always 1))
(ignore-errors (beep))
(ignore-errors (ding))
(ignore-errors (sit-for 0))
(ignore-errors (get-internal-run-time))
(ignore-errors (emacs-build-time))
(ignore-errors (emacs-pid))
(ignore-errors (emacs-version))
(ignore-errors (emacs-version t))
;; data.rs paths
(progn
  (defvaralias 'probe-alias 'probe-target)
  (ignore-errors (boundp 'probe-target))
  (ignore-errors (set 'probe-target 5))
  (ignore-errors (symbol-value 'probe-alias))
  (ignore-errors (indirect-variable 'probe-alias))
  (ignore-errors (makunbound 'probe-alias)))
(progn
  (defalias 'probe-fn 'car)
  (ignore-errors (symbol-function 'probe-fn))
  (ignore-errors (indirect-function 'probe-fn))
  (ignore-errors (indirect-function 'probe-fn t))
  (defalias 'probe-fn2 'probe-fn)
  (ignore-errors (indirect-function 'probe-fn2))
  (ignore-errors (fmakunbound 'probe-fn)))
(let ((p (list 1 2 3)))
  (ignore-errors (setcar p 0))
  (ignore-errors (setcdr p '(9)))
  (ignore-errors (car-safe p))
  (ignore-errors (cdr-safe p)))
(ignore-errors (default-boundp 'car))
(ignore-errors (default-value 'fill-column))
(ignore-errors (set-default 'fill-column 72))
(ignore-errors (default-value 'fill-column))
(ignore-errors (boundp 'fill-column))
(ignore-errors (fboundp 'car))
(ignore-errors (fboundp 'no-such))
(ignore-errors (keywordp :x))
(ignore-errors (keywordp 'x))
(ignore-errors (symbolp :x))
(ignore-errors (obarrayp nil))
(ignore-errors (sequencep [1]))
(ignore-errors (seqp [1]))
(ignore-errors (arrayp [1]))
(ignore-errors (arrayp "s"))
(ignore-errors (booleanp t))
(ignore-errors (booleanp nil))
(ignore-errors (markerp (make-marker)))
(ignore-errors (nlistp 'x))
(ignore-errors (nlistp nil))
(ignore-errors (symbol-name 'abc))
(ignore-errors (symbol-name (make-symbol "u")))
(ignore-errors (intern "probe-sym"))
(ignore-errors (intern-soft "probe-sym"))
(ignore-errors (intern-soft "no-such-sym-xyz"))
(ignore-errors (unintern 'probe-sym))
(ignore-errors (unintern "probe-sym2"))
(ignore-errors (make-symbol "x"))
(ignore-errors (put 'ps 'prop 'val))
(ignore-errors (get 'ps 'prop))
(ignore-errors (plist-get '(a 1 b 2) 'b))
(ignore-errors (plist-put '(a 1) 'c 3))
(ignore-errors (lax-plist-get '(a 1) 'a))
(ignore-errors (plist-member '(a 1) 'a))
(ignore-errors (symbol-plist 'ps))
(ignore-errors (setplist 'ps '(x 1)))
(ignore-errors (documentation 'car))
(ignore-errors (documentation-property 'ps 'prop))
(ignore-errors (get 'ps 'prop))
;; readfn
(ignore-errors (read "(a b)"))
(ignore-errors (read))
(ignore-errors (read nil))
(ignore-errors (read 42))
(ignore-errors (with-temp-buffer
                 (insert "(1 2) tail")
                 (goto-char (point-min))
                 (list (read (current-buffer)) (point))))
(ignore-errors (with-temp-buffer
                 (insert "(3 4)")
                 (goto-char (point-min))
                 (let ((m (point-marker)))
                   (list (read m) (marker-position m)))))
(ignore-errors (let ((m (make-marker))) (read m)))
(ignore-errors (let ((chars (list ?\( ?1 ?\))))
                 (read (lambda () (car-safe (prog1 chars (setq chars (cdr chars))))))))
(ignore-errors (read-from-string "(a b)"))
(ignore-errors (read-from-string "(a b)" 1))
(ignore-errors (read-from-string "(a b)" 1 4))
(ignore-errors (read-positioning-symbols "(a)"))
(ignore-errors (read-buffer-name))
(ignore-errors (read-command "P: "))
(ignore-errors (read-variable "V: "))
(ignore-errors (read-char-choice "P: " '(?a ?b)))
(ignore-errors (read-string "P: "))
(ignore-errors (read-string "P: " "init"))
(ignore-errors (read-string "P: " nil 'hist))
(ignore-errors (read-no-blanks-input "P: "))
(ignore-errors (read-regexp "R: "))
(ignore-errors (read-regexp "R: " '("a" "b")))
(ignore-errors (completing-read "P: " '("x" "y")))
(ignore-errors (completing-read "P: " '("x" "y") nil t))
(ignore-errors (completing-read "P: " '("x" "y") nil nil "x"))
(ignore-errors (completing-read "P: " nil nil nil nil nil "def"))
(ignore-errors (try-completion "a" '(("aa" . 1) ("ab" . 2))))
(ignore-errors (try-completion "a" '(("aa" . 1) ("ab" . 2)) (lambda (s) t)))
(ignore-errors (all-completions "" '(("aa" . 1) ("bb" . 2))))
(ignore-errors (all-completions "a" '(("aa" . 1) ("ab" . 2))))
(ignore-errors (all-completions "a" '(("aa" . 1) ("ab" . 2)) (lambda (s) t)))
(ignore-errors (test-completion "aa" '(("aa" . 1))))
(ignore-errors (completion-boundaries "ab" '(("ab" . 1)) nil ""))
(ignore-errors (minibuffer-completion-table))
(ignore-errors (minibuffer-completion-predicate))
(ignore-errors (minibuffer-completing-symbol))
;; buffer/extra coverage
(ignore-errors (buffer-list))
(ignore-errors (other-buffer))
(ignore-errors (other-buffer (current-buffer)))
(ignore-errors (other-buffer (current-buffer) t))
(ignore-errors (other-buffer (current-buffer) nil (selected-frame)))
(ignore-errors (last-buffer))
(ignore-errors (buffer-name))
(ignore-errors (buffer-file-name))
(ignore-errors (buffer-base-buffer))
(ignore-errors (buffer-base-buffer (current-buffer)))
(ignore-errors (get-buffer (buffer-name)))
(ignore-errors (get-buffer-create "probe-buf"))
(ignore-errors (get-buffer-create "probe-buf" t))
(ignore-errors (buffer-live-p (current-buffer)))
(ignore-errors (buffer-live-p 'nosym))
(ignore-errors (generate-new-buffer "gen-probe"))
(ignore-errors (generate-new-buffer-name "probe-buf"))
(ignore-errors (generate-new-buffer-name "probe-buf" (get-buffer "probe-buf")))
(ignore-errors (rename-buffer "probe-renamed"))
(ignore-errors (rename-buffer "probe-renamed2" t))
(ignore-errors (rename-buffer (current-buffer)))
(ignore-errors (kill-buffer (current-buffer)))
(let ((b (get-buffer-create "kb")))
  (ignore-errors (kill-buffer b))
  (ignore-errors (kill-buffer (buffer-name b))))
(ignore-errors (bury-buffer))
(ignore-errors (bury-buffer (current-buffer)))
(ignore-errors (unbury-buffer))
(ignore-errors (set-buffer (current-buffer)))
(ignore-errors (set-buffer " *Minibuf-0*"))
(ignore-errors (set-buffer-major-mode (current-buffer)))
(ignore-errors (pop-to-buffer-same-window (current-buffer)))
(ignore-errors (replace-buffer-in-windows (current-buffer)))
(ignore-errors (replace-buffer-in-windows " *Minibuf-0*"))
(ignore-errors (restore-buffer-modified-p nil))
(ignore-errors (restore-buffer-modified-p t))
(ignore-errors (restore-buffer-modified-p nil (current-buffer)))
(ignore-errors (buffer-modified-p))
(ignore-errors (buffer-modified-p (current-buffer)))
(ignore-errors (set-buffer-modified-p t))
(ignore-errors (set-buffer-modified-p nil))
(ignore-errors (buffer-modified-tick))
(ignore-errors (buffer-modified-tick (current-buffer)))
(ignore-errors (buffer-chars-modified-tick))
(ignore-errors (buffer-chars-modified-tick (current-buffer)))
(ignore-errors (buffer-enable-undo))
(ignore-errors (buffer-enable-undo (current-buffer)))
(ignore-errors (buffer-disable-undo))
(ignore-errors (buffer-disable-undo (current-buffer)))
(ignore-errors (buffer-undo-list))
(ignore-errors (buffer-undo-list (current-buffer)))
(ignore-errors (erase-buffer))
(ignore-errors (kill-all-local-variables))
(ignore-errors (kill-all-local-variables t))
(ignore-errors (buffer-local-variables))
(ignore-errors (buffer-local-variables (current-buffer)))
(ignore-errors (buffer-local-value 'fill-column (current-buffer)))
(ignore-errors (buffer-local-value 'case-fold-search (current-buffer)))
(ignore-errors (local-variable-p 'fill-column))
(ignore-errors (local-variable-p 'fill-column (current-buffer)))
(ignore-errors (local-variable-if-set-p 'fill-column))
(ignore-errors (make-local-variable 'probe-lv))
(ignore-errors (make-variable-buffer-local 'probe-lv2))
(ignore-errors (kill-local-variable 'probe-lv))
(ignore-errors (kill-local-variable 'probe-lv2))
(ignore-errors (variable-binding-locus 'probe-lv))
(ignore-errors (variable-binding-locus 'fill-column))
(ignore-errors (buffer-substring 1 5))
(ignore-errors (buffer-substring (point-min) (point-max)))
(ignore-errors (buffer-substring-no-properties 1 3))
(ignore-errors (buffer-string))
(ignore-errors (buffer-size))
(ignore-errors (buffer-size (current-buffer)))
(ignore-errors (current-buffer))
(ignore-errors (with-current-buffer (current-buffer) (point)))
(ignore-errors (with-temp-buffer (insert "x") (buffer-string)))
(ignore-errors (save-current-buffer (set-buffer (current-buffer)) (point)))
(ignore-errors (save-excursion (goto-char 1) (point)))
(ignore-errors (save-restriction (widen) (point)))
;; misc data
(ignore-errors (make-finalizer (lambda () nil)))
(ignore-errors (posnp nil))
(ignore-errors (posn-at-point))
(ignore-errors (posn-at-x-y 0 0))
(ignore-errors (narrow-to-region 1 1))
(ignore-errors (widen))
(ignore-errors (point-min))
(ignore-errors (point-max))
(ignore-errors (point-min-marker))
(ignore-errors (point-max-marker))
;; predicate × type matrix
(let ((vals (list nil t 1 1.5 "s" 'sym [1] '(a) (current-buffer)
                  (make-marker) #'car (lambda (x) x) (make-hash-table)
                  (make-bool-vector 4 nil) (make-char-table 'x)
                  (selected-window) (selected-frame) :kw)))
  (dolist (v vals)
    (ignore-errors (atom v))
    (ignore-errors (consp v))
    (ignore-errors (listp v))
    (ignore-errors (nlistp v))
    (ignore-errors (null v))
    (ignore-errors (not v))
    (ignore-errors (symbolp v))
    (ignore-errors (stringp v))
    (ignore-errors (vectorp v))
    (ignore-errors (arrayp v))
    (ignore-errors (sequencep v))
    (ignore-errors (seqp v))
    (ignore-errors (booleanp v))
    (ignore-errors (bufferp v))
    (ignore-errors (markerp v))
    (ignore-errors (functionp v))
    (ignore-errors (subrp v))
    (ignore-errors (macrop v))
    (ignore-errors (keywordp v))
    (ignore-errors (numberp v))
    (ignore-errors (integerp v))
    (ignore-errors (floatp v))
    (ignore-errors (natnump v))
    (ignore-errors (wholenump v))
    (ignore-errors (zerop v))
    (ignore-errors (booleanp v))
    (ignore-errors (char-table-p v))
    (ignore-errors (hash-table-p v))
    (ignore-errors (bool-vector-p v))
    (ignore-errors (windowp v))
    (ignore-errors (framep v))
    (ignore-errors (keymapp v))
    (ignore-errors (obarrayp v))
    (ignore-errors (type-of v))
    (ignore-errors (cl-type-of v))))
;; evalfn deep paths
(ignore-errors (error "msg %s" 'x))
(ignore-errors (user-error "umsg"))
(ignore-errors (signal 'error '("d")))
(ignore-errors (signal 'args-out-of-range '(1 2)))
(ignore-errors (signal 'void-variable '(x)))
(ignore-errors (throw 'tag 'val))
(ignore-errors (featurep 'emacs))
(ignore-errors (featurep 'emacs '(sub)))
(ignore-errors (featurep 'no-such-feature))
(ignore-errors (require 'no-such))
(ignore-errors (load "/tmp/remacs-noload"))
(ignore-errors (load "/tmp/remacs-noload" t))
(ignore-errors (load-file "/tmp/remacs-noload"))
(ignore-errors (message "fmt %s %d" 'x 1))
(ignore-errors (message nil))
(ignore-errors (message ""))
(ignore-errors (float-time))
(ignore-errors (float-time (current-time)))
(ignore-errors (float-time '(0 0)))
(ignore-errors (prog1 1 2 3))
(ignore-errors (eval-buffer))
(ignore-errors (eval-buffer (current-buffer)))
(ignore-errors (eval-buffer nil nil "/tmp/f"))
(ignore-errors (eval-region 1 2))
(ignore-errors (eval-last-sexp nil))
(ignore-errors (defvar probe-dv 1 "doc"))
(ignore-errors (defvar probe-dv))
(ignore-errors (defconst probe-dc 2 "doc"))
(ignore-errors (defun probe-fn3 (x &optional y) "doc" (list x y)))
(ignore-errors (defmacro probe-mac (x) `(list ,x)))
(ignore-errors (probe-mac 5))
(ignore-errors (declare-function 'fn "f" "file" '(x)))
(ignore-errors (declare (indent 1)))
(ignore-errors (macroexpand '(probe-mac 5)))
(ignore-errors (macroexpand-all '(when t 1)))
(ignore-errors (function-get 'car 'doc))
(ignore-errors (function-put 'ps2 'p 'v))
(ignore-errors (special-variable-p 'probe-dv))
(ignore-errors (special-variable-p 'car))
(ignore-errors (indirect-function 'car))
(ignore-errors (indirect-function 'car t))
(ignore-errors (kill-emacs))
(ignore-errors (funcall 'prog1 1 2 3))
(ignore-errors (apply 'or '(nil 2)))
(ignore-errors (apply 'and '(1 nil)))
(ignore-errors (recursive-edit))
(ignore-errors (catch 'exit-recursive-edit (exit-recursive-edit)))
(ignore-errors (catch 'exit-recursive-edit (progn (recursive-edit) (exit-recursive-edit))))
(ignore-errors (catch 'top-level (top-level)))
(ignore-errors (run-hook-wrapped 'probe-hook2 #'identity))
(ignore-errors (let ((probe-hook3 (list #'1+ #'car))) (run-hook-wrapped 'probe-hook3 #'apply 1)))
(ignore-errors (macroexp-let2 nil 'x 'v 'body))
(ignore-errors (macroexp-let2* nil 'x 'v 'body))
(ignore-errors (provide 'probe-sf '(sub1 sub2)))
(ignore-errors (provide 'probe-sf2 '(a . b)))
(ignore-errors (provide 'probe-sf3 'notalist))
(ignore-errors (message "%10d" 5))
(ignore-errors (message "%-10s|end" "x"))
(ignore-errors (message "%.3f" 1.23456))
(ignore-errors (message "%d %s %S %%" 1 "a" 'b))
(ignore-errors (with-output-to-string (princ "hi") (prin1 42)))
(ignore-errors (with-output-to-string (error "boom")))
(ignore-errors (output-switches))
(ignore-errors (defun probe-decl (a) (declare (indent 1) (debug t)) a))
(ignore-errors (probe-decl 9))
(ignore-errors (macroexpand '(defun probe-decl2 (a) (declare (indent 1)) a)))
