;; coverage probe: char-code-property descriptions, translation
;; tables, arith edges, with-output-to-string, charset internals.
(defun P (x) (prin1 x) (terpri))

;; char-code-property-description: every general-category value.
(dolist (v '(Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pc Pd Ps Pe Pi Pf Po
             Sm Sc Sk So Zs Zl Zp Cc Cf Cs Co Cn XX))
  (P (char-code-property-description 'general-category v)))
;; bidi-class: every value.
(dolist (v '(L R AL EN ES ET AN CS NSM BN B S WS ON LRE LRO RLE RLO
             PDF LRI RLI FSI PDI XX))
  (P (char-code-property-description 'bidi-class v)))
;; Unknown property / value → nil.
(P (char-code-property-description 'nope 'x))
(P (char-code-property-description 'general-category 'nope))
(P (char-code-property-description 'bidi-class 'nope))

;; general-category of assorted ASCII chars (ascii_general_category).
(dolist (c '(?a ?Z ?0 ?9 ?\s ?! ?\( 3 ?\n ?_ ?+ ?$ ?~))
  (P (get-char-code-property c 'general-category)))
;; other char-code properties + put/get round-trip.
(P (get-char-code-property ?a 'bidi-class))
(P (get-char-code-property ?a 'decimal-digit-value))
(P (get-char-code-property ?5 'decimal-digit-value))
(P (get-char-code-property ?a 'numeric-value))
(P (get-char-code-property ?a 'mirrored))
(P (get-char-code-property ?a 'old-name))
(P (get-char-code-property ?a 'iso-10646-comment))
(P (get-char-code-property ?a 'nope-property))
;; GNU validates the property table's purpose/extras deeply; guard so the
;; probe still runs there.
(P (condition-case e (define-char-code-property 'my-prop "prop-file")
     (t (car e))))
(P (condition-case e (put-char-code-property ?q 'my-prop 'val) (t (car e))))
(P (condition-case e (get-char-code-property ?q 'my-prop) (t (car e))))
(P (condition-case e (get-char-code-property ?q 'my-prop2) (t (car e))))
(P (condition-case e (char-code-property-description 'my-prop 'val) (t (car e))))

;; translation tables.
(P (condition-case e (type-of (make-translation-table '((65 . 66) (300 . 5) (-1 . 2))))
     (t (car e))))
(define-translation-table 'tt13 '((97 . 98)))
(P (get 'tt13 'translation-table))
(P (condition-case e (type-of (set-translation-table (make-translation-table '((65 . 66)))))
     (t (car e))))
(P (condition-case e (set-translation-table nil) (t (car e))))
(let ((v (make-vector 256 nil)))
  (dotimes (k 256) (aset v k k))
  (aset v 65 900)
  (P (type-of (make-translation-table-from-vector v))))
(P (condition-case e (make-translation-table-from-vector [1 2]) (error (car e))))
(P (condition-case e (make-translation-table-from-vector 5) (error (car e))))

;; coding systems + charset internals.
(P (coding-system-charset-list 'utf-8))
(P (coding-system-charset-list 'iso-latin-1))
(P (condition-case e (coding-system-charset-list 'no-such-cs) (t (car e))))
(set-coding-system-priority 'utf-8 'iso-latin-1)
(with-temp-buffer
  (insert "abc")
  (P (find-coding-systems-region-internal 1 4)))
(P (find-charset-string "abc"))
(P (find-charset-string "aé中"))
(P (find-charset-string ""))
(with-temp-buffer
  (insert "abc")
  (P (find-charset-region 1 4)))
(P (charsetp 'ascii))
(P (charsetp 'unicode))
(P (charsetp 'no-such))
(P (charset-plist 'ascii))
(set-charset-plist 'ascii '(:x 1))
(P (charset-plist 'ascii))
(P (get-charset-property 'ascii 'x))
(put-charset-property 'ascii 'y 7)
(P (get-charset-property 'ascii 'y))
(P (get-charset-property 'ascii 'z))
(P (condition-case e (get-charset-property 'no-such 'x) (error (car e))))
(define-charset-alias 'my-alias 'ascii)
(P (charsetp 'my-alias))
(P (char-charset ?a))
(P (char-charset ?a 'ascii))
(P (char-charset ?a 'iso-latin-1))
(P (charset-after))
(P (charset-after 1))
(P (charset-after 999))
(P (condition-case e (define-charset 'my-charset [1 2 3] :invalid-code 255)
     (t (car e))))
(P (condition-case e (define-charset 'my-charset [1 2 3] :invalid-code 255
                                     :code-offset 0)
     (t (car e))))
(P (charsetp 'my-charset))
(P (condition-case e (unify-charset 'unicode) (error (car e))))
(P (condition-case e (unify-charset 'ascii) (error (car e))))
(P (encode-char ?a 'ascii))
(P (condition-case e (encode-char ?a 'iso-8859-1) (t (car e))))
(P (decode-char 'ascii 97))
(P (condition-case e (decode-char 'iso-8859-1 233) (t (car e))))
(P (decode-char 'ascii 300))
(set-keyboard-coding-system-internal 'utf-8)

;; with-output-to-string.
(P (with-output-to-string (princ "hi") (princ 5)))
(P (with-output-to-string))
(P (with-output-to-string (print 'x)))

;; arith edges.
(P (ash 1 63))
(P (ash -1 -200))
(P (ash 1 -200))
(P (ash 5 -1))
(P (condition-case e (ash 1 128) (error (car e))))
(P (condition-case e (ash (1+ most-positive-fixnum) 100) (error (car e))))
(P (lsh 1 63))
(P (lsh -1 -1))
(P (lsh -1 -63))
(P (lsh -1 -200))
(P (lsh (ash 1 100) -70))
(P (lsh (ash 1 100) -200))
(P (condition-case e (lsh 1 128) (error (car e))))
(P (condition-case e (lsh (1+ most-positive-fixnum) 60) (error (car e))))
(P (mod 10 3))
(P (mod -10 3))
(P (mod 10 -3))
(P (mod 10.5 3))
(P (mod 10 3.5))
(P (mod 10.5 3.2))
(P (condition-case e (mod 10 0) (error (car e))))
(P (condition-case e (mod 10 0.0) (error (car e))))
(P (% 10 3))
(P (condition-case e (% 10.5 3) (error (car e))))
(P (condition-case e (% -10.5 3) (error (car e))))
(P (condition-case e (% 10 0) (error (car e))))
(P (/ 10 3))
(P (/ 10.0 4))
(P (/ 10 4.0))
(P (/ 6 3 2))
(P (condition-case e (/ 1 0) (error (car e))))
(P (condition-case e (/ 1.0 0.0) (error (car e))))
(P (1+ 5))
(P (1+ 5.5))
(P (1- 5))
(P (abs -5))
(P (abs -5.5))
(P (abs 5))
(P (float 5))
(P (truncate 3.7))
(P (truncate -3.7))
(P (truncate 7.5 2))
(P (truncate 5 2))
(P (floor 3.7))
(P (floor -3.2))
(P (floor 7.5 2))
(P (ceiling 3.2))
(P (ceiling -3.7))
(P (ceiling 7.5 2))
(P (round 3.5))
(P (round -3.5))
(P (round 7.5 2))
(P (round 2.5))
(P (condition-case e (round 1 0) (error (car e))))
(P (condition-case e (truncate 'x) (error (car e))))
(P (ffloor 3.7))
(P (fceiling 3.2))
(P (fround 3.5))
(P (ftruncate 3.7))
(P (condition-case e (ffloor 3) (error (car e))))
(P (floatp (ffloor 3.0)))
(P (condition-case e (isqrt 16) (error (car e))))
(P (condition-case e (isqrt 17) (error (car e))))
(P (condition-case e (isqrt 0) (error (car e))))
(P (condition-case e (isqrt -1) (error (car e))))
(P (expt 2 10))
(P (expt 2.0 3))
(P (expt 2 -2))
(P (expt 2 0))
(P (expt -2 3))
(P (exp 1))
(P (log 10))
(P (log 100 10))
(P (log -1))
(P (logb 16))
(P (logb 0.0))
(P (ldexp 1.5 3))
(P (condition-case e (copysign 1.5 -1) (error (car e))))
(P (copysign -1.5 1.0))
(P (condition-case e (copysign -1.5 1) (error (car e))))
(P (frexp 8.0))
(P (isnan 1.0))
(P (isnan (/ 0.0 0.0)))
(P (= 1 1.0))
(P (/= 1 2))
(P (< 1 2 3))
(P (< 3 1))
(P (<= 1 1))
(P (> 3 2 1))
(P (> 1 2))
(P (>= 2 2))
(P (max 1 2 3))
(P (min 3 1 2))
(P (max 1.5 2))
(P (min 1.5 2))
(P (+ 1 2 3))
(P (+ 1.5 2))
(P (+))
(P (- 10 1 2))
(P (- 5))
(P (- 10.5 0.5))
(P (* 2 3 4))
(P (* 2.5 4))
(P (*))
(P (logand 12 10))
(P (logand -1 5))
(P (logior 12 10))
(P (logxor 12 10))
(P (lognot 0))
(P (lognot -1))
(P (logcount 255))
(P (logcount -1))
(P (logcount 0))
(P (natnump 5))
(P (natnump -1))
(P (natnump 5.0))
(P (fixnump 5))
(P (fixnump 5.0))
(P (bignump 5))
(P (bignump (ash 1 100)))
(P (integerp 5.0))
(P (number-or-marker-p 5))
(P (number-or-marker-p 'x))
(P (zerop 0))
(P (zerop 1))
(P (condition-case e (+ 1 'x) (error (car e))))
(P (condition-case e (ash 'x 1) (error (car e))))
(random 5)
(random t)
(P (numberp (random 5)))

;; process coverage: signals, services, plist keys, eol coding.
(dolist (sig '(SIGWINCH SIGURG SIGCONT SIGIO SIGCHLD SIGCLD SIGTSTP SIGSTOP
               SIGTTIN SIGTTOU))
  (let ((p (make-process :name "sig" :command '("sleep" "30"))))
    (P (condition-case e (signal-process p sig) (error (car e))))
    (delete-process p)))
(dolist (sig '(SIGTERM SIGKILL SIGINT SIGQUIT SIGABRT SIGHUP SIGUSR1 SIGUSR2
               SIGALRM SIGPIPE SIGILL SIGTRAP SIGBUS SIGFPE SIGSYS SIGXCPU
               SIGXFSZ SIGVTALRM SIGPROF SIGSEGV SIGEMT))
  (let ((p (make-process :name "sig" :command '("sleep" "30"))))
    (P (condition-case e (signal-process p sig) (error (car e))))
    (delete-process p)))
(let ((p (make-process :name "sig" :command '("sleep" "30"))))
  (P (signal-process p 0))
  (P (condition-case e (signal-process p 'SIGBOGUS) (error (car e))))
  (P (condition-case e (signal-process p "x") (error (car e))))
  (delete-process p))
(let ((p (make-process :name "srv" :command '("sleep" "30"))))
  (P (signal-process (process-name p) 0))
  (P (signal-process (process-name p) 'SIGTERM))
  (delete-process p))

;; service_port: named, numeric-string, integer, bogus.
;; Named services resolve but binding port 80 needs root — just cover lookup.
(P (condition-case e (make-network-process :name "n1" :server t :host "127.0.0.1"
                     :service "http") (error (car e))))
(let ((s (make-network-process :name "n2" :server t :host "127.0.0.1" :service "0")))
  (P (process-contact s :local))
  (delete-process s))
(P (condition-case e (make-network-process :name "n3" :server t :host "127.0.0.1"
                     :service "bogus") (error (car e))))
(P (condition-case e (make-network-process :name "n4" :server t :host "127.0.0.1"
                     :service 'x) (error (car e))))
(let ((d (make-network-process :name "dg" :type 'datagram :server t
                               :host "127.0.0.1" :service 0)))
  (P (process-contact d :local))
  (delete-process d))
(let ((s (condition-case e
             (make-network-process :name "npl" :server t :host "127.0.0.1"
                                   :service 0 :plist '(:a 1 :b 2)
                                   :coding '(raw-text-unix . utf-8-dos)
                                   :noquery t :nowait t)
           (error (car e)))))
  (P (if (processp s) (plist-get (process-plist s) :b) s))
  (P (if (processp s) (process-coding-system s) 'na))
  (P (if (processp s) (process-query-on-exit-flag s) 'na))
  (if (processp s) (delete-process s)))

;; finish_setup plist keys on make-process.
(let ((p (make-process :name "keys" :command '("cat")
                       :connection-type 'pipe
                       :filter (lambda (pr s) (princ (format "FLT:%s" s)))
                       :sentinel (lambda (pr ev) (princ (format "SNT:%s" ev)))
                       :coding '(utf-8-unix . utf-8-unix)
                       :noquery t :plist '(:k 9))))
  (P (plist-get (process-plist p) :k))
  (process-send-string p "x\n")
  (accept-process-output p 1)
  (delete-process p))
(let ((p (make-process :name "nq" :command '("sleep" "30") :query-on-exit nil)))
  (P (process-query-on-exit-flag p))
  (delete-process p))
(P (condition-case e (make-process :name "bad" :command '("cat") :connection-type 'nope)
     (error (car e))))

;; eol_normalize via set-process-coding-system variants.
(let ((p (make-pipe-process :name "cod")))
  (dolist (cs '((raw-text-unix . raw-text-dos) (utf-8-mac . latin-1)
                ("utf-8-dos" . "utf-8-mac") (undecided . undecided)))
    (P (condition-case e
           (progn (set-process-coding-system p (car cs) (cdr cs))
                  (process-coding-system p))
         (error (car e)))))
  (set-process-coding-system p)
  (P (process-coding-system p))
  (delete-process p))

;; format-network-address: family list, string path, bad args.
(P (format-network-address '(2 (127 0 0 1) 8080)))
(P (format-network-address '(2130706433 80)))
(P (format-network-address "/tmp/sock"))
(P (format-network-address nil))
(P (condition-case e (format-network-address '("localhost" 80)) (error (car e))))
(P (condition-case e (format-network-address 5) (error (car e))))

;; accept-process-output flag combinations on a live proc.
(let ((p (make-process :name "acc" :command '("cat"))))
  (process-send-string p "hey\n")
  (P (accept-process-output p 1))
  (P (accept-process-output p 0 50))
  (P (accept-process-output p 0 50 t))
  (P (accept-process-output p 0 50 nil))
  (process-send-eof p)
  (delete-process p))
(P (accept-process-output nil 0))

;; deliver_output: filter lambda, buffer target, marker mid-buffer.
(let ((p (make-process :name "fl" :command '("echo" "out")
                       :filter (lambda (pr s) (princ (format "F:%s" s))))))
  (accept-process-output p 1)
  (delete-process p))
(let ((b (get-buffer-create "pb13")))
  (let ((p (make-process :name "bf" :command '("echo" "zz") :buffer b)))
    (accept-process-output p 1)
    (P (with-current-buffer b (buffer-string)))
    (delete-process p))
  (kill-buffer b))

;; pipe processes: plist keys + send-string + eof + stop/continue.
(let ((p (make-pipe-process :name "pp" :buffer "ppb" :coding '(raw-text . raw-text)
                            :noquery t :stop t :plist '(:w 3)
                            :filter 'internal-default-process-filter
                            :sentinel 'ignore)))
  (P (process-status p))
  (P (plist-get (process-plist p) :w))
  (P (process-tty-name p))
  (P (process-command p))
  (continue-process p)
  (P (process-status p))
  (process-send-string p "data")
  (process-send-eof p)
  (P (condition-case e (signal-process p 'SIGKILL) (error (car e))))
  (delete-process p)
  (kill-buffer "ppb"))

;; serial: full key set on a pty path borrowed from a child proc.
(let* ((c (make-process :name "tty" :command '("sleep" "30")))
       (tty (process-tty-name c)))
  (let ((s (condition-case e
               (make-serial-process :name "ser" :port tty :speed 9600
                                    :bytesize 8 :parity 'none :stopbits 1
                                    :flowcontrol 'none :coding '(raw-text . raw-text)
                                    :noquery t)
             (t (car e)))))
    (P (if (processp s) (process-contact s) s))
    (P (if (processp s) (process-contact s t) 'na))
    (P (if (processp s) (process-status s) 'na))
    (if (processp s) (process-send-string s "x"))
    (P (if (processp s)
           (condition-case e (process-send-eof s) (error (car e)))
         'na))
    (if (processp s) (delete-process s)))
  (delete-process c))
(P (condition-case e (make-serial-process :name "s0" :port "/no/such" :speed 9600)
     (t (car e))))
(P (condition-case e (make-serial-process :name "s1" :port 'x :speed 9600)
     (t (car e))))
(P (condition-case e (make-serial-process :name "s2" :speed 9600)
     (t (car e))))
(P (make-serial-process))

;; send-region / send-string on a cat proc.
(let ((p (make-process :name "rg" :command '("cat") :buffer "rgb")))
  (with-temp-buffer (insert "abc") (process-send-region p 1 4))
  (process-send-string p "\n")
  (accept-process-output p 1)
  (P (with-current-buffer "rgb" (buffer-string)))
  (delete-process p)
  (kill-buffer "rgb"))

;; process-lines + set-process-buffer + process-mark mid-buffer.
(P (process-lines "echo" "l1" "l2"))
(P (process-lines "printf" "a\nb\n"))
(let ((p (make-process :name "mb" :command '("echo" "mid"))))
  (set-process-buffer p (get-buffer-create "mbb"))
  (accept-process-output p 1)
  (with-current-buffer "mbb"
    (goto-char (point-min))
    (insert "pre "))
  (P (marker-position (process-mark p)))
  (P (buffer-name (process-buffer p)))
  (delete-process p)
  (kill-buffer "mbb"))
(princ "eval13 done") (terpri)
