;; Deep probe: buffer text ops, narrowing, regions, markers, undo,
;; windows/frames, keymaps, minibuffer state, syntax scanning.
(progn
  (ignore-errors (insert "alpha beta gamma\ndelta epsilon\n\nzeta\n"))
  (ignore-errors (set-mark 5))
  (ignore-errors (activate-mark))
  (ignore-errors (mark))
  (ignore-errors (mark-marker))
  (ignore-errors (region-beginning))
  (ignore-errors (region-end))
  (ignore-errors (buffer-substring 1 5))
  (ignore-errors (buffer-substring-no-properties 1 5))
  (ignore-errors (delete-region 3 6))
  (ignore-errors (insert-before-markers "XX"))
  (ignore-errors (insert-and-inherit "YY"))
  (ignore-errors (insert-char ?q 3))
  (ignore-errors (insert-char ?\n 2 t))
  (ignore-errors (delete-char -1))
  (ignore-errors (delete-char 1 t))
  (ignore-errors (erase-buffer))
  (ignore-errors (insert "line1\nline2\nline3\n"))
  ;; narrowing
  (ignore-errors (narrow-to-region 1 6))
  (ignore-errors (point-min))
  (ignore-errors (point-max))
  (ignore-errors (widen))
  (ignore-errors (narrow-to-defun))
  (ignore-errors (narrow-to-page))
  (ignore-errors (widen))
  ;; markers
  (ignore-errors (let ((m (point-marker))) (set-marker m 3) (marker-position m)))
  (ignore-errors (let ((m (copy-marker 2))) (marker-buffer m)))
  (ignore-errors (let ((m (copy-marker 2 t))) (set-marker m nil)))
  (ignore-errors (let ((m (make-marker))) (marker-insertion-type m)))
  ;; text properties
  (ignore-errors (put-text-property 1 3 'face 'bold))
  (ignore-errors (get-text-property 1 'face))
  (ignore-errors (text-properties-at 1))
  (ignore-errors (add-text-properties 1 2 '(font-lock-face warning)))
  (ignore-errors (remove-text-properties 1 2 '(face)))
  (ignore-errors (set-text-properties 1 2 nil))
  (ignore-errors (next-property-change 1))
  (ignore-errors (next-single-property-change 1 'face))
  (ignore-errors (previous-property-change 5))
  (ignore-errors (previous-single-property-change 5 'face))
  (ignore-errors (text-property-any 1 8 'face 'bold))
  (ignore-errors (text-property-not-all 1 8 'face 'bold))
  ;; kill ring
  (ignore-errors (kill-new "ring-item"))
  (ignore-errors (kill-append "more" nil))
  (ignore-errors (current-kill 0))
  (ignore-errors (current-kill 1 t))
  (ignore-errors (kill-region 1 4))
  (ignore-errors (copy-region-as-kill 1 3))
  (ignore-errors (yank))
  (ignore-errors (yank-pop))
  ;; case ops on region/point
  (ignore-errors (upcase-region 1 3))
  (ignore-errors (downcase-region 1 3))
  (ignore-errors (capitalize-region 1 5))
  (ignore-errors (upcase-word 1))
  (ignore-errors (downcase-word 1))
  (ignore-errors (capitalize-word 1))
  ;; columns/indent
  (ignore-errors (insert "\tx\ty\n"))
  (ignore-errors (goto-char 2))
  (ignore-errors (current-column))
  (ignore-errors (move-to-column 10))
  (ignore-errors (indent-to 12))
  (ignore-errors (indent-relative))
  (ignore-errors (tab-to-tab-stop))
  (ignore-errors (line-beginning-position))
  (ignore-errors (line-end-position))
  (ignore-errors (line-number-at-pos))
  (ignore-errors (count-lines 1 5))
  (ignore-errors (count-screen-lines 1 5))
  ;; char/eol checks
  (ignore-errors (bolp))
  (ignore-errors (eolp))
  (ignore-errors (eobp))
  (ignore-errors (bobp))
  (ignore-errors (char-after 1))
  (ignore-errors (char-before 2))
  (ignore-errors (following-char))
  (ignore-errors (preceding-char))
  ;; word/char scanning
  (ignore-errors (forward-word))
  (ignore-errors (skip-chars-forward "a-z"))
  (ignore-errors (skip-chars-backward "a-z"))
  (ignore-errors (skip-syntax-forward "w"))
  (ignore-errors (skip-syntax-backward "w"))
  (ignore-errors (forward-comment 1))
  ;; search
  (ignore-errors (search-forward "line"))
  (ignore-errors (search-backward "line"))
  (ignore-errors (re-search-forward "l[ai]ne"))
  (ignore-errors (re-search-backward "l[ai]ne"))
  (ignore-errors (search-forward "zzz" nil t))
  (ignore-errors (looking-at "li"))
  (ignore-errors (looking-back "li" nil))
  (ignore-errors (re-search-forward "\\(li\\)\\(ne\\)" nil t))
  (ignore-errors (match-beginning 0))
  (ignore-errors (match-end 0))
  (ignore-errors (match-beginning 1))
  (ignore-errors (match-string 0))
  (ignore-errors (match-string 2))
  (ignore-errors (match-data)))
(progn
  ;; buffers
  (ignore-errors (generate-new-buffer "test-gen"))
  (ignore-errors (get-buffer-create "test-gc"))
  (ignore-errors (buffer-name (get-buffer "test-gc")))
  (ignore-errors (buffer-size))
  (ignore-errors (buffer-size (get-buffer "test-gc")))
  (ignore-errors (buffer-modified-p))
  (ignore-errors (set-buffer-modified-p t))
  (ignore-errors (buffer-modified-p))
  (ignore-errors (restore-buffer-modified-p nil))
  (ignore-errors (buffer-enable-undo))
  (ignore-errors (buffer-disable-undo))
  (ignore-errors (buffer-local-value 'fill-column (get-buffer "test-gc")))
  (ignore-errors (buffer-live-p (get-buffer "test-gc")))
  (ignore-errors (buffer-live-p "test-gc"))
  (ignore-errors (buffer-list))
  (ignore-errors (other-buffer))
  (ignore-errors (bury-buffer))
  (ignore-errors (bury-buffer (get-buffer "test-gc")))
  (ignore-errors (unbury-buffer))
  (ignore-errors (kill-buffer "test-gc"))
  (ignore-errors (kill-buffer nil))
  (ignore-errors (get-buffer "nonexistent"))
  (ignore-errors (rename-buffer "renamed-buf"))
  (ignore-errors (rename-buffer "unique" t)))
(progn
  ;; windows & frames
  (ignore-errors (split-window))
  (ignore-errors (split-window nil 20))
  (ignore-errors (split-window nil nil t))
  (ignore-errors (delete-window))
  (ignore-errors (delete-other-windows))
  (ignore-errors (other-window 1))
  (ignore-errors (window-list))
  (ignore-errors (window-list nil t))
  (ignore-errors (walk-windows (lambda (w) w)))
  (ignore-errors (window-buffer))
  (ignore-errors (window-point))
  (ignore-errors (window-start))
  (ignore-errors (window-end))
  (ignore-errors (window-end nil t))
  (ignore-errors (set-window-point (selected-window) 5))
  (ignore-errors (set-window-start (selected-window) 1))
  (ignore-errors (set-window-buffer (selected-window) (current-buffer)))
  (ignore-errors (window-height))
  (ignore-errors (window-width))
  (ignore-errors (window-body-height))
  (ignore-errors (window-body-width))
  (ignore-errors (window-total-height))
  (ignore-errors (window-total-width))
  (ignore-errors (window-edges))
  (ignore-errors (window-body-edges))
  (ignore-errors (window-inside-edges))
  (ignore-errors (window-pixel-edges))
  (ignore-errors (window-absolute-pixel-edges))
  (ignore-errors (coordinates-in-window-p '(1 . 1)))
  (ignore-errors (window-at 1 1))
  (ignore-errors (window-frame))
  (ignore-errors (frame-selected-window))
  (ignore-errors (frame-first-window))
  (ignore-errors (frame-root-window))
  (ignore-errors (window-minibuffer-p))
  (ignore-errors (minibuffer-window))
  (ignore-errors (window-live-p (selected-window)))
  (ignore-errors (window-valid-p (selected-window)))
  (ignore-errors (windowp (selected-window)))
  (ignore-errors (window-dedicated-p))
  (ignore-errors (set-window-dedicated-p (selected-window) t))
  (ignore-errors (window-parameter (selected-window) 'test))
  (ignore-errors (set-window-parameter (selected-window) 'test 42))
  (ignore-errors (window-parameters))
  (ignore-errors (window-prev-buffers))
  (ignore-errors (window-next-buffers))
  (ignore-errors (window-use-time))
  (ignore-errors (window-display-table))
  (ignore-errors (window-text-pixel-size))
  (ignore-errors (window-line-height))
  (ignore-errors (window-left-column))
  (ignore-errors (window-hscroll))
  (ignore-errors (set-window-hscroll (selected-window) 5))
  (ignore-errors (window-margins))
  (ignore-errors (set-window-margins (selected-window) 2 2))
  (ignore-errors (window-fringes))
  (ignore-errors (window-scroll-bars))
  (ignore-errors (window-divider-width))
  (ignore-errors (enlarge-window 2))
  (ignore-errors (enlarge-window 2 t))
  (ignore-errors (shrink-window 1))
  (ignore-errors (enlarge-window-horizontal 3))
  (ignore-errors (shrink-window-horizontally 1))
  (ignore-errors (balance-windows))
  (ignore-errors (fit-window-to-buffer))
  (ignore-errors (maximize-window))
  (ignore-errors (minimize-window))
  (ignore-errors (window-resize (selected-window) 2))
  (ignore-errors (window-resizable-p (selected-window) 1))
  (ignore-errors (split-window-below))
  (ignore-errors (split-window-right))
  (ignore-errors (delete-window (selected-window)))
  (ignore-errors (scroll-up 2))
  (ignore-errors (scroll-down 1))
  (ignore-errors (scroll-other-window 1))
  (ignore-errors (scroll-up-command))
  (ignore-errors (scroll-down-command))
  (ignore-errors (recenter))
  (ignore-errors (recenter 0))
  (ignore-errors (recenter-top-bottom))
  (ignore-errors (move-to-window-line 0))
  (ignore-errors (beginning-of-buffer-other-window))
  (ignore-errors (posn-at-point))
  (ignore-errors (posn-at-x-y 1 1))
  (ignore-errors (pos-visible-in-window-p))
  (ignore-errors (vertical-motion 1))
  (ignore-errors (line-pixel-height))
  (ignore-errors (window-text-height))
  (ignore-errors (frame-height))
  (ignore-errors (frame-width))
  (ignore-errors (frame-char-height))
  (ignore-errors (frame-char-width))
  (ignore-errors (frame-pixel-height))
  (ignore-errors (frame-pixel-width))
  (ignore-errors (frame-text-height))
  (ignore-errors (frame-text-width))
  (ignore-errors (frame-inner-height))
  (ignore-errors (frame-outer-height))
  (ignore-errors (frame-edges))
  (ignore-errors (frame-geometry))
  (ignore-errors (frame-position))
  (ignore-errors (frame-visible-p (selected-frame)))
  (ignore-errors (framep (selected-frame)))
  (ignore-errors (frame-live-p (selected-frame)))
  (ignore-errors (select-frame (selected-frame)))
  (ignore-errors (selected-frame))
  (ignore-errors (window-frame (selected-window))))
(progn
  ;; keymaps deeper
  (ignore-errors (let ((m (make-sparse-keymap "M"))) (keymap-prompt m)))
  (ignore-errors (keymap-prompt (make-keymap)))
  (ignore-errors (let ((m (make-keymap))) (set-keymap-parent m nil) m))
  (ignore-errors (keymapp (current-global-map)))
  (ignore-errors (lookup-key (current-global-map) "\C-x"))
  (ignore-errors (lookup-key (current-global-map) "\C-x\C-f"))
  (ignore-errors (lookup-key (current-global-map) "\C-x\C-f\C-z"))
  (ignore-errors (lookup-key (current-global-map) "\C-q"))
  (ignore-errors (define-key (current-global-map) [f9] 'forward-word))
  (ignore-errors (lookup-key (current-global-map) [f9]))
  (ignore-errors (define-key (current-global-map) [f9] nil))
  (ignore-errors (lookup-key (current-global-map) [f9]))
  (ignore-errors (key-binding "a"))
  (ignore-errors (key-binding [t]))
  (ignore-errors (local-key-binding "a"))
  (ignore-errors (global-key-binding "a"))
  (ignore-errors (minor-mode-key-binding 'auto-fill-function))
  (ignore-errors (commandp 'next-line))
  (ignore-errors (commandp 'not-a-command))
  (ignore-errors (commandp '(lambda (x) (interactive) x)))
  (ignore-errors (keymap-parent (current-global-map)))
  (ignore-errors (substitute-command-keys "Press \\[next-line]")))
(progn
  ;; misc runtime
  (ignore-errors (make-obsolete 'foo 'bar))
  (ignore-errors (make-obsolete-variable 'vfoo 'vbar))
  (ignore-errors (interactive-p))
  (ignore-errors (called-interactively-p 'any))
  (ignore-errors (command-line))
  (ignore-errors (force-mode-line-update))
  (ignore-errors (force-mode-line-update t))
  (ignore-errors (sit-for 0))
  (ignore-errors (sleep-for 0))
  (ignore-errors (accept-process-output nil 0))
  (ignore-errors (recursion-depth))
  (ignore-errors (max-specpdl-size))
  (ignore-errors (garbage-collect))
  (ignore-errors (memory-limit))
  (ignore-errors (memory-use-counts))
  (ignore-errors (emacs-pid))
  (ignore-errors (dump-emacs "x" "y"))
  (ignore-errors (dump-emacs-portable "x"))
  (ignore-errors (frame-or-buffer-changed-p))
  (ignore-errors (open-termscript "f"))
  (ignore-errors (suspend-emacs))
  (ignore-errors (kill-emacs 0))
  (ignore-errors (iconify-or-deiconify-frame))
  (ignore-errors (list-timers))
  (ignore-errors (current-idle-time))
  (ignore-errors (float-time))
  (ignore-errors (float-time '(100 200)))
  (ignore-errors (emacs-uptime))
  (ignore-errors (emacs-uptime "%S"))
  (ignore-errors (format-seconds "%y, %d, %h, %m, %s" 1000))
  (ignore-errors (recent-keys))
  (ignore-errors (this-command-keys))
  (ignore-errors (this-single-command-keys))
  (ignore-errors (this-single-command-raw-keys))
  (ignore-errors (clear-this-command-keys))
  (ignore-errors (lossage-size))
  (ignore-errors (discard-input))
  (ignore-errors (input-pending-p))
  (ignore-errors (input-pending-p t))
  (ignore-errors (momentary-string-display "msg" 1))
  (ignore-errors (open-dribble-file "/tmp/dribble-test"))
  (ignore-errors (open-dribble-file nil)))
