;; probe_buffer4 — deeper primitives coverage: text properties,
;; markers, narrowing, match data, buffer-local vars, undo

;; ---- text properties ----
(with-temp-buffer
  (insert "abcdefghij")
  (put-text-property 1 4 'face 'bold)
  (put-text-property 3 6 'help-echo "hint")
  (add-text-properties 7 9 '(mouse-face highlight))
  (get-text-property 1 'face)
  (get-text-property 3 'help-echo)
  (text-properties-at 1)
  (text-properties-at 8)
  (next-property-change 1)
  (next-property-change 3)
  (previous-property-change 4)
  (next-single-property-change 1 'face)
  (previous-single-property-change 6 'help-echo)
  (text-property-any 1 10 'face 'bold)
  (text-property-not-all 1 10 'face 'bold)
  (remove-text-properties 1 3 '(face))
  (set-text-properties 4 6 '(custom val))
  (propertize "x" 'face 'bold)
  (buffer-substring-with-properties 1 5)
  (substring-no-properties "abc")
  (remove-list-of-text-properties 1 10 '(help-echo custom)))

;; ---- markers ----
(with-temp-buffer
  (insert "marker text here")
  (let* ((m (make-marker))
         (m2 (copy-marker (point-min-marker)))
         (m3 (point-max-marker)))
    (markerp m)
    (set-marker m 5)
    (marker-position m)
    (marker-buffer m)
    (set-marker m (point-max))
    (marker-insertion-type m)
    (set-marker-insertion-type m t)
    (insert-before-markers "X")
    (insert "Y")
    (marker-position m)
    (set-marker m nil)
    (byte-to-position 3)
    (position-bytes 3)
    (max-char)))

;; ---- narrowing ----
(with-temp-buffer
  (insert "aaabbbccc")
  (narrow-to-region 4 7)
  (point-min)
  (point-max)
  (buffer-size)
  (widen)
  (point-min)
  (point-max)
  (narrow-to-page 1))

;; ---- match data ----
(with-temp-buffer
  (insert "abc123def456")
  (goto-char (point-min))
  (re-search-forward "\\([0-9]+\\)")
  (match-beginning 0)
  (match-end 0)
  (match-beginning 1)
  (match-end 1)
  (match-string 0)
  (match-string 1)
  (match-string-no-properties 0)
  (match-data)
  (match-data t)
  (set-match-data (match-data))
  (replace-match "X")
  (goto-char (point-min))
  (string-match "\\([a-z]+\\)" "aaBBcc" 0)
  (match-beginning 1)
  (looking-at "abc")
  (looking-back "abc" nil)
  (re-search-backward "123" nil t)
  (search-forward "def" nil t)
  (search-backward "abc" nil t)
  (skip-chars-forward "a-z")
  (skip-chars-backward "0-9")
  (skip-syntax-forward "w")
  (skip-syntax-backward "w")
  (syntax-after (point))
  (following-char)
  (preceding-char)
  (char-after)
  (char-before))

;; ---- buffer-local variables ----
(with-temp-buffer
  (make-local-variable 'probe-lv)
  (setq probe-lv 7)
  (local-variable-p 'probe-lv)
  (local-variable-if-set-p 'probe-lv)
  (buffer-local-value 'probe-lv (current-buffer))
  (buffer-local-variables)
  (kill-local-variable 'probe-lv)
  (make-variable-buffer-local 'probe-lv2)
  (setq probe-lv2 9)
  (kill-all-local-variables)
  (default-boundp 'fill-column)
  (default-value 'fill-column)
  (set-default 'probe-dv 3)
  (default-value 'probe-dv))

;; ---- undo ----
(with-temp-buffer
  (buffer-enable-undo)
  (insert "undo me")
  (primitive-undo 1 buffer-undo-list)
  (buffer-disable-undo)
  (buffer-enable-undo)
  (insert "x"))

;; ---- buffers ----
(generate-new-buffer-name "probe-nm")
(generate-new-buffer " probe-hidden")
(bury-buffer)
(unbury-buffer)
(buffer-list)
(other-buffer)
(last-buffer)
(buffer-base-buffer (current-buffer))
(buffer-live-p (current-buffer))
(buffer-name)
(buffer-file-name)
(buffer-modified-p)
(set-buffer-modified-p nil)
(buffer-string)
(buffer-size)
(buffer-disable-undo)
(rename-buffer "probe-renamed" t)
(current-buffer)
(set-buffer (current-buffer))
(buffer-substring 1 3)
(insert-buffer-substring (current-buffer) 1 3)
(erase-buffer)

;; ---- point/column/line motion ----
(with-temp-buffer
  (insert "one\ntwo\nthree\nfour\n")
  (goto-char (point-min))
  (forward-line 2)
  (end-of-line)
  (beginning-of-line)
  (forward-char 2)
  (backward-char 1)
  (forward-word 1)
  (backward-word 1)
  (move-to-column 2)
  (current-column)
  (line-number-at-pos)
  (count-lines (point-min) (point-max))
  (pos-bol)
  (pos-eol)
  (line-beginning-position)
  (line-end-position)
  (line-beginning-position 2)
  (line-end-position 2)
  (count-words-region (point-min) (point-max))
  (thing-at-point 'word)
  (symbol-at-point)
  (word-at-point)
  (current-word)
  (open-line 1)
  (newline 2)
  (insert-char ?x 3)
  (self-insert-command 1)
  (delete-char 1)
  (delete-backward-char 1)
  (delete-region (point-min) (+ 2 (point-min)))
  (delete-and-extract-region (point-min) (point-max)))

;; ---- mark ----
(with-temp-buffer
  (insert "mark test")
  (push-mark 3)
  (push-mark 6 t)
  (mark)
  (mark-marker)
  (set-mark 8)
  (pop-mark)
  (exchange-point-and-mark)
  (activate-mark)
  (region-active-p)
  (use-region-p)
  (region-beginning)
  (region-end)
  (deactivate-mark)
  (barf-if-buffer-read-only))

;; ---- regexps ----
(regexp-quote "a.b*c")
(regexp-opt '("foo" "bar" "baz"))
(regexp-opt-depth (regexp-opt '("foo" "bar")))
(condition-case e (match-substitute-replacement "x&y") (error e))
(with-temp-buffer
  (insert "abc")
  (goto-char (point-min))
  (re-search-forward "b")
  (match-substitute-replacement "x&y"))
(string-match "\\(a\\)" "ba")
(match-substitute-replacement "x\\1y" nil nil "ba")
(looking-at-p "a")

;; ---- misc positions ----
(with-temp-buffer
  (insert "point stuff")
  (point-marker)
  (point-min-marker)
  (point-max-marker)
  (bobp)
  (eobp)
  (bolp)
  (eolp)
  (gap-position)
  (gap-size)
  (following-char)
  (preceding-char))
