;; Deep probe: string ops, eval paths, misc builtins with valid args.
(progn
  ;; strings
  (ignore-errors (string-to-list "abc"))
  (ignore-errors (string-to-vector "abc"))
  (ignore-errors (string-make-unibyte "abc"))
  (ignore-errors (string-make-multibyte "abc"))
  (ignore-errors (string-to-multibyte "abc"))
  (ignore-errors (string-as-unibyte "abc"))
  (ignore-errors (string-as-multibyte "abc"))
  (ignore-errors (concat "a" "b" "c"))
  (ignore-errors (vconcat [1 2] [3 4]))
  (ignore-errors (append '(1) '(2) "ab"))
  (ignore-errors (split-string "a,b,c" ","))
  (ignore-errors (split-string "a  b" nil t))
  (ignore-errors (split-string "aXbXc" "X" nil "[ \t]*"))
  (ignore-errors (string-join '("a" "b") "-"))
  (ignore-errors (string-trim "  x  "))
  (ignore-errors (string-trim-left "--x"))
  (ignore-errors (string-trim-right "x--"))
  (ignore-errors (string-pad "x" 5))
  (ignore-errors (string-pad "x" 5 ?0 t))
  (ignore-errors (string-chop-newline "x\n"))
  (ignore-errors (string-clean-whitespace " a  b "))
  (ignore-errors (string-lines "a\nb\nc"))
  (ignore-errors (string-empty-p ""))
  (ignore-errors (string-blank-p "  "))
  (ignore-errors (string-equal-ignore-case "A" "a"))
  (ignore-errors (string-prefix-p "ab" "abc"))
  (ignore-errors (string-suffix-p "bc" "abc"))
  (ignore-errors (string-distance "abc" "abd"))
  (ignore-errors (string-distance "abc" "abd" t))
  (ignore-errors (string-lessp "a" "b"))
  (ignore-errors (string-greaterp "b" "a"))
  (ignore-errors (string-version-lessp "1.2" "1.10"))
  (ignore-errors (string-collate-lessp "a" "b"))
  (ignore-errors (compare-strings "abc" nil nil "abd" nil nil))
  (ignore-errors (assoc-string "a" '(("a" . 1) ("b" . 2))))
  (ignore-errors (assoc-string "A" '(("a" . 1)) t))
  (ignore-errors (substring "abcdef" 1 3))
  (ignore-errors (substring "abcdef" -2))
  (ignore-errors (substring "abcdef" 0 -1))
  (ignore-errors (substring-no-properties "ab" 0 1))
  (ignore-errors (take 2 "abcd"))
  (ignore-errors (ntake 2 '(1 2 3 4)))
  (ignore-errors (string-pixel-width "abc"))
  (ignore-errors (string-width "abc"))
  (ignore-errors (truncate-string-to-width "abcdef" 3))
  (ignore-errors (truncate-string-to-width "abcdef" 3 nil ?…))
  (ignore-errors (truncate-string-to-width "abcdef" 3 nil nil "..."))
  (ignore-errors (buffer-substring-relative-to-window (selected-window) 1 2))
  (ignore-errors (string-glyph-split "abc"))
  (ignore-errors (upcase "aBc"))
  (ignore-errors (downcase "aBc"))
  (ignore-errors (capitalize "hello world"))
  (ignore-errors (upcase-initials "hello world"))
  (ignore-errors (upcase-initials-region 1 2))
  (ignore-errors (format "%d %s %c %f %%" 42 "x" ?a 1.5))
  (ignore-errors (format "%5d|%-5d|%05d" 7 7 7))
  (ignore-errors (format "%x %o %e %g" 255 8 1.5 0.25))
  (ignore-errors (format "%S" '(a b)))
  (ignore-errors (format "%s" 1 2))
  (ignore-errors (format-message "%s" 'a))
  (ignore-errors (prin1-char ?\n))
  (ignore-errors (prin1-to-string "x\ty"))
  (ignore-errors (make-string 5 ?x))
  (ignore-errors (string-repeat "ab" 3))
  (ignore-errors (reverse "abc"))
  (ignore-errors (aref "abc" 1))
  (ignore-errors (aset (make-vector 3 0) 1 'x))
  (ignore-errors (fillarray (make-vector 2 nil) 'z))
  (ignore-errors (clear-string (copy-sequence "abc")))
  (ignore-errors (char-equal ?a ?A))
  (ignore-errors (char-equal ?a ?A t))
  (ignore-errors (multibyte-char-to-unibyte ?a))
  (ignore-errors (unibyte-char-to-multibyte ?a))
  (ignore-errors (char-to-string ?a))
  (ignore-errors (char-charset ?a))
  (ignore-errors (string-to-char "abc"))
  (ignore-errors (string-to-number "42"))
  (ignore-errors (string-to-number "ff" 16))
  (ignore-errors (string-to-number "abc"))
  (ignore-errors (number-to-string 3.14))
  (ignore-errors (number-to-string -7))
  (ignore-errors (byte-to-string 65))
  (ignore-errors (eight-bit-p ?a)))
(progn
  ;; eval paths
  (ignore-errors (eval '(+ 1 2)))
  (ignore-errors (eval '(+ 1 2) t))
  (ignore-errors (eval-buffer))
  (ignore-errors (eval-region 1 3))
  (ignore-errors (apply #'+ 1 2 '(3 4)))
  (ignore-errors (apply #'list 1 '(2 3)))
  (ignore-errors (funcall '+ 1 2 3))
  (ignore-errors (funcall-interactively 'forward-char))
  (ignore-errors (mapcar '1+ '(1 2 3)))
  (ignore-errors (mapc 'print '(1 2)))
  (ignore-errors (mapcan 'list '(1 2)))
  (ignore-errors (mapconcat 'upcase '("a" "b") ","))
  (ignore-errors (mapc-internal nil nil))
  (ignore-errors (funcall-with-delayed-message 1 "x" 'ignore))
  (ignore-errors (run-hook-with-args 'ignore 1))
  (ignore-errors (run-hooks 'ignore))
  (ignore-errors (add-hook 'test-hook 'ignore))
  (ignore-errors (remove-hook 'test-hook 'ignore))
  (ignore-errors (add-hook 'test-hook 'ignore t))
  (ignore-errors (add-hook 'test-hook 'ignore nil t))
  (ignore-errors (run-hook-wrapped 'test-hook (lambda (f) nil)))
  (ignore-errors (defvaralias 'alias-v 'target-v))
  (ignore-errors (makunbound 'alias-v))
  (ignore-errors (boundp 'target-v))
  (ignore-errors (defconst in-place t))
  (ignore-errors (special-variable-p 'lexical-binding))
  (ignore-errors (special-variable-p 'fill-column))
  (ignore-errors (makunbound 'fill-column))
  (ignore-errors (let ((x 1)) (setq-local x 2)))
  (ignore-errors (setq-default fill-column 80))
  (ignore-errors (default-value 'fill-column))
  (ignore-errors (set-default 'fill-column 72))
  (ignore-errors (default-boundp 'fill-column))
  (ignore-errors (kill-local-variable 'fill-column))
  (ignore-errors (local-variable-p 'fill-column))
  (ignore-errors (local-variable-if-set-p 'fill-column))
  (ignore-errors (buffer-local-variables))
  (ignore-errors (variable-binding-locus 'fill-column))
  (ignore-errors (indirect-variable 'fill-column))
  (ignore-errors (symbol-value 'fill-column))
  (ignore-errors (set 'sym-test 9))
  (ignore-errors (fset 'sym-f 'ignore))
  (ignore-errors (symbol-function 'car))
  (ignore-errors (fboundp 'car))
  (ignore-errors (fmakunbound 'x-tmp))
  (ignore-errors (makunbound 'x-tmp2))
  (ignore-errors (indirect-function 'car))
  (ignore-errors (indirect-function 'car t))
  (ignore-errors (subrp 'car))
  (ignore-errors (subrp (symbol-function 'car)))
  (ignore-errors (subr-arity (symbol-function 'car)))
  (ignore-errors (subr-name (symbol-function 'car)))
  (ignore-errors (apropos-internal "^car"))
  (ignore-errors (apropos-internal "^car" 'fboundp))
  (ignore-errors (symbol-plist 'car))
  (ignore-errors (put 'xx 'pp 'vv))
  (ignore-errors (get 'xx 'pp))
  (ignore-errors (function-get 'xx 'pp))
  (ignore-errors (symbol-name 'abc))
  (ignore-errors (intern "qqq"))
  (ignore-errors (intern-soft "qqq"))
  (ignore-errors (intern-soft "qqq" obarray))
  (ignore-errors (unintern "qqq"))
  (ignore-errors (unintern "qqq" obarray))
  (ignore-errors (mapatoms 'identity))
  (ignore-errors (mapatoms (lambda (s) s) obarray))
  (ignore-errors (obarray-make))
  (ignore-errors (obarray-make 13))
  (ignore-errors (obarray-size))
  (ignore-errors (obarrayp obarray)))
(progn
  ;; misc builtins
  (ignore-errors (bool-vector '(t nil t)))
  (ignore-errors (bool-vector-subsetp (bool-vector '(t nil)) (bool-vector '(t t))))
  (ignore-errors (bool-vector-count-population (bool-vector '(t nil))))
  (ignore-errors (bool-vector-not (bool-vector '(t))))
  (ignore-errors (make-bool-vector 4 t))
  (ignore-errors (bool-vector-p (make-bool-vector 2 nil)))
  (ignore-errors (eql 1 1))
  (ignore-errors (eql 1.0 1.0))
  (ignore-errors (equal-including-properties "a" "a"))
  (ignore-errors (sxhash '(1 2)))
  (ignore-errors (sxhash-eq 'x))
  (ignore-errors (sxhash-eql "x"))
  (ignore-errors (sxhash-equal "x"))
  (ignore-errors (sxhash-equal-including-properties "x"))
  (ignore-errors (lognot 5))
  (ignore-errors (lsh 1 3))
  (ignore-errors (ash 1 3))
  (ignore-errors (logand 12 10))
  (ignore-errors (logior 12 10))
  (ignore-errors (logxor 12 10))
  (ignore-errors (logcount 255))
  (ignore-errors (string-bytes "abc"))
  (ignore-errors (multibyte-string-p "abc"))
  (ignore-errors (string-to-unibyte "abc"))
  (ignore-errors (max-char))
  (ignore-errors (identity 5))
  (ignore-errors (ignore))
  (ignore-errors (gensym))
  (ignore-errors (gensym "pre"))
  (ignore-errors (random))
  (ignore-errors (random 10))
  (ignore-errors (random "seed"))
  (ignore-errors (random t))
  (ignore-errors (get-internal-run-time))
  (ignore-errors (get-internal-real-time))
  (ignore-errors (decode-time))
  (ignore-errors (decode-time nil))
  (ignore-errors (decode-time nil 'list))
  (ignore-errors (encode-time '(0 0 0 1 1 2000)))
  (ignore-errors (encode-time 0 0 0 1 1 2000))
  (ignore-errors (current-time-string))
  (ignore-errors (current-time-string nil))
  (ignore-errors (current-time-zone))
  (ignore-errors (format-time-string "%Y-%m-%d %H:%M:%S"))
  (ignore-errors (format-time-string "%A %B %e %j %z" '(23000 0)))
  (ignore-errors (time-add 1 2))
  (ignore-errors (time-subtract '(23000 0) '(0 1)))
  (ignore-errors (time-less-p '(1 0) '(2 0)))
  (ignore-errors (time-equal-p '(1 0) '(1 0)))
  (ignore-errors (time-convert '(1 2) 'list))
  (ignore-errors (time-convert '(1 2) t))
  (ignore-errors (time-convert '(1 2) 'integer))
  (ignore-errors (days-between "2024-01-01" "2024-01-05"))
  (ignore-errors (date-to-time "2024-01-01T00:00:00"))
  (ignore-errors (secure-hash 'md5 "abc"))
  (ignore-errors (secure-hash 'sha256 "abc" nil nil nil))
  (ignore-errors (secure-hash 'sha1 "abc" nil nil t))
  (ignore-errors (base64-encode-string "abc"))
  (ignore-errors (base64-decode-string "YWJj"))
  (ignore-errors (base64url-encode-string "abc"))
  (ignore-errors (base64url-decode-string "YWJj"))
  (ignore-errors (md5 "abc"))
  (ignore-errors (md5 "abc" nil nil 'utf-8 t))
  (ignore-errors (buffer-hash))
  (ignore-errors (zone-mode)))
