;; probe_editor2 — second pass over editor/primitives subrs
;; faces
(ignore-errors (facep 'default))
(ignore-errors (face-list))
(ignore-errors (face-id 'default))
(ignore-errors (face-id 'default (selected-frame)))
(ignore-errors (face-equal 'default 'default))
(ignore-errors (face-all-attributes 'default))
(ignore-errors (face-all-attributes 'default (selected-frame)))
(ignore-errors (face-attribute 'default :family))
(ignore-errors (face-attribute 'default :family (selected-frame)))
(ignore-errors (face-attribute 'default :family nil 'default))
(ignore-errors (face-attribute-relative-p :height 1.0))
(ignore-errors (face-attrs-more-relative-p '(:height 1.0) '(:height 1.0)))
(ignore-errors (internal-lisp-face-p 'default))
(ignore-errors (internal-lisp-face-empty-p 'default))
(ignore-errors (internal-lisp-face-equal-p 'default 'default))
(ignore-errors (internal-lisp-face-attribute-values :family))
(ignore-errors (internal-get-lisp-face-attribute 'default :family))
(ignore-errors (internal-set-lisp-face-attribute 'default :family "x"))
(ignore-errors (internal-merge-in-global-face 'default))
(ignore-errors (set-face-attribute 'default nil :family "x"))
(ignore-errors (merge-face-attribute :family "x" "y"))
(ignore-errors (make-face 'probe-face))
(ignore-errors (copy-face 'default 'probe-face2))
(ignore-errors (copy-face 'default 'probe-face3 (selected-frame)))
(ignore-errors (display-supports-face-attributes-p '(:underline)))
(ignore-errors (display-supports-face-attributes-p '(:underline) (selected-frame)))
(ignore-errors (clear-face-cache))
(ignore-errors (clear-face-cache t))
;; fonts
(ignore-errors (fontp 'x))
(ignore-errors (find-font 'x))
(ignore-errors (font-get 'x :family))
(ignore-errors (font-put 'x :family "y"))
(ignore-errors (font-xlfd-name 'x))
(ignore-errors (list-fonts 'x))
(ignore-errors (list-fonts 'x (selected-frame)))
(ignore-errors (list-fonts 'x nil 'default))
(ignore-errors (list-fonts 'x nil nil 3))
(ignore-errors (fontset-list))
(ignore-errors (fontset-list-all))
(ignore-errors (fontset-info "fontset"))
(ignore-errors (fontset-font "fontset" 65))
(ignore-errors (set-fontset-font "fontset" 65 'x))
(ignore-errors (new-fontset "fs" '()))
(ignore-errors (query-font 'x))
(ignore-errors (internal-char-font nil '(65)))
(ignore-errors (clear-font-cache))
(ignore-errors (x-list-fonts "pat"))
(ignore-errors (x-list-fonts "pat" 'default))
(ignore-errors (x-list-fonts "pat" nil nil 2))
;; colors
(ignore-errors (color-defined-p "red"))
(ignore-errors (color-defined-p "red" (selected-frame)))
(ignore-errors (defined-colors))
(ignore-errors (defined-colors (selected-frame)))
(ignore-errors (color-values "red"))
(ignore-errors (color-values "red" (selected-frame)))
(ignore-errors (x-color-values "red"))
(ignore-errors (xw-color-values "red"))
(ignore-errors (tty-color-values "red"))
(ignore-errors (tty-defined-colors))
(ignore-errors (tty-defined-colors (selected-frame)))
(ignore-errors (display-color-p))
(ignore-errors (display-color-p (selected-frame)))
(ignore-errors (display-graphic-p))
(ignore-errors (display-graphic-p (selected-frame)))
(ignore-errors (display-grayscale-p))
(ignore-errors (display-mouse-p))
;; frames / windows
(ignore-errors (frame-list))
(ignore-errors (visible-frame-list))
(ignore-errors (frame-live-p (selected-frame)))
(ignore-errors (frame-live-p 'x))
(ignore-errors (framep (selected-frame)))
(ignore-errors (framep 'x))
(ignore-errors (frame-visible-p (selected-frame)))
(ignore-errors (frame-char-height))
(ignore-errors (frame-char-height (selected-frame)))
(ignore-errors (frame-char-width))
(ignore-errors (frame-pixel-height))
(ignore-errors (frame-pixel-height (selected-frame)))
(ignore-errors (frame-pixel-width))
(ignore-errors (frame-edges))
(ignore-errors (frame-edges (selected-frame)))
(ignore-errors (frame-edges (selected-frame) 'inner-edges))
(ignore-errors (frame-edges (selected-frame) 'native-edges))
(ignore-errors (frame-edges (selected-frame) 'outer-edges))
(ignore-errors (frame-terminal))
(ignore-errors (frame-terminal (selected-frame)))
(ignore-errors (frame-focus-state))
(ignore-errors (frame-focus-state (selected-frame)))
(ignore-errors (frame-or-buffer-changed-p))
(ignore-errors (frame-or-buffer-changed-p 'probe-state))
(ignore-errors (iconify-frame))
(ignore-errors (iconify-frame (selected-frame)))
(ignore-errors (select-frame (selected-frame)))
(ignore-errors (select-frame (selected-frame) t))
(ignore-errors (handle-switch-frame (selected-frame)))
(ignore-errors (delete-frame))
(ignore-errors (delete-frame (selected-frame)))
(ignore-errors (delete-frame (selected-frame) t))
(ignore-errors (last-nonminibuffer-frame))
(ignore-errors (tty-top-frame))
(ignore-errors (tty-top-frame (terminal-list)))
(ignore-errors (terminal-name))
(ignore-errors (terminal-name (terminal-list)))
(ignore-errors (tty-type))
(ignore-errors (redraw-frame))
(ignore-errors (redraw-frame (selected-frame)))
(ignore-errors (redraw-display))
(ignore-errors (internal-show-cursor nil t))
(ignore-errors (internal-show-cursor-p))
(ignore-errors (windowp (selected-window)))
(ignore-errors (windowp 'x))
(ignore-errors (window-safe-p (selected-window)))
(ignore-errors (window-at 0 0))
(ignore-errors (window-at 0 0 (selected-frame)))
(ignore-errors (window-list))
(ignore-errors (window-list (selected-frame)))
(ignore-errors (window-list nil nil (minibuffer-window)))
(ignore-errors (next-window))
(ignore-errors (next-window (selected-window)))
(ignore-errors (next-window (selected-window) 'minibuf))
(ignore-errors (next-window nil nil t))
(ignore-errors (window-point))
(ignore-errors (window-point (selected-window)))
(ignore-errors (window-height))
(ignore-errors (window-height (selected-window)))
(ignore-errors (window-width))
(ignore-errors (window-width (selected-window)))
(ignore-errors (window-width (selected-window) t))
(ignore-errors (window-total-height))
(ignore-errors (window-total-height (selected-window)))
(ignore-errors (window-total-height (selected-window) 'ceiling))
(ignore-errors (window-total-width))
(ignore-errors (window-total-width (selected-window)))
(ignore-errors (window-total-width (selected-window) t))
(ignore-errors (window-text-width))
(ignore-errors (window-text-width (selected-window)))
(ignore-errors (window-text-width (selected-window) t))
(ignore-errors (window-inside-edges))
(ignore-errors (window-inside-edges (selected-window)))
(ignore-errors (window-pixel-edges))
(ignore-errors (window-pixel-edges (selected-window)))
(ignore-errors (window-left-char))
(ignore-errors (window-left-char (selected-window)))
(ignore-errors (window-top-line))
(ignore-errors (window-top-line (selected-window)))
(ignore-errors (window-use-time))
(ignore-errors (window-use-time (selected-window)))
(ignore-errors (window-new-total))
(ignore-errors (window-new-total (selected-window)))
(ignore-errors (window-new-normal))
(ignore-errors (window-new-normal (selected-window)))
(ignore-errors (window-fringes))
(ignore-errors (window-fringes (selected-window)))
(ignore-errors (window-scroll-bars))
(ignore-errors (window-scroll-bars (selected-window)))
(ignore-errors (window-state-get (selected-window)))
(ignore-errors (window-state-get (selected-window) t))
(ignore-errors (window-state-put '((minibuffer . t))))
(ignore-errors (window-state-put '((minibuffer . t)) (selected-window)))
(ignore-errors (window-state-put '((minibuffer . t)) nil t))
(ignore-errors (window-cursor-type))
(ignore-errors (window-cursor-type (selected-window)))
(ignore-errors (set-window-cursor-type (selected-window) t))
(ignore-errors (window-display-table))
(ignore-errors (window-display-table (selected-window)))
(ignore-errors (set-window-display-table (selected-window) nil))
(ignore-errors (minibuffer-window))
(ignore-errors (minibuffer-window (selected-frame)))
(ignore-errors (set-minibuffer-window (minibuffer-window)))
(ignore-errors (delete-window))
(ignore-errors (delete-window (selected-window)))
(ignore-errors (split-window))
(ignore-errors (split-window (selected-window)))
(ignore-errors (split-window (selected-window) -5))
(ignore-errors (split-window (selected-window) -5 'right))
(ignore-errors (split-window (selected-window) -5 'below))
(ignore-errors (split-window (selected-window) nil t))
(ignore-errors (current-window-configuration))
(ignore-errors (current-window-configuration (selected-frame)))
(ignore-errors (set-window-configuration (current-window-configuration)))
(ignore-errors (window-configuration-p (current-window-configuration)))
(ignore-errors (scroll-up))
(ignore-errors (scroll-up 1))
(ignore-errors (beginning-of-buffer-other-window))
(ignore-errors (forward-line-command))
(ignore-errors (what-line))
;; keymaps / input
(ignore-errors (keymapp (make-sparse-keymap)))
(ignore-errors (keymapp (current-global-map)))
(ignore-errors (make-keymap))
(ignore-errors (make-keymap "prompt"))
(ignore-errors (copy-keymap (make-sparse-keymap)))
(ignore-errors (keymap-parent (make-sparse-keymap)))
(ignore-errors (keymap-prompt (make-sparse-keymap)))
(ignore-errors (keymap-get-key "C-x"))
(ignore-errors (keymap-get-key (kbd "C-x")))
(ignore-errors (key-binding "C-f"))
(ignore-errors (key-binding (kbd "C-f")))
(ignore-errors (key-binding [?a]))
(ignore-errors (lookup-key (current-global-map) "a"))
(ignore-errors (lookup-key (current-global-map) (kbd "C-f")))
(ignore-errors (lookup-key (current-global-map) "a" t))
(ignore-errors (minor-mode-key-binding 'x))
(ignore-errors (current-minor-mode-maps))
(ignore-errors (use-global-map (current-global-map)))
(ignore-errors (use-local-map (make-sparse-keymap)))
(ignore-errors (use-local-map nil))
(ignore-errors (describe-bindings-internal))
(ignore-errors (describe-bindings-internal nil t))
(ignore-errors (kbd "C-x C-c"))
(ignore-errors (kbd "<f1>"))
(ignore-errors (read-key))
(ignore-errors (read-char))
(ignore-errors (read-event))
(ignore-errors (input-pending-p))
(ignore-errors (input-pending-p t))
(ignore-errors (discard-input))
(ignore-errors (recent-keys))
(ignore-errors (clear-this-command-keys))
(ignore-errors (clear-this-command-keys t))
(ignore-errors (y-or-n-p "Q? "))
(ignore-errors (yes-or-no-p "Q? "))
(ignore-errors (read-number "N: "))
(ignore-errors (read-number "N: " 5))
(ignore-errors (read-string "S: "))
(ignore-errors (read-buffer "B: "))
(ignore-errors (read-buffer "B: " nil t))
(ignore-errors (read-buffer "B: " "x" nil 'pred))
(ignore-errors (read-command "C: "))
(ignore-errors (read-command "C: " "x"))
(ignore-errors (internal-complete-buffer "sc" nil 1))
(ignore-errors (internal-complete-buffer "sc" nil 2))
(ignore-errors (internal-complete-buffer "sc" nil 3))
(ignore-errors (read-directory-name "D: "))
(ignore-errors (read-directory-name "D: " "/tmp"))
(ignore-errors (minibuffer-prompt-end))
;; keyboard macros
(ignore-errors (start-kbd-macro))
(ignore-errors (start-kbd-macro t))
(ignore-errors (start-kbd-macro nil t))
(ignore-errors (end-kbd-macro))
(ignore-errors (defining-kbd-macro))
(ignore-errors (defining-kbd-macro t))
(ignore-errors (cancel-kbd-macro-events))
(ignore-errors (store-kbd-macro-event ?a))
(ignore-errors (call-last-kbd-macro))
(ignore-errors (call-last-kbd-macro 1))
(ignore-errors (call-last-kbd-macro nil (lambda () nil)))
(ignore-errors (execute-kbd-macro "abc"))
(ignore-errors (execute-kbd-macro [?a ?b]))
(ignore-errors (execute-kbd-macro [?a] 2))
(ignore-errors (kmacro-exec-ring-item '(a b) 0))
(ignore-errors (kmacro-query))
(ignore-errors (key-macro-query)) ;; may be void
;; syntax
(ignore-errors (syntax-table))
(ignore-errors (standard-syntax-table))
(ignore-errors (copy-syntax-table))
(ignore-errors (copy-syntax-table (syntax-table)))
(ignore-errors (set-syntax-table (syntax-table)))
(ignore-errors (syntax-table-p (syntax-table)))
(ignore-errors (char-syntax ?a))
(ignore-errors (char-syntax ?w))
(ignore-errors (modify-syntax-entry ?a "w"))
(ignore-errors (modify-syntax-entry ?a "w" (syntax-table)))
(ignore-errors (modify-syntax-entry ?a ". (1"))
(ignore-errors (string-to-syntax "w"))
(ignore-errors (string-to-syntax ". (1"))
(ignore-errors (string-to-syntax "w p"))
(ignore-errors (syntax-class (syntax-table)))
(ignore-errors (syntax-after 1))
(ignore-errors (syntax-after))
(ignore-errors (inside-comment-p))
(ignore-errors (inside-comment-p 1))
(ignore-errors (syntax-propertize 10))
(ignore-errors (internal--syntax-propertize 1 10))
;; display tables
(ignore-errors (display-table-p (make-display-table)))
(ignore-errors (make-display-table))
(ignore-errors (standard-display-table))
(ignore-errors (display-table-slot (make-display-table) 0))
(ignore-errors (set-display-table-slot (make-display-table) 0 65))
(ignore-errors (describe-display-table (make-display-table)))
;; modes / hooks / timers
(ignore-errors (normal-mode))
(ignore-errors (normal-mode t))
(ignore-errors (set-auto-mode))
(ignore-errors (set-auto-mode t))
(ignore-errors (set-auto-mode-0))
(ignore-errors (set-buffer-major-mode (current-buffer)))
(ignore-errors (major-mode-suspend))
(ignore-errors (run-mode-hooks))
(ignore-errors (run-mode-hooks 'probe-mode-hook))
(ignore-errors (blink-cursor-mode))
(ignore-errors (blink-cursor-mode -1))
(ignore-errors (timerp nil))
(ignore-errors (run-at-time 0 nil 'ignore))
(ignore-errors (run-at-time "1 sec" 1 'ignore 'x))
(ignore-errors (run-with-timer 0 1 'ignore))
(ignore-errors (run-with-idle-timer 0 nil 'ignore))
(ignore-errors (run-with-idle-timer 1 t 'ignore 'x))
(ignore-errors (cancel-timer nil))
(ignore-errors (timer-activate nil))
(ignore-errors (timer-activate nil t))
(ignore-errors (current-idle-time))
;; file ops
(ignore-errors (file-modes "/tmp"))
(ignore-errors (file-modes "/tmp" 'integer))
(ignore-errors (set-file-modes "/tmp/remacs-nope" 420))
(ignore-errors (default-file-modes))
(ignore-errors (set-default-file-modes 511))
(ignore-errors (file-modes-symbolic-to-number "u+r" 0))
(ignore-errors (file-modes-symbolic-to-number "u+r"))
(ignore-errors (make-directory "/tmp/remacs-probe-dir"))
(ignore-errors (make-directory "/tmp/remacs-probe-dir" t))
(ignore-errors (delete-directory "/tmp/remacs-probe-dir"))
(ignore-errors (delete-directory "/tmp/remacs-probe-dir" t))
(ignore-errors (copy-file "/tmp/remacs-nope-a" "/tmp/remacs-nope-b"))
(ignore-errors (copy-file "/tmp/remacs-nope-a" "/tmp/remacs-nope-b" t))
(ignore-errors (delete-file "/tmp/remacs-nope"))
(ignore-errors (file-equal-p "/tmp" "/tmp"))
(ignore-errors (file-accessible-directory-p "/tmp"))
(ignore-errors (file-remote-p "/tmp"))
(ignore-errors (file-remote-p "/tmp" 'method))
(ignore-errors (file-local-name "/tmp/x"))
(ignore-errors (file-name-quote "abc"))
(ignore-errors (file-name-quote "abc" 'top))
(ignore-errors (file-name-unquote "abc"))
(ignore-errors (file-name-concat "/tmp" "x"))
(ignore-errors (file-name-concat "/tmp/" "x" "y"))
(ignore-errors (file-name-history))
(ignore-errors (file-system-info "/tmp"))
(ignore-errors (unhandled-file-name-directory "/tmp/x"))
(ignore-errors (insert-directory "/tmp" "-la"))
(ignore-errors (insert-directory "/tmp" nil))
(ignore-errors (insert-directory-literally "/tmp" "-la"))
(ignore-errors (verify-visited-file-modtime-princ (current-buffer)))
(ignore-errors (verify-visited-file-modtime (current-buffer)))
(ignore-errors (clear-visited-file-modtime))
(ignore-errors (visited-file-modtime))
(ignore-errors (set-visited-file-modtime))
(ignore-errors (set-visited-file-modtime 0))
(ignore-errors (hack-local-variables))
(ignore-errors (hack-local-variables t))
(ignore-errors (hack-dir-local-variables))
(ignore-errors (dir-locals-set-class-variables 'c))
(ignore-errors (find-file "/tmp/remacs-probe-visit"))
(ignore-errors (find-file-literally "/tmp/remacs-probe-visit2"))
(ignore-errors (save-buffer))
(ignore-errors (save-buffer 0))
(ignore-errors (write-region-annotate-functions))
(ignore-errors (write-region-post-annotation-function))
(ignore-errors (write-region-charset-for-write))
;; processes (stubs)
(ignore-errors (processp nil))
(ignore-errors (process-list))
(ignore-errors (get-process "x"))
(ignore-errors (process-name nil))
(ignore-errors (process-buffer nil))
(ignore-errors (process-mark nil))
(ignore-errors (process-id nil))
(ignore-errors (process-status nil))
(ignore-errors (process-exit-status nil))
(ignore-errors (process-get nil 'p))
(ignore-errors (process-put nil 'p 1))
(ignore-errors (set-process-filter nil nil))
(ignore-errors (set-process-sentinel nil nil))
(ignore-errors (process-send-string nil "x"))
(ignore-errors (process-send-eof))
(ignore-errors (process-send-eof nil))
(ignore-errors (delete-process))
(ignore-errors (delete-process nil))
(ignore-errors (accept-process-output))
(ignore-errors (accept-process-output nil 0))
(ignore-errors (accept-process-output nil 0 0))
;; overlays
(ignore-errors (overlayp nil))
(ignore-errors (overlays-at 1))
(ignore-errors (overlays-at-point))
(ignore-errors (previous-overlay-change 1))
(ignore-errors (overlay-get nil 'p))
(ignore-errors (overlay-put nil 'p 1))
(ignore-errors (overlay-start nil))
(ignore-errors (overlay-end nil))
(ignore-errors (delete-overlay nil))
;; mark/region
(ignore-errors (mark))
(ignore-errors (mark t))
(ignore-errors (mark-marker))
(ignore-errors (set-mark 1))
(ignore-errors (set-mark (make-marker)))
(ignore-errors (push-mark))
(ignore-errors (push-mark 1))
(ignore-errors (push-mark nil t))
(ignore-errors (push-mark nil nil t))
(ignore-errors (pop-mark))
(ignore-errors (activate-mark))
(ignore-errors (deactivate-mark))
(ignore-errors (region-end))
(ignore-errors (exchange-point-and-mark-inactive))
(ignore-errors (mark-defun))
(ignore-errors (mark-page))
;; kill ring
(ignore-errors (kill-new "str"))
(ignore-errors (kill-new "str" t))
(ignore-errors (current-kill 0))
(ignore-errors (current-kill 0 t))
(ignore-errors (yank))
(ignore-errors (yank 1))
(ignore-errors (kill-ring-save 1 2))
(ignore-errors (kill-line))
(ignore-errors (kill-line 1))
(ignore-errors (kill-word 1))
;; movement / text
(ignore-errors (down-list))
(ignore-errors (down-list -1))
(ignore-errors (up-list))
(ignore-errors (up-list 1))
(ignore-errors (up-list -1))
(ignore-errors (up-list 1 t))
(ignore-errors (up-list 1 nil t))
(ignore-errors (forward-list))
(ignore-errors (forward-list -1))
(ignore-errors (backward-list))
(ignore-errors (backward-list -1))
(ignore-errors (backward-up-list))
(ignore-errors (backward-up-list 1))
(ignore-errors (backward-up-list -1))
(ignore-errors (scan-lists 1 1 0))
(ignore-errors (scan-lists 1 -1 0))
(ignore-errors (scan-lists 1 0 1))
(ignore-errors (end-of-defun))
(ignore-errors (end-of-defun 1))
(ignore-errors (end-of-defun -1))
(ignore-errors (end-of-defun nil t))
(ignore-errors (join-line))
(ignore-errors (join-line 1))
(ignore-errors (indent-to 10))
(ignore-errors (indent-to 10 4))
(ignore-errors (set-goal-column))
(ignore-errors (set-goal-column t))
(ignore-errors (tab-to-tab-stop))
(ignore-errors (narrow-to-page))
(ignore-errors (narrow-to-page 1))
(ignore-errors (count-lines-page))
(ignore-errors (count-words 1 10))
(ignore-errors (count-words-region 1 10))
(ignore-errors (untabify 1 100))
(ignore-errors (upcase-region 1 5))
(ignore-errors (comment-beginning))
(ignore-errors (narrow-to-region 1 1))
;; undo
(ignore-errors (undo-start))
(ignore-errors (undo-more 1))
(ignore-errors (undo-auto-amalgamate))
(ignore-errors (undo-outer-limit-truncate 100))
(ignore-errors (activate-change-group nil))
(ignore-errors (cancel-change-group nil))
(ignore-errors (handle-change-group nil))
(ignore-errors (combine-change-calls 1 1 (lambda () nil)))
(ignore-errors (combine-after-change-calls (lambda () nil)))
;; char props
(ignore-errors (get-char-property 1 'face))
(ignore-errors (get-char-property 1 'face (current-buffer)))
(ignore-errors (get-char-property-and-overlay 1 'face))
(ignore-errors (object-intervals "s"))
(ignore-errors (propertize "s" 'face 'bold))
(ignore-errors (propertize "s" 'face 'bold 'x 1))
(ignore-errors (previous-property-change 5))
(ignore-errors (previous-property-change 5 (current-buffer)))
(ignore-errors (text-props-copy '(a 1)))
(ignore-errors (internal-set-alist 'sym 'k 'v))
;; buffer/word ops
(ignore-errors (buffer-word-at-point))
(ignore-errors (word-at-point))
(ignore-errors (current-word))
(ignore-errors (current-word t))
(ignore-errors (current-word nil t))
(ignore-errors (bobp))
(ignore-errors (eobp))
(ignore-errors (bolp))
(ignore-errors (eolp))
(ignore-errors (pos-bol))
(ignore-errors (pos-bol 5))
(ignore-errors (pos-eol))
(ignore-errors (pos-eol 5))
(ignore-errors (current-column))
(ignore-errors (char-after))
(ignore-errors (char-after 1))
(ignore-errors (char-before))
(ignore-errors (char-before 2))
(ignore-errors (following-char))
(ignore-errors (preceding-char))
(ignore-errors (max-char))
(ignore-errors (gap-size))
(ignore-errors (newline))
(ignore-errors (newline 2))
(ignore-errors (newline nil t))
(ignore-errors (insert "abc"))
(ignore-errors (insert ?a ?b))
(ignore-errors (insert 97 "x"))
(ignore-errors (insert-and-inherit "y"))
(ignore-errors (insert-before-markers "z"))
(ignore-errors (insert-before-markers-and-inherit "w"))
(ignore-errors (goto-char 1))
(ignore-errors (goto-char (point-max)))
(ignore-errors (goto-char (point-min)))
(ignore-errors (end-of-buffer))
(ignore-errors (end-of-line))
(ignore-errors (end-of-line 1))
(ignore-errors (end-of-line -1))
(ignore-errors (compare-buffer-substrings nil 1 2 nil 1 2))
(ignore-errors (compare-buffer-substrings (current-buffer) 1 2 (current-buffer) 1 2))
;; searching
(ignore-errors (looking-at "a"))
(ignore-errors (looking-at-p "a"))
(ignore-errors (looking-back "a"))
(ignore-errors (looking-back "a" 1))
(ignore-errors (looking-back "a" nil t))
(ignore-errors (search-forward-regexp "a"))
(ignore-errors (search-backward-regexp "a"))
(ignore-errors (word-search-forward "a"))
(ignore-errors (word-search-forward "a" nil t))
(ignore-errors (word-search-forward "a" nil nil 1))
(ignore-errors (word-search-backward "a"))
(ignore-errors (posix-looking-at "a"))
(ignore-errors (posix-string-match "a" "a"))
(ignore-errors (posix-string-match "a" "a" t))
(ignore-errors (string-match-p "a" "a"))
(ignore-errors (match-string-no-properties 0))
(ignore-errors (match-string-no-properties 0 "abc"))
;; lock / visited-file
(ignore-errors (file-locked-p "/tmp/x"))
(ignore-errors (lock-buffer))
(ignore-errors (lock-buffer "/tmp/x"))
(ignore-errors (unlock-buffer))
(ignore-errors (ask-user-about-lock "/tmp/x" "u"))
;; misc
(ignore-errors (negative-argument))
(ignore-errors (universal-argument))
(ignore-errors (suspend-emacs))
(ignore-errors (unix-sync))
(ignore-errors (menu-bar-menu-at-x-y 0 0))
(ignore-errors (menu-bar-menu-at-x-y 0 0 (selected-frame)))
(ignore-errors (menu-or-popup-active-p))
(ignore-errors (x-menu-bar-open-internal))
(ignore-errors (x-popup-menu t 'x))
(ignore-errors (x-popup-dialog t 'x))
(ignore-errors (current-kill 0))
(ignore-errors (visible-p))
(ignore-errors (frame-visible-p (selected-frame)))
(ignore-errors (beginning-of-buffer-other-window 1))
(ignore-errors (Snarf-documentation "x"))
(ignore-errors (dump-glyph-matrix))
(ignore-errors (dump-glyph-matrix 1))
(ignore-errors (open-font 'x))
(ignore-errors (open-font 'x -1))
(ignore-errors (open-font 'x nil (selected-frame)))
(ignore-errors (close-font 'x))
(ignore-errors (get-pos-property 1 'face))
