;; probe_editor4 — deep coverage of editor/mod.rs: help/doc, process,
;; file ops, overlays, indent, keymaps, frames, sexp scanning

;; ---- doc/help paths ----
(substitute-command-keys "\\[forward-char]")
(substitute-command-keys "press \\[next-line] or \\=x")
(substitute-command-keys "\\<global-map>\\[previous-line]")
(condition-case e (documentation 'forward-char) (error e))
(condition-case e (documentation-property 'x 'y) (error e))
(condition-case e (describe-bindings) (error e))
(condition-case e (key-binding "\C-f") (error e))
(condition-case e (key-binding [?\C-f]) (error e))
(condition-case e (key-binding "\M-x" t) (error e))
(condition-case e (local-key-binding "\C-f") (error e))
(condition-case e (global-key-binding "\C-f") (error e))
(condition-case e (minor-mode-key-binding "\C-f") (error e))
(condition-case e (lookup-key global-map "\C-f") (error e))
(condition-case e (lookup-key global-map "\C-x") (error e))
(where-is-internal 'forward-char)
(where-is-internal 'next-line nil t)
(where-is-internal 'self-insert-command)
(command-remapping 'kill-region)
(condition-case e (describe-key "\C-f") (error e))
(apropos-internal "buffer")
(apropos-internal "char" 'commandp)

;; ---- keymap ops ----
(let ((m (make-sparse-keymap)))
  (define-key m "a" 'ignore)
  (define-key m "bc" 'next-line)
  (lookup-key m "a")
  (lookup-key m "b")
  (keymap-parent m)
  (set-keymap-parent m global-map)
  (keymap-parent m)
  (keymapp m)
  (map-keymap (lambda (k v) (list k v)) m)
  (accessible-keymaps m)
  (copy-keymap m)
  (current-global-map)
  (current-local-map)
  (use-local-map m)
  (current-local-map)
  (use-local-map nil))
(make-keymap)
(define-prefix-command 'probe-prefix)
(current-active-maps)
(condition-case e (active-minor-mode-keymaps) (error e))

;; ---- process ----
(call-process "echo" nil nil nil "hi")
(with-temp-buffer
  (call-process "echo" nil t nil "from-process")
  (call-process-region (point-min) (point-max) "cat" t t nil)
  (call-process-region (point-min) (point-max) "cat" nil nil nil))
(condition-case e (call-process "nonexistent-cmd-xyz" nil nil nil) (error e))
(condition-case e (shell-command "echo hi") (error e))

;; ---- file ops ----
(directory-files "/tmp")
(directory-files "/tmp" t)
(directory-files "/tmp" nil "^a")
(directory-files-and-attributes "/tmp")
(file-attributes "/tmp")
(file-exists-p "/tmp")
(file-directory-p "/tmp")
(file-regular-p "/tmp/passwd-nonexistent")
(file-readable-p "/tmp")
(file-writable-p "/tmp")
(file-executable-p "/bin/sh")
(file-symlink-p "/tmp")
(file-name-absolute-p "/tmp/x")
(file-name-absolute-p "rel")
(expand-file-name "x" "/tmp")
(expand-file-name "~" "/")
(expand-file-name "./x" "/tmp")
(file-name-directory "/tmp/a/b")
(file-name-nondirectory "/tmp/a/b")
(file-name-sans-extension "/tmp/a.txt")
(file-name-extension "/tmp/a.txt")
(file-name-extension "/tmp/a")
(file-relative-name "/tmp/a/b" "/tmp")
(file-name-concat "/tmp" "a" "b")
(abbreviate-file-name "/tmp/x")
(substitute-in-file-name "/tmp/$HOME/x")
(file-newer-than-file-p "/tmp" "/etc")
(file-in-directory-p "/tmp/a/b" "/tmp")
(file-in-directory-p "/etc/x" "/tmp")
(file-local-copy "/etc/hosts")
(file-modes "/tmp")
(file-readable-p "/etc/hosts")
(default-file-modes)
(condition-case e (file-locked-p "/tmp/x") (error e))
(condition-case e (file-name-as-directory "/tmp") (error e))
(make-temp-name "/tmp/probe")
(condition-case e (file-name-all-completions "a" "/tmp") (error e))
(condition-case e (file-name-completion "a" "/tmp") (error e))
(condition-case e (delete-file "/tmp/nonexistent-probe") (error e))
(let ((tmp (make-temp-name "/tmp/remacs-probe")))
  (with-temp-file tmp
    (insert "file body\nline2\n"))
  (insert-file-contents tmp)
  (insert-file-contents-literally tmp)
  (find-file-noselect tmp)
  (verify-visited-file-modtime (get-file-buffer tmp))
  (clear-visited-file-modtime)
  (condition-case e (write-region 1 3 tmp) (error e))
  (delete-file tmp))
(condition-case e (insert-file-contents "/nonexistent-xyz") (error e))
(condition-case e (find-file-noselect "/nonexistent-dir-xyz/f") (error e))

;; ---- overlays ----
(with-temp-buffer
  (insert "overlay text here")
  (let ((o (make-overlay 2 6)))
    (overlayp o)
    (overlay-start o)
    (overlay-end o)
    (overlay-buffer o)
    (overlay-put o 'face 'bold)
    (overlay-get o 'face)
    (overlay-properties o)
    (move-overlay o 3 8)
    (overlays-at 4)
    (overlays-in 1 10)
    (overlay-start o)
    (delete-overlay o)
    (overlay-start o)
    (make-overlay 1 3 (current-buffer) t t)
    (make-overlay 1 3 (current-buffer) nil nil)
    (remove-overlays)
    (remove-overlays 1 5)
    (condition-case e (next-overlay-change 1) (error e))
    (condition-case e (previous-overlay-change 5) (error e))))

;; ---- indent ----
(with-temp-buffer
  (insert "aa\nbb\ncc\n")
  (indent-rigidly (point-min) (point-max) 2)
  (indent-rigidly (point-min) (point-max) -1)
  (goto-char (point-min))
  (insert "\t\tx\ty\tz")
  (untabify (point-min) (point-max))
  (tabify (point-min) (point-max))
  (indent-to 8)
  (indent-to-column 4)
  (current-indentation)
  (condition-case e (indent-region (point-min) (point-max)) (error e))
  (condition-case e (indent-line-to 4) (error e))
  (condition-case e (indent-for-tab-command) (error e))
  (move-to-left-margin)
  (delete-to-left-margin)
  (condition-case e (center-line) (error e))
  (condition-case e (center-region (point-min) (point-max)) (error e)))

;; ---- sexp/defun scanning ----
(with-temp-buffer
  (insert "(defun f (x)\n  (let ((y 1))\n    (+ x y)))\n\n(defun g () 2)\n")
  (goto-char (point-min))
  (parse-partial-sexp 1 20)
  (parse-partial-sexp 1 20 0 nil (syntax-table))
  (beginning-of-defun)
  (end-of-defun)
  (condition-case e (forward-list) (error e))
  (condition-case e (backward-list) (error e))
  (condition-case e (up-list) (error e))
  (condition-case e (backward-up-list) (error e))
  (condition-case e (down-list) (error e))
  (scan-lists 1 1 0)
  (scan-lists 1 -1 0)
  (scan-sexps 1 1)
  (condition-case e (scan-sexps 1 -1) (error e)))

;; ---- windows/frames ----
(frame-parameters)
(frame-parameter nil 'width)
(frame-parameter nil 'name)
(modify-frame-parameters nil '((height . 30)))
(frame-height)
(frame-width)
(frame-char-height)
(frame-char-width)
(selected-window)
(selected-frame)
(window-list)
(windowp (selected-window))
(window-buffer)
(window-start)
(window-end)
(window-point)
(window-body-height)
(window-body-width)
(window-height)
(window-width)
(window-hscroll)
(set-window-hscroll (selected-window) 0)
(window-left)
(window-right)
(pos-visible-in-window-p)
(condition-case e (window-edges) (error e))
(condition-case e (window-inside-edges) (error e))
(condition-case e (window-pixel-edges) (error e))
(condition-case e (window-absolute-pixel-edges) (error e))
(window-minibuffer-p)
(minibuffer-window)
(condition-case e (window-dedicated-p) (error e))
(condition-case e (window-parameter nil 'name) (error e))
(condition-case e (set-window-parameter nil 'name 'v) (error e))
(condition-case e (window-parameters) (error e))
(condition-case e (window-display-table) (error e))
(condition-case e (window-margins) (error e))
(condition-case e (window-fringes) (error e))
(condition-case e (window-scroll-bars) (error e))
(condition-case e (window-vscroll) (error e))
(condition-case e (set-window-vscroll nil 0) (error e))
(condition-case e (window-new-normal) (error e))
(condition-case e (window-normal-size) (error e))
(condition-case e (window-valid-p (selected-window)) (error e))
(condition-case e (window-live-p (selected-window)) (error e))
(condition-case e (next-window) (error e))
(condition-case e (previous-window) (error e))
(condition-case e (get-buffer-window) (error e))
(condition-case e (get-lru-window) (error e))
(condition-case e (get-largest-window) (error e))
(condition-case e (frame-first-window) (error e))
(condition-case e (window-frame) (error e))
(condition-case e (frame-root-window) (error e))
(condition-case e (minibuffer-selected-window) (error e))
(condition-case e (walk-windows (lambda (w) w)) (error e))
(condition-case e (frame-list) (error e))
(condition-case e (visible-frame-list) (error e))
(condition-case e (frame-visible-p (selected-frame)) (error e))
(condition-case e (framep (selected-frame)) (error e))
(condition-case e (window-frame (selected-window)) (error e))
(condition-case e (select-frame (selected-frame)) (error e))
(condition-case e (frame-selected-window) (error e))
(condition-case e (set-frame-height nil 30) (error e))
(condition-case e (set-frame-width nil 90) (error e))
(condition-case e (set-frame-position nil 0 0) (error e))
(condition-case e (frame-position nil) (error e))
(condition-case e (raise-frame) (error e))
(condition-case e (lower-frame) (error e))
(condition-case e (iconify-frame) (error e))
(condition-case e (make-frame-visible) (error e))
(condition-case e (make-frame-invisible) (error e))
(condition-case e (redraw-frame) (error e))
(condition-case e (frame-focus-state) (error e))
(condition-case e (terminal-list) (error e))
(condition-case e (terminal-name) (error e))
(condition-case e (terminal-parameter nil 'x) (error e))
(condition-case e (suspend-frame) (error e))

;; ---- scrolling ----
(with-temp-buffer
  (insert (mapconcat 'number-to-string (number-sequence 1 200) "\n"))
  (goto-char (point-min))
  (condition-case e (scroll-up 5) (error e))
  (condition-case e (scroll-down 3) (error e))
  (condition-case e (scroll-up-command) (error e))
  (condition-case e (scroll-down-command) (error e))
  (condition-case e (scroll-other-window) (error e))
  (condition-case e (scroll-left) (error e))
  (condition-case e (scroll-right) (error e))
  (condition-case e (recenter) (error e))
  (condition-case e (recenter 0) (error e))
  (condition-case e (move-to-window-line 0) (error e))
  (condition-case e (beginning-of-buffer) (error e))
  (condition-case e (end-of-buffer) (error e))
  (condition-case e (scroll-up-line) (error e))
  (condition-case e (scroll-down-line) (error e)))

;; ---- completion ----
(completing-read "P: " '("aa" "ab" "ba") nil t)
(condition-case e (completing-read "P: " '((("a" . 1)) ("b")) nil nil "a") (error e))
(condition-case e (try-completion "a" '("aa" "ab" "ba")) (error e))
(condition-case e (all-completions "a" '("aa" "ab" "ba")) (error e))
(condition-case e (test-completion "aa" '("aa" "ab")) (error e))
(condition-case e (completion-boundaries "a/b" '(a b) "/" "b") (error e))
(condition-case e (completion-metadata "s" '((a)) nil) (error e))
(condition-case e (minibuffer-completion-contents) (error e))
(condition-case e (minibuffer-prompt) (error e))
(condition-case e (completion-table-with-cache 'ignore) (error e))
(condition-case e (completion-table-dynamic 'ignore) (error e))
(condition-case e (completion-table-case-fold 'ignore) (error e))
(condition-case e (completion-in-region 1 2 '("a")) (error e))
(condition-case e (read-string "P: ") (error e))
(condition-case e (read-from-minibuffer "P: ") (error e))
(condition-case e (read-regexp "P: ") (error e))
(condition-case e (read-number "P: ") (error e))
(condition-case e (read-passwd "P: ") (error e))
(condition-case e (read-command "P: ") (error e))
(condition-case e (read-buffer "P: ") (error e))
(condition-case e (read-file-name "P: ") (error e))
(condition-case e (read-directory-name "P: ") (error e))
(condition-case e (read-variable "P: ") (error e))
(condition-case e (y-or-n-p "Q? ") (error e))
(condition-case e (yes-or-no-p "Q? ") (error e))

;; ---- misc editor ----
(condition-case e (command-execute 'forward-char) (error e))
(condition-case e (execute-kbd-macro "\C-f") (error e))
(condition-case e (call-interactively 'forward-char) (error e))
(prefix-numeric-value 4)
(prefix-numeric-value '-)
(prefix-numeric-value nil)
(condition-case e (universal-argument) (error e))
(condition-case e (digit-argument 4) (error e))
(condition-case e (negative-argument 2) (error e))
(condition-case e (beginning-of-buffer-other-window) (error e))
(condition-case e (set-transient-map (make-sparse-keymap)) (error e))
(condition-case e (set-transient-map (make-sparse-keymap) t) (error e))
(condition-case e (clear-transient-map) (error e))
(condition-case e (internal-describe-map-value 'forward-char) (error e))
(condition-case e (where-is 'forward-char) (error e))
(condition-case e (this-command-keys) (error e))
(condition-case e (this-command-keys-vector) (error e))
(condition-case e (recent-keys) (error e))
(condition-case e (current-input-mode) (error e))
(condition-case e (set-input-mode nil nil nil nil) (error e))
(condition-case e (open-dribble-file "/tmp/probe-dribble") (error e))
(condition-case e (open-dribble-file nil) (error e))
(condition-case e (discard-input) (error e))
(condition-case e (input-pending-p) (error e))
(condition-case e (last-input-event) (error e))
(condition-case e (last-nonminibuffer-frame) (error e))
(condition-case e (listify-key-sequence "ab") (error e))
(condition-case e (event-convert-list '(control ?a)) (error e))
(condition-case e (event-basic-type 'C-f) (error e))
(condition-case e (key-description [?\C-f]) (error e))
(condition-case e (single-key-description ?\C-f) (error e))
(condition-case e (single-key-description 'f10) (error e))
(condition-case e (text-char-description ?\C-a) (error e))
(condition-case e (keymap-prompt global-map) (error e))
(condition-case e (key-binding "\C-x\C-f" nil nil) (error e))
(condition-case e (binding-for-key 'forward-char) (error e))
(condition-case e (command-name 'forward-char) (error e))
(condition-case e (edmacro-parse-keys "C-f") (error e))
(condition-case e (format-kbd-macro "C-f") (error e))
(condition-case e (start-kbd-macro nil) (error e))
(condition-case e (end-kbd-macro) (error e))
(condition-case e (cancel-kbd-macro-events) (error e))
(condition-case e (kmacro-keyboard-macro) (error e))
(condition-case e (defining-kbd-macro t) (error e))
(condition-case e (store-kbd-macro-event ?a) (error e))
(condition-case e (catch 'exit-recursive-edit (exit-recursive-edit)) (error e))
(condition-case e (command-error-default-function nil nil nil) (error e))
(condition-case e (emacs-version) (error e))
(condition-case e (emacs-pid) (error e))
(condition-case e (emacs-repository-version) (error e))
(condition-case e (emacs-build-time) (error e))
(condition-case e (internal--top-level-message) (error e))
(condition-case e (dump-emacs-portable "x") (error e))
(condition-case e (dump-emacs "x" "y") (error e))
(condition-case e (recent-save-hooks) (error e))
