;; Missing-subr batch: new primitives, handler-bind, watchers.
;; Differential-verified against GNU Emacs 31.1.
(progn
  ;; trivial builtins
  (princ (list 'a (subr-primitive-p (symbol-function 'car))
               (subr-type (symbol-function 'car))
               (condition-case e (subr-type 5) (error (car e)))
               (subr-native-lambda-list (symbol-function 'car))
               (syntax-class-to-char 2) (syntax-class-to-char 15)
               (syntax-class-to-char 0)
               (condition-case e (syntax-class-to-char 99) (error (car e)))
               (matching-paren ?\() (matching-paren ?\)) (matching-paren ?a)
               (ngettext "x" "xs" 1) (ngettext "x" "xs" 3)
               (condition-case e (ngettext 'a 'b 1) (error (car e)))))
  (terpri)
  ;; access-file
  (let ((tf (make-temp-file "subrs-probe")))
    (princ (list 'b (access-file tf "ok %s")
                 (condition-case e (access-file "/nonexistent-dir-zzz/f" "msg %s")
                   (error (car e)))))
    (delete-file tf))
  (terpri)
  ;; single-char property changes with PROP/OBJECT/LIMIT
  (with-temp-buffer
    (insert "abcdef")
    (put-text-property 2 4 'face 'bold)
    (princ (list 'c (next-single-char-property-change 1 'face)
                 (next-single-char-property-change 2 'face)
                 (next-single-char-property-change 4 'face nil 6)
                 (next-single-char-property-change 6 'face)
                 (previous-single-char-property-change 5 'face)
                 (previous-single-char-property-change 4 'face)
                 (previous-single-char-property-change 2 'face)
                 (next-single-char-property-change 0 'face "abcd")
                 (previous-single-char-property-change 3 'face "abcd"))))
  (terpri)
  ;; base64url + get-byte
  (princ (list 'd (base64url-encode-string "a?b?") (base64url-encode-string "a?b?" t)
               (get-byte 0 "ABC") (get-byte 2 "ABC")
               (condition-case e (get-byte 0 "é") (error (cadr e)))))
  (terpri)
  ;; variable watchers: set/let/unlet/makunbound
  (let ((log nil))
    (add-variable-watcher 'vw-t1 (lambda (s n o w) (push (list s n o) log)))
    (setq vw-t1 1)
    (let ((vw-t1 2)) t)
    (makunbound 'vw-t1)
    (princ (list 'e (nreverse log) (length (get-variable-watchers 'vw-t1))))
    (remove-variable-watcher 'vw-t1 (lambda (s n o w) t))
    (terpri))
  ;; find-file-name-handler + misc
  (princ (list 'f (find-file-name-handler "/tmp/x" 'insert-file-contents)
               (combine-after-change-execute)
               (with-temp-buffer (make-overlay 1 1) (delete-all-overlays) t)
               (current-message)))
  (terpri)
  ;; replace-region-contents
  (with-temp-buffer
    (insert "hello world")
    (replace-region-contents 1 6 "goodbye ")
    (princ (list 'g (buffer-string))))
  (terpri)
  ;; bury-buffer-internal / make-indirect-buffer
  (princ (list 'h2 (with-temp-buffer
                     (bury-buffer-internal (current-buffer))
                     t)
               (bufferp (condition-case e
                            (make-indirect-buffer (current-buffer) "ind-probe")
                          (error e)))))
  (terpri)
  ;; handler-bind: caught signals do not fire handlers
  (let ((log nil))
    (handler-bind ((error (lambda (c) (push 'ran log))))
      (condition-case e (signal 'error '(x)) (error nil)))
    (princ (list 'h log)))
  (terpri)
  ;; handler ordering within one form: argument order, innermost first
  (let ((log nil))
    (catch 'done
      (handler-bind ((error (lambda (c) (push 'first log)))
                     (error (lambda (c) (push 'second log) (throw 'done 'esc))))
        (signal 'error '(boom))))
    (princ (list 'ord (nreverse log))))
  (terpri)
  ;; signal-hook-function sees caught signals; nested let so the hook
  ;; closure captures `log' (parallel `let' inits can't see own bindings).
  (let ((log nil))
    (let ((signal-hook-function (lambda (s d) (push (list 'hk s) log))))
      (condition-case e (signal 'arith-error '(z)) (error (push 'cc log))))
    (princ (list 'hook (nreverse log))))
  (terpri)
  ;; handler receives (sym . data); condition-list membership
  (let ((got nil))
    (catch 'out
      (handler-bind (((arith-error file-error)
                      (lambda (c) (setq got c) (throw 'out 'done))))
        (signal 'arith-error '(d1 d2))))
    (princ (list 'cond got)))
  (terpri)
  ;; macroexpand + throw-escape
  (princ (list 'i (macroexpand '(handler-bind ((error h)) b))))
  (terpri)
  (princ (list 'j (catch 'out
                    (handler-bind ((error (lambda (c) (throw 'out 'inner))))
                      (signal 'error '(e))))))
  (terpri)
  ;; condition-case-unless-debug
  (princ (list 'k (condition-case-unless-debug v (error "x") (error 'caught))))
  (terpri)
  ;; ignore-errors must suppress handler-bind handlers
  (let ((log nil))
    (handler-bind ((error (lambda (c) (push 'ran log))))
      (ignore-errors (signal 'error '(x))))
    (princ (list 'ie log)))
  (terpri)
  ;; autoload-do-load returns nil on non-autoload
  (princ (list 'l (autoload-do-load (symbol-function 'car) 'car)))
  (terpri)
  ;; load honors the lexical-binding cookie (nil cookie -> dynamic file)
  (let ((tf (make-temp-file "subrs-load" nil ".el")))
    (with-temp-file tf
      (insert "(defvar probe-dyn t) (let ((probe-dyn 'lex)) (setq probe-let-seen probe-dyn))"))
    (load tf)
    (delete-file tf))
  (princ (list 'load-dyn (boundp 'probe-dyn) (boundp 'probe-let-seen)))
  (terpri)
  (let ((tf (make-temp-file "subrs-load-lex" nil ".el")))
    (with-temp-file tf
      (insert ";; -*- lexical-binding: t -*-\n(defvar probe-lex t)"))
    (load tf)
    (delete-file tf))
  (princ (list 'load-lex (boundp 'probe-lex)))
  (terpri)
  (princ (list 'load-missing
               (condition-case e (load "/nonexistent-subrs-zzz.el")
                 (file-error (car e)))))
  (terpri)
  ;; make-indirect-buffer: API surface (name uniqueness, base link)
  (let ((b (get-buffer-create "subrs-base")))
    (with-current-buffer b (insert "HELLO"))
    (let ((ib (make-indirect-buffer b "subrs-ind" t)))
      (princ (list 'ind (bufferp ib) (buffer-name ib)
                   (eq (buffer-base-buffer ib) b)
                   (buffer-base-buffer b)
                   (with-current-buffer ib (buffer-string)))))
    (princ (list 'ind-dup
                 (condition-case e (make-indirect-buffer b "subrs-ind")
                   (error (car e)))))
    (kill-buffer "subrs-ind")
    (terpri))
  ;; translate-region-internal + buffer-line-statistics
  (with-temp-buffer
    (insert "abc")
    (translate-region-internal 1 4 (make-string 128 ?.))
    (princ (list 'tri (buffer-string))))
  (terpri)
  (let ((tab (make-string 128 0)))
    (aset tab ?a ?X) (aset tab ?b ?Y)
    (with-temp-buffer
      (insert "abc")
      (translate-region-internal 1 4 tab)
      (princ (list 'tri2 (buffer-string)))))
  (terpri)
  (princ (list 'tri3 (condition-case e
                         (with-temp-buffer (translate-region-internal 1 1 5))
                       (error (car e)))))
  (terpri)
  (princ (list 'bls (with-temp-buffer (buffer-line-statistics))
               (with-temp-buffer (insert "a\n\n") (buffer-line-statistics))
               (with-temp-buffer (insert "a\nbb\nccc") (buffer-line-statistics))))
  (terpri)
  ;; threads: cooperative model — zombie stays live until joined
  (let ((th (make-thread (lambda () (+ 1 2)) "worker")))
    (princ (list 'mt (threadp th) (thread-name th) (thread-live-p th)
                 (eq th (current-thread)))))
  (terpri)
  (let ((th (make-thread (lambda () (+ 1 2)) "worker")))
    (princ (list 'join (thread-join th) (thread-live-p th))))
  (terpri)
  (let ((th (make-thread (lambda () (signal 'arith-error '(x))) "bad")))
    (princ (list 'terr (thread-live-p th)
                 (condition-case e (thread-join th) (error (car e)))
                 (thread-last-error))))
  (terpri)
  (princ (list 'at (length (all-threads)) (threadp (car (all-threads)))
               (threadp 'x) (type-of (current-thread))))
  (terpri)
  nil)

;; string predicates: GNU has string-equal/string-lessp/string-greaterp as
;; primitives accepting strings-or-symbols; string=/</> are Lisp aliases.
(let ((probe '(t)))
  (dolist (f '(string-equal string-lessp string-greaterp
               string= string< string> string<= string>=
               string-empty-p string-blank-p string-prefix-p string-suffix-p))
    (princ (list 'fp f (fboundp f) (subr-primitive-p (symbol-function f)))))
  (terpri))
(let ((probe '(t)))
  (mapc (lambda (x) (condition-case e (princ (list 'sp (car x) (eval x)))
                                    (error (princ (list 'sp (car x) (car e)))))
                    (terpri))
        '((string-equal "a" "a") (string-equal 'a "a") (string-equal nil "")
          (string-lessp "a" "b") (string-lessp 'a "b") (string-lessp "a" nil)
          (string-greaterp "b" "a") (string-greaterp 'b 'a)
          (string= "a" "a") (string< "a" "b") (string> "b" "a")
          (string-empty-p "") (string-empty-p "a") (string-empty-p nil)
          (string-blank-p " ") (string-blank-p "x")
          (string-prefix-p "he" "hello") (string-prefix-p "AB" "ab" t)
          (string-suffix-p "lo" "hello") (string-suffix-p "LO" "hello" t))))

;; sync objects, case tables, toplevel values, file internals
(let ((probe '(t)))
  (let ((m (make-mutex "mx")))
    (princ (list 'mx (mutexp m) (mutex-name m) (type-of m)
                 (mutex-lock m) (mutex-unlock m)
                 (condition-case e (mutex-unlock m) (error (car e)))
                 (condition-case e (mutex-lock 'x) (error (car e))))))
  (terpri)
  (let* ((m (make-mutex)) (c (make-condition-variable m "cv")))
    (princ (list 'cv (condition-variable-p c) (condition-name c)
                 (eq m (condition-mutex c)) (type-of c)
                 (condition-case e (condition-wait c) (error (car e)))
                 (condition-case e (condition-notify c) (error (car e))))))
  (terpri)
  (princ (list 'fin (type-of (make-finalizer #'ignore))))
  (terpri)
  (setq probe-var 42)
  (princ (list 'tv (default-toplevel-value 'probe-var)
               (condition-case e (buffer-local-toplevel-value 'probe-var)
                 (error (car e)))))
  (terpri)
  (let ((probe-var 99))
    (princ (list 'tvl (default-toplevel-value 'probe-var)
                 (condition-case e (buffer-local-toplevel-value 'probe-var)
                   (error (car e))))))
  (terpri)
  (make-local-variable 'probe-var)
  (setq probe-var 7)
  (set-buffer-local-toplevel-value 'probe-var 33)
  (princ (list 'tvs (buffer-local-toplevel-value 'probe-var) probe-var))
  (terpri)
  (princ (list 'ct (case-table-p (current-case-table))
               (eq (current-case-table) (standard-case-table))
               (case-table-p (make-char-table 'case-table nil))
               (case-table-p (make-char-table 'syntax-table nil))))
  (terpri)
  (princ (list 'misc (byte-to-string 65) (num-processors)
               (text-quoting-style) (internal-subr-documentation 'car)
               (length (get-load-suffixes)) (length (signal-names))
               (user-ptrp nil)))
  (terpri)
  (princ (list 'files
               (condition-case e (delete-file-internal "/nope-xyz") (error (car e)))
               (condition-case e (delete-directory-internal "/nope-xyz") (error (car e)))
               (locate-file-internal "sh" '("/bin"))
               (locate-file-internal "nope-xyz" exec-path)))
  (terpri)
  (princ (list 'rec (make-record 'foo 2 nil) (recordp (make-record 'foo 2 0))))
  (terpri)
  (princ (list 'scb (subr-primitive-p (symbol-function 'save-current-buffer))))
  (terpri)
  (princ (list 'dq (subr-primitive-p (symbol-function 'defvar-1))
               (progn (defvar-1 'probe-dv1 5 "doc") probe-var))
           )
  (terpri)
  nil)

;; misc stubs: group/ccl/redisplay internals
(let ((probe '(t)))
  (princ (list 'gn (stringp (group-name 0)) (group-name 999999)))
  (terpri)
  (princ (list 'wfu (waiting-for-user-input-p) (bitmap-spec-p 5)
               (get-truename-buffer "x")
               (unencodable-char-position 0 3 'utf-8 1 "abc")))
  (terpri)
  (princ (list 'comp (condition-case e (compose-region-internal 1 2)
                       (error (car e)))
               (compose-string-internal "ab" 0 1)
               (condition-case e (compose-string-internal "ab" 0 9)
                 (error (car e)))))
  (terpri)
  (princ (list 'ccl
               (condition-case e (register-ccl-program 'x "s") (error e))
               (condition-case e (register-ccl-program 'x [1]) (error (car e)))
               (register-ccl-program 'x [0 0 0])
               (register-ccl-program 'x [0 0 0 0])
               (ccl-program-p 'x) (ccl-program-p 'y)
               (condition-case e (ccl-execute 'y [0]) (error (car e)))
               (register-code-conversion-map 'm [0])
               (condition-case e (register-code-conversion-map 'm2 '((a . b)))
                 (error e))))
  (terpri)
  (princ (list 'rds (set-buffer-redisplay (current-buffer) 1 1 nil)
               (delete-other-windows-internal)))
  (terpri)
  nil)

;; zlib, find-buffer, tty stubs
(let ((probe '(t)))
  (princ (list 'zl (zlib-available-p)))
  (terpri)
  (with-temp-buffer
    (insert "abc")
    (princ (condition-case e (zlib-decompress-region 1 4) (error (car e)))))
  (terpri)
  (with-temp-buffer
    (setq-local buffer-file-coding-system 'utf-8)
    (princ (list 'fb (bufferp (find-buffer 'buffer-file-coding-system 'utf-8))
                 (find-buffer 'buffer-file-coding-system 'nope)
                 (condition-case e (find-buffer 'buffer-name "x")
                   (error (car e))))))
  (terpri)
  (with-temp-buffer
    (insert-byte 65 3)
    (princ (list 'ib (buffer-string)
                 (condition-case e (insert-byte 300 1) (error (car e))))))
  (terpri)
  (princ (list 'tty (set-quit-char 7)
               (set-binary-mode 'stdin t)
               (condition-case e (set-binary-mode 'foo t) (error (car e)))
               (condition-case e (set-output-flow-control nil t) (error (car e)))
               (newline-cache-check) (tab-bar-height)
               (condition-case e (insert-special-event 'x) (error (car e)))
               (buffer-text-pixel-size) (format-mode-line "abc")
               (debugger-trap)))
  (terpri)
  nil)

;; category tables
(let ((probe '(t)))
  (princ (list 'mk (category-table-p (make-category-table))
               (char-table-subtype (make-category-table))
               (category-table-p (standard-category-table))
               (eq (category-table) (standard-category-table))))
  (terpri)
  (princ (list 'std-sets (category-set-mnemonics (char-category-set ?a))
               (category-set-mnemonics (char-category-set ?5))
               (category-set-mnemonics (char-category-set 32))
               (category-set-mnemonics (char-category-set ?\\))))
  (terpri)
  (let ((t1 (make-category-table)))
    (princ (list 'def (define-category ?x "docx" t1)
                 (category-docstring ?x t1)
                 (condition-case e (define-category ?x "again" t1)
                   (error (car e)))
                 (condition-case e (define-category 5 "d" t1)
                   (error (car e)))
                 (condition-case e (define-category 999 "d" t1)
                   (error (car e)))))
    (terpri)
    (princ (list 'mod (modify-category-entry ?a ?x t1)
                 (modify-category-entry '(?A . ?C) ?x t1)
                 (condition-case e
                     (category-set-mnemonics (char-table-range t1 97))
                   (error (car e)))))
    (terpri)
    (princ (list 'mod2 (condition-case e
                           (category-set-mnemonics (char-table-range t1 ?B))
                         (error (car e)))
                 (condition-case e (modify-category-entry ?a ?y t1)
                   (error (cadr e)))
                 (get-unused-category t1)
                 (category-docstring ?y t1)))
    (terpri)
    (let ((c (copy-category-table t1)))
      (princ (list 'copy (category-table-p c)
                   (not (eq c t1))
                   (category-docstring ?x c)
                   (category-set-mnemonics (char-table-range c ?a))))
      (terpri)))
  (princ (list 'mcs (bool-vector-p (make-category-set ""))
               (category-set-mnemonics (make-category-set "xy"))
               (condition-case e (category-set-mnemonics 5) (error (car e)))
               (condition-case e (category-set-mnemonics nil) (error (car e)))))
  (terpri)
  nil)

;; Platform/internals batch: availability predicates, input-mode,
;; charset/unicode internals, labeled narrowing, hash/obarray
;; introspection, buffer completion. Differential-checked vs GNU 31.1.
(progn
  (princ (list 'avail (gnutls-available-p) (sqlite-available-p)
               (libxml-available-p) (treesit-available-p)
               (imagep nil) (long-line-optimizations-p)))
  (terpri)
  (princ (list 'input (current-input-mode)
               (set-input-mode t nil t 7)
               (set-input-interrupt-mode t)
               (set-input-meta-mode t)
               (set-quit-char 7)
               (current-bidi-paragraph-direction)
               (find-operation-coding-system 'write-region 1 2 "f")
               (condition-case e (define-coding-system-alias 'a 'b)
                 (error (car e)))
               (define-coding-system-alias 'my-utf8 'utf-8)
               (next-read-file-uses-dialog-p)))
  (terpri)
  (princ (list 'disp (lossage-size)
               (condition-case e (lossage-size 99) (error (car e)))
               (mouse-position-in-root-frame)
               (window-scroll-bar-width) (window-scroll-bar-height)
               (line-number-display-width) (move-to-window-line 0)
               (condition-case e (window-configuration-equal-p 1 2)
                 (error (car e)))
               (internal-stack-stats) (pdumper-stats)
               (profiler-cpu-running-p)
               (redirect-debugging-output "/dev/null")
               (comp-libgccjit-version)
               (condition-case e (subr-native-comp-unit 5) (error (car e)))
               (native-comp-function-p #'car) (module-function-p #'car)
               (condition-case e (comp-el-to-eln-filename "/nonexistent-x.el")
                 (error (car e)))))
  (terpri)
  (princ (list 'proc (internal-default-signal-process 1 2)
               (condition-case e (internal-default-process-sentinel 1 "x")
                 (error (car e)))
               (condition-case e (set-network-process-option 1 :x 2)
                 (error (car e)))
               (condition-case e (process-thread 1) (error (car e)))
               (print--preprocess [1]) (clear-composition-cache)
               (condition-case e (re--describe-compiled 1) (error (car e)))
               (condition-case e (system-move-file-to-trash "/no-such-xyz")
                 (error (car e)))))
  (terpri)
  (princ (list 'cs (charset-id-internal 'ascii) (charset-id-internal 'unicode)
               (charset-id-internal 'emacs)
               (condition-case e (charset-id-internal 'nope) (error (car e)))
               (charsetp 'ascii)
               (sort-charsets '(unicode)) (sort-charsets '(emacs ascii))
               (set-charset-priority 'ascii 'unicode)
               (condition-case e (map-charset-chars (lambda (r) nil) 'ascii nil nil t)
                 (error (car e)))
               (condition-case e (declare-equiv-charset 'unicode 1 2 3)
                 (error (car e)))
               (clear-charset-maps)))
  (terpri)
  (let ((gt (unicode-property-table-internal 'general-category))
        (bt (unicode-property-table-internal 'bidi-class)))
    (princ (list 'uni (char-table-p gt)
                 (get-unicode-property-internal gt ?a)
                 (put-unicode-property-internal bt ?a 'L)
                 (get-unicode-property-internal bt ?a)
                 (condition-case e (get-unicode-property-internal 'sym ?a)
                   (error (car e)))))
    (terpri))
  (with-temp-buffer
    (insert "abcdef")
    (internal--labeled-narrow-to-region 2 4 'lab)
    (princ (list 'lownar (point-min) (point-max))) (terpri)
    (internal--labeled-widen 'lab)
    (princ (list 'lowid (point-min) (point-max))) (terpri))
  (let ((ht (make-hash-table)))
    (princ (list 'htab (internal--hash-table-index-size ht)
                 (internal--hash-table-buckets ht)
                 (internal--hash-table-histogram ht)))
    (terpri)
    (puthash 'a 1 ht)
    (princ (list 'htab2 (internal--hash-table-index-size ht)
                 (listp (internal--hash-table-buckets ht))
                 (internal--hash-table-histogram ht)))
    (terpri))
  (princ (list 'vars (internal--define-uninitialized-variable 'uqvar "doc")
               (boundp 'uqvar)
               (condition-case e (internal-delete-indirect-variable 'uqvar)
                 (error (car e)))
               (listp (internal--obarray-buckets obarray))))
  (terpri)
  (with-temp-buffer
    (let ((t0 (buffer-modified-tick)))
      (internal--set-buffer-modified-tick 42)
      (princ (list 'tick t0 (buffer-modified-tick))) (terpri)))
  (princ (list 'asv (recent-auto-save-p) (set-buffer-auto-saved)
               (clear-buffer-auto-save-failure)))
  (terpri)
  (princ (list 'cbuf (internal-complete-buffer "*scr" nil nil)
               (listp (internal-complete-buffer "" nil t))
               (internal-complete-buffer "*scratch*" nil 'lambda)))
  (terpri)
  ;; GUI/font internals: nil stubs (no display). NB: several of these
  ;; SIGABRT a batch GNU (no X/font machinery); only the safe ones are
  ;; differentially comparable.
  (princ (list 'gui (get-display-property 1 'x) (lookup-image-map [1] 2 3)
               (condition-case e (clear-image-cache) (error (car e)))
               (image-cache-size)
               (display--line-is-continued-p)
               (condition-case e (internal-handle-focus-in nil) (error (car e)))
               (condition-case e (internal-handle-focus-in '(focus-in nil))
                 (error (car e)))
               ;; internal-face-x-get-resource SIGABRTs batch GNU.
               'internal-face-x-get-resource
               (internal-set-alternative-font-family-alist nil)
               (condition-case e (internal-set-font-selection-order nil)
                 (error (car e)))
               (condition-case e (query-fontset "x") (error (car e)))
               (condition-case e (close-font 1) (error (car e)))
               (condition-case e (define-fringe-bitmap 'b []) (error (car e)))
               (condition-case e (destroy-fringe-bitmap 'b) (error (car e)))
               (condition-case e (tty-frame-edges) (error (car e)))
               (condition-case e (tty-frame-geometry) (error (car e)))
               (condition-case e (make-terminal-frame '((a . b)))
                 (error (car e)))))
  (terpri)
  (princ (list 'thr (condition-case e (thread-buffer-disposition 1)
                 (error (car e)))
               (thread-buffer-disposition (car (all-threads)))
               (condition-case e
                   (thread-set-buffer-disposition (car (all-threads)) 'x)
                 (error (car e)))
               (thread-set-buffer-disposition (car (all-threads)) nil)))
  (terpri)
  (princ (list 'cjk
               (decode-big5-char #xA440) (decode-big5-char 65)
               (condition-case e (decode-big5-char 99999) (error (cadr e)))
               (encode-big5-char #x4E00)
               (decode-sjis-char #x8140) (decode-sjis-char #xB1)
               (condition-case e (decode-sjis-char #xFF) (error (cadr e)))
               (encode-sjis-char #x3000) (encode-sjis-char #xFF71)
               (decode-char 'big5 #xA440) (decode-char 'cp932 #xB1)
               (decode-char 'japanese-jisx0208 #x2121)
               (decode-char 'jisx0201 #x61) (decode-char 'katakana-sjis #xB1)
               (decode-char 'chinese-big5-1 #x2121)
               (encode-char #x4E00 'big5) (encode-char #x3000 'cp932)
               (encode-char #xFF71 'cp932)
               (condition-case e (decode-char 'sjis 1) (error (car e)))
               (charsetp 'big5) (charsetp 'sjis)))
  (terpri)
  (princ (list 'kbdmacro
               (car (subr-arity (symbol-function 'defining-kbd-macro)))
               (autoloadp (symbol-function 'kbd-macro-query))
               (autoloadp (symbol-function 'define-minor-mode))
               (macrop (symbol-function 'define-minor-mode))
               (progn (start-kbd-macro nil)
                      (store-kbd-macro-event ?a)
                      (end-kbd-macro)
                      last-kbd-macro)
               (condition-case e (end-kbd-macro) (error (cadr e)))
               (condition-case e (start-kbd-macro t) (error (car e)))
               defining-kbd-macro executing-kbd-macro
               (progn (define-minor-mode probe-mm "D" :lighter " PM")
                      (list (fboundp 'probe-mm) (boundp 'probe-mm)))
               (progn (probe-mm 1) probe-mm)
               (progn (probe-mm -1) probe-mm)
               (assq 'probe-mm minor-mode-alist)))
  (terpri)
    (princ (list 'lisplib
               (cl-case 'b (a 1) ((b c) 2) (t 9))
               (condition-case e (cl-ecase 'z (a 1)) (error (cadr e)))
               (cl-typecase 3 (string 's) (integer 'i))
               (cl-destructuring-bind (a b &rest r) '(1 2 3 4) (list a b r))
               (cl-position 3 '(1 2 3 4)) (cl-count 1 '(1 1 2))
               (cl-find 'b '((a . 1) (b . 2)) :key #'car)
               (cl-remove 2 '(1 2 3 2)) (cl-substitute 9 2 '(1 2 3))
               (cl-member 'b '((a) (b)) :key #'car :test #'eq)
               (cl-assoc "b" '(("a" . 1) ("b" . 2)) :test #'equal)
               (cl-rassoc 2 '((a . 1) (b . 2)))
               (cl-adjoin 5 '(1 2)) (cl-union '(1 2) '(2 3))
               (cl-intersection '(1 2 3) '(2 3)) (cl-set-difference '(1 2 3) '(2))
               (cl-subsetp '(1 2) '(1 2 3)) (cl-tailp '(2 3) '(1 2 3))
               (cl-ldiff '(1 2 3) (cddr '(0 1 2 3)))
               (cl-pairlis '(a) '(1) '((b . 2))) (cl-copy-list '(1 2))
               (cl-minusp -1) (cl-plusp 1) (cl-oddp 3) (cl-evenp 4)
               (cl-signum -3) (cl-gcd 12 18) (cl-lcm 4 6) (cl-isqrt 17)
               (cl-equalp "a" "A") (cl-equalp 1 1.0)
               (cl-coerce '(97 98) 'string) (cl-typep 3 'integer)
               (cl-reduce #'+ '(1 2 3)) (cl-reduce #'list '(1 2 3) :from-end t)
               (let ((x 0)) (incf x 5) (decf x) x)
               (let ((x 0)) (cl-incf x 3) x)
               (let ((l '(1))) (cl-pushnew 2 l) (cl-pushnew 2 l) l)
               (let ((a 1) (b 2)) (cl-rotatef a b) (list a b))
               (let ((a 1) (b 2)) (list (cl-shiftf a b 9) a b))
               (let ((l '((a . 1) (b . 2)))) (cl-remf l 'b) l)
               (setf (car (cons 0 nil)) 7)
               (cl-loop for i from 1 to 5 collect (* i i))
               (cl-loop for x in '(a b) for i from 0 collect (list x i))
               (cl-loop for x across [1 2 3] sum x)
               (cl-loop for i below 4 collect i)
               (cl-loop for i from 5 downto 1 collect i)
               (cl-loop repeat 3 collect 'x)
               (cl-loop for i in '(1 2 3 4) if (cl-evenp i) collect i else collect 0)
               (cl-flet ((sq (n) (* n n))) (sq 4))
               (cl-labels ((sq (n) (* n n))) (sq 5))
               (cl-macrolet ((tw (x) `(* 2 ,x))) (tw 3))
               (cl-symbol-macrolet ((h (car z))) (let ((z '(9 8))) h))
               (cl-letf (((symbol-function 'car) (symbol-function 'cdr)))
                 (car '(1 2 3)))
               (cl-dolist (x '(1 2) 'done) x)
               (cl-dotimes (i 3 'done) i)
               (cl-defstruct pt q w)
               (let ((p (make-pt :q 1 :w 2))) (list (pt-p p) (pt-q p)))
               (progn (cl-defun f2 (a &key (b 5)) (list a b)) (f2 1 :b 2))
               (xor nil 5) (xor 1 nil) (xor 1 2)
               (if-let* ((x 1) (y nil)) 'yes 'no)
               (when-let* ((x 1)) x)
               (and-let* ((x 1) (y 2)) (+ x y))
               (if-let ((v 7)) v 'no)
               (thread-first 5 (+ 1) (* 2)) (thread-last '(1 2 3) (cdr) (car))
               (dlet ((x 1)) x)
               (assoc-delete-all 'a '((a . 1) (b . 2) (a . 3)))
               (string-limit "abcdef" 3)
               (string-clean-whitespace "a  b  c")
               (delete-consecutive-dups '(1 1 2 2 1))
               (seq-sort #'> '(1 3 2)) (seq-partition '(1 2 3 4 5) 2)
               (seq-group-by #'cl-evenp '(1 2 3 4)) (seq-mapn #'+ '(1 2) '(10 20))
               (file-name-parent-directory "/a/b/c")
               (file-name-with-extension "/a/b/c.txt" "md")
               (locate-file "prel.el" '("/tmp"))
               (keymapp (define-keymap "a" #'ignore))
               (progn (defvar-keymap probe-km "x" #'ignore)
                      (keymapp probe-km))
               (progn (define-error 'probe-err "boom" 'file-error)
                      (condition-case e (signal 'probe-err nil)
                        (file-error (car e))))
               (progn (eval-after-load "probe-lib" '(setq probe-eal t))
                      (cl-some (lambda (e) (string-match "probe-lib" (car e)))
                               after-load-alist))
               (progn (with-suppressed-warnings ((obsolete car)) (1+ 1)))
               (path-separator) (listp (exec-path))
               (alist-get 'b '((a . 1) (b . 2)))
               (progn (setq probe-ol '(2 3 1))
                      (add-to-ordered-list 'probe-ol 4 0)
                      (add-to-ordered-list 'probe-ol 0 9)
                      probe-ol)
               (progn (setq probe-hist '(x))
                      (put 'probe-hist 'history-length 3)
                      (add-to-history 'probe-hist 'a)
                      (add-to-history 'probe-hist 'b)
                      (add-to-history 'probe-hist 'c)
                      (add-to-history 'probe-hist 'd)
                      probe-hist)
               (progn (add-to-invisibility-spec 'probe-inv)
                      (and (memq 'probe-inv buffer-invisibility-spec)
                           (progn
                             (remove-from-invisibility-spec 'probe-inv)
                             (not (memq 'probe-inv
                                        buffer-invisibility-spec)))))
               (buffer-narrowed-p) (flatten-list '(a (b c) ((d))))
               (split-string-and-unquote "a\\ b\\'c\\$d")
               (split-string-and-unquote "\"a b\" c")
               (combine-and-quote-strings '("a b" "c"))
               (string-replace "a" "o" "banana")
               (time-to-seconds '(0 0 0 0))
               (numberp (emacs-init-time))
               (progn (defun probe-adv (x) (+ x 1))
                      (advice-add 'probe-adv :around
                                  (lambda (f x) (* (funcall f x) 2)))
                      (advice-add 'probe-adv :filter-return #'1-)
                      (let ((r (probe-adv 3)))
                        (advice-remove 'probe-adv #'1-)
                        r))
               (advice-member-p #'car 'probe-adv)
               (condition-case e
                   (advice-add 'probe-adv :bogus #'car)
                 (error (car e)))
               (let ((dyn (completion-table-dynamic
                           (lambda (s) (list (concat s "-a")
                                           (concat s "-b"))))))
                 (list (try-completion "al" dyn nil)
                       (all-completions "al" dyn nil)))
               (let ((m (completion-table-merge '("alpha" "alpine")
                                                '("gamma" "alder"))))
                 (list (try-completion "al" m nil)
                       (all-completions "al" m nil)))
               (let ((it (completion-table-in-turn '("alpha" "alpine")
                                                  '("gamma"))))
                 (list (try-completion "al" it nil)
                       (all-completions "ga" it nil)))
               (let ((cw (completion-table-with-cache
                          (lambda (s) (list (concat s "!"))))))
                 (list (try-completion "a" cw nil)
                       (try-completion "ab" cw nil)))
               (completion-table-with-context "pre-" '("alpha" "alpine")
                                              "al" nil nil)
               (completion-table-with-context "pre-" '("alpha" "alpine")
                                              "al" nil t)
               (macroexp-quote 'a) (macroexp-quote 5)
               (macroexp-quote :k) (macroexp-quote '(x))))
  (terpri)

;; nadvice place forms: add-function / remove-function.
(defun probe-af-base (x) (list 'base x))
(defvar probe-af-var nil)
(setq probe-af-var (lambda (x) (* x 10)))
(princ
 (list (progn
         (add-function :before (symbol-function 'probe-af-base)
                       (lambda (x) (princ (list 'before x))))
         (prog1 (probe-af-base 1)
           (remove-function (symbol-function 'probe-af-base)
                            (lambda (x) (princ (list 'before x))))))
       (probe-af-base 2)
       (progn (add-function :around probe-af-var
                            (lambda (orig &rest r)
                              (list 'around (apply orig r))))
              (funcall probe-af-var 3))
       (progn (add-function :filter-return probe-af-var
                            (lambda (v) (list 'fr v)))
              (funcall probe-af-var 4))
       (progn (remove-function probe-af-var
                               (lambda (v) (list 'fr v)))
              (funcall probe-af-var 4))
       (progn (put 'probe-holder 'fn 'probe-af-base)
              (add-function :before-until (get 'probe-holder 'fn)
                            (lambda (x) (and (> x 5) (list 'big x))))
              (list (funcall (get 'probe-holder 'fn) 3)
                    (funcall (get 'probe-holder 'fn) 7)))
       (progn (add-function :after probe-af-var
                            (lambda (x) (princ 'named!)) '((name . probe-name)))
              (add-function :after probe-af-var
                            (lambda (x) (princ 'dup!)) '((name . probe-name)))
              (funcall probe-af-var 1)
              (remove-function probe-af-var 'probe-name)
              (funcall probe-af-var 1))
       (condition-case e
           (add-function :bogus probe-af-var #'ignore)
         (error (list (car e) (cadr e))))
       (macrop 'add-function) (macrop 'remove-function)
       (fboundp 'easy-mmode-define-minor-mode)))
(terpri)
(define-advice probe-af-base (:around (orig &rest r) probe-adv)
  (list 'adv (apply orig r)))
(princ (list (probe-af-base 9)
             (and (advice-member-p 'probe-adv 'probe-af-base) t)
             (boundp 'standard-output)))
(terpri)
(advice-mapc (lambda (f p) (princ (list 'mapc (cdr (assq 'name p)))))
             'probe-af-base)
(terpri)
;; pp / gv / cl-generic / print-streams / misc batch.
(let ((probe '(t)))
  (princ (list 'ppaut
               (mapcar (lambda (n) (and (fboundp n) t))
                       '(pp pp-to-string pp-buffer pp-eval-last-sexp
                         pp-macroexpand-last-sexp))
               (autoloadp (symbol-function 'pp))
               (autoloadp (symbol-function 'pp-to-string))
               (autoloadp (symbol-function 'gv-ref))
               (autoloadp (symbol-function 'gv-letplace))
               (autoloadp (symbol-function 'gv-get))
               (fboundp 'gv-deref)
               (fboundp 'transient-mark-mode)
               (fboundp 'with-output-to-temp-buffer)
               (fboundp 'add-timeout)
               (fboundp 'read-minibuffer)
               (fboundp 'eval-minibuffer)
               (fboundp 'values--store-value))))
  (terpri)
  (princ (pp-to-string 'sym))(princ (pp-to-string '(a b)))(princ (pp-to-string [1 2]))
  (princ (pp-to-string '(let ((a 1) (b 2)) (list a b))))
  (princ (pp-to-string '(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
                        ccccccccccccccccccccccccccccc ddddddddddddddddddddddddddddddd
                        eeeeeeeeeeeeeeeeeeeeeeeeeeeee ffffffffffffffffffffffffffffff)))
  (terpri)
  (macroexpand '(gv-ref probe-gv-x))
  (terpri)
  (defvar probe-gv-x '(1 2 3))
  (let ((r (gv-ref probe-gv-x)))
    (funcall (cdr r) '(4 5))
    (princ (list (funcall (car r)) probe-gv-x)))
  (terpri)
  (setf (gv-deref (gv-ref probe-gv-x)) '(8 9))
  (princ probe-gv-x)
  (terpri)
  (princ (macroexpand '(gv-letplace (g s) (car probe-gv-x) (list 'progn g (funcall s 'v)))))
  (terpri)
  (cl-defgeneric probe-cg (x) "doc")
  (cl-defmethod probe-cg ((x integer)) (list 'int x))
  (cl-defmethod probe-cg ((x string)) (list 'str x))
  (cl-defmethod probe-cg (x) (list 'any x))
  (cl-defmethod probe-cg ((x (eql 's))) (list 'eql x))
  (princ (list (probe-cg 1) (probe-cg "a") (probe-cg 1.5) (probe-cg 's) (probe-cg 'q)))
  (terpri)
  (cl-defmethod probe-cg :around ((x integer)) (list 'around (cl-call-next-method x)))
  (princ (probe-cg 5))
  (terpri)
  (cl-defmethod probe-cg :before ((x string)) (princ 'beforestr))
  (cl-defmethod probe-cg :after ((x string)) (princ 'afterstr))
  (princ (probe-cg "z"))
  (terpri)
  (cl-defmethod probe-cg ((x integer)) (list 'int2 x))
  (princ (probe-cg 1))
  (terpri)
  (princ (condition-case e (progn (cl-defgeneric probe-cg3 (x)) (probe-cg3 1))
           (t (list (car e) (cdr e)))))
  (terpri)
  (princ (list (condition-case e (cl-next-method-p) (error (cadr e)))
               (condition-case e (cl-call-next-method) (error (cadr e)))
               (fboundp 'cl-call-next-method)))
  (terpri)
  ;; print to explicit streams
  (with-temp-buffer
    (prin1 '(x y) (current-buffer))
    (princ 'z (current-buffer))
    (princ (buffer-string)))
  (terpri)
  (with-temp-buffer
    (insert "AB")
    (let ((m (copy-marker 2)))
      (princ "XX" m)
      (princ (list (buffer-string) (marker-position m)))))
  (terpri)
  (let ((out nil))
    (princ "fn" (lambda (s) (setq out (cons s out))))
    (princ (nreverse out)))
  (terpri)
  (let ((out nil))
    (prin1 '(a) (lambda (s) (setq out (cons s out))))
    (princ (nreverse out)))
  (terpri)
  ;; terpri ENSURE: skip when already at BOL, returns t/nil
  (with-temp-buffer
    (insert "ab")
    (let ((r1 (terpri (current-buffer) t))
          (r2 (progn (insert "c") (terpri (current-buffer) t)))
          (r3 (progn (terpri (current-buffer) t))))
      (princ (list r1 r2 r3 (buffer-string)))))
  (terpri)
  (princ (list (subr-arity (symbol-function 'terpri))
               (condition-case e (terpri (lambda (c) nil) t)
                 (error (list (car e) (cadr e))))))
  (terpri)
  ;; indent-line-to honors indent-tabs-mode/tab-width
  (with-temp-buffer
    (let ((indent-tabs-mode t) (tab-width 8))
      (insert "x\ny")
      (goto-char 2)
      (indent-line-to 10)
      (princ (list (buffer-string) (point)))))
  (terpri)
  (with-temp-buffer
    (let ((indent-tabs-mode nil))
      (insert "x\ny")
      (goto-char 2)
      (indent-line-to 10)
      (princ (buffer-string))))
  (terpri)
  (transient-mark-mode 1)
  (princ transient-mark-mode)
  (transient-mark-mode -1)
  (princ transient-mark-mode)
  (terpri)
  (with-output-to-temp-buffer "*probe-temp*" (princ "hi"))
  (princ (with-current-buffer "*probe-temp*" (buffer-string)))
  (terpri)
  ;; EIEIO subset: defclass/make-instance/slot ops/dispatch.
  (princ (list 'eieio-aut (autoloadp (symbol-function 'defclass))
               (autoloadp (symbol-function 'make-instance))))
  (terpri)
  (defclass probe-pt ()
    ((x :initarg :x :initform 0)
     (nb)))
  (defclass probe-pt2 (probe-pt) ((z :initarg :z :initform 9)))
  (let ((p (make-instance 'probe-pt :x 3)))
    (princ (list (oref p x)
                 (condition-case e (oref p nb) (error (car e)))))
    (terpri))
  (let ((p (make-instance 'probe-pt :x 3)))
    (oset p nb 7)
    (princ (list (oref p nb) (slot-value p 'x)
                 (class-of p) (eieio-object-p p)
                 (object-of-class-p p 'probe-pt)
                 (object-of-class-p p 'probe-pt2)
                 (slot-boundp p 'x)
                 (condition-case e (oref p 'noslot) (error (car e)))
                 (condition-case e (slot-value p 'nb) (error (car e))))))
  (terpri)
  (let ((q (make-instance 'probe-pt2)))
    (princ (list (oref q x) (oref q z)
                 (child-of-class-p 'probe-pt2 'probe-pt)
                 (object-of-class-p q 'probe-pt)
                 (same-class-p q 'probe-pt2)
                 (oref-default probe-pt x))))
  (terpri)
  (princ (condition-case e (make-instance 'probe-nope)
           (error (car e))))
  (terpri)
  (princ (condition-case e (make-instance 'probe-pt :bogus 1)
           (error (car e))))
  (terpri)
  (let ((p (make-instance 'probe-pt :x 1)))
    (with-slots (x) p (setq x 42))
    (princ (oref p x))
    (setf (oref p x) 43)
    (princ (oref p x)))
  (terpri)
  (cl-defgeneric probe-area (s))
  (cl-defmethod probe-area ((s probe-pt2)) (list 'pt2 (oref s z)))
  (cl-defmethod probe-area ((s probe-pt)) (list 'pt (oref s x)))
  (princ (list (probe-area (make-instance 'probe-pt2 :x 1 :z 2))
               (probe-area (make-instance 'probe-pt :x 5))))
  (terpri)
  (princ (list (slot-exists-p (make-instance 'probe-pt2) 'x)
               (slot-exists-p 'probe-pt2 'z)
               (slot-exists-p 'probe-pt2 'nope)))
  (terpri)
nil)
;; --- syntax tables / parse-partial-sexp / lisp indent / modes ---
(let ((out nil))
  (with-temp-buffer
    (insert "(a (b c) \"str \\\" x\") ; cmt\n  (d '(e) |f|)\n(z)")
    (dolist (p '(1 4 12 20 28 31)) (push (syntax-ppss p) out))
    (goto-char 5) (syntax-ppss) (push (point) out)
    (goto-char 1) (push (list (parse-partial-sexp 1 12) (point)) out)
    (goto-char 1) (push (list (parse-partial-sexp 1 40 1) (point)) out)
    (goto-char 1) (push (list (parse-partial-sexp 1 40 nil t) (point)) out)
    (goto-char 1)
    (let ((s1 (parse-partial-sexp 1 4)))
      (push (parse-partial-sexp (point) 15 nil nil s1) out)))
  (with-temp-buffer
    (insert "\"ab") (push (syntax-ppss 3) out))
  (with-temp-buffer
    (insert "; x") (push (syntax-ppss 3) out))
  (with-temp-buffer
    (modify-syntax-entry ?\; ".")
    (insert "; not-comment (a")
    (push (syntax-ppss 15) out)
    (push (char-syntax ?\;) out))
  (push (list (char-syntax ?\() (char-syntax ?\)) (char-syntax ?a)
              (char-syntax ?_) (char-syntax ?\s) (char-syntax ?')
              (char-syntax ?\")) out)
  (with-temp-buffer
    (insert "(defun f (x)\n(let ((a 1))\n(+ a x)))")
    (goto-char (point-min)) (forward-line 1)
    (push (calculate-lisp-indent) out)
    (forward-line 1) (beginning-of-line)
    (push (calculate-lisp-indent) out))
  (with-temp-buffer
    (insert "(foo bar\nbaz)") (forward-line 1) (beginning-of-line)
    (push (calculate-lisp-indent) out))
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "(defun f (x)\n(let ((a 1))\n(+ a x)))")
    (goto-char (point-min)) (forward-line 1)
    (lisp-indent-line) (forward-line 1) (lisp-indent-line)
    (push (buffer-string) out))
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "(let ((a 1))\n(a))")
    (goto-char (point-min)) (forward-line 1)
    (indent-according-to-mode)
    (push (buffer-string) out))
  (dolist (x (nreverse out)) (prin1 x) (terpri)))
(let ((out nil))
  (with-temp-buffer (lisp-interaction-mode)
    (push (list major-mode (char-syntax ?') indent-line-function) out))
  (with-temp-buffer (text-mode) (push major-mode out))
  (with-temp-buffer (special-mode) (push major-mode out))
  (with-temp-buffer (prog-mode) (push major-mode out))
  (with-temp-buffer (lisp-mode) (push major-mode out))
  (push (list (get 'defun 'lisp-indent-function)
              (get 'let 'lisp-indent-function)
              (get 'lambda 'lisp-indent-function)
              (get 'progn 'lisp-indent-function)) out)
  (push (list (derived-mode-p 'lisp-interaction-mode 'emacs-lisp-mode)
              (derived-mode-p 'emacs-lisp-mode 'prog-mode)
              (derived-mode-p 'text-mode 'prog-mode)
              (derived-mode-p 'emacs-lisp-mode 'lisp-mode)) out)
  (push (list (fboundp 'calculate-lisp-indent) (fboundp 'lisp-indent-line)
              (fboundp 'lisp-ppss) (fboundp 'lisp-indent-specform)
              (fboundp 'lisp-indent-defform) (fboundp 'split-line)
              (fboundp 'move-to-tab-stop) (fboundp 'reindent-then-newline-and-indent)
              (fboundp 'count-screen-lines) (fboundp 'beginning-of-defun-raw)
              (fboundp 'indent-new-comment-line) (fboundp 'indent-pp-sexp)
              (boundp 'lisp-body-indent) (boundp 'lisp-indent-offset)
              (boundp 'defun-prompt-regexp) (boundp 'widen-automatically)) out)
  (dolist (x (nreverse out)) (prin1 x) (terpri)))
