;; probe_buffer4 — deeper primitives coverage: text properties,
;; markers, narrowing, match data, buffer-local vars, undo

;; ---- text properties ----
(with-temp-buffer
  (insert "abcdefghij")
  (put-text-property 1 4 'face 'bold)
  (put-text-property 3 6 'help-echo "hint")
  (add-text-properties 7 9 '(mouse-face highlight))
  (get-text-property 1 'face)
  (get-text-property 3 'help-echo)
  (text-properties-at 1)
  (text-properties-at 8)
  (next-property-change 1)
  (next-property-change 3)
  (previous-property-change 4)
  (next-single-property-change 1 'face)
  (previous-single-property-change 6 'help-echo)
  (text-property-any 1 10 'face 'bold)
  (text-property-not-all 1 10 'face 'bold)
  (remove-text-properties 1 3 '(face))
  (set-text-properties 4 6 '(custom val))
  (propertize "x" 'face 'bold)
  (condition-case e (buffer-substring-with-properties 1 5) (error e))
  (substring-no-properties "abc")
  (remove-list-of-text-properties 1 10 '(help-echo custom)))

;; ---- markers ----
(with-temp-buffer
  (insert "marker text here")
  (let* ((m (make-marker))
         (m2 (copy-marker (point-min-marker)))
         (m3 (point-max-marker)))
    (markerp m)
    (set-marker m 5)
    (marker-position m)
    (marker-buffer m)
    (set-marker m (point-max))
    (marker-insertion-type m)
    (set-marker-insertion-type m t)
    (insert-before-markers "X")
    (insert "Y")
    (marker-position m)
    (set-marker m nil)
    (byte-to-position 3)
    (position-bytes 3)
    (max-char)))

;; ---- narrowing ----
(with-temp-buffer
  (insert "aaabbbccc")
  (narrow-to-region 4 7)
  (point-min)
  (point-max)
  (buffer-size)
  (widen)
  (point-min)
  (point-max)
  (narrow-to-page 1))

;; ---- match data ----
(with-temp-buffer
  (insert "abc123def456")
  (goto-char (point-min))
  (re-search-forward "\\([0-9]+\\)")
  (match-beginning 0)
  (match-end 0)
  (match-beginning 1)
  (match-end 1)
  (match-string 0)
  (match-string 1)
  (match-string-no-properties 0)
  (match-data)
  (match-data t)
  (set-match-data (match-data))
  (replace-match "X")
  (goto-char (point-min))
  (string-match "\\([a-z]+\\)" "aaBBcc" 0)
  (match-beginning 1)
  (looking-at "abc")
  (looking-back "abc" nil)
  (re-search-backward "123" nil t)
  (search-forward "def" nil t)
  (search-backward "abc" nil t)
  (skip-chars-forward "a-z")
  (skip-chars-backward "0-9")
  (skip-syntax-forward "w")
  (skip-syntax-backward "w")
  (syntax-after (point))
  (following-char)
  (preceding-char)
  (char-after)
  (char-before))

;; ---- buffer-local variables ----
(with-temp-buffer
  (make-local-variable 'probe-lv)
  (setq probe-lv 7)
  (local-variable-p 'probe-lv)
  (local-variable-if-set-p 'probe-lv)
  (buffer-local-value 'probe-lv (current-buffer))
  (buffer-local-variables)
  (kill-local-variable 'probe-lv)
  (make-variable-buffer-local 'probe-lv2)
  (setq probe-lv2 9)
  (kill-all-local-variables)
  (default-boundp 'fill-column)
  (default-value 'fill-column)
  (set-default 'probe-dv 3)
  (default-value 'probe-dv))

;; ---- undo ----
(with-temp-buffer
  (buffer-enable-undo)
  (insert "undo me")
  (primitive-undo 1 buffer-undo-list)
  (buffer-disable-undo)
  (buffer-enable-undo)
  (insert "x"))

;; ---- buffers ----
(generate-new-buffer-name "probe-nm")
(generate-new-buffer " probe-hidden")
(bury-buffer)
(unbury-buffer)
(buffer-list)
(other-buffer)
(last-buffer)
(buffer-base-buffer (current-buffer))
(buffer-live-p (current-buffer))
(buffer-name)
(buffer-file-name)
(buffer-modified-p)
(set-buffer-modified-p nil)
(buffer-string)
(buffer-size)
(buffer-disable-undo)
(rename-buffer "probe-renamed" t)
(current-buffer)
(set-buffer (current-buffer))
(buffer-substring 1 3)
(insert-buffer-substring (current-buffer) 1 3)
(erase-buffer)

;; ---- point/column/line motion ----
(with-temp-buffer
  (insert "one\ntwo\nthree\nfour\n")
  (goto-char (point-min))
  (forward-line 2)
  (end-of-line)
  (beginning-of-line)
  (forward-char 2)
  (backward-char 1)
  (forward-word 1)
  (backward-word 1)
  (move-to-column 2)
  (current-column)
  (line-number-at-pos)
  (count-lines (point-min) (point-max))
  (pos-bol)
  (pos-eol)
  (line-beginning-position)
  (line-end-position)
  (line-beginning-position 2)
  (line-end-position 2)
  (count-words-region (point-min) (point-max))
  (require 'thingatpt)
  (thing-at-point 'word)
  (symbol-at-point)
  (word-at-point)
  (current-word)
  (open-line 1)
  (newline 2)
  (insert-char ?x 3)
  (self-insert-command 1)
  (delete-char 1)
  (delete-backward-char 1)
  (delete-region (point-min) (+ 2 (point-min)))
  (delete-and-extract-region (point-min) (point-max)))

;; ---- mark ----
(with-temp-buffer
  (insert "mark test")
  (push-mark 3)
  (push-mark 6 t)
  (mark)
  (mark-marker)
  (set-mark 8)
  (pop-mark)
  (exchange-point-and-mark)
  (activate-mark)
  (region-active-p)
  (use-region-p)
  (region-beginning)
  (region-end)
  (deactivate-mark)
  (barf-if-buffer-read-only))

;; ---- regexps ----
(regexp-quote "a.b*c")
(regexp-opt '("foo" "bar" "baz"))
(regexp-opt-depth (regexp-opt '("foo" "bar")))
(condition-case e (match-substitute-replacement "x&y") (error e))
(with-temp-buffer
  (insert "abc")
  (goto-char (point-min))
  (re-search-forward "b")
  (match-substitute-replacement "x&y"))
(string-match "\\(a\\)" "ba")
(match-substitute-replacement "x\\1y" nil nil "ba")
(looking-at-p "a")

;; ---- misc positions ----
(with-temp-buffer
  (insert "point stuff")
  (point-marker)
  (point-min-marker)
  (point-max-marker)
  (bobp)
  (eobp)
  (bolp)
  (eolp)
  (gap-position)
  (gap-size)
  (following-char)
  (preceding-char))

;; ---- round 2: uncovered branches ----
(with-current-buffer (get-buffer-create "undo-test")
  (erase-buffer)
  (insert "abc")
  buffer-undo-list
  (undo-boundary)
  (undo)
  (buffer-string)
  (insert "def")
  (undo 1)
  (undo-start)
  (condition-case e (undo-more 1) (error e))
  (kill-buffer "undo-test"))
(with-temp-buffer
  (condition-case e (undo) (error e)))
(with-temp-buffer
  (insert "hello world")
  (goto-char 2)
  (thing-at-point 'word)
  (thing-at-point 'symbol)
  (thing-at-point 'line)
  (thing-at-point 'number t)
  (word-at-point)
  (symbol-at-point))
(with-temp-buffer
  (insert "a(b)c")
  (goto-char 1)
  (syntax-after 1)
  (syntax-after 2))
(with-temp-buffer
  (insert "; comment\nx")
  (goto-char 1)
  (forward-comment 1)
  (point)
  (goto-char (point-max))
  (forward-comment -1))
(with-temp-buffer
  (insert "aaa bbb")
  (goto-char 1)
  (re-search-forward "aaa")
  (replace-match "ZZZ")
  (buffer-string)
  (goto-char 1)
  (re-search-forward "b\\(b\\)b")
  (replace-match "X\\1Y" nil nil nil 1)
  (buffer-string))
(with-temp-buffer
  (insert "aaa")
  (string-match "aa" "aaab")
  (replace-match "Q" nil nil "aaab")
  (replace-match "Q" t nil "aaab"))
(regexp-opt '("aa" "bb"))
(regexp-opt '("aa" "ab") t)
(regexp-opt nil)
(with-temp-buffer
  (insert "  \txy")
  (goto-char 1)
  (move-to-column 5)
  (move-to-column 5 t)
  (current-column))
(with-temp-buffer
  (insert "abc")
  (add-text-properties 1 3 '(face bold))
  (text-properties-at 1)
  (text-properties-at 2)
  (text-properties-at 3))
(with-temp-buffer
  (insert "xy")
  (let ((m (set-marker (make-marker) 2)))
    (goto-char 1)
    (insert-before-markers "QQ")
    (marker-position m))
  (let ((m (make-marker)))
    (set-marker m nil)))
(with-temp-buffer
  (rename-buffer "rn-buf")
  (buffer-name)
  (rename-buffer "rn-buf2" t))
(with-temp-buffer
  (insert "01234")
  (goto-char 1)
  (condition-case e (goto-char 'x) (error e))
  (condition-case e (goto-char 100) (error e))
  (condition-case e (goto-char -5) (error e))
  (goto-char (point-min))
  (let ((m (set-marker (make-marker) 4)))
    (goto-char m)))
(with-temp-buffer
  (insert "(a b) (c d)")
  (goto-char 1)
  (scan-sexps 1 1)
  (scan-sexps 1 2)
  (forward-sexp -1)
  (forward-sexp 2)
  (backward-sexp)
  (condition-case e (up-list -1) (error e))
  (condition-case e (scan-sexps 1 99) (error e)))
(get-buffer-create "gb-new")
(get-buffer-create "gb-new2" t)
(condition-case e (get-buffer-create nil) (error e))
(get-buffer "gb-new")
(condition-case e (get-buffer 42) (error e))
(condition-case e (kill-buffer "no-such-buf-xyz") (error e))
(kill-buffer "gb-new")
(kill-buffer "gb-new2")
(let ((m (make-marker)))
  (condition-case e (set-marker m "notabuf") (error e)))

;; ---- round 3: field/motion/replace branches ----
(with-temp-buffer
  (insert "aaa bbb")
  (goto-char 1)
  (replace-string "aaa" "ZZZ")
  (buffer-string))
(with-temp-buffer
  (insert "a1b2c3")
  (goto-char 1)
  (replace-regexp "[0-9]" "N")
  (buffer-string))
(with-temp-buffer
  (insert "field1\tfield2")
  (goto-char 2)
  (field-beginning)
  (field-end)
  (field-string)
  (delete-field)
  (buffer-string)
  (constrain-to-field nil 1)
  (constrain-to-field 1 5))
(with-temp-buffer
  (insert "line1\nline2\nline3")
  (goto-char 1)
  (vertical-motion 1)
  (vertical-motion -1)
  (compute-motion 1 '(1 . 0) 20 '(0 . 0) 80 0 nil))
(with-temp-buffer
  (insert "abc")
  (add-face-text-property 1 3 'bold)
  (next-property-change 1)
  (previous-property-change 3)
  (get-pos-property 1 'face)
  (get-pos-property 2 'face)
  (get-char-property-and-overlay 1 'face))
(marker-last-position (set-marker (make-marker) 2 (get-buffer-create "mlp")))
(kill-buffer "mlp")
(with-temp-buffer
  (insert "HELLO")
  (translate-region 1 3 (make-translation-table-from-alist '((?H . ?h))))
  (buffer-string))
(buffer-swap-text (get-buffer-create "swap-b"))
(kill-buffer "swap-b")
(with-temp-buffer
  (insert "x")
  (let ((m (point-marker)))
    (insert-before-markers "a")
    (marker-position m)))
(with-temp-buffer
  (insert "txt")
  (put-text-property 1 2 'field 'fld)
  (field-beginning)
  (field-end))
