;; -*- lexical-binding: t -*-
(defun show (tag fn)
  (with-current-buffer "*r*"
    (erase-buffer)
    (insert "ab\ncdefghij\nkl\n")
    (goto-char (point-min))
    (condition-case e (funcall fn) (error (princ (format "%s ERR %s\n" tag e))))
    (princ (format "%s=<%s>\n" tag (buffer-string)))))
(get-buffer-create "*r*")
(show 'del (lambda () (delete-rectangle 2 15)))
(show 'clr (lambda () (clear-rectangle 2 15)))
(show 'clrfill (lambda () (clear-rectangle 2 15 t)))
(show 'opn (lambda () (open-rectangle 2 15)))
(show 'str (lambda () (string-rectangle 2 15 "XY")))
(show 'strins (lambda () (string-insert-rectangle 2 15 "XY")))
(show 'killed (lambda () (kill-rectangle 2 15) (princ (format "kr=%s\n" killed-rectangle))))
(show 'yank (lambda () (kill-rectangle 2 15) (goto-char (point-min)) (yank-rectangle)))
(show 'yankeof (lambda () (kill-rectangle 2 15) (goto-char (point-max)) (yank-rectangle)))
(with-current-buffer "*r*"
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (delete-rectangle 5 15)
  (princ (format "del2=<%s>\n" (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (open-rectangle 5 15)
  (princ (format "opn2=<%s>\n" (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (clear-rectangle 5 15)
  (princ (format "clr2=<%s>\n" (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (string-rectangle 5 15 "Q")
  (princ (format "str2=<%s>\n" (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (princ (format "ex=%s\n" (extract-rectangle 6 15)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (princ (format "dex=%s buf=<%s>\n" (delete-extract-rectangle 6 15) (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (rectangle-number-lines 6 15 7 "N%d: ")
  (princ (format "num=<%s>\n" (buffer-string)))
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (rectangle-number-lines 6 15 7)
  (princ (format "numdef=<%s>\n" (buffer-string)))
  ;; tab-splitting kill
  (erase-buffer) (insert "a\tb\nc\td\n")
  (kill-rectangle 2 9)
  (princ (format "tabkr=%s buf=<%s>\n" killed-rectangle (buffer-string)))
  ;; extract only
  (erase-buffer) (insert "a\tb\nc\td\n")
  (princ (format "tabex=%s buf=<%s>\n" (extract-rectangle 2 9) (buffer-string)))
  ;; delete-whitespace-rectangle
  (erase-buffer) (insert "aa   bb\ncc dd\n")
  (delete-whitespace-rectangle 3 13)
  (princ (format "dws=<%s>\n" (buffer-string))))

;; --- register coverage (moved-adjacent sanity) ---
(with-current-buffer "*r*"
  (erase-buffer) (insert "zz\n")
  (point-to-register ?p)
  (princ (format "regp=%s\n" (get-register ?p))))

;; --- extended rectangle API ---
(with-current-buffer "*r*"
  (erase-buffer) (insert "x\nabcdefgh\nyz\n")
  (princ (format "dims=%s\n" (rectangle-dimensions 6 15)))
  (princ (format "coords=%s %s\n" (rectangle-position-as-coordinates 6) (rectangle-position-as-coordinates 15)))
  (princ (format "bounds=%s\n" (extract-rectangle-bounds 6 15)))
  (princ (format "inter=%s %s\n" (rectangle-intersect-p '(0 . 0) '(2 . 2) '(1 . 1) '(2 . 2))
                 (rectangle-intersect-p '(0 . 0) '(1 . 1) '(2 . 2) '(2 . 2))))
  (princ (format "ss=<%s>\n" (spaces-string 4)))
  (let ((hits nil))
    (apply-on-rectangle (lambda (sc ec) (push (list (point) sc ec) hits)) 6 15)
    (princ (format "aon=%s\n" (nreverse hits))))
  (let ((hits nil))
    (operate-on-rectangle (lambda (sp be ee) (push (list sp be ee (point)) hits)) 6 15 nil)
    (princ (format "opon=%s\n" (nreverse hits))))
  (let ((hits nil))
    (operate-on-rectangle (lambda (sp be ee) (push (list sp be ee (point)) hits)) 6 15 t)
    (princ (format "opont=%s\n" (nreverse hits)))))
