;; probe_buffer3 — deep buffer ops on structured content
;; list navigation on real parens
(with-temp-buffer
  (insert "(a (b c) d) (e f)\n(x y)\n")
  (goto-char (point-min))
  (ignore-errors (down-list))
  (ignore-errors (up-list))
  (ignore-errors (forward-list))
  (ignore-errors (backward-list))
  (ignore-errors (backward-up-list))
  (goto-char (point-min))
  (ignore-errors (scan-lists (point) 1 0))
  (goto-char (point-min))
  (ignore-errors (scan-lists (point) -1 0))
  (goto-char (point-min))
  (ignore-errors (scan-lists (point) 0 1))
  (goto-char 3)
  (ignore-errors (down-list))
  (ignore-errors (up-list))
  (ignore-errors (backward-up-list -1))
  (goto-char (point-max))
  (ignore-errors (backward-list))
  (ignore-errors (forward-list -1)))
;; searching in a real buffer
(with-temp-buffer
  (insert "hello world foo bar hello\nsecond line\n")
  (goto-char (point-min))
  (ignore-errors (search-forward "world"))
  (ignore-errors (search-backward "hello"))
  (ignore-errors (search-forward-regexp "w.rld"))
  (ignore-errors (search-backward-regexp "h.llo"))
  (goto-char (point-min))
  (ignore-errors (looking-at "hello"))
  (ignore-errors (looking-at-p "hello"))
  (goto-char 7)
  (ignore-errors (looking-back "hello "))
  (ignore-errors (looking-back "hello " 1))
  (ignore-errors (looking-back "hello " nil t))
  (ignore-errors (posix-looking-at "hello"))
  (goto-char (point-min))
  (ignore-errors (word-search-forward "world"))
  (goto-char (point-max))
  (ignore-errors (word-search-backward "hello"))
  (ignore-errors (word-search-forward "world" nil t))
  (ignore-errors (word-search-backward "hello" nil t))
  (ignore-errors (re-search-forward "h.llo" nil t))
  (ignore-errors (re-search-backward "w.rld" nil t))
  (ignore-errors (string-match "h.llo" (buffer-string)))
  (ignore-errors (string-match-p "h.llo" (buffer-string)))
  (ignore-errors (posix-string-match "h.llo" (buffer-string)))
  (ignore-errors (match-end 0))
  (ignore-errors (match-string-no-properties 0))
  (ignore-errors (match-string-no-properties 0 "hello")))
;; position/movement on multi-line
(with-temp-buffer
  (insert "line one\nline two\nline three\n")
  (goto-char 15)
  (ignore-errors (pos-bol))
  (ignore-errors (pos-bol 15))
  (ignore-errors (pos-eol))
  (ignore-errors (pos-eol 15))
  (ignore-errors (char-after))
  (ignore-errors (char-after 5))
  (ignore-errors (char-before))
  (ignore-errors (char-before 20))
  (ignore-errors (bolp))
  (ignore-errors (eolp))
  (ignore-errors (bobp))
  (ignore-errors (eobp))
  (ignore-errors (current-word))
  (ignore-errors (current-word t))
  (ignore-errors (word-at-point))
  (ignore-errors (buffer-word-at-point))
  (ignore-errors (current-column))
  (ignore-errors (end-of-line))
  (ignore-errors (beginning-of-line))
  (ignore-errors (forward-line 1))
  (ignore-errors (forward-line -1))
  (ignore-errors (goto-char (point-max)))
  (ignore-errors (end-of-buffer))
  (ignore-errors (newline))
  (ignore-errors (newline 2))
  (ignore-errors (erase-buffer)))
;; markers
(with-temp-buffer
  (insert "abcdefghij")
  (let ((m (make-marker))
        (m2 (point-marker)))
    (ignore-errors (set-marker m 5))
    (ignore-errors (set-marker m 3 (current-buffer)))
    (ignore-errors (marker-position m))
    (ignore-errors (marker-buffer m))
    (ignore-errors (move-marker m 8))
    (ignore-errors (copy-marker m))
    (ignore-errors (copy-marker m t))
    (ignore-errors (copy-marker m2))
    (ignore-errors (marker-insertion-type m))
    (ignore-errors (set-marker-insertion-type m t))
    (ignore-errors (marker-insertion-type m))
    (ignore-errors (markerp m))
    (ignore-errors (markerp m2))))
;; overlays — real ones
(with-temp-buffer
  (insert "0123456789")
  (let ((o (ignore-errors (make-overlay 2 6))))
    (ignore-errors (overlayp o))
    (ignore-errors (overlay-start o))
    (ignore-errors (overlay-end o))
    (ignore-errors (overlay-buffer o))
    (ignore-errors (overlay-put o 'face 'bold))
    (ignore-errors (overlay-get o 'face))
    (ignore-errors (overlay-properties o))
    (ignore-errors (overlays-at 3))
    (ignore-errors (overlays-in 1 10))
    (ignore-errors (overlays-at-point))
    (ignore-errors (next-overlay-change 1))
    (ignore-errors (previous-overlay-change 5))
    (ignore-errors (move-overlay o 1 4))
    (ignore-errors (move-overlay o 1 4 (current-buffer)))
    (ignore-errors (delete-overlay o))
    (ignore-errors (overlay-recenter 5))))
;; mark/region with a real mark
(with-temp-buffer
  (insert "abcdefghij")
  (goto-char 3)
  (ignore-errors (push-mark))
  (ignore-errors (push-mark 7))
  (ignore-errors (push-mark nil t))
  (ignore-errors (set-mark 2))
  (ignore-errors (mark))
  (ignore-errors (mark t))
  (ignore-errors (mark-marker))
  (ignore-errors (region-end))
  (ignore-errors (region-beginning))
  (ignore-errors (activate-mark))
  (ignore-errors (deactivate-mark))
  (ignore-errors (pop-mark))
  (ignore-errors (exchange-point-and-mark))
  (ignore-errors (transient-mark-mode 1))
  (ignore-errors (mark-active)))
;; kill ring ops
(with-temp-buffer
  (insert "kill this text\nsecond line\n")
  (goto-char (point-min))
  (ignore-errors (kill-line))
  (ignore-errors (kill-line 1))
  (ignore-errors (kill-word 1))
  (ignore-errors (kill-region 1 3))
  (ignore-errors (kill-ring-save 1 5))
  (ignore-errors (kill-new "inserted"))
  (ignore-errors (kill-new "inserted" t))
  (ignore-errors (current-kill 0))
  (ignore-errors (current-kill 1))
  (ignore-errors (current-kill 0 t))
  (ignore-errors (yank))
  (ignore-errors (yank 1))
  (ignore-errors (yank-pop))
  (ignore-errors (rotate-yank-pointer 1))
  (ignore-errors (copy-to-buffer (current-buffer) 1 3)))
;; windows — real split
(let ((w (selected-window)))
  (ignore-errors (window-point w))
  (ignore-errors (window-list))
  (ignore-errors (window-list (selected-frame)))
  (ignore-errors (next-window))
  (ignore-errors (next-window w))
  (ignore-errors (window-at 1 1))
  (ignore-errors (window-fringes))
  (ignore-errors (window-fringes w))
  (ignore-errors (window-pixel-edges))
  (ignore-errors (window-pixel-edges w))
  (ignore-errors (window-text-width))
  (ignore-errors (window-text-width w))
  (ignore-errors (window-top-line))
  (ignore-errors (window-top-line w))
  (ignore-errors (window-total-height))
  (ignore-errors (window-total-height w))
  (ignore-errors (window-total-width))
  (ignore-errors (window-total-width w))
  (ignore-errors (delete-window w))
  (ignore-errors (split-window w))
  (ignore-errors (split-window w -5))
  (ignore-errors (split-window w -5 'below))
  (ignore-errors (window-new-normal))
  (ignore-errors (window-new-total)))
;; files — real temp files
(let ((f "/tmp/remacs-probe-real.txt"))
  (ignore-errors (write-region "content\n" nil f))
  (ignore-errors (file-modes f))
  (ignore-errors (file-modes f 'integer))
  (ignore-errors (set-file-modes f 420))
  (ignore-errors (file-modes f 'integer))
  (ignore-errors (file-accessible-directory-p "/tmp"))
  (ignore-errors (file-equal-p f f))
  (ignore-errors (copy-file f "/tmp/remacs-probe-copy.txt"))
  (ignore-errors (copy-file f "/tmp/remacs-probe-copy.txt" t))
  (ignore-errors (copy-file f "/tmp/remacs-probe-copy.txt" nil nil nil nil))
  (ignore-errors (delete-file "/tmp/remacs-probe-copy.txt"))
  (ignore-errors (make-directory "/tmp/remacs-probe-dir2"))
  (ignore-errors (make-directory "/tmp/remacs-probe-dir2" t))
  (ignore-errors (delete-directory "/tmp/remacs-probe-dir2"))
  (ignore-errors (delete-file f)))
(ignore-errors (find-file "/tmp/remacs-probe-find.txt"))
(ignore-errors (find-file-literally "/tmp/remacs-probe-find2.txt"))
;; syntax tables real use
(let ((st (copy-syntax-table)))
  (ignore-errors (syntax-table-p st))
  (ignore-errors (set-syntax-table st))
  (ignore-errors (char-syntax ?a))
  (ignore-errors (modify-syntax-entry ?a "w" st))
  (ignore-errors (char-syntax ?a))
  (ignore-errors (copy-syntax-table st))
  (ignore-errors (standard-syntax-table)))
;; read-* noninteractive fallbacks
(ignore-errors (read-char))
(ignore-errors (read-buffer "P: "))
(ignore-errors (read-buffer "P: " "def"))
(ignore-errors (read-buffer "P: " nil t))
(ignore-errors (read-command "C: "))
(ignore-errors (read-directory-name "D: "))
(ignore-errors (read-directory-name "D: " "/tmp"))
(ignore-errors (read-regexp "R: "))
(ignore-errors (yes-or-no-p "Y? "))
(ignore-errors (kbd "a"))
(ignore-errors (kbd "C-M-x"))
(ignore-errors (key-binding "C-f"))
(ignore-errors (key-binding (kbd "M-x")))
(ignore-errors (lookup-key (current-global-map) (kbd "C-f")))
(ignore-errors (lookup-key (current-global-map) "a"))
(ignore-errors (keymap-parent (make-keymap)))
(ignore-errors (use-global-map (current-global-map)))
(ignore-errors (negative-argument))
(ignore-errors (universal-argument))
(ignore-errors (select-frame (selected-frame)))
(ignore-errors (frame-edges))
(ignore-errors (frame-edges (selected-frame) 'inner-edges))
(ignore-errors (frame-pixel-height))
(ignore-errors (frame-pixel-width))
(ignore-errors (terminal-list))
(ignore-errors (terminal-name))
(ignore-errors (tty-type))
(ignore-errors (last-nonminibuffer-frame))
(ignore-errors (color-defined-p "red"))
(ignore-errors (char-syntax ?\())
;; misc primitives
(ignore-errors (max-char))
(ignore-errors (bufferp (current-buffer)))
(ignore-errors (region-end))
(ignore-errors (previous-property-change 3))
(ignore-errors (previous-property-change 3 (current-buffer)))
(ignore-errors (set-default-toplevel-value 'x 1))
(ignore-errors (erase-buffer))
;; extra.rs region ops on real text
(with-temp-buffer
  (insert "banana\napple\ncherry\napple\n")
  (ignore-errors (sort-lines nil 1 (point-max)))
  (ignore-errors (reverse-region 1 (point-max)))
  (ignore-errors (how-many "apple" 1 (point-max)))
  (ignore-errors (how-many "apple"))
  (ignore-errors (count-matches "apple" 1 (point-max)))
  (ignore-errors (count-words-region 1 (point-max)))
  (ignore-errors (count-words 1 (point-max)))
  (ignore-errors (flush-lines "apple" 1 (point-max)))
  (ignore-errors (keep-lines "cherry" 1 (point-max)))
  (ignore-errors (replace-string "cherry" "grape" 1 (point-max)))
  (ignore-errors (replace-string "x" "y" 1 (point-max) nil))
  (ignore-errors (replace-regexp "gr.pe" "PLUM" 1 (point-max)))
  (ignore-errors (replace-regexp "z*" "q" 1 (point-max) nil nil nil t))
  (ignore-errors (mark-whole-buffer))
  (ignore-errors (narrow-to-defun))
  (ignore-errors (transpose-regions 1 3 3 5))
  (ignore-errors (transpose-regions 1 3 3 5 t))
  (ignore-errors (subst-char-in-region 1 (point-max) ?a ?b))
  (ignore-errors (translate-region 1 (point-max) "abc"))
  (ignore-errors (compute-motion 1 nil 1 nil 10 80 nil))
  (ignore-errors (current-indentation))
  (ignore-errors (current-indentation 3)))
;; text properties
(with-temp-buffer
  (insert "abcdefghij")
  (ignore-errors (put-text-property 1 4 'face 'bold))
  (ignore-errors (put-text-property 5 8 'face 'italic))
  (ignore-errors (text-property-any 1 10 'face 'bold))
  (ignore-errors (text-property-any 1 10 'face 'italic))
  (ignore-errors (text-property-any 1 10 'face 'bold (current-buffer)))
  (ignore-errors (text-property-not-all 1 10 'face 'bold))
  (ignore-errors (text-property-not-all 1 10 'face nil))
  (ignore-errors (get-text-property 2 'face))
  (ignore-errors (text-properties-at 2))
  (ignore-errors (remove-text-properties 1 4 '(face)))
  (ignore-errors (next-property-change 1))
  (ignore-errors (next-single-property-change 1 'face))
  (ignore-errors (previous-single-property-change 5 'face))
  (ignore-errors (add-text-properties 1 3 '(x 1)))
  (ignore-errors (set-text-properties 1 3 nil)))
;; fields
(with-temp-buffer
  (insert "aa:bb:cc")
  (ignore-errors (field-beginning))
  (ignore-errors (field-beginning 4))
  (ignore-errors (field-beginning nil t))
  (ignore-errors (field-end))
  (ignore-errors (field-end 4))
  (ignore-errors (field-end nil nil 3))
  (ignore-errors (field-string))
  (ignore-errors (field-string 4))
  (ignore-errors (field-string-no-properties 4))
  (ignore-errors (delete-field))
  (ignore-errors (delete-field 4)))
;; buffer-swap-text
(let ((a (generate-new-buffer " *pa*"))
      (b (generate-new-buffer " *pb*")))
  (ignore-errors (with-current-buffer a (insert "A")))
  (ignore-errors (with-current-buffer b (insert "B")))
  (ignore-errors (with-current-buffer a (buffer-swap-text b)))
  (ignore-errors (buffer-last-name))
  (ignore-errors (with-current-buffer a (buffer-string))))
