;; Editor-module coverage probe: file ops, faces, windows, minibuffer,
;; whitespace commands, input readers. Wrapped in ignore-errors; the
;; goal is exercising branches without panics.
(progn
  ;; ---- file-name functions ----
  (ignore-errors (abbreviate-file-name "/tmp/x"))
  (ignore-errors (abbreviate-file-name "~/x"))
  (ignore-errors (expand-file-name "x" "/tmp"))
  (ignore-errors (expand-file-name "/abs/path"))
  (ignore-errors (expand-file-name "~/x"))
  (ignore-errors (expand-file-name "../x" "/tmp/a"))
  (ignore-errors (file-name-directory "/a/b/c.txt"))
  (ignore-errors (file-name-directory "/a/b/"))
  (ignore-errors (file-name-directory "c.txt"))
  (ignore-errors (file-name-nondirectory "/a/b/c.txt"))
  (ignore-errors (file-name-nondirectory "/a/b/"))
  (ignore-errors (file-name-extension "/a/b/c.txt"))
  (ignore-errors (file-name-extension "/a/b/c"))
  (ignore-errors (file-name-extension "/a/.hidden"))
  (ignore-errors (file-name-sans-extension "/a/b/c.txt"))
  (ignore-errors (file-name-base "/a/b/c.txt"))
  (ignore-errors (file-name-as-directory "/a/b"))
  (ignore-errors (file-name-as-directory "/a/b/"))
  (ignore-errors (directory-file-name "/a/b/"))
  (ignore-errors (directory-file-name "/a/b"))
  (ignore-errors (file-name-concat "/a" "b" "c"))
  (ignore-errors (file-name-concat "/a/" "b"))
  (ignore-errors (file-name-absolute-p "/a"))
  (ignore-errors (file-name-absolute-p "rel"))
  (ignore-errors (file-name-absolute-p "~/x"))
  (ignore-errors (file-relative-name "/a/b/c" "/a"))
  (ignore-errors (file-relative-name "/x/y" "/a"))
  (ignore-errors (file-name-quote "/a b"))
  (ignore-errors (file-name-unquote "/a/:b"))
  (ignore-errors (file-local-name "/a/b"))
  (ignore-errors (file-remote-p "/a/b"))
  (ignore-errors (file-name-sans-directory "/a/b/c"))
  (ignore-errors (file-name-sans-versions "/a/b~"))
  (ignore-errors (substitute-in-file-name "$HOME/x"))
  (ignore-errors (substitute-in-file-name "/a/$UNSET_VAR_XYZ/y"))
  (ignore-errors (unhandled-file-name-directory "/a"))
  ;; ---- file ops on real temp files ----
  (let ((dir (concat "/tmp/remacs-probe-" (number-to-string (random 100000))))
        (f1 "/tmp/remacs-p1.txt") (f2 "/tmp/remacs-p2.txt"))
    (ignore-errors (make-directory dir))
    (ignore-errors (write-region "hello\nworld\n" nil f1))
    (ignore-errors (write-region "more" nil f1 nil 'append))
    (ignore-errors (write-region "abc" nil f2 nil nil nil 'excl))
    (ignore-errors (file-exists-p f1))
    (ignore-errors (file-readable-p f1))
    (ignore-errors (file-writable-p f1))
    (ignore-errors (file-executable-p f1))
    (ignore-errors (file-regular-p f1))
    (ignore-errors (file-symlink-p f1))
    (ignore-errors (file-directory-p dir))
    (ignore-errors (file-directory-p f1))
    (ignore-errors (file-accessible-directory-p dir))
    (ignore-errors (file-equal-p f1 f1))
    (ignore-errors (file-equal-p f1 f2))
    (ignore-errors (file-newer-than-file-p f1 f2))
    (ignore-errors (file-attributes f1))
    (ignore-errors (file-attributes f1 'integer))
    (ignore-errors (file-attributes f1 'string))
    (ignore-errors (file-modes f1))
    (ignore-errors (file-modes-symbolic-to-number "a+x"))
    (ignore-errors (file-modes-symbolic-to-number "u=rwx,go="))
    (ignore-errors (file-modes-symbolic-to-number "644" 0 t))
    (ignore-errors (set-file-modes f1 420))
    (ignore-errors (default-file-modes))
    (ignore-errors (set-default-file-modes 493))
    (ignore-errors (set-default-file-modes (default-file-modes)))
    (ignore-errors (file-system-info f1))
    (ignore-errors (file-truename f1))
    (ignore-errors (copy-file f1 f2))
    (ignore-errors (copy-file f1 f2 t))
    (ignore-errors (rename-file f2 (concat f2 ".renamed") t))
    (ignore-errors (append-to-file 1 2 f2))
    (ignore-errors (add-name-to-file f1 (concat f1 ".link")))
    (ignore-errors (make-symbolic-link f1 (concat f1 ".sym") t))
    (ignore-errors (file-name-completion "rem" "/tmp"))
    (ignore-errors (file-name-all-completions "rem" "/tmp"))
    (ignore-errors (file-name-completion "zzz-nope" "/tmp"))
    (ignore-errors (directory-files "/tmp"))
    (ignore-errors (directory-files "/tmp" nil "^rem"))
    (ignore-errors (directory-files "/tmp" nil nil t))
    (ignore-errors (directory-files-and-attributes "/tmp" nil "^remacs-p1"))
    (ignore-errors (insert-file-contents f1))
    (ignore-errors (insert-file-contents f1 nil 1 3))
    (ignore-errors (insert-file-contents-literally f1))
    (ignore-errors (find-file-noselect f1))
    (ignore-errors (find-file-noselect f1 t))
    (ignore-errors (find-file f1))
    (ignore-errors (find-file-literally f1))
    (ignore-errors (write-region nil nil "/tmp/remacs-wr.txt"))
    (ignore-errors (delete-file (concat f1 ".link")))
    (ignore-errors (delete-file (concat f1 ".sym")))
    (ignore-errors (delete-file (concat f2 ".renamed")))
    (ignore-errors (delete-directory dir))
    (ignore-errors (delete-file f1))
    (ignore-errors (delete-file "/nonexistent-remacs-xyz"))
    (ignore-errors (copy-directory dir (concat dir "-copy")))
    (ignore-errors (delete-directory dir t))
    (ignore-errors (delete-directory (concat dir "-copy") t t)))
  ;; ---- faces ----
  (ignore-errors (facep 'bold))
  (ignore-errors (facep 'nonexistent-face-xyz))
  (ignore-errors (face-list))
  (ignore-errors (face-id 'bold))
  (ignore-errors (face-id 'default))
  (ignore-errors (face-all-attributes 'bold))
  (ignore-errors (face-attribute 'bold :weight))
  (ignore-errors (face-attribute 'default :foreground))
  (ignore-errors (face-attribute 'bold :weight nil t))
  (ignore-errors (face-attribute-relative-p :weight 'bold))
  (ignore-errors (face-attribute-relative-p :weight 700))
  (ignore-errors (face-attrs-more-relative-p 'bold 'default))
  (ignore-errors (face-equal 'bold 'bold))
  (ignore-errors (face-equal 'bold 'italic))
  (ignore-errors (make-face 'probe-face))
  (ignore-errors (copy-face 'bold 'probe-face-copy))
  (ignore-errors (set-face-attribute 'probe-face nil :weight 'bold))
  (ignore-errors (internal-get-lisp-face-attribute 'bold :weight))
  (ignore-errors (internal-get-lisp-face-attribute 'bold :weight nil))
  (ignore-errors (internal-lisp-face-attribute-values :weight))
  (ignore-errors (internal-lisp-face-empty-p 'bold))
  (ignore-errors (internal-lisp-face-empty-p 'default))
  (ignore-errors (internal-lisp-face-equal-p 'bold 'bold))
  (ignore-errors (internal-lisp-face-equal-p 'bold 'italic))
  (ignore-errors (internal-lisp-face-p 'bold))
  (ignore-errors (internal-lisp-face-p 'nonexistent-xyz))
  (ignore-errors (internal-merge-in-global-face 'bold))
  (ignore-errors (internal-set-lisp-face-attribute 'probe-face :weight 'bold))
  (ignore-errors (merge-face-attribute :weight 'bold 'normal))
  (ignore-errors (merge-face-attribute :weight 'normal 'bold))
  (ignore-errors (merge-face-attribute :weight 'unspecified 'bold))
  (ignore-errors (internal-char-font 0 ?a))
  (ignore-errors (internal-char-font 1 ?a))
  (ignore-errors (clear-font-cache))
  (ignore-errors (defined-colors))
  (ignore-errors (color-defined-p "red"))
  (ignore-errors (color-defined-p "not-a-color-xyz"))
  (ignore-errors (color-values "red"))
  (ignore-errors (color-values "#ff0000"))
  (ignore-errors (xw-color-values "red"))
  (ignore-errors (display-color-p))
  (ignore-errors (display-graphic-p))
  (ignore-errors (display-grayscale-p))
  (ignore-errors (display-mouse-p))
  (ignore-errors (display-supports-face-attributes-p))
  (ignore-errors (fontp 'fixed))
  (ignore-errors (font-get 'fixed :family))
  (ignore-errors (font-put 'fixed :family "mono"))
  (ignore-errors (font-xlfd-name 'fixed))
  (ignore-errors (query-font 'fixed))
  (ignore-errors (find-font 'fixed))
  (ignore-errors (fontset-list))
  (ignore-errors (fontset-list-all))
  (ignore-errors (fontset-info "fontset-default"))
  (ignore-errors (fontset-font "fontset-default" ?a))
  (ignore-errors (set-fontset-font "fontset-default" ?a 'fixed))
  (ignore-errors (new-fontset "fontset-probe" nil))
  (ignore-errors (x-list-fonts "*"))
  ;; ---- windows/frames ----
  (ignore-errors (selected-window))
  (ignore-errors (frame-first-window))
  (ignore-errors (frame-root-window))
  (ignore-errors (frame-selected-window))
  (ignore-errors (frame-list))
  (ignore-errors (frame-live-p (selected-frame)))
  (ignore-errors (frame-visible-p (selected-frame)))
  (ignore-errors (framep (selected-frame)))
  (ignore-errors (frame-parameter (selected-frame) 'name))
  (ignore-errors (frame-parameter (selected-frame) 'height))
  (ignore-errors (frame-parameters (selected-frame)))
  (ignore-errors (frame-height))
  (ignore-errors (frame-height (selected-frame)))
  (ignore-errors (frame-width))
  (ignore-errors (frame-char-height))
  (ignore-errors (frame-char-width))
  (ignore-errors (frame-pixel-height))
  (ignore-errors (frame-pixel-width))
  (ignore-errors (frame-edges))
  (ignore-errors (frame-edges (selected-frame) 'inner-edges))
  (ignore-errors (frame-position))
  (ignore-errors (frame-terminal))
  (ignore-errors (frame-focus-state))
  (ignore-errors (frame-or-buffer-changed-p))
  (ignore-errors (frame-or-buffer-changed-p (selected-frame)))
  (ignore-errors (last-nonminibuffer-frame))
  (ignore-errors (select-frame (selected-frame)))
  (ignore-errors (handle-switch-frame (selected-frame)))
  (ignore-errors (iconify-frame))
  (ignore-errors (delete-frame))
  (ignore-errors (make-frame))
  (ignore-errors (window-new-normal))
  (ignore-errors (window-new-normal (selected-window)))
  (ignore-errors (window-new-total))
  (ignore-errors (window-new-total (selected-window)))
  (ignore-errors (get-buffer-window (current-buffer)))
  (ignore-errors (get-buffer-window))
  (ignore-errors (get-buffer-window-list))
  (ignore-errors (get-buffer-window-list (current-buffer)))
  (ignore-errors (get-buffer-window-list nil nil 'visible))
  (ignore-errors (set-window-buffer (selected-window) (current-buffer)))
  (ignore-errors (set-window-buffer nil (current-buffer) t))
  (ignore-errors (select-window (selected-window)))
  (ignore-errors (select-window (selected-window) t))
  (ignore-errors (split-window))
  (ignore-errors (split-window nil 10))
  (ignore-errors (split-window nil nil t))
  (ignore-errors (delete-window))
  (ignore-errors (delete-other-windows))
  (ignore-errors (window-text-width))
  (ignore-errors (window-text-width (selected-window)))
  (ignore-errors (window-top-line))
  (ignore-errors (window-fringes))
  (ignore-errors (window-margins))
  (ignore-errors (window-scroll-bars))
  (ignore-errors (window-display-table))
  (ignore-errors (window-display-table (selected-window)))
  (ignore-errors (set-window-display-table (selected-window) nil))
  (ignore-errors (display-table-p nil))
  (ignore-errors (display-table-slot nil 0))
  (ignore-errors (describe-display-table))
  (ignore-errors (window-state-get))
  (ignore-errors (window-state-get (selected-window)))
  (ignore-errors (window-state-get nil t))
  (ignore-errors (window-configuration-p nil))
  (let ((wc (ignore-errors (current-window-configuration))))
    (ignore-errors (window-configuration-p wc))
    (ignore-errors (set-window-configuration wc)))
  (ignore-errors (current-minor-mode-maps))
  (ignore-errors (active-minibuffer-window))
  (ignore-errors (minibuffer-window))
  (ignore-errors (set-minibuffer-window (minibuffer-window)))
  ;; ---- minibuffer accessors ----
  (ignore-errors (minibuffer-contents))
  (ignore-errors (minibuffer-contents-no-properties))
  (ignore-errors (minibuffer-prompt))
  (ignore-errors (minibuffer-prompt-end))
  (ignore-errors (minibuffer-message "hi"))
  (ignore-errors (minibufferp))
  (ignore-errors (minibufferp (current-buffer)))
  (ignore-errors (delete-minibuffer-contents))
  ;; ---- readers (return nil/error without a frontend) ----
  (ignore-errors (read-buffer "Buf: "))
  (ignore-errors (read-buffer "Buf: " nil t))
  (ignore-errors (read-buffer "Buf: " nil nil "x"))
  (ignore-errors (read-command "Cmd: "))
  (ignore-errors (read-variable "Var: "))
  (ignore-errors (read-file-name "File: "))
  (ignore-errors (read-file-name "File: " "/tmp"))
  (ignore-errors (read-directory-name "Dir: "))
  (ignore-errors (read-number "Num: "))
  (ignore-errors (read-number "Num: " 5))
  (ignore-errors (read-from-minibuffer "Q: "))
  (ignore-errors (read-from-minibuffer "Q: " "init"))
  (ignore-errors (read-char))
  (ignore-errors (read-char-exclusive))
  (ignore-errors (read-event))
  (ignore-errors (read-key))
  (ignore-errors (read-key-sequence "K: "))
  (ignore-errors (read-key-sequence-vector "K: "))
  (ignore-errors (internal-complete-buffer "sc" nil 0))
  (ignore-errors (completing-read "Pick: " '("a" "b")))
  (ignore-errors (try-completion "a" '("ab" "ac")))
  (ignore-errors (try-completion "ab" '("ab" "ac")))
  (ignore-errors (try-completion "z" '("ab")))
  (ignore-errors (try-completion "" nil))
  (ignore-errors (all-completions "a" '("ab" "ac" "b")))
  (ignore-errors (all-completions "" '("a")))
  (ignore-errors (test-completion "ab" '("ab" "ac")))
  (ignore-errors (test-completion "z" '("ab")))
  (ignore-errors (completion-boundaries "ab" '("abc") "" "x"))
  (ignore-errors (completion-boundaries "ab" nil "" ""))
  (ignore-errors (yes-or-no-p "Q?"))
  ;; ---- input/kbd macro ----
  (ignore-errors (input-pending-p))
  (ignore-errors (input-pending-p t))
  (ignore-errors (discard-input))
  (ignore-errors (clear-this-command-keys))
  (ignore-errors (recent-keys))
  (ignore-errors (recent-keys nil))
  (ignore-errors (this-command-keys))
  (ignore-errors (this-command-keys-vector))
  (ignore-errors (this-single-command-keys))
  (ignore-errors (this-single-command-raw-keys))
  (ignore-errors (open-dribble-file "/tmp/remacs-dribble"))
  (ignore-errors (open-dribble-file nil))
  (ignore-errors (start-kbd-macro nil))
  (ignore-errors (defining-kbd-macro))
  (ignore-errors (end-kbd-macro))
  (ignore-errors (end-kbd-macro nil))
  (ignore-errors (call-last-kbd-macro))
  (ignore-errors (execute-kbd-macro nil))
  (ignore-errors (execute-kbd-macro [?a ?b]))
  (ignore-errors (execute-kbd-macro "ab"))
  (ignore-errors (cancel-kbd-macro-events))
  (ignore-errors (start-kbd-macro))
  (ignore-errors (end-kbd-macro 1))
  ;; ---- timers/processes ----
  (ignore-errors (current-idle-time))
  (ignore-errors (run-at-time 0 nil #'ignore))
  (ignore-errors (run-at-time "1 sec" nil #'ignore))
  (ignore-errors (run-with-timer 0.01 nil #'ignore))
  (ignore-errors (run-with-idle-timer 0.01 nil #'ignore))
  (ignore-errors (cancel-timer (timer-create)))
  (ignore-errors (with-timeout (0.1 'timeout-val) 'body-val))
  (ignore-errors (unix-sync))
  (ignore-errors (sleep-for 0))
  (ignore-errors (sleep-for 0 1))
  (ignore-errors (sit-for 0))
  (ignore-errors (sit-for 0 t))
  (ignore-errors (accept-process-output nil 0))
  (ignore-errors (get-process "nosuch"))
  (ignore-errors (delete-process nil))
  (ignore-errors (set-process-sentinel nil nil))
  (ignore-errors (process-list))
  (ignore-errors (start-process "p" nil "true"))
  (ignore-errors (call-process "true"))
  (ignore-errors (call-process "echo" nil t nil "hi"))
  (ignore-errors (call-process-region 1 1 "true"))
  (ignore-errors (shell-command "true"))
  (ignore-errors (shell-command-to-string "echo hi"))
  (ignore-errors (suspend-emacs))
  ;; ---- whitespace/indent commands ----
  (with-temp-buffer
    (insert "a  b   c\nline two\n   indented\nlast")
    (goto-char (point-min))
    (ignore-errors (just-one-space))
    (ignore-errors (just-one-space 2))
    (ignore-errors (just-one-space -1))
    (ignore-errors (delete-horizontal-space))
    (ignore-errors (delete-horizontal-space t))
    (goto-char (point-min)) (forward-line 1)
    (ignore-errors (delete-indentation))
    (ignore-errors (delete-indentation t))
    (goto-char (point-min))
    (ignore-errors (join-line))
    (ignore-errors (join-line t))
    (goto-char (point-min))
    (ignore-errors (kill-whole-line))
    (ignore-errors (kill-whole-line 1))
    (goto-char (point-min))
    (ignore-errors (indent-line-to 4))
    (ignore-errors (indent-line-to 0))
    (ignore-errors (indent-rigidly 1 3 2))
    (ignore-errors (indent-rigidly 1 3 -1))
    (ignore-errors (count-words 1 5))
    (ignore-errors (count-words-region 1 5))
    (ignore-errors (count-lines-page))
    (ignore-errors (downcase-region 1 3))
    (ignore-errors (upcase-region 1 3))
    (ignore-errors (capitalize-region 1 3))
    (ignore-errors (downcase-word 1))
    (ignore-errors (upcase-word 1))
    (ignore-errors (capitalize-word 1))
    (ignore-errors (backward-kill-word 1))
    (ignore-errors (backward-kill-word -1))
    (ignore-errors (delete-trailing-whitespace))
    (ignore-errors (delete-trailing-whitespace 1 nil))
    (ignore-errors (narrow-to-defun))
    (ignore-errors (narrow-to-defun t))
    (widen)
    (ignore-errors (beginning-of-defun))
    (ignore-errors (beginning-of-defun -1))
    (ignore-errors (end-of-defun))
    (ignore-errors (end-of-defun -1))
    (ignore-errors (beginning-of-buffer-other-window))
    (ignore-errors (copy-region-as-kill 1 3))
    (ignore-errors (copy-region-as-kill 1 3 t))
    (ignore-errors (copy-to-buffer (current-buffer) 1 3))
    (ignore-errors (current-kill 0))
    (ignore-errors (current-kill 0 t))
    (ignore-errors (exchange-point-and-mark-inactive)))
  ;; ---- docs/bindings ----
  (ignore-errors (documentation 'car))
  (ignore-errors (documentation 'car t))
  (ignore-errors (documentation 'forward-char))
  (ignore-errors (documentation 'probe-face 'face))
  (ignore-errors (documentation-property 'car 'variable-documentation))
  (ignore-errors (documentation-property 'x 'variable-documentation t))
  (ignore-errors (apropos-internal "car"))
  (ignore-errors (apropos-internal "car" #'commandp))
  (ignore-errors (describe-bindings-internal))
  (ignore-errors (commandp 'forward-char))
  (ignore-errors (commandp 'car))
  (ignore-errors (commandp 'nonexistent-xyz))
  (ignore-errors (command-remapping 'forward-char))
  (ignore-errors (call-interactively 'forward-char))
  (ignore-errors (call-interactively 'forward-char t))
  (ignore-errors (call-interactively 'nonexistent-xyz))
  (ignore-errors (execute-extended-command nil))
  (ignore-errors (global-key-binding [?a]))
  (ignore-errors (local-key-binding [?a]))
  (ignore-errors (minor-mode-key-binding nil))
  (ignore-errors (use-global-map (current-global-map)))
  (ignore-errors (copy-keymap (current-global-map)))
  (ignore-errors (copy-keymap nil))
  (ignore-errors (define-prefix-command 'probe-prefix))
  (ignore-errors (copy-syntax-table))
  (ignore-errors (copy-syntax-table (standard-syntax-table)))
  (ignore-errors (char-syntax ?a))
  (ignore-errors (char-syntax ?\s))
  (ignore-errors (char-syntax ?())
  (ignore-errors (char-syntax ?a (standard-syntax-table)))
  (ignore-errors (comment-beginning))
  (ignore-errors (delay-mode-hooks (ignore)))
  (ignore-errors (run-mode-hooks))
  (ignore-errors (run-mode-hooks 'probe-hook))
  (ignore-errors (set-buffer-major-mode (current-buffer)))
  (ignore-errors (fundamental-mode))
  (ignore-errors (dump-glyph-matrix))
  (ignore-errors (blink-cursor-mode))
  (ignore-errors (blink-cursor-mode 1))
  (ignore-errors (internal-show-cursor nil t))
  (ignore-errors (internal-show-cursor-p))
  (ignore-errors (cursor-type))
  (ignore-errors (negative-argument 2))
  (ignore-errors (universal-argument))
  (ignore-errors (digit-argument ?5))
  (ignore-errors (forward-line-command 1))
  (ignore-errors (forward-line-command -1))
  (ignore-errors (x-popup-menu nil nil))
  (ignore-errors (x-popup-dialog nil nil))
  (ignore-errors (insert-directory "/tmp" "-la"))
  (ignore-errors (insert-directory-literally "/tmp" "-la"))
  (ignore-errors (file-name-history))
  (ignore-errors (car-less-than-car '(1 . a) '(2 . b)))
  (ignore-errors (dir-locals-set-class-variables 'c '((a . 1))))
  (ignore-errors (set-buffer-modified-p nil))
  (ignore-errors (save-buffer))
  (ignore-errors (write-file "/tmp/remacs-wf.txt"))
  (ignore-errors (delete-file "/tmp/remacs-wf.txt"))
  nil)
