;; Probe: evalfn/arith/seq/regexp/print remaining branches.
(progn
  ;; ---- macroexp-parse-body ----------------------------------------
  (prin1 (macroexp-parse-body '((declare (indent 1)) "doc" (a) (b))))
  (prin1 (macroexp-parse-body '("doc-only")))
  (prin1 (macroexp-parse-body '((interactive "p") (body))))
  ;; ---- regexp parser: classes, escapes, repeats, shy groups ---------
  (mapc (lambda (p) (prin1 (string-match (car p) (cdr p))))
        '(("[[:alnum:]]+" . "!!ab12")
          ("[[:ascii:]]+" . "ab\tcd")
          ("[[:blank:]]+" . "a \tb")
          ("[[:cntrl:]]+" . "a\001b")
          ("[[:graph:]]+" . "  a!b ")
          ("[[:multibyte:]]" . "a")
          ("[[:nonascii:]]" . "abc")
          ("[[:print:]]+" . " a b")
          ("[[:unibyte:]]" . "a")
          ("[[:word:]]+" . "_x9!")
          ("[a-cx-z]+" . "qabzy")
          ("[[:alpha:][:digit:]]+" . "!a1")
          ("\\bcat\\b" . "a cat b")
          ("\\Bcat" . "scat")
          ("\\<cat\\>" . "a cat")
          ("\\w+" . " ab_9")
          ("\\W+" . "ab !")
          ("\\s(\\w" . "a (b")
          ("\\s)" . "a)b")
          ("x\\{2\\}" . "xxx")
          ("x\\{2,\\}" . "xxxx")
          ("x\\{1,3\\}" . "xxxx")
          ("\\(?:ab\\)+" . "abab")
          ("\\(?1:a\\)\\(?2:b\\)" . "ab")
          ("a\\`" . "a")
          ("\\'z" . "z")
          ("^a" . "ba")
          ("b$" . "ab")))
  (condition-case e (string-match "[" "x") (error (prin1 (car e))))
  (condition-case e (string-match "a\\{b" "x") (error (prin1 (car e))))
  (condition-case e (string-match "\\(?z:" "x") (error (prin1 (car e))))
  ;; ---- regexp search backward / posix -------------------------------
  (with-temp-buffer
    (insert "x1 y22 z333")
    (goto-char (point-max))
    (prin1 (re-search-backward "[a-z][0-9]+" nil t))
    (prin1 (match-string 0))
    (goto-char (point-min))
    (prin1 (posix-search-forward "[a-z][0-9]*" nil t))
    (prin1 (match-string 0)))
  (prin1 (posix-string-match "[a-z]+" "aa bb"))
  ;; ---- aset/elt on records, bool-vectors, strings --------------------
  (let ((r (record 't1 'a 'b)))
    (aset r 1 'z)
    (prin1 (aref r 1))
    (prin1 (aref r 2))
    (condition-case e (elt r 0) (error (prin1 (car e)))))
  (let ((bv (bool-vector t nil t)))
    (aset bv 1 t)
    (prin1 (aref bv 1))
    (prin1 (elt bv 0)))
  (let ((s (copy-sequence "abc")))
    (aset s 1 ?Z)
    (prin1 s)
    (prin1 (elt s 0)))
  (let ((v [1 2 3]))
    (aset v 2 'z)
    (prin1 (elt v 2)))
  (condition-case e (aset "abc" 5 ?x) (error (prin1 (car e))))
  (condition-case e (aset [1] 'a ?x) (error (prin1 (car e))))
  (condition-case e (elt '(1 2) 5) (error (prin1 (car e))))
  (prin1 (elt '(a b c) 1))
  (prin1 (elt "xy" 0))
  ;; ---- arith branches -------------------------------------------------
  (prin1 (/ 8 2 2))
  (prin1 (/ 1.5 0.5))
  (prin1 (mod 7 3))
  (prin1 (mod -7 3))
  (prin1 (mod 7.5 2))
  (condition-case e (% 7.5 2) (error (prin1 (car e))))
  (prin1 (lsh 1 4))
  (prin1 (lsh 256 -4))
  (prin1 (lsh -1 1))
  (prin1 (ash 1 10))
  (prin1 (ash -8 -2))
  (prin1 (logand 12 10))
  (prin1 (logior 12 10))
  (prin1 (logxor 12 10))
  (prin1 (lognot 0))
  (prin1 (1+ 5))
  (prin1 (1- 5))
  (prin1 (abs -7))
  (prin1 (min 3 1 2))
  (prin1 (max 3 1 2))
  (prin1 (expt 2 10))
  (prin1 (expt 2.0 0.5))
  (prin1 (sqrt 16))
  (condition-case e (sqrt -1) (error (prin1 (car e))))
  (prin1 (exp 0))
  (prin1 (log 1))
  (prin1 (log 100 10))
  (prin1 (sin 0.0))
  (prin1 (cos 0.0))
  (prin1 (tan 0.0))
  (prin1 (asin 0.0))
  (prin1 (acos 1.0))
  (prin1 (atan 1.0))
  (prin1 (atan 1.0 1.0))
  (prin1 (isnan (/ 0.0 0.0)))
  (prin1 (frexp 8.0))
  (prin1 (ldexp 0.5 4))
  (prin1 (copysign 1.5 -1.0))
  (prin1 (logb 16.0))
  ;; ---- format-time-string ---------------------------------------------
  (prin1 (stringp (format-time-string "%Y-%m-%d" '(0 0))))
  (prin1 (stringp (format-time-string "%H:%M:%S" '(0 0) t)))
  ;; ---- string → sequence ------------------------------------------------
  (prin1 (vconcat "ab" [1]))
  (prin1 (append "ab" nil))
  (prin1 (string-to-list "ab"))
  (prin1 (string-to-vector "ab"))
  ;; ---- require -----------------------------------------------------------
  (prin1 (require 'emacs))
  (prin1 (require 'no-such-feature-xyz nil t))
  (condition-case e (require 'no-such-feature-xyz) (error (prin1 (car e))))
  (prin1 (featurep 'emacs))
  ;; ---- lambda printing ------------------------------------------------------
  (prin1 (lambda (a &optional b &rest c) a))
  (prin1 (lambda (a b) a))
  ;; ---- function/condition-case/prog1/and/or raw paths (unevalled call) -------
  (prin1 (or nil (progn 'x)))
  (prin1 (and 1 2 3))
  (prin1 (prog1 'a 'b 'c))
  (prin1 (prog2 'a 'b 'c))
  (prin1 (progn))
  (prin1 (condition-case nil (error "x") (error 'caught)))
  ;; ---- parse-integer / string conversion -------------------------------------
  (prin1 (string-to-number "42"))
  (prin1 (string-to-number "0x1f" 16))
  (prin1 (string-to-number "abc"))
  (prin1 (number-to-string 255))
  (prin1 'done))
