;; probe_misc2 — valid-argument coverage for src/lisp/builtins/misc.rs
;; bool-vectors
(let ((a (make-bool-vector 8 nil))
      (b (make-bool-vector 8 t)))
  (ignore-errors (bool-vector-p a))
  (ignore-errors (bool-vector-length a))
  (ignore-errors (aset a 0 t))
  (ignore-errors (aset a 3 t))
  (ignore-errors (bool-vector-count-population a))
  (ignore-errors (bool-vector-count-consecutive a nil 0))
  (ignore-errors (bool-vector-count-consecutive b t 0))
  (ignore-errors (bool-vector-union a b))
  (ignore-errors (bool-vector-intersection a b))
  (ignore-errors (bool-vector-set-difference a b))
  (ignore-errors (bool-vector-exclusive-or a b))
  (ignore-errors (bool-vector-subsetp a b))
  (ignore-errors (bool-vector-not a)))
;; char tables
(let ((ct (make-char-table 'test 'init)))
  (ignore-errors (char-table-p ct))
  (ignore-errors (char-table-subtype ct))
  (ignore-errors (char-table-parent ct))
  (ignore-errors (set-char-table-parent ct nil))
  (ignore-errors (char-table-range ct 65))
  (ignore-errors (set-char-table-range ct 65 'x))
  (ignore-errors (char-table-range ct '(65 . 90)))
  (ignore-errors (set-char-table-range ct '(65 . 90) 'y))
  (ignore-errors (char-table-extra-slot ct 0))
  (ignore-errors (set-char-table-extra-slot ct 0 'z))
  (ignore-errors (map-char-table (lambda (k v) v) ct))
  (ignore-errors (optimize-char-table ct)))
;; coding systems
(ignore-errors (coding-system-list))
(ignore-errors (coding-system-p 'utf-8))
(ignore-errors (coding-system-aliases 'utf-8))
(ignore-errors (coding-system-base 'utf-8))
(ignore-errors (coding-system-eol-type 'utf-8))
(ignore-errors (coding-system-plist 'utf-8))
(ignore-errors (coding-system-get 'utf-8 :mnemonic))
(ignore-errors (coding-system-put 'utf-8 :mnemonic ?U))
(ignore-errors (coding-system-priority-list))
(ignore-errors (check-coding-system 'utf-8))
(ignore-errors (check-coding-systems-region 1 10 '(utf-8)))
(ignore-errors (decode-coding-string "abc" 'utf-8))
(ignore-errors (encode-coding-string "abc" 'utf-8))
(ignore-errors (encode-coding-char ?a 'utf-8))
(ignore-errors (detect-coding-string "abc"))
(ignore-errors (detect-coding-region 1 5))
(ignore-errors (decode-coding-region 1 5 'utf-8))
(ignore-errors (encode-coding-region 1 5 'utf-8))
(ignore-errors (keyboard-coding-system))
(ignore-errors (terminal-coding-system))
(ignore-errors (default-terminal-coding-system))
(ignore-errors (file-name-coding-system))
;; display
(ignore-errors (display-pixel-width))
(ignore-errors (display-pixel-height))
(ignore-errors (display-mm-width))
(ignore-errors (display-mm-height))
(ignore-errors (display-mm-dimensions-alist))
(ignore-errors (display-backing-store))
(ignore-errors (display-save-under))
(ignore-errors (display-planes))
(ignore-errors (display-color-cells))
(ignore-errors (display-visual-class))
(ignore-errors (display-images-p))
(ignore-errors (display-monitor-attributes-list))
(ignore-errors (frame-monitor-attributes))
(ignore-errors (color-supported-p "red"))
(ignore-errors (color-gray-p "gray50"))
(ignore-errors (xw-color-defined-p "red"))
(ignore-errors (xw-display-color-p))
(ignore-errors (tool-bar-height))
(ignore-errors (tool-bar-pixel-width))
(ignore-errors (x-open-connection ":0"))
(ignore-errors (x-close-connection ":0"))
(ignore-errors (x-display-list))
(ignore-errors (x-synchronize t))
;; events
(ignore-errors (eventp ?a))
(ignore-errors (eventp 'down))
(ignore-errors (eventp '(mouse-1 (1 . 2))))
(ignore-errors (event-basic-type ?a))
(ignore-errors (event-basic-type 'down))
(ignore-errors (event-basic-type 24))
(ignore-errors (event-basic-type '(mouse-1)))
(ignore-errors (event-modifiers ?a))
(ignore-errors (event-modifiers 'down))
(ignore-errors (event-modifiers 'C-down))
(ignore-errors (event-modifiers 24))
(ignore-errors (event-modifiers '(control mouse-1)))
(ignore-errors (event-convert-list '(control ?a)))
(ignore-errors (event-convert-list '(shift down)))
(ignore-errors (key-parse "<C-down>"))
(ignore-errors (key-parse "abc"))
(ignore-errors (key-valid-p "<f1>"))
(ignore-errors (key-valid-p "C-x"))
(ignore-errors (key-valid-p ""))
;; keymaps
(ignore-errors (current-active-maps))
(ignore-errors (text-mode-map))
(ignore-errors (make-composed-keymap nil))
(ignore-errors (make-composed-keymap (list (make-sparse-keymap))))
(ignore-errors (suppress-keymap (make-sparse-keymap)))
(ignore-errors (suppress-keymap (make-sparse-keymap) t))
(ignore-errors (listify-key-sequence (kbd "abc")))
(ignore-errors (listify-key-sequence [?a ?b]))
(ignore-errors (map-keymap-internal (lambda (k v) v) (make-sparse-keymap)))
(ignore-errors (set-transient-map (make-sparse-keymap)))
(ignore-errors (keymap--mergable (make-sparse-keymap)))
(ignore-errors (keymap-canonicalize (make-sparse-keymap)))
;; misc predicates / objects
(ignore-errors (closurep '(lambda (x) x)))
(ignore-errors (closurep (lambda (x) x)))
(ignore-errors (cl-type-of 1))
(ignore-errors (cl-type-of "s"))
(ignore-errors (cl-type-of 's))
(ignore-errors (cl-type-of [1]))
(ignore-errors (cl-type-of (lambda (x) x)))
(ignore-errors (string-or-null-p "s"))
(ignore-errors (string-or-null-p nil))
(ignore-errors (mutexp nil))
(ignore-errors (threadp nil))
(ignore-errors (condition-variable-p nil))
(ignore-errors (subr-native-elisp-p #'car))
(ignore-errors (bare-symbol-p 'x))
(ignore-errors (vector-or-char-table-p [1]))
(ignore-errors (vector-or-char-table-p (make-char-table 'x)))
(ignore-errors (frame-configuration-p nil))
(ignore-errors (current-frame-configuration))
;; env / system
(ignore-errors (getenv "PATH"))
(ignore-errors (getenv-internal "PATH"))
(ignore-errors (setenv "REMACS_PROBE_VAR" "1"))
(ignore-errors (getenv "REMACS_PROBE_VAR"))
(ignore-errors (user-login-name))
(ignore-errors (user-real-login-name))
(ignore-errors (user-full-name))
(ignore-errors (user-uid))
(ignore-errors (user-real-uid))
(ignore-errors (system-groups))
(ignore-errors (system-name))
(ignore-errors (invocation-name))
(ignore-errors (invocation-directory))
(ignore-errors (emacs-uptime))
(ignore-errors (emacs-pid))
(ignore-errors (memory-limit))
(ignore-errors (lock-file "/tmp/remacs-probe-lock"))
(ignore-errors (unlock-file "/tmp/remacs-probe-lock"))
;; time
(ignore-errors (date-to-time "1970-01-01 00:00:00"))
(ignore-errors (days-between "2020-01-01" "2020-01-10"))
(ignore-errors (time-add (current-time) (seconds-to-time 60)))
(ignore-errors (time-equal-p (current-time) (current-time)))
(ignore-errors (time-less-p (list 0 0) (list 0 1)))
(ignore-errors (current-cpu-time))
;; versions
(ignore-errors (version-to-list "1.2.3"))
(ignore-errors (version-listp '(1 2 3)))
(ignore-errors (version-list-< '(1 2) '(1 3)))
(ignore-errors (version-list-<= '(1 2) '(1 2)))
(ignore-errors (version-list-= '(1 2) '(1 2)))
(ignore-errors (version< "1.0" "2.0"))
(ignore-errors (version<= "1.0" "1.0"))
(ignore-errors (version= "1.0" "1.0"))
;; windows
(ignore-errors (get-mru-window))
(ignore-errors (minibuffer-selected-window))
(ignore-errors (window-child (selected-window)))
(ignore-errors (window-child-count (selected-window)))
(ignore-errors (window-group (selected-window)))
(ignore-errors (window-combined-p (selected-window)))
(ignore-errors (window-combined-p (selected-window) t))
(ignore-errors (window-fixed-size-p (selected-window)))
(ignore-errors (window-has-dark-scroll-bar))
(ignore-errors (window-left-column (selected-window)))
(ignore-errors (window-leftmost-p (selected-window)))
(ignore-errors (window-rightmost-p (selected-window)))
(ignore-errors (window-topmost-p (selected-window)))
(ignore-errors (window-bottommost-p (selected-window)))
(ignore-errors (window-line (selected-window)))
(ignore-errors (window-main-window))
(ignore-errors (window-max-chars-per-line (selected-window)))
(ignore-errors (window-min-height (selected-window)))
(ignore-errors (window-min-width (selected-window)))
(ignore-errors (window-normalize-buffer (current-buffer)))
(ignore-errors (window-normalize-frame (selected-frame)))
(ignore-errors (window-normalize-window (selected-window)))
(ignore-errors (window-preserve-size (selected-window)))
(ignore-errors (window-safely-shrinkable-p (selected-window)))
(ignore-errors (window-sizable (selected-window) 1))
(ignore-errors (window-sizable (selected-window) 1 t))
(ignore-errors (window-in-direction 'right))
(ignore-errors (window-at-side-p (selected-window) 'left))
(ignore-errors (window--display-buffer (current-buffer) (selected-window) 'reuse))
(ignore-errors (get-window-with-predicate (lambda (w) t)))
(ignore-errors (split-window-sensibly (selected-window)))
(ignore-errors (fit-window-to-buffer))
(ignore-errors (shrink-window-if-larger-than-buffer))
(ignore-errors (delete-windows-on (current-buffer)))
(ignore-errors (pos-visible-in-window-group-p (point)))
;; mouse
(ignore-errors (mouse-position))
(ignore-errors (mouse-pixel-position))
(ignore-errors (set-mouse-position (selected-frame) 1 1))
(ignore-errors (set-mouse-pixel-position (selected-frame) 1 1))
;; faces / misc
(ignore-errors (clear-face-cache))
(ignore-errors (invert-face 'default))
(ignore-errors (buffer-display-table))
(ignore-errors (buffer-hash))
(ignore-errors (command-error-default-function nil nil nil))
(ignore-errors (command-modes))
(ignore-errors (abort-minibuffers))
(ignore-errors (accessible-keymaps (current-global-map)))
(ignore-errors (function-documentation #'car))
(ignore-errors (help-function-arglist #'car))
(ignore-errors (help-function-arglist 'car t))
(ignore-errors (gensym))
(ignore-errors (gensym "prefix"))
(ignore-errors (md5 "abc"))
(ignore-errors (md5 "abc" 1 2))
(ignore-errors (base64-encode-string "hello"))
(ignore-errors (base64-decode-string "aGVsbG8="))
(ignore-errors (file-acl "/tmp"))
