;; Coverage probe: builtins edge branches.
(format-time-string "%Y-%m-%d %H:%M:%S")
(format-time-string "%a %b %e %Z")
(format-time-string "%j %U %W %w")
(format-time-string "%p %c %x %X %%")
(format-time-string "%s %N")
(format-time-string "%Y" '(100000 0))
(format-time-string "%z %Z" nil "UTC")
(format-time-string "%Y" nil t)
(condition-case e (format-time-string 5) (error e))
(aset [1 2 3] 1 9)
(aset "abc" 1 ?Z)
(let ((bv (bool-vector t nil)))
  (aset bv 0 nil)
  (aref bv 0))
(let ((ct (make-char-table 'x nil)))
  (aset ct 65 'v)
  (aref ct 65))
(condition-case e (aset 5 0 1) (error e))
(condition-case e (aset [1] 99 1) (error e))
(condition-case e (aset "ab" 5 ?x) (error e))
(let ((s (copy-sequence "abcdef")))
  (store-substring s 2 "XY")
  s)
(store-substring "abc" 0 90)
(store-substring "abc" 0 "de")
(condition-case e (store-substring "abc" 99 "x") (error e))
(format "%d|%5d|%-5d|%05d|%x|%o|%c" 42 42 42 42 255 8 65)
(format "%s|%.2s|%S" "hello" "hello" '(a b))
(format "%e|%f|%.2f|%g" 1234.5 1.25 3.14159 0.0001)
(format "%1$s %2$s %1$s" "a" "b")
(format "%%|%d" 5)
(condition-case e (format "%*d" 5 7) (error e))
(condition-case e (format "%d" "x") (error e))
(condition-case e (format "%s %s" "a") (error e))
(condition-case e (format) (error e))
(elt [1 2 3] 1)
(elt '(a b c) 2)
(elt "xyz" 0)
(elt (bool-vector t nil) 1)
(condition-case e (elt '(a) 5) (error e))
(condition-case e (elt 5 0) (error e))
(/ 10 3)
(/ 10.0 4)
(/ -7 2)
(condition-case e (/ 1 0) (error e))
(condition-case e (/ 1.0 0) (error e))
(condition-case e (/ "x" 2) (error e))
(- 5)
(- 5.5)
(- 10 3 2)
(mod 7 3)
(mod -7 3)
(mod 7.5 2)
(condition-case e (mod 1 0) (error e))
(expt 2 10)
(expt 2.0 0.5)
(expt 0 0)
(expt -2 3)
(lsh 1 10)
(lsh -1 1)
(lsh 256 -4)
(lsh most-positive-fixnum 1)
(condition-case e (lsh 1 "x") (error e))
(ash 1 5)
(ash -8 -1)
(1+ 5)
(1- 5.5)
(abs -3)
(abs -3.5)
(float 7)
(truncate 7.9)
(truncate -7.9)
(floor 7.9)
(floor -7.9)
(ceiling 7.1)
(ceiling -7.1)
(round 7.5)
(round 8.5)
(round -7.5)
(ftruncate 7.9)
(ffloor 7.9)
(fceiling 7.1)
(fround 7.5)
(fround -7.5)
(condition-case e (truncate "x") (error e))
(condition-case e (float "x") (error e))
(isnan 0.0)
(isnan (/ 0.0 0.0))
(frexp 8.0)
(ldexp 0.5 4)
(logb 8.0)
(logb 0.5)
(copysign 1.5 -2.0)
(seq-contains-p '(1 2 3) 2)
(seq-contains-p '(1 2 3) 9)
(seq-contains-p [a b] 'b)
(seq-contains-p "xy" ?x)
(seq-contains-p nil 1)
(seq-concatenate 'list '(1) '(2) '(3))
(seq-concatenate 'vector '(1 2) [3])
(seq-concatenate 'string '(?a ?b) "cd")
(seq-concatenate 'list nil)
(seq-concatenate 'bool-vector '(t nil) '(nil))
(condition-case e (seq-concatenate 'bogus '(1)) (error e))
(with-output-to-string (princ "a") (princ 1))
(with-output-to-string)
(let ((standard-output 'ignore))
  (princ "x")
  standard-output)
(sort '(3 1 2) '<)
(sort '(3 1 2) '>)
(sort [3 1 2] '<)
(condition-case e (sort "cba" '<) (error e))
(sort nil '<)
(condition-case e (sort '(1) "x") (error e))
(string< "a" "b")
(string< "a" "a")
(string> "b" "a")
(string= "x" "x")
(string-equal "x" "x")
(string-version-lessp "a1" "a2")
(string-greaterp "b" "a")
(string-lessp "a" "b")
(string-collate-lessp "a" "b")
(string-collate-equalp "a" "a")
(compare-strings "abc" 0 1 "abd" 0 1)
(compare-strings "abc" nil nil "abc" nil nil)
(string-to-list "ab")
(string-to-vector "ab")
(string-to-list "")
(append '(1) '(2) 3)
(reverse '(1 2 3))
(reverse [1 2 3])
(reverse "abc")
(reverse nil)
(nreverse (list 1 2 3))
(nreverse [1 2 3])
(condition-case e (nreverse 5) (error e))
(substring "hello" 1 3)
(substring "hello" 1)
(substring "hello" -2)
(substring "hello" nil nil)
(condition-case e (substring "x" 5) (error e))
(substring nil)
(run-hooks 'no-such-hook)
(let ((h nil))
  (add-hook 'h (lambda () (setq x 1)))
  (run-hooks 'h))
(run-hook-wrapped 'hh (lambda (f) (funcall f) nil))
(condition-case e (run-hooks 5) (error e))
(progn (require 'cl-lib nil t) t)
(condition-case e (require 'nonexistent-feature-xyz) (error e))
(featurep 'cl-lib)
(provide 'my-feat)
(featurep 'my-feat)
(macroexpand-1 '(when t 1))
(macroexpand-1 'x)
(macroexp-progn '(1 2))
(macroexp-progn nil)
(macroexp-progn '(a))
(internal--build-binding 'x 1)
(eval '(+ 1 2) t)
(eval '(+ 1 2) nil)
(condition-case e (eval 5) (error e))
(garbage-collect)
(load-average)
(memory-info)
(emacs-uptime)
(invocation-name)
(invocation-directory)
(daemonp)
