;; Missing-subr batch: new primitives, handler-bind, watchers.
;; Differential-verified against GNU Emacs 31.1.
(progn
  ;; trivial builtins
  (princ (list 'a (subr-primitive-p (symbol-function 'car))
               (subr-type (symbol-function 'car))
               (condition-case e (subr-type 5) (error (car e)))
               (subr-native-lambda-list (symbol-function 'car))
               (syntax-class-to-char 2) (syntax-class-to-char 15)
               (syntax-class-to-char 0)
               (condition-case e (syntax-class-to-char 99) (error (car e)))
               (matching-paren ?\() (matching-paren ?\)) (matching-paren ?a)
               (ngettext "x" "xs" 1) (ngettext "x" "xs" 3)
               (condition-case e (ngettext 'a 'b 1) (error (car e)))))
  (terpri)
  ;; access-file
  (let ((tf (make-temp-file "subrs-probe")))
    (princ (list 'b (access-file tf "ok %s")
                 (condition-case e (access-file "/nonexistent-dir-zzz/f" "msg %s")
                   (error (car e)))))
    (delete-file tf))
  (terpri)
  ;; single-char property changes with PROP/OBJECT/LIMIT
  (with-temp-buffer
    (insert "abcdef")
    (put-text-property 2 4 'face 'bold)
    (princ (list 'c (next-single-char-property-change 1 'face)
                 (next-single-char-property-change 2 'face)
                 (next-single-char-property-change 4 'face nil 6)
                 (next-single-char-property-change 6 'face)
                 (previous-single-char-property-change 5 'face)
                 (previous-single-char-property-change 4 'face)
                 (previous-single-char-property-change 2 'face)
                 (next-single-char-property-change 0 'face "abcd")
                 (previous-single-char-property-change 3 'face "abcd"))))
  (terpri)
  ;; base64url + get-byte
  (princ (list 'd (base64url-encode-string "a?b?") (base64url-encode-string "a?b?" t)
               (get-byte 0 "ABC") (get-byte 2 "ABC")
               (condition-case e (get-byte 0 "é") (error (cadr e)))))
  (terpri)
  ;; variable watchers: set/let/unlet/makunbound
  (let ((log nil))
    (add-variable-watcher 'vw-t1 (lambda (s n o w) (push (list s n o) log)))
    (setq vw-t1 1)
    (let ((vw-t1 2)) t)
    (makunbound 'vw-t1)
    (princ (list 'e (nreverse log) (length (get-variable-watchers 'vw-t1))))
    (remove-variable-watcher 'vw-t1 (lambda (s n o w) t))
    (terpri))
  ;; find-file-name-handler + misc
  (princ (list 'f (find-file-name-handler "/tmp/x" 'insert-file-contents)
               (combine-after-change-execute)
               (with-temp-buffer (make-overlay 1 1) (delete-all-overlays) t)
               (current-message)))
  (terpri)
  ;; replace-region-contents
  (with-temp-buffer
    (insert "hello world")
    (replace-region-contents 1 6 "goodbye ")
    (princ (list 'g (buffer-string))))
  (terpri)
  ;; bury-buffer-internal / make-indirect-buffer
  (princ (list 'h2 (with-temp-buffer
                     (bury-buffer-internal (current-buffer))
                     t)
               (bufferp (condition-case e
                            (make-indirect-buffer (current-buffer) "ind-probe")
                          (error e)))))
  (terpri)
  ;; handler-bind: caught signals do not fire handlers
  (let ((log nil))
    (handler-bind ((error (lambda (c) (push 'ran log))))
      (condition-case e (signal 'error '(x)) (error nil)))
    (princ (list 'h log)))
  (terpri)
  ;; handler ordering within one form: argument order, innermost first
  (let ((log nil))
    (catch 'done
      (handler-bind ((error (lambda (c) (push 'first log)))
                     (error (lambda (c) (push 'second log) (throw 'done 'esc))))
        (signal 'error '(boom))))
    (princ (list 'ord (nreverse log))))
  (terpri)
  ;; signal-hook-function sees caught signals; nested let so the hook
  ;; closure captures `log' (parallel `let' inits can't see own bindings).
  (let ((log nil))
    (let ((signal-hook-function (lambda (s d) (push (list 'hk s) log))))
      (condition-case e (signal 'arith-error '(z)) (error (push 'cc log))))
    (princ (list 'hook (nreverse log))))
  (terpri)
  ;; handler receives (sym . data); condition-list membership
  (let ((got nil))
    (catch 'out
      (handler-bind (((arith-error file-error)
                      (lambda (c) (setq got c) (throw 'out 'done))))
        (signal 'arith-error '(d1 d2))))
    (princ (list 'cond got)))
  (terpri)
  ;; macroexpand + throw-escape
  (princ (list 'i (macroexpand '(handler-bind ((error h)) b))))
  (terpri)
  (princ (list 'j (catch 'out
                    (handler-bind ((error (lambda (c) (throw 'out 'inner))))
                      (signal 'error '(e))))))
  (terpri)
  ;; condition-case-unless-debug
  (princ (list 'k (condition-case-unless-debug v (error "x") (error 'caught))))
  (terpri)
  ;; ignore-errors must suppress handler-bind handlers
  (let ((log nil))
    (handler-bind ((error (lambda (c) (push 'ran log))))
      (ignore-errors (signal 'error '(x))))
    (princ (list 'ie log)))
  (terpri)
  ;; autoload-do-load returns nil on non-autoload
  (princ (list 'l (autoload-do-load (symbol-function 'car) 'car)))
  (terpri)
  ;; load honors the lexical-binding cookie (nil cookie -> dynamic file)
  (let ((tf (make-temp-file "subrs-load" nil ".el")))
    (with-temp-file tf
      (insert "(defvar probe-dyn t) (let ((probe-dyn 'lex)) (setq probe-let-seen probe-dyn))"))
    (load tf)
    (delete-file tf))
  (princ (list 'load-dyn (boundp 'probe-dyn) (boundp 'probe-let-seen)))
  (terpri)
  (let ((tf (make-temp-file "subrs-load-lex" nil ".el")))
    (with-temp-file tf
      (insert ";; -*- lexical-binding: t -*-\n(defvar probe-lex t)"))
    (load tf)
    (delete-file tf))
  (princ (list 'load-lex (boundp 'probe-lex)))
  (terpri)
  (princ (list 'load-missing
               (condition-case e (load "/nonexistent-subrs-zzz.el")
                 (file-error (car e)))))
  (terpri)
  ;; make-indirect-buffer: API surface (name uniqueness, base link)
  (let ((b (get-buffer-create "subrs-base")))
    (with-current-buffer b (insert "HELLO"))
    (let ((ib (make-indirect-buffer b "subrs-ind" t)))
      (princ (list 'ind (bufferp ib) (buffer-name ib)
                   (eq (buffer-base-buffer ib) b)
                   (buffer-base-buffer b)
                   (with-current-buffer ib (buffer-string)))))
    (princ (list 'ind-dup
                 (condition-case e (make-indirect-buffer b "subrs-ind")
                   (error (car e)))))
    (kill-buffer "subrs-ind")
    (terpri))
  ;; translate-region-internal + buffer-line-statistics
  (with-temp-buffer
    (insert "abc")
    (translate-region-internal 1 4 (make-string 128 ?.))
    (princ (list 'tri (buffer-string))))
  (terpri)
  (let ((tab (make-string 128 0)))
    (aset tab ?a ?X) (aset tab ?b ?Y)
    (with-temp-buffer
      (insert "abc")
      (translate-region-internal 1 4 tab)
      (princ (list 'tri2 (buffer-string)))))
  (terpri)
  (princ (list 'tri3 (condition-case e
                         (with-temp-buffer (translate-region-internal 1 1 5))
                       (error (car e)))))
  (terpri)
  (princ (list 'bls (with-temp-buffer (buffer-line-statistics))
               (with-temp-buffer (insert "a\n\n") (buffer-line-statistics))
               (with-temp-buffer (insert "a\nbb\nccc") (buffer-line-statistics))))
  (terpri)
  ;; threads: cooperative model — zombie stays live until joined
  (let ((th (make-thread (lambda () (+ 1 2)) "worker")))
    (princ (list 'mt (threadp th) (thread-name th) (thread-live-p th)
                 (eq th (current-thread)))))
  (terpri)
  (let ((th (make-thread (lambda () (+ 1 2)) "worker")))
    (princ (list 'join (thread-join th) (thread-live-p th))))
  (terpri)
  (let ((th (make-thread (lambda () (signal 'arith-error '(x))) "bad")))
    (princ (list 'terr (thread-live-p th)
                 (condition-case e (thread-join th) (error (car e)))
                 (thread-last-error))))
  (terpri)
  (princ (list 'at (length (all-threads)) (threadp (car (all-threads)))
               (threadp 'x) (type-of (current-thread))))
  (terpri)
  nil)

;; string predicates: GNU has string-equal/string-lessp/string-greaterp as
;; primitives accepting strings-or-symbols; string=/</> are Lisp aliases.
(let ((probe '(t)))
  (dolist (f '(string-equal string-lessp string-greaterp
               string= string< string> string<= string>=
               string-empty-p string-blank-p string-prefix-p string-suffix-p))
    (princ (list 'fp f (fboundp f) (subr-primitive-p (symbol-function f)))))
  (terpri))
(let ((probe '(t)))
  (mapc (lambda (x) (condition-case e (princ (list 'sp (car x) (eval x)))
                                    (error (princ (list 'sp (car x) (car e)))))
                    (terpri))
        '((string-equal "a" "a") (string-equal 'a "a") (string-equal nil "")
          (string-lessp "a" "b") (string-lessp 'a "b") (string-lessp "a" nil)
          (string-greaterp "b" "a") (string-greaterp 'b 'a)
          (string= "a" "a") (string< "a" "b") (string> "b" "a")
          (string-empty-p "") (string-empty-p "a") (string-empty-p nil)
          (string-blank-p " ") (string-blank-p "x")
          (string-prefix-p "he" "hello") (string-prefix-p "AB" "ab" t)
          (string-suffix-p "lo" "hello") (string-suffix-p "LO" "hello" t))))

;; sync objects, case tables, toplevel values, file internals
(let ((probe '(t)))
  (let ((m (make-mutex "mx")))
    (princ (list 'mx (mutexp m) (mutex-name m) (type-of m)
                 (mutex-lock m) (mutex-unlock m)
                 (condition-case e (mutex-unlock m) (error (car e)))
                 (condition-case e (mutex-lock 'x) (error (car e))))))
  (terpri)
  (let* ((m (make-mutex)) (c (make-condition-variable m "cv")))
    (princ (list 'cv (condition-variable-p c) (condition-name c)
                 (eq m (condition-mutex c)) (type-of c)
                 (condition-case e (condition-wait c) (error (car e)))
                 (condition-case e (condition-notify c) (error (car e))))))
  (terpri)
  (princ (list 'fin (type-of (make-finalizer #'ignore))))
  (terpri)
  (setq probe-var 42)
  (princ (list 'tv (default-toplevel-value 'probe-var)
               (condition-case e (buffer-local-toplevel-value 'probe-var)
                 (error (car e)))))
  (terpri)
  (let ((probe-var 99))
    (princ (list 'tvl (default-toplevel-value 'probe-var)
                 (condition-case e (buffer-local-toplevel-value 'probe-var)
                   (error (car e))))))
  (terpri)
  (make-local-variable 'probe-var)
  (setq probe-var 7)
  (set-buffer-local-toplevel-value 'probe-var 33)
  (princ (list 'tvs (buffer-local-toplevel-value 'probe-var) probe-var))
  (terpri)
  (princ (list 'ct (case-table-p (current-case-table))
               (eq (current-case-table) (standard-case-table))
               (case-table-p (make-char-table 'case-table nil))
               (case-table-p (make-char-table 'syntax-table nil))))
  (terpri)
  (princ (list 'misc (byte-to-string 65) (num-processors)
               (text-quoting-style) (internal-subr-documentation 'car)
               (length (get-load-suffixes)) (length (signal-names))
               (user-ptrp nil)))
  (terpri)
  (princ (list 'files
               (condition-case e (delete-file-internal "/nope-xyz") (error (car e)))
               (condition-case e (delete-directory-internal "/nope-xyz") (error (car e)))
               (locate-file-internal "sh" '("/bin"))
               (locate-file-internal "nope-xyz" exec-path)))
  (terpri)
  (princ (list 'rec (make-record 'foo 2 nil) (recordp (make-record 'foo 2 0))))
  (terpri)
  (princ (list 'scb (subr-primitive-p (symbol-function 'save-current-buffer))))
  (terpri)
  (princ (list 'dq (subr-primitive-p (symbol-function 'defvar-1))
               (progn (defvar-1 'probe-dv1 5 "doc") probe-var))
           )
  (terpri)
  nil)

;; misc stubs: group/ccl/redisplay internals
(let ((probe '(t)))
  (princ (list 'gn (stringp (group-name 0)) (group-name 999999)))
  (terpri)
  (princ (list 'wfu (waiting-for-user-input-p) (bitmap-spec-p 5)
               (get-truename-buffer "x")
               (unencodable-char-position 0 3 'utf-8 1 "abc")))
  (terpri)
  (princ (list 'comp (condition-case e (compose-region-internal 1 2)
                       (error (car e)))
               (compose-string-internal "ab" 0 1)
               (condition-case e (compose-string-internal "ab" 0 9)
                 (error (car e)))))
  (terpri)
  (princ (list 'ccl
               (condition-case e (register-ccl-program 'x "s") (error e))
               (condition-case e (register-ccl-program 'x [1]) (error (car e)))
               (register-ccl-program 'x [0 0 0])
               (register-ccl-program 'x [0 0 0 0])
               (ccl-program-p 'x) (ccl-program-p 'y)
               (condition-case e (ccl-execute 'y [0]) (error (car e)))
               (register-code-conversion-map 'm [0])
               (condition-case e (register-code-conversion-map 'm2 '((a . b)))
                 (error e))))
  (terpri)
  (princ (list 'rds (set-buffer-redisplay (current-buffer) 1 1 nil)
               (delete-other-windows-internal)))
  (terpri)
  nil)

;; zlib, find-buffer, tty stubs
(let ((probe '(t)))
  (princ (list 'zl (zlib-available-p)))
  (terpri)
  (with-temp-buffer
    (insert "abc")
    (princ (condition-case e (zlib-decompress-region 1 4) (error (car e)))))
  (terpri)
  (with-temp-buffer
    (setq-local buffer-file-coding-system 'utf-8)
    (princ (list 'fb (bufferp (find-buffer 'buffer-file-coding-system 'utf-8))
                 (find-buffer 'buffer-file-coding-system 'nope)
                 (condition-case e (find-buffer 'buffer-name "x")
                   (error (car e))))))
  (terpri)
  (with-temp-buffer
    (insert-byte 65 3)
    (princ (list 'ib (buffer-string)
                 (condition-case e (insert-byte 300 1) (error (car e))))))
  (terpri)
  (princ (list 'tty (set-quit-char 7)
               (set-binary-mode 'stdin t)
               (condition-case e (set-binary-mode 'foo t) (error (car e)))
               (condition-case e (set-output-flow-control nil t) (error (car e)))
               (newline-cache-check) (tab-bar-height)
               (condition-case e (insert-special-event 'x) (error (car e)))
               (buffer-text-pixel-size) (format-mode-line "abc")
               (debugger-trap)))
  (terpri)
  nil)

;; category tables
(let ((probe '(t)))
  (princ (list 'mk (category-table-p (make-category-table))
               (char-table-subtype (make-category-table))
               (category-table-p (standard-category-table))
               (eq (category-table) (standard-category-table))))
  (terpri)
  (princ (list 'std-sets (category-set-mnemonics (char-category-set ?a))
               (category-set-mnemonics (char-category-set ?5))
               (category-set-mnemonics (char-category-set 32))
               (category-set-mnemonics (char-category-set ?\\))))
  (terpri)
  (let ((t1 (make-category-table)))
    (princ (list 'def (define-category ?x "docx" t1)
                 (category-docstring ?x t1)
                 (condition-case e (define-category ?x "again" t1)
                   (error (car e)))
                 (condition-case e (define-category 5 "d" t1)
                   (error (car e)))
                 (condition-case e (define-category 999 "d" t1)
                   (error (car e)))))
    (terpri)
    (princ (list 'mod (modify-category-entry ?a ?x t1)
                 (modify-category-entry '(?A . ?C) ?x t1)
                 (condition-case e
                     (category-set-mnemonics (char-table-range t1 97))
                   (error (car e)))))
    (terpri)
    (princ (list 'mod2 (condition-case e
                           (category-set-mnemonics (char-table-range t1 ?B))
                         (error (car e)))
                 (condition-case e (modify-category-entry ?a ?y t1)
                   (error (cadr e)))
                 (get-unused-category t1)
                 (category-docstring ?y t1)))
    (terpri)
    (let ((c (copy-category-table t1)))
      (princ (list 'copy (category-table-p c)
                   (not (eq c t1))
                   (category-docstring ?x c)
                   (category-set-mnemonics (char-table-range c ?a))))
      (terpri)))
  (princ (list 'mcs (bool-vector-p (make-category-set ""))
               (category-set-mnemonics (make-category-set "xy"))
               (condition-case e (category-set-mnemonics 5) (error (car e)))
               (condition-case e (category-set-mnemonics nil) (error (car e)))))
  (terpri)
  nil)

;; Platform/internals batch: availability predicates, input-mode,
;; charset/unicode internals, labeled narrowing, hash/obarray
;; introspection, buffer completion. Differential-checked vs GNU 31.1.
(progn
  (princ (list 'avail (gnutls-available-p) (sqlite-available-p)
               (libxml-available-p) (treesit-available-p)
               (imagep nil) (long-line-optimizations-p)))
  (terpri)
  (princ (list 'input (current-input-mode)
               (set-input-mode t nil t 7)
               (set-input-interrupt-mode t)
               (set-input-meta-mode t)
               (set-quit-char 7)
               (current-bidi-paragraph-direction)
               (find-operation-coding-system 'write-region 1 2 "f")
               (condition-case e (define-coding-system-alias 'a 'b)
                 (error (car e)))
               (define-coding-system-alias 'my-utf8 'utf-8)
               (next-read-file-uses-dialog-p)))
  (terpri)
  (princ (list 'disp (lossage-size)
               (condition-case e (lossage-size 99) (error (car e)))
               (mouse-position-in-root-frame)
               (window-scroll-bar-width) (window-scroll-bar-height)
               (line-number-display-width) (move-to-window-line 0)
               (condition-case e (window-configuration-equal-p 1 2)
                 (error (car e)))
               (internal-stack-stats) (pdumper-stats)
               (profiler-cpu-running-p)
               (redirect-debugging-output "/dev/null")
               (comp-libgccjit-version)
               (condition-case e (subr-native-comp-unit 5) (error (car e)))
               (native-comp-function-p #'car) (module-function-p #'car)
               (condition-case e (comp-el-to-eln-filename "/nonexistent-x.el")
                 (error (car e)))))
  (terpri)
  (princ (list 'proc (internal-default-signal-process 1 2)
               (condition-case e (internal-default-process-sentinel 1 "x")
                 (error (car e)))
               (condition-case e (set-network-process-option 1 :x 2)
                 (error (car e)))
               (condition-case e (process-thread 1) (error (car e)))
               (print--preprocess [1]) (clear-composition-cache)
               (condition-case e (re--describe-compiled 1) (error (car e)))
               (condition-case e (system-move-file-to-trash "/no-such-xyz")
                 (error (car e)))))
  (terpri)
  (princ (list 'cs (charset-id-internal 'ascii) (charset-id-internal 'unicode)
               (charset-id-internal 'emacs)
               (condition-case e (charset-id-internal 'nope) (error (car e)))
               (charsetp 'ascii)
               (sort-charsets '(unicode)) (sort-charsets '(emacs ascii))
               (set-charset-priority 'ascii 'unicode)
               (condition-case e (map-charset-chars (lambda (r) nil) 'ascii nil nil t)
                 (error (car e)))
               (condition-case e (declare-equiv-charset 'unicode 1 2 3)
                 (error (car e)))
               (clear-charset-maps)))
  (terpri)
  (let ((gt (unicode-property-table-internal 'general-category))
        (bt (unicode-property-table-internal 'bidi-class)))
    (princ (list 'uni (char-table-p gt)
                 (get-unicode-property-internal gt ?a)
                 (put-unicode-property-internal bt ?a 'L)
                 (get-unicode-property-internal bt ?a)
                 (condition-case e (get-unicode-property-internal 'sym ?a)
                   (error (car e)))))
    (terpri))
  (with-temp-buffer
    (insert "abcdef")
    (internal--labeled-narrow-to-region 2 4 'lab)
    (princ (list 'lownar (point-min) (point-max))) (terpri)
    (internal--labeled-widen 'lab)
    (princ (list 'lowid (point-min) (point-max))) (terpri))
  (let ((ht (make-hash-table)))
    (princ (list 'htab (internal--hash-table-index-size ht)
                 (internal--hash-table-buckets ht)
                 (internal--hash-table-histogram ht)))
    (terpri)
    (puthash 'a 1 ht)
    (princ (list 'htab2 (internal--hash-table-index-size ht)
                 (listp (internal--hash-table-buckets ht))
                 (internal--hash-table-histogram ht)))
    (terpri))
  (princ (list 'vars (internal--define-uninitialized-variable 'uqvar "doc")
               (boundp 'uqvar)
               (condition-case e (internal-delete-indirect-variable 'uqvar)
                 (error (car e)))
               (listp (internal--obarray-buckets obarray))))
  (terpri)
  (with-temp-buffer
    (let ((t0 (buffer-modified-tick)))
      (internal--set-buffer-modified-tick 42)
      (princ (list 'tick t0 (buffer-modified-tick))) (terpri)))
  (princ (list 'asv (recent-auto-save-p) (set-buffer-auto-saved)
               (clear-buffer-auto-save-failure)))
  (terpri)
  (princ (list 'cbuf (internal-complete-buffer "*scr" nil nil)
               (listp (internal-complete-buffer "" nil t))
               (internal-complete-buffer "*scratch*" nil 'lambda)))
  (terpri)
  ;; GUI/font internals: nil stubs (no display). NB: several of these
  ;; SIGABRT a batch GNU (no X/font machinery); only the safe ones are
  ;; differentially comparable.
  (princ (list 'gui (get-display-property 1 'x) (lookup-image-map [1] 2 3)
               (condition-case e (clear-image-cache) (error (car e)))
               (image-cache-size)
               (display--line-is-continued-p)
               (condition-case e (internal-handle-focus-in nil) (error (car e)))
               (condition-case e (internal-handle-focus-in '(focus-in nil))
                 (error (car e)))
               ;; internal-face-x-get-resource SIGABRTs batch GNU.
               'internal-face-x-get-resource
               (internal-set-alternative-font-family-alist nil)
               (condition-case e (internal-set-font-selection-order nil)
                 (error (car e)))
               (condition-case e (query-fontset "x") (error (car e)))
               (condition-case e (close-font 1) (error (car e)))
               (condition-case e (define-fringe-bitmap 'b []) (error (car e)))
               (condition-case e (destroy-fringe-bitmap 'b) (error (car e)))
               (condition-case e (tty-frame-edges) (error (car e)))
               (condition-case e (tty-frame-geometry) (error (car e)))
               (condition-case e (make-terminal-frame '((a . b)))
                 (error (car e)))))
  (terpri)
  (princ (list 'thr (condition-case e (thread-buffer-disposition 1)
                 (error (car e)))
               (thread-buffer-disposition (car (all-threads)))
               (condition-case e
                   (thread-set-buffer-disposition (car (all-threads)) 'x)
                 (error (car e)))
               (thread-set-buffer-disposition (car (all-threads)) nil)))
  (terpri)
  (princ (list 'cjk
               (decode-big5-char #xA440) (decode-big5-char 65)
               (condition-case e (decode-big5-char 99999) (error (cadr e)))
               (encode-big5-char #x4E00)
               (decode-sjis-char #x8140) (decode-sjis-char #xB1)
               (condition-case e (decode-sjis-char #xFF) (error (cadr e)))
               (encode-sjis-char #x3000) (encode-sjis-char #xFF71)
               (decode-char 'big5 #xA440) (decode-char 'cp932 #xB1)
               (decode-char 'japanese-jisx0208 #x2121)
               (decode-char 'jisx0201 #x61) (decode-char 'katakana-sjis #xB1)
               (decode-char 'chinese-big5-1 #x2121)
               (encode-char #x4E00 'big5) (encode-char #x3000 'cp932)
               (encode-char #xFF71 'cp932)
               (condition-case e (decode-char 'sjis 1) (error (car e)))
               (charsetp 'big5) (charsetp 'sjis)))
  (terpri)
  nil)
