;;; flymake.el --- minimal stub satisfying flymake autoloads -*- lexical-binding: t -*-

;; GNU's flymake.el is a full syntax-checking framework requiring
;; comint/compile/project.  remacs embeds this minimal version so that
;; the `flymake' autoloads generated by loaddefs.el resolve: loading
;; the library defines each autoloaded entry point, which is the
;; contract `autoload' checks.  Diagnostics are represented as
;; (LOCUS BEG END TYPE TEXT . DATA) lists.

(defvar flymake-diagnostic-types-alist nil)
(defvar flymake-diagnostic-functions nil)
(defvar flymake-mode nil)
(defvar-local flymake--diagnostics nil)

(defun flymake-log (level msg &rest args)
  "Log, at level LEVEL, the message MSG formatted with ARGS.
LEVEL is passed to `warning-minimum-level' filtering; this stub
routes the message through `message' at high verbosity only."
  (when (>= (or (bound-and-true-p flymake-log-level) 0) (or level 0))
    (apply #'message msg args)))

(defun flymake-make-diagnostic (locus beg end type text &optional data _overlay-properties)
  "Make a Flymake diagnostic for LOCUS's region from BEG to END.
This stub represents the diagnostic as a plain list."
  (list locus beg end type text data))

(defun flymake-diag-region (buffer line &optional col)
  "Compute BUFFER's region (BEG . END) corresponding to LINE and COL.
If COL is nil, return a region for the whole line."
  (with-current-buffer buffer
    (save-excursion
      (save-restriction
        (widen)
        (goto-char (point-min))
        (forward-line (1- line))
        (if col
            (cons (min (+ (point) (1- col)) (point-max))
                  (min (+ (point) col) (point-max)))
          (cons (point) (line-end-position)))))))

(defun flymake-diagnostics (&optional _beg _end)
  "Get Flymake diagnostics in the current buffer."
  flymake--diagnostics)

(defun flymake-mode (&optional arg)
  "Toggle Flymake mode on or off (stub)."
  (interactive)
  (setq flymake-mode
        (if (null arg)
            (not flymake-mode)
          (> (prefix-numeric-value arg) 0))))

(defun flymake-mode-on ()
  "Turn Flymake mode on."
  (flymake-mode 1))

(defun flymake-mode-off ()
  "Turn Flymake mode off."
  (flymake-mode 0))

(provide 'flymake)
;;; flymake.el ends here
